microhil-base: src/channel/channel.h File Reference
channel.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "ws2812.pio.h"
Macros
#define MICROHIL_SUCCESS 0
Return value for success state.
#define MICROHIL_FAILED 1
Return value for failed state.
#define MICROHIL_NUMBER_OF_CHANNELS 8
Total number of supported channels.
#define MICROHIL_BUZZER 6
GPIO port pin number for buzzer.
#define MICROHIL_CMD_LEN 13
Command message length.
#define MICROHIL_CMD_PREFIX "mh#ch#"
Command message prefix.
#define MICROHIL_PROP_ON_RESERVE 4
Prpperty channel ON length.
#define MICROHIL_PROP_OFF_RESERVE 5
Prpperty channel OFF length.
#define MICROHIL_CMD_PROP_ALL_ON "all#on"
Command message propery all ON.
#define MICROHIL_CMD_PROP_ALL_OFF "all#off"
Command message propery all OFF.
Typedefs
typedef enum _channel_gpio_num channel_gpio_num
GPIO ports and numbers for channels.
Enumerations
enum _channel_gpio_num {
MICROHIL_ALL_CHANNELS_ON = 300 , MICROHIL_ALL_CHANNELS_OFF = 200 , MICROHIL_CHANNELS_ERROR = 127 , MICROHIL_CHANNEL_0 = 21 ,
MICROHIL_CHANNEL_1 = 20 , MICROHIL_CHANNEL_2 = 19 , MICROHIL_CHANNEL_3 = 18 , MICROHIL_CHANNEL_4 = 17 ,
MICROHIL_CHANNEL_5 = 16 , MICROHIL_CHANNEL_6 = 15 , MICROHIL_CHANNEL_7 = 14
}
GPIO ports and numbers for channels.
Functions
bool microhil_init ()
Global initialization of microHIL device.
bool microhil_pio_init ()
Initialization of PIO state machine.
bool microhil_init_relay ()
Initializatio of relay channels.
bool microhil_init_buzzer ()
Initializatio of buzzer channel.
void microhil_all_channels_on ()
Set all channels to ON.
void microhil_all_channels_off ()
Set all channels to OFF.
void microhil_channel_switch (channel_gpio_num id)
Switch channel state.
void microhil_write_pixel (uint32_t pixel_rgb)
Write 32-bit RGB value to PIO state machine.
uint32_t urgb_u32 (uint8_t red, uint8_t green, uint8_t blue)
Generate 32-bit RGB value.
uint16_t microhil_fetch_command (uint8_t *buffer)
Fetch microHIL command messages from the serial port.
unsigned char * microhil_extract_command_property (unsigned char *cmd)
Extract command property.
channel_gpio_num microhil_process_command (unsigned char *cmd)
Process microHIL command messages from uart.
channel_gpio_num index_to_gpio (int id)
Convert index to GPIO port number.
Macro Definition Documentation
MICROHIL_BUZZER
#define MICROHIL_BUZZER 6
GPIO port pin number for buzzer.
Definition at line 57 of file channel.h.
MICROHIL_CMD_LEN
#define MICROHIL_CMD_LEN 13
Command message length.
Definition at line 61 of file channel.h.
MICROHIL_CMD_PREFIX
#define MICROHIL_CMD_PREFIX "mh#ch#"
Command message prefix.
Definition at line 65 of file channel.h.
MICROHIL_CMD_PROP_ALL_OFF
#define MICROHIL_CMD_PROP_ALL_OFF "all#off"
Command message propery all OFF.
Definition at line 81 of file channel.h.
MICROHIL_CMD_PROP_ALL_ON
#define MICROHIL_CMD_PROP_ALL_ON "all#on"
Command message propery all ON.
Definition at line 77 of file channel.h.
MICROHIL_FAILED
#define MICROHIL_FAILED 1
Return value for failed state.
Definition at line 32 of file channel.h.
MICROHIL_NUMBER_OF_CHANNELS
#define MICROHIL_NUMBER_OF_CHANNELS 8
Total number of supported channels.
Definition at line 36 of file channel.h.
MICROHIL_PROP_OFF_RESERVE
#define MICROHIL_PROP_OFF_RESERVE 5
Prpperty channel OFF length.
Definition at line 73 of file channel.h.
MICROHIL_PROP_ON_RESERVE
#define MICROHIL_PROP_ON_RESERVE 4
Prpperty channel ON length.
Definition at line 69 of file channel.h.
MICROHIL_SUCCESS
#define MICROHIL_SUCCESS 0
Return value for success state.
Definition at line 28 of file channel.h.
Typedef Documentation
channel_gpio_num
typedef enum _channel_gpio_num channel_gpio_num
GPIO ports and numbers for channels.
Enumeration Type Documentation
_channel_gpio_num
enum _channel_gpio_num
GPIO ports and numbers for channels.
Enumerator
MICROHIL_ALL_CHANNELS_ON
MICROHIL_ALL_CHANNELS_OFF
MICROHIL_CHANNELS_ERROR
MICROHIL_CHANNEL_0
MICROHIL_CHANNEL_1
MICROHIL_CHANNEL_2
MICROHIL_CHANNEL_3
MICROHIL_CHANNEL_4
MICROHIL_CHANNEL_5
MICROHIL_CHANNEL_6
MICROHIL_CHANNEL_7
Definition at line 40 of file channel.h.
{
    MICROHIL_ALL_CHANNELS_ON = 300,
    MICROHIL_ALL_CHANNELS_OFF = 200,
    MICROHIL_CHANNELS_ERROR = 127,
    MICROHIL_CHANNEL_0 = 21,
    MICROHIL_CHANNEL_1 = 20,
    MICROHIL_CHANNEL_2 = 19,
    MICROHIL_CHANNEL_3 = 18,
    MICROHIL_CHANNEL_4 = 17,
    MICROHIL_CHANNEL_5 = 16,
    MICROHIL_CHANNEL_6 = 15,
    MICROHIL_CHANNEL_7 = 14
} channel_gpio_num;
Function Documentation
index_to_gpio()
channel_gpio_num index_to_gpio (int id)
Convert index to GPIO port number.
Parameters
id is index
Returns
GPIO port number
Definition at line 54 of file channel.c.
{
    switch (id)
    {
        case 0: return MICROHIL_CHANNEL_0;
        case 1: return MICROHIL_CHANNEL_1;
        case 2: return MICROHIL_CHANNEL_2;
        case 3: return MICROHIL_CHANNEL_3;
        case 4: return MICROHIL_CHANNEL_4;
        case 5: return MICROHIL_CHANNEL_5;
        case 6: return MICROHIL_CHANNEL_6;
        case 7: return MICROHIL_CHANNEL_7;
    }
    return MICROHIL_CHANNELS_ERROR;
}
References MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, and MICROHIL_CHANNELS_ERROR.
Referenced by microhil_process_command().
microhil_all_channels_off()
void microhil_all_channels_off ()
Set all channels to OFF.
Set relay channels to OFF
Store channel states
Led notification
Buzzer notification
Definition at line 108 of file channel.c.
{
    microhil_digital_write(MICROHIL_CHANNEL_7, false);
    microhil_digital_write(MICROHIL_CHANNEL_6, false);
    microhil_digital_write(MICROHIL_CHANNEL_5, false);
    microhil_digital_write(MICROHIL_CHANNEL_4, false);
    microhil_digital_write(MICROHIL_CHANNEL_3, false);
    microhil_digital_write(MICROHIL_CHANNEL_2, false);
    microhil_digital_write(MICROHIL_CHANNEL_1, false);
    microhil_digital_write(MICROHIL_CHANNEL_0, false);
    for (int i = 0; i < MICROHIL_NUMBER_OF_CHANNELS; i++)
    {
        channels[i] = 0x0;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_ALL_OFF);
    microhil_write_pixel(urgb_u32(0, 0, 0));
    microhil_write_pwm(80, PWM_CHAN_A);
    microhil_delay_ms(100);
    microhil_write_pwm(0, PWM_CHAN_A);
}
References channels, MICROHIL_ALL_OFF, MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, MICROHIL_CHANNEL_INFO, microhil_delay_ms(), microhil_digital_write(), MICROHIL_NUMBER_OF_CHANNELS, microhil_write_pixel(), microhil_write_pwm(), and urgb_u32().
Referenced by microhil_channel_switch().
microhil_all_channels_on()
void microhil_all_channels_on ()
Set all channels to ON.
Set relay channels to ON
Store channel states
Led notification
Buzzer notification
Definition at line 73 of file channel.c.
{
    microhil_digital_write(MICROHIL_CHANNEL_7, true);
    microhil_digital_write(MICROHIL_CHANNEL_6, true);
    microhil_digital_write(MICROHIL_CHANNEL_5, true);
    microhil_digital_write(MICROHIL_CHANNEL_4, true);
    microhil_digital_write(MICROHIL_CHANNEL_3, true);
    microhil_digital_write(MICROHIL_CHANNEL_2, true);
    microhil_digital_write(MICROHIL_CHANNEL_1, true);
    microhil_digital_write(MICROHIL_CHANNEL_0, true);
    for (int i = 0; i < MICROHIL_NUMBER_OF_CHANNELS; i++)
    {
        channels[i] = 0x1;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_ALL_ON);
    microhil_write_pixel(urgb_u32(255, 255, 255));
    microhil_write_pwm(80, PWM_CHAN_A);
    microhil_delay_ms(100);
    microhil_write_pwm(0, PWM_CHAN_A);
}
References channels, MICROHIL_ALL_ON, MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, MICROHIL_CHANNEL_INFO, microhil_delay_ms(), microhil_digital_write(), MICROHIL_NUMBER_OF_CHANNELS, microhil_write_pixel(), microhil_write_pwm(), and urgb_u32().
Referenced by microhil_channel_switch().
microhil_channel_switch()
void microhil_channel_switch (channel_gpio_num gpio)
Switch channel state.
Parameters
id is GPIO port number
Store channel state and write to GPIO porn pin
Led notification
Buzzer notification
Definition at line 144 of file channel.c.
{
    switch (gpio)
    {
        case MICROHIL_ALL_CHANNELS_OFF:
            microhil_all_channels_off();
            break;
        case MICROHIL_ALL_CHANNELS_ON:
            microhil_all_channels_on();
            break;
        case MICROHIL_CHANNELS_ERROR:
            printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_NO_SUPPORT);
            break;
        default:
            unsigned int index = gpio_to_index(gpio);
            if (index == MICROHIL_CHANNELS_ERROR)
            {
                printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_NO_SUPPORT);
                break;
            }
            channels[index] = !channels[index];
            microhil_digital_write(gpio, (bool)channels[index]);
            if (channels[index] == 1)
            {
                printf("%s channel %d on\n", MICROHIL_CHANNEL_INFO, index);
            }
            else if (channels[index] == 0)
            {
                printf("%s channel %d off\n", MICROHIL_CHANNEL_INFO, index);
            }
            microhil_write_pixel(urgb_u32(255, 0, 0));
            microhil_write_pwm(80, PWM_CHAN_A);
            microhil_delay_ms(100);
            microhil_write_pwm(0, PWM_CHAN_A);
            break;
    }
}
References channels, gpio_to_index(), microhil_all_channels_off(), MICROHIL_ALL_CHANNELS_OFF, microhil_all_channels_on(), MICROHIL_ALL_CHANNELS_ON, MICROHIL_CHANNEL_ERROR, MICROHIL_CHANNEL_INFO, MICROHIL_CHANNELS_ERROR, microhil_delay_ms(), microhil_digital_write(), MICROHIL_NO_SUPPORT, microhil_write_pixel(), microhil_write_pwm(), and urgb_u32().
Referenced by main().
microhil_extract_command_property()
unsigned char * microhil_extract_command_property (unsigned char * cmd)
Extract command property.
Parameters
cmd is whole command messsage for processing
Returns
command property
Extract command property.
Parameters
cmd is whole command messsage for processing
Returns
command property
Sanity check for expected command message prefix
Not matched expected command message prefix
Extract command property
Command message property (microHIL format)
Definition at line 54 of file channel_uart.c.
{
    int cmd_len = strlen(cmd);
    int prefix_len = strlen(MICROHIL_CMD_PREFIX);
    int len = cmd_len - prefix_len;
    int status = strncmp(cmd, MICROHIL_CMD_PREFIX, prefix_len);
    if (status != 0)
    {
        return NULL;
    }
    unsigned char *cmd_property = (unsigned char *)malloc(len);
    sprintf(cmd_property, "%s", cmd + prefix_len);
    return cmd_property;
}
References MICROHIL_CMD_PREFIX.
Referenced by microhil_process_command().
microhil_fetch_command()
uint16_t microhil_fetch_command (uint8_t * buffer)
Fetch microHIL command messages from the serial port.
Parameters
buffer storage for received message from the serial port
Returns
number of received bytes from the serial port
Definition at line 28 of file channel_uart.c.
{
    uint16_t buffer_index = 0;
    while (true)
    {
        int byte = getchar_timeout_us(100);
        if (byte != PICO_ERROR_TIMEOUT && buffer_index < MICROHIL_CMD_LEN)
        {
            buffer[buffer_index++] = (byte & 0xFF);
        }
        else
        {
            buffer[buffer_index] = 0;
            break;
        }
    }
    return buffer_index;
}
References MICROHIL_CMD_LEN.
Referenced by main().
microhil_init()
bool microhil_init ()
Global initialization of microHIL device.
Returns
true for success else false
Perform initialization for stdio types
Failed to perform initialization for stdio types
Perform initialization for stdio usb
Failed to perform initialization for stdio usb
Perform initialization for RELAY
Failed to perform initialization for RELAY
Perform initialization for PIO
Failed to perform initialization for PIO
Perform initialization for port pin configuration of BUZZER
Failed to perform initialization for pin configuration Buzzer
Perform initialization for PWM channel of BUZZER
Failed to perform initialization for PWM Buzzer
Led notification
Buzzer notification
Definition at line 29 of file channel_init.c.
{
    bool status = false;
    status = stdio_init_all();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    status = stdio_usb_init();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    status = microhil_init_relay();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    status = microhil_pio_init();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    status = microhil_init_buzzer();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    status = microhil_init_pwm(MICROHIL_BUZZER, PWM_CHAN_A);
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    microhil_write_pixel(urgb_u32(0, 0, 0));
    microhil_digital_write(MICROHIL_BUZZER, true);
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_INIT_DONE);
    return status;
}
References MICROHIL_BUZZER, MICROHIL_CHANNEL_ERROR, MICROHIL_CHANNEL_INFO, microhil_digital_write(), microhil_init_buzzer(), MICROHIL_INIT_DONE, MICROHIL_INIT_FAILED, microhil_init_pwm(), microhil_init_relay(), microhil_pio_init(), microhil_write_pixel(), and urgb_u32().
Referenced by main().
microhil_init_buzzer()
bool microhil_init_buzzer ()
Initializatio of buzzer channel.
Returns
true for success else false
Initialize channel for buzzer
Buzzer port pin configuration done
Definition at line 25 of file channel_buzzer.c.
{
    bool status = false;
    microhil_gpio_mode(MICROHIL_BUZZER, GPIO_OUT);
    status = true;
    return status;
}
References MICROHIL_BUZZER, and microhil_gpio_mode().
Referenced by microhil_init().
microhil_init_relay()
bool microhil_init_relay ()
Initializatio of relay channels.
Returns
true for success else false
Initialize channels
Relay port pins configuration done
Definition at line 25 of file channel_relay.c.
{
    bool status = false;
    microhil_gpio_mode(MICROHIL_CHANNEL_0, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_1, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_2, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_3, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_4, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_5, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_6, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_7, GPIO_OUT);
    status = true;
    return status;
}
References MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, and microhil_gpio_mode().
Referenced by microhil_init().
microhil_pio_init()
bool microhil_pio_init ()
Initialization of PIO state machine.
Returns
true for success else false
Add PIO program
Failed to load PIO program
Perform WS2812 program initialization
Definition at line 28 of file channel_pio.c.
{
    bool status = false;
    ws2812_init init = {
        .pio = pio0,
        .sm = 0,
        .offset = pio_add_program(pio0, &ws2812_program),
        .pin = MICROHIL_WS2812_DIN,
        .freq = 800000,
        .rgbw = true
    };
    if (init.offset == 0)
    {
        return status;
    }
    ws2812_program_init(&init);
    status = true;
    return status;
}
References MICROHIL_WS2812_DIN, _ws2812_init::offset, _ws2812_init::pio, ws2812_program, and ws2812_program_init().
Referenced by microhil_init().
microhil_process_command()
channel_gpio_num microhil_process_command (unsigned char * cmd)
Process microHIL command messages from uart.
Parameters
cmd is whole command for processing
Returns
GPIO port number
Failed to extract command property
Request command all channels ON
Request command all channels OFF
Request command switch channel 1..8
Request command switch channel 1..8
Requested command not supported
Definition at line 145 of file channel_uart.c.
{
    unsigned char *cmd_property = microhil_extract_command_property(cmd);
    if (cmd_property == NULL)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_EXT_PROP_FAILED);
        return MICROHIL_CHANNELS_ERROR;
    }
    if (microhil_process_all_on(cmd_property) == 0)
    {
        free(cmd_property);
        return MICROHIL_ALL_CHANNELS_ON;
    }
    if (microhil_process_all_off(cmd_property) == 0)
    {
        free(cmd_property);
        return MICROHIL_ALL_CHANNELS_OFF;
    }
    for (int i = 0; i < MICROHIL_NUMBER_OF_CHANNELS; i++)
    {
        if (microhil_process_channel_on(cmd_property, i) == 0)
        {
            free(cmd_property);
            return index_to_gpio(i);
        }
        if (microhil_process_channel_off(cmd_property, i) == 0)
        {
            free(cmd_property);
            return index_to_gpio(i);
        }
    }
    free(cmd_property);
    printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_NO_SUPPORT);
    return MICROHIL_CHANNELS_ERROR;
}
References index_to_gpio(), MICROHIL_ALL_CHANNELS_OFF, MICROHIL_ALL_CHANNELS_ON, MICROHIL_CHANNEL_ERROR, MICROHIL_CHANNELS_ERROR, MICROHIL_EXT_PROP_FAILED, microhil_extract_command_property(), MICROHIL_NO_SUPPORT, MICROHIL_NUMBER_OF_CHANNELS, microhil_process_all_off(), microhil_process_all_on(), microhil_process_channel_off(), and microhil_process_channel_on().
Referenced by main().
microhil_write_pixel()
void microhil_write_pixel (uint32_t pixel_rgb)
Write 32-bit RGB value to PIO state machine.
Parameters
pixel_rgb is 32-bit RGB value
Definition at line 24 of file channel_led.c.
{
    pio_sm_put_blocking(pio0, 0, pixel_rgb << 8u);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().
urgb_u32()
uint32_t urgb_u32 (uint8_t red, uint8_t green, uint8_t blue)
Generate 32-bit RGB value.
Parameters
red color value
green color value
blue color value
Returns
32-bit RGB value
Definition at line 35 of file channel_led.c.
{
    return ((uint32_t)(red) << 8) |
           ((uint32_t)(green) << 16) |
           (uint32_t)(blue);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().