microhil-device0: src/channel/microhil_channel_utils.c File Reference
microhil_channel_utils.c File Reference
#include "microhil_channel.h"
Functions
void put_pixel (uint32_t pixel_grb)
uint32_t urgb_u32 (uint8_t r, uint8_t g, uint8_t b)
void microhil_write_pwm (uint8_t value)
Function Documentation
microhil_write_pwm()
void microhil_write_pwm (uint8_t value)
Parameters
value
Definition at line 45 of file microhil_channel_utils.c.
{
    if (value < 0 || value > 100)
    {
        printf("microhil_write_pwm Error \r\n");
    }
    else
    {
        pwm_set_chan_level(slice_num, PWM_CHAN_A, value);
    }
}
References slice_num.
Referenced by microhil_all_channels_on(), and microhil_channel_switch().
put_pixel()
void put_pixel (uint32_t pixel_grb)
Parameters
pixel_grb
Definition at line 24 of file microhil_channel_utils.c.
{
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().
urgb_u32()
uint32_t urgb_u32 (uint8_t r, uint8_t g, uint8_t b)
Parameters
r
g
b
Returns
Definition at line 35 of file microhil_channel_utils.c.
{
    return ((uint32_t)(r) << 8) |
           ((uint32_t)(g) << 16) |
           (uint32_t)(b);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().