microhildesk: MHController Class Reference
MHController Class Reference
MHController class is implementation of controller.
#include <microhil_controller.h>
Public Member Functions
MHController (SPtr< IMHModel > model, SPtr< IMHView > view)
MHController constructor.
~MHController () noexcept=default
MHController destructor.
void setEnabled (bool switchController) final
Enables controller (enable/disable communication)
bool isEnabled () const final
Checks is controller enabled (is serial communication enabled)
Private Member Functions
void mapping () final
Maps views and backend (signals and slots)
void onLogSettingsChanged (UString &path, int level) final
Slot for processing log settings changes.
void onLogSettingsLoaded (UString &path, int level) final
Slot for processing log settings loaded.
void onSerialSettingsChanged (UString &dev, VecUInt &params) final
Slot for processing serial settings changes.
void onSerialSettingsLoaded (UString &dev, VecUInt &params) final
Slot for processing serial settings changes.
void onSerialControlChanged (bool state) final
Slot for processing serial port changes.
Private Attributes
bool m_enabled {false}
Enable/Disable state of controller.
SPtr< IMHModel > m_model {nullptr}
Model instance.
SPtr< IMHView > m_view {nullptr}
View instance.
SPtr< IMHConfig > m_config {nullptr}
Configuration instance.
SPtr< IMHLog > m_log {nullptr}
Log instance.
SPtr< IMHCom > m_serial {nullptr}
Serial port instance.
Detailed Description
MHController class is implementation of controller.
Definition at line 30 of file microhil_controller.h.
Constructor & Destructor Documentation
MHController()
MHController::MHController (SPtr< IMHModel > model, SPtr< IMHView > view) explicit
MHController constructor.
Parameters
model represents model instance
view represents view instance
Maps views and backend (signals and slots)
Checks existance of configuration
Loads configuration from file
Sets log file destination from configuration
Sets log level from configuration
Definition at line 21 of file microhil_controller.cc.
    : m_model{model}
    , m_view{view}
    , m_config{makeSPtr<MHConfig>()}
    , m_log{makeSPtr<MHLog>()}
    , m_serial{makeSPtr<MHSerialCom>()}
{
    mapping();
    if (!m_config->isPreValid())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    if (!m_config->load())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    m_log->setFilePath(m_config->getLogPath());
    m_log->setLogLevel(m_config->getLogLevel());
    if (!m_log->open())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
}
References m_config, m_log, and mapping().
~MHController()
MHController::~MHController () inline default noexcept
MHController destructor.
Member Function Documentation
isEnabled()
bool MHController::isEnabled () const final virtual
Checks is controller enabled (is serial communication enabled)
Returns
status true for enabled else false
Checks is controller enabled
Implements IMHController.
Definition at line 82 of file microhil_controller.cc.
{
    return m_enabled;
}
References m_enabled.
mapping()
void MHController::mapping () final private virtual
Maps views and backend (signals and slots)
Maps log settings signal from configuration with controller slot
Maps serial settings signal from configuration with controller slot
Maps log view signal with controller slot
Maps serial view signal with controller slot
Maps view signal and controller slot
Implements IMHController.
Definition at line 21 of file microhil_controller_map.cc.
{
    m_config->LogConfigLoaded().connect(
        sigc::mem_fun(*this, &MHController::onLogSettingsLoaded)
    );
    m_config->SerialConfigLoaded().connect(
        sigc::mem_fun(*this, &MHController::onSerialSettingsLoaded)
    );
    m_view->getLogSettings()->logSetupChanged().connect(
        sigc::mem_fun(*this, &MHController::onLogSettingsChanged)
    );
    m_view->getSerialSettings()->serialSetupChanged().connect(
        sigc::mem_fun(*this, &MHController::onSerialSettingsChanged)
    );
    m_view->serialControlChanged().connect(
        sigc::mem_fun(*this, &MHController::onSerialControlChanged)
    );
}
References m_config, m_view, onLogSettingsChanged(), onLogSettingsLoaded(), onSerialControlChanged(), onSerialSettingsChanged(), and onSerialSettingsLoaded().
Referenced by MHController().
onLogSettingsChanged()
void MHController::onLogSettingsChanged (UString & path, int level) final private virtual
Slot for processing log settings changes.
Parameters
path represents absolute path of log file
level represents level for logging messages
Updates the log configuration
Updates log handler
Implements IMHController.
Definition at line 21 of file microhil_controller_slots.cc.
{
    m_config->setLogPath(path);
    m_config->setLogLevel(level);
    if (!m_config->store())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    if (!m_log->close())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    m_log->setFilePath(path);
    m_log->setLogLevel(level);
    if (!m_log->open())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    // TODO
    // logging
}
References m_config, and m_log.
Referenced by mapping().
onLogSettingsLoaded()
void MHController::onLogSettingsLoaded (UString & path, int level) final private virtual
Slot for processing log settings loaded.
Parameters
path represents absolute path of log file
logLevel represents level for logging messages
Implements IMHController.
Definition at line 67 of file microhil_controller_slots.cc.
{
    m_view->getLogSettings()->logSettingsLoaded(path, level);
}
References m_view.
Referenced by mapping().
onSerialControlChanged()
void MHController::onSerialControlChanged (bool state) final private virtual
Slot for processing serial port changes.
Parameters
state true for enable port, else false
Implements IMHController.
Definition at line 106 of file microhil_controller_slots.cc.
{
    if (state)
    {
        VecUInt serialParams{};
        serialParams.push_back(m_config->getBaudRate());
        serialParams.push_back(m_config->getDataBits());
        serialParams.push_back(
            m_config->parityUnicodeStringToInt(m_config->getParity())
        );
        serialParams.push_back(m_config->getStopBits());
        m_serial->setup(m_config->getDevice(), serialParams);
        // TODO
        // logging
    }
    else
    {
        m_serial->close();
    }
}
References m_config, and m_serial.
Referenced by mapping().
onSerialSettingsChanged()
void MHController::onSerialSettingsChanged (UString & dev, VecUInt & params) final private virtual
Slot for processing serial settings changes.
Parameters
dev represents file path for serial device
params represents set of serial parameters
Updates the serial port configuration Note: Glib::KeyFile store only signed integers
Updates serial handler
Implements IMHController.
Definition at line 72 of file microhil_controller_slots.cc.
{
    m_config->setDevice(dev);
    m_config->setBaudRate(static_cast<int>(params[0]));
    m_config->setDataBits(static_cast<int>(params[1]));
    m_config->setParity(static_cast<int>(params[2]));
    m_config->setStopBits(static_cast<int>(params[3]));
    if (!m_config->store())
    {
        // TODO
        // Emit signal for error handler
        // TODO
        // logging
        return;
    }
    m_serial->setup(dev, params);
    // TODO
    // logging
}
References m_config, and m_serial.
Referenced by mapping().
onSerialSettingsLoaded()
void MHController::onSerialSettingsLoaded (UString & dev, VecUInt & params) final private virtual
Slot for processing serial settings changes.
Parameters
dev represents file path for serial device
params represents set of serial parameters
Implements IMHController.
Definition at line 101 of file microhil_controller_slots.cc.
{
    m_view->getSerialSettings()->serialSettingsLoaded(dev, params);
}
References m_view.
Referenced by mapping().
setEnabled()
void MHController::setEnabled (bool switchController) final virtual
Enables controller (enable/disable communication)
Parameters
switchController represents requested enable value
Sets controller state (enabled - true, or disabled - false)
Implements IMHController.
Definition at line 75 of file microhil_controller.cc.
{
    m_enabled = switchController;
}
References m_enabled.
Member Data Documentation
m_config
SPtr<IMHConfig> MHController::m_config {nullptr} private
Configuration instance.
Definition at line 101 of file microhil_controller.h.
Referenced by mapping(), MHController(), onLogSettingsChanged(), onSerialControlChanged(), and onSerialSettingsChanged().
m_enabled
bool MHController::m_enabled {false} private
Enable/Disable state of controller.
Definition at line 89 of file microhil_controller.h.
Referenced by isEnabled(), and setEnabled().
m_log
SPtr<IMHLog> MHController::m_log {nullptr} private
Log instance.
Definition at line 105 of file microhil_controller.h.
Referenced by MHController(), and onLogSettingsChanged().
m_model
SPtr<IMHModel> MHController::m_model {nullptr} private
Model instance.
Definition at line 93 of file microhil_controller.h.
m_serial
SPtr<IMHCom> MHController::m_serial {nullptr} private
Serial port instance.
Definition at line 109 of file microhil_controller.h.
Referenced by onSerialControlChanged(), and onSerialSettingsChanged().
m_view
SPtr<IMHView> MHController::m_view {nullptr} private
View instance.
Definition at line 97 of file microhil_controller.h.
Referenced by mapping(), onLogSettingsLoaded(), and onSerialSettingsLoaded().
The documentation for this class was generated from the following files:
controller/microhil_controller.h
controller/microhil_controller.cc
controller/microhil_controller_map.cc
controller/microhil_controller_slots.cc