microhildesk: MicroHILViewLog Class Reference
MicroHILViewLog Class Reference
MicroHILViewLog class declaration and definition.
#include <microhil_view_log.h>
Public Member Functions
MicroHILViewLog (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
MicroHILViewLog constructor.
~MicroHILViewLog ()=default
MicroHILViewLog destructor.
SigLogSetup logSetupChanged () final
Signal for log settings.
SigLogFilePath logFilePathChanged () final
Signal for log file path input.
void onLogFilePathChanged () final
Slot for processing log file path input.
SigSelectLogLevel logLevelChanged () final
Signal for log level combobox.
void onLogLevelChanged () final
Slot for processing log level combobox.
SigCancelLog cancelLogTriggered () final
Signal for Cancel button.
SigOkLog okLogTriggered () final
Signal for Ok button.
void onCancelLogTriggered () final
Slot for processing Cancel button.
void onOkLogTriggered () final
Slot for processing Ok button.
void logSettingsLoaded (MHString filePath, int logLevel)
Set loaded parameters for log settings view.
Public Member Functions inherited from AbMicroHILViewLog
virtual ~AbMicroHILViewLog ()=default
AbMicroHILViewLog destructor.
virtual SigLogSetup logSetupChanged ()=0
Signal for log settings.
virtual SigLogFilePath logFilePathChanged ()=0
Signal for log file path input.
virtual void onLogFilePathChanged ()=0
Slot for processing log file path input.
virtual SigSelectLogLevel logLevelChanged ()=0
Signal for log level combobox.
virtual void onLogLevelChanged ()=0
Slot for processing log level combobox.
virtual SigCancelLog cancelLogTriggered ()=0
Signal for Cancel button.
virtual SigOkLog okLogTriggered ()=0
Signal for Ok button.
virtual void onCancelLogTriggered ()=0
Slot for processing Cancel button.
virtual void onOkLogTriggered ()=0
Slot for processing Ok button.
Private Member Functions
void mapping ()
Map all widgets (signals and slots)
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui {nullptr}
UI builder instance.
Glib::RefPtr< Gtk::Entry > m_device {nullptr}
UI entry for setting file log path.
Glib::RefPtr< Gtk::ComboBoxText > m_level {nullptr}
Combobox for selecting log level type.
Glib::RefPtr< Gtk::Button > m_cancel {nullptr}
Cancel button.
Glib::RefPtr< Gtk::Button > m_ok {nullptr}
Confirm button.
SigLogSetup m_logSetup {}
Signal for log settings.
SigLogFilePath m_logFilePath {}
Signal for log file path input.
SigSelectLogLevel m_logLevel {}
Signal for log level combobox.
SigCancelLog m_cancelLog {}
Signal for Cancel button (dismiss)
SigOkLog m_okLog {}
Signal for Ok button (confirm)
Additional Inherited Members
Public Types inherited from AbMicroHILViewLog
using SigLogSetup = sigc::signal< void(MHString, int)>
Signal type for log settings.
using SigLogFilePath = sigc::signal< void(MHString)>
Signal type for log file path input.
using SigSelectLogLevel = sigc::signal< void(int)>
Signal type for log level combobox.
using SigCancelLog = sigc::signal< void(bool)>
Signal type for Cancel button (dismiss)
using SigOkLog = sigc::signal< void(bool)>
Signal type for Ok button (confirm)
Detailed Description
MicroHILViewLog class declaration and definition.
Definition at line 30 of file microhil_view_log.h.
Constructor & Destructor Documentation
MicroHILViewLog()
MicroHILViewLog::MicroHILViewLog (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
MicroHILViewLog constructor.
Parameters
object base object instance
ui bulder instance
Bind Log file path entry
Bind Log level combobox
Bind Cancel button
Bind Ok button
Map all widgets (signals and slots)
Hide Log Settings by default
Definition at line 40 of file microhil_view_log.cc.
 : Gtk::Dialog(object), m_ui{ui}
{
    m_device = Glib::RefPtr<Gtk::Entry>::cast_dynamic(
        m_ui->get_object(kLogDevicePathId)
    );
    m_level = Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
        m_ui->get_object(kLogLevelSelectorId)
    );
    m_cancel = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kCancelButtonId)
    );
    m_ok = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kOkButtonId)
    );
    mapping();
    this->hide();
}
References m_cancel, m_device, m_level, m_ok, m_ui, and mapping().
~MicroHILViewLog()
MicroHILViewLog::~MicroHILViewLog () default
MicroHILViewLog destructor.
Member Function Documentation
cancelLogTriggered()
MicroHILViewLog::SigCancelLog MicroHILViewLog::cancelLogTriggered () final virtual
Signal for Cancel button.
Returns
Signal for clicked Cancel button
Implements AbMicroHILViewLog.
Definition at line 36 of file microhil_view_log_signals.cc.
{
    return m_cancelLog;
}
References m_cancelLog.
logFilePathChanged()
MicroHILViewLog::SigLogFilePath MicroHILViewLog::logFilePathChanged () final virtual
Signal for log file path input.
Returns
Signal for changed log file path entry
Implements AbMicroHILViewLog.
Definition at line 26 of file microhil_view_log_signals.cc.
{
    return m_logFilePath;
}
References m_logFilePath.
logLevelChanged()
MicroHILViewLog::SigSelectLogLevel MicroHILViewLog::logLevelChanged () final virtual
Signal for log level combobox.
Returns
Signal for selected log level combobox
Implements AbMicroHILViewLog.
Definition at line 31 of file microhil_view_log_signals.cc.
{
    return m_logLevel;
}
References m_logLevel.
logSettingsLoaded()
void MicroHILViewLog::logSettingsLoaded (MHString filePath, int logLevel)
Set loaded parameters for log settings view.
Parameters
filePath is absolute log file path
logLevel is level for logging
Definition at line 77 of file microhil_view_log.cc.
{
    m_device->set_text(filePath);
    m_level->set_active(logLevel);
}
References m_device, and m_level.
logSetupChanged()
MicroHILViewLog::SigLogSetup MicroHILViewLog::logSetupChanged () final virtual
Signal for log settings.
Returns
Signal for changed log settings
Implements AbMicroHILViewLog.
Definition at line 21 of file microhil_view_log_signals.cc.
{
    return m_logSetup;
}
References m_logSetup.
mapping()
void MicroHILViewLog::mapping () private
Map all widgets (signals and slots)
Map all widgets (signals and slots)
Definition at line 21 of file microhil_view_log_map.cc.
{
    m_device->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewLog::onLogFilePathChanged)
    );
    m_level->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewLog::onLogLevelChanged)
    );
    m_cancel->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewLog::onCancelLogTriggered)
    );
    m_ok->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewLog::onOkLogTriggered)
    );
}
References m_cancel, m_device, m_level, m_ok, onCancelLogTriggered(), onLogFilePathChanged(), onLogLevelChanged(), and onOkLogTriggered().
Referenced by MicroHILViewLog().
okLogTriggered()
MicroHILViewLog::SigOkLog MicroHILViewLog::okLogTriggered () final virtual
Signal for Ok button.
Returns
Signal for clicked Ok button
Implements AbMicroHILViewLog.
Definition at line 41 of file microhil_view_log_signals.cc.
{
    return m_okLog;
}
References m_okLog.
onCancelLogTriggered()
void MicroHILViewLog::onCancelLogTriggered () final virtual
Slot for processing Cancel button.
Implements AbMicroHILViewLog.
Definition at line 38 of file microhil_view_log_slots.cc.
{
    this->hide();
}
Referenced by mapping().
onLogFilePathChanged()
void MicroHILViewLog::onLogFilePathChanged () final virtual
Slot for processing log file path input.
Implements AbMicroHILViewLog.
Definition at line 22 of file microhil_view_log_slots.cc.
{
    auto logPath = m_device->get_text();
    auto logPathExists = std::filesystem::exists(std::string(logPath));
    if(logPathExists)
    {
        // TODO Dialog message box with confirmation
    }
}
References m_device.
Referenced by mapping().
onLogLevelChanged()
void MicroHILViewLog::onLogLevelChanged () final virtual
Slot for processing log level combobox.
Implements AbMicroHILViewLog.
Definition at line 33 of file microhil_view_log_slots.cc.
{
    // TODO
}
Referenced by mapping().
onOkLogTriggered()
void MicroHILViewLog::onOkLogTriggered () final virtual
Slot for processing Ok button.
Emit new log settings
Implements AbMicroHILViewLog.
Definition at line 43 of file microhil_view_log_slots.cc.
{
    auto logPath = m_device->get_text();
    auto logLevel = m_level->get_active_row_number();
    m_logSetup.emit(logPath, logLevel);
    this->hide();
}
References m_device, m_level, and m_logSetup.
Referenced by mapping().
Member Data Documentation
m_cancel
Glib::RefPtr<Gtk::Button> MicroHILViewLog::m_cancel {nullptr} private
Cancel button.
Definition at line 111 of file microhil_view_log.h.
Referenced by mapping(), and MicroHILViewLog().
m_cancelLog
SigCancelLog MicroHILViewLog::m_cancelLog {} private
Signal for Cancel button (dismiss)
Definition at line 131 of file microhil_view_log.h.
Referenced by cancelLogTriggered().
m_device
Glib::RefPtr<Gtk::Entry> MicroHILViewLog::m_device {nullptr} private
UI entry for setting file log path.
Definition at line 103 of file microhil_view_log.h.
Referenced by logSettingsLoaded(), mapping(), MicroHILViewLog(), onLogFilePathChanged(), and onOkLogTriggered().
m_level
Glib::RefPtr<Gtk::ComboBoxText> MicroHILViewLog::m_level {nullptr} private
Combobox for selecting log level type.
Definition at line 107 of file microhil_view_log.h.
Referenced by logSettingsLoaded(), mapping(), MicroHILViewLog(), and onOkLogTriggered().
m_logFilePath
SigLogFilePath MicroHILViewLog::m_logFilePath {} private
Signal for log file path input.
Definition at line 123 of file microhil_view_log.h.
Referenced by logFilePathChanged().
m_logLevel
SigSelectLogLevel MicroHILViewLog::m_logLevel {} private
Signal for log level combobox.
Definition at line 127 of file microhil_view_log.h.
Referenced by logLevelChanged().
m_logSetup
SigLogSetup MicroHILViewLog::m_logSetup {} private
Signal for log settings.
Definition at line 119 of file microhil_view_log.h.
Referenced by logSetupChanged(), and onOkLogTriggered().
m_ok
Glib::RefPtr<Gtk::Button> MicroHILViewLog::m_ok {nullptr} private
Confirm button.
Definition at line 115 of file microhil_view_log.h.
Referenced by mapping(), and MicroHILViewLog().
m_okLog
SigOkLog MicroHILViewLog::m_okLog {} private
Signal for Ok button (confirm)
Definition at line 135 of file microhil_view_log.h.
Referenced by okLogTriggered().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILViewLog::m_ui {nullptr} private
UI builder instance.
Definition at line 99 of file microhil_view_log.h.
Referenced by MicroHILViewLog().
The documentation for this class was generated from the following files:
view/settings/log/microhil_view_log.h
view/settings/log/microhil_view_log.cc
view/settings/log/microhil_view_log_map.cc
view/settings/log/microhil_view_log_signals.cc
view/settings/log/microhil_view_log_slots.cc