microhil-device0: src/io_config/io_config.c File Reference
io_config.c File Reference
#include "io_config_info.h"
#include "io_config_error.h"
#include "io_config.h"
Functions
void microhil_gpio_mode (uint16_t pin, uint16_t mode)
Setting port pin configuration.
void microhil_digital_write (uint16_t pin, uint8_t value)
Drive GPIO pin.
uint8_t microhil_digital_read (uint16_t pin)
Get GPIO state.
void microhil_spi_write_byte (uint8_t value)
Write byte to an SPI device (blocking)
void microhil_spi_write_n_bytes (uint8_t *data, uint32_t len)
Write n bytes to an SPI device (blocking)
void microhil_i2c_write_byte (uint8_t addr, uint8_t reg, uint8_t value)
Send byte to i2c device.
void microhil_i2c_write_n_bytes (uint8_t addr, uint8_t *data, uint32_t len)
Send n bytes to i2c device.
uint8_t microhil_i2c_read_byte (uint8_t addr, uint8_t reg)
Read byte from i2c bus device.
void microhil_delay_ms (uint32_t ms)
Delay in miliseconds.
void microhil_delay_us (uint32_t us)
Delay in microseconds.
void microhil_gpio_init ()
Private function for initialization reserved pins.
void microhil_set_pwm_1 (uint8_t value)
Set the current PWM counter compare value for one channel.
bool microhil_module_init ()
PWM, I2C, SPI modules initialization.
bool microhil_module_exit ()
Perform actions on exit.
Variables
int epd_rst_pin
TODO.
int epd_dc_pin
TODO.
int epd_cs_pin
TODO.
int epd_bl_pin
TODO.
int epd_clk_pin
TODO.
int epd_mosi_pin
TODO.
int epd_scl_pin
TODO.
int epd_sda_pin
TODO.
uint slice_num
TODO.
Function Documentation
microhil_delay_ms()
void microhil_delay_ms (uint32_t ms)
Delay in miliseconds.
Parameters
ms is number of miliseconds to sleep
Definition at line 152 of file io_config.c.
{
    sleep_ms(ms);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), and microhil_channel_switch().
microhil_delay_us()
void microhil_delay_us (uint32_t us)
Delay in microseconds.
Parameters
us is number of microseconds to sleep
Definition at line 160 of file io_config.c.
{
    sleep_us(us);
}
microhil_digital_read()
uint8_t microhil_digital_read (uint16_t pin)
Get GPIO state.
Parameters
pin is GPIO pin number
Returns
state of GPIO pin
Definition at line 90 of file io_config.c.
{
    return gpio_get(pin);
}
microhil_digital_write()
void microhil_digital_write (uint16_t pin, uint8_t value)
Drive GPIO pin.
Parameters
pin is GPIO number
value is GPIO value (true - set | false - clear)
Definition at line 81 of file io_config.c.
{
    gpio_put(pin, value);
}
Referenced by microhil_gpio_init().
microhil_gpio_init()
void microhil_gpio_init ()
Private function for initialization reserved pins.
Definition at line 167 of file io_config.c.
{
    microhil_gpio_mode(epd_rst_pin, 1);
    microhil_gpio_mode(epd_dc_pin, 1);
    microhil_gpio_mode(epd_cs_pin, 1);
    microhil_gpio_mode(epd_bl_pin, 1);
    microhil_gpio_mode(epd_cs_pin, 1);
    microhil_gpio_mode(epd_bl_pin, 1);
    microhil_digital_write(epd_cs_pin, 1);
    microhil_digital_write(epd_dc_pin, 0);
    microhil_digital_write(epd_bl_pin, 1);
}
References epd_bl_pin, epd_cs_pin, epd_dc_pin, epd_rst_pin, microhil_digital_write(), and microhil_gpio_mode().
Referenced by microhil_module_init().
microhil_gpio_mode()
void microhil_gpio_mode (uint16_t pin, uint16_t mode)
Setting port pin configuration.
Parameters
pin is GPIO pin number
mode is GPIO pin direction (GPIO_IN | GPIO_OUT)
Definition at line 63 of file io_config.c.
{
    gpio_init(pin);
    if (mode == 0 || mode == GPIO_IN)
    {
        gpio_set_dir(pin, GPIO_IN);
    }
    else
    {
        gpio_set_dir(pin, GPIO_OUT);
    }
}
Referenced by microhil_gpio_init().
microhil_i2c_read_byte()
uint8_t microhil_i2c_read_byte (uint8_t addr, uint8_t reg)
Read byte from i2c bus device.
Parameters
addr is address of device
reg is data to send
Returns
byte from i2c device
Definition at line 139 of file io_config.c.
{
    uint8_t buffer;
    i2c_write_blocking(MICROHIL_I2C_PORT_1, addr, &reg, 1, true);
    i2c_read_blocking(MICROHIL_I2C_PORT_1, addr, &buffer, 1, false);
    return buffer;
}
References MICROHIL_I2C_PORT_1.
microhil_i2c_write_byte()
void microhil_i2c_write_byte (uint8_t addr, uint8_t reg, uint8_t value)
Send byte to i2c device.
Send data to i2c device.
Parameters
addr is address of device
reg is register destination
value is byte to send
Definition at line 117 of file io_config.c.
{
    uint8_t data[2] = {reg, value};
    i2c_write_blocking(MICROHIL_I2C_PORT_1, addr, data, 2, false);
}
References MICROHIL_I2C_PORT_1.
microhil_i2c_write_n_bytes()
void microhil_i2c_write_n_bytes (uint8_t addr, uint8_t * data, uint32_t len)
Send n bytes to i2c device.
Parameters
addr is address of device
data to send
len is length of data to send
Definition at line 129 of file io_config.c.
{
    i2c_write_blocking(MICROHIL_I2C_PORT_1, addr, data, len, false);
}
References MICROHIL_I2C_PORT_1.
microhil_module_exit()
bool microhil_module_exit ()
Perform actions on exit.
Returns
true for success else false
Definition at line 248 of file io_config.c.
{
    return true;
}
microhil_module_init()
bool microhil_module_init ()
PWM, I2C, SPI modules initialization.
Returns
true for success else false
Failed to perform initialization for stdio types
Definition at line 199 of file io_config.c.
{
    bool status = false;
    status = stdio_init_all();
    if (!status)
    {
        return status;
    }
    epd_rst_pin = 12;
    epd_dc_pin = 8;
    epd_bl_pin = 6;
    epd_cs_pin = 9;
    epd_clk_pin = 10;
    epd_mosi_pin = 11;
    epd_scl_pin = 7;
    epd_sda_pin = 6;
    spi_init(MICROHIL_SPI_PORT_1, 1000 * 1000);
    gpio_set_function(epd_clk_pin, GPIO_FUNC_SPI);
    gpio_set_function(epd_mosi_pin, GPIO_FUNC_SPI);
    microhil_gpio_init();
    gpio_set_function(epd_bl_pin, GPIO_FUNC_PWM);
    slice_num = pwm_gpio_to_slice_num(epd_bl_pin);
    pwm_set_wrap(slice_num, 100);
    pwm_set_chan_level(slice_num, PWM_CHAN_B, 1);
    pwm_set_clkdiv(slice_num, 50);
    pwm_set_enabled(slice_num, true);
    i2c_init(MICROHIL_I2C_PORT_1, 100 * 1000);
    gpio_set_function(epd_sda_pin, GPIO_FUNC_I2C);
    gpio_set_function(epd_scl_pin, GPIO_FUNC_I2C);
    gpio_pull_up(epd_sda_pin);
    gpio_pull_up(epd_scl_pin);
    printf("%s %s\n", MICROHIL_IO_CONFIG_INFO, MICROHIL_MODULE_INIT_OK);
    return status;
}
References epd_bl_pin, epd_clk_pin, epd_cs_pin, epd_dc_pin, epd_mosi_pin, epd_rst_pin, epd_scl_pin, epd_sda_pin, microhil_gpio_init(), MICROHIL_I2C_PORT_1, MICROHIL_IO_CONFIG_INFO, MICROHIL_MODULE_INIT_OK, MICROHIL_SPI_PORT_1, and slice_num.
microhil_set_pwm_1()
void microhil_set_pwm_1 (uint8_t value)
Set the current PWM counter compare value for one channel.
Parameters
value is new value for selected output
Definition at line 184 of file io_config.c.
{
    if (value < 0 || value > 100)
    {
        printf("%s %s\n", MICROHIL_IO_CONFIG_ERROR, MICROHIL_PWM_SET_ERROR);
    }
    else
    {
        pwm_set_chan_level(slice_num, PWM_CHAN_B, value);
    }
}
References MICROHIL_IO_CONFIG_ERROR, MICROHIL_PWM_SET_ERROR, and slice_num.
microhil_spi_write_byte()
void microhil_spi_write_byte (uint8_t value)
Write byte to an SPI device (blocking)
Parameters
value is byte for write
Definition at line 98 of file io_config.c.
{
    spi_write_blocking(MICROHIL_SPI_PORT_1, &value, 1);
}
References MICROHIL_SPI_PORT_1.
microhil_spi_write_n_bytes()
void microhil_spi_write_n_bytes (uint8_t * data, uint32_t len)
Write n bytes to an SPI device (blocking)
Parameters
data is buffer for write
len is length of buffer to write
Definition at line 107 of file io_config.c.
{
    spi_write_blocking(MICROHIL_SPI_PORT_1, data, len);
}
References MICROHIL_SPI_PORT_1.
Variable Documentation
epd_bl_pin
int epd_bl_pin
TODO.
Definition at line 37 of file io_config.c.
Referenced by microhil_gpio_init(), and microhil_module_init().
epd_clk_pin
int epd_clk_pin
TODO.
Definition at line 41 of file io_config.c.
Referenced by microhil_module_init().
epd_cs_pin
int epd_cs_pin
TODO.
Definition at line 33 of file io_config.c.
Referenced by microhil_gpio_init(), and microhil_module_init().
epd_dc_pin
int epd_dc_pin
TODO.
Definition at line 29 of file io_config.c.
Referenced by microhil_gpio_init(), and microhil_module_init().
epd_mosi_pin
int epd_mosi_pin
TODO.
Definition at line 45 of file io_config.c.
Referenced by microhil_module_init().
epd_rst_pin
int epd_rst_pin
TODO.
Definition at line 25 of file io_config.c.
Referenced by microhil_gpio_init(), and microhil_module_init().
epd_scl_pin
int epd_scl_pin
TODO.
Definition at line 49 of file io_config.c.
Referenced by microhil_module_init().
epd_sda_pin
int epd_sda_pin
TODO.
Definition at line 53 of file io_config.c.
Referenced by microhil_module_init().
slice_num
uint slice_num
TODO.
Definition at line 57 of file io_config.c.
Referenced by microhil_init_pwm(), microhil_module_init(), microhil_set_pwm_1(), and microhil_write_pwm().