microhil-device0: src/channel/microhil_channel_action.c File Reference
microhil_channel_action.c File Reference
#include "microhil_channel.h"
Functions
void microhil_all_channels_on ()
void microhil_all_channels_off ()
void microhil_channel_switch (int id)
unsigned int id_to_gpio (int id)
Function Documentation
id_to_gpio()
unsigned int id_to_gpio (int id)
Parameters
id
Returns
Definition at line 112 of file microhil_channel_action.c.
{
    switch (id)
    {
    case 1:
        return JDQ1;
    case 2:
        return JDQ2;
    case 3:
        return JDQ3;
    case 4:
        return JDQ4;
    case 5:
        return JDQ5;
    case 6:
        return JDQ6;
    case 7:
        return JDQ7;
    case 8:
        return JDQ8;
    case 9:
        return JDQ_ALL_OFF;
    case 10:
        return JDQ_ALL_ON;
    }
    return JDQ_ERROR;
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, JDQ_ALL_OFF, JDQ_ALL_ON, and JDQ_ERROR.
Referenced by microhil_channel_switch().
microhil_all_channels_off()
void microhil_all_channels_off ()
Definition at line 48 of file microhil_channel_action.c.
{
    gpio_put(JDQ8, 0);
    gpio_put(JDQ7, 0);
    gpio_put(JDQ6, 0);
    gpio_put(JDQ5, 0);
    gpio_put(JDQ4, 0);
    gpio_put(JDQ3, 0);
    gpio_put(JDQ2, 0);
    gpio_put(JDQ1, 0);
    printf("***Relay ALL off***\r\n\n");
    for (int i = 0; i < 8; i++)
    {
        Relays[i] = 0x1;
    }
    put_pixel(urgb_u32(0, 0, 0));
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, put_pixel(), Relays, and urgb_u32().
Referenced by microhil_channel_switch().
microhil_all_channels_on()
void microhil_all_channels_on ()
Definition at line 23 of file microhil_channel_action.c.
{
    gpio_put(JDQ8, 1);
    gpio_put(JDQ7, 1);
    gpio_put(JDQ6, 1);
    gpio_put(JDQ5, 1);
    gpio_put(JDQ4, 1);
    gpio_put(JDQ3, 1);
    gpio_put(JDQ2, 1);
    gpio_put(JDQ1, 1);
    printf("***Relay ALL on****\r\n\n");
    for (int i = 0; i < 8; i++)
    {
        Relays[i] = 0x0;
    }
    put_pixel(urgb_u32(255, 255, 255));
    microhil_write_pwm(80); // buzzer
    microhil_delay_ms(100);
    microhil_write_pwm(0);
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, microhil_delay_ms(), microhil_write_pwm(), put_pixel(), Relays, and urgb_u32().
Referenced by microhil_channel_switch().
microhil_channel_switch()
void microhil_channel_switch (int id)
Parameters
id
Definition at line 71 of file microhil_channel_action.c.
{
    unsigned int gpio = id_to_gpio(id);
    switch (gpio)
    {
    case JDQ_ALL_OFF:
        microhil_all_channels_off();
        break;
    case JDQ_ALL_ON:
        microhil_all_channels_on();
        break;
    case JDQ_ERROR:
        printf("****Error*****\r\n\n");
        break;
    default:
        // TODO check gpio value
        gpio_put(gpio, Relays[id - 1]);
        if (Relays[id - 1] == 1)
        {
            put_pixel(urgb_u32(255, 0, 0));
            microhil_write_pwm(80); // buzzer
            microhil_delay_ms(100);
            microhil_write_pwm(0);
            printf("****Relay 1 on*****\r\n\n");
        }
        else if (Relays[id - 1] == 0)
        {
            printf("****Relay 1 off*****\r\n\n");
        }
        Relays[id - 1] = !Relays[id - 1];
        break;
    }
}
References id_to_gpio(), JDQ_ALL_OFF, JDQ_ALL_ON, JDQ_ERROR, microhil_all_channels_off(), microhil_all_channels_on(), microhil_delay_ms(), microhil_write_pwm(), put_pixel(), Relays, and urgb_u32().
Referenced by main().