microhil-base: src/main.c File Reference
main.c File Reference
#include <string.h>
#include "tusb.h"
#include "pico/stdio_usb.h"
#include "channel.h"
Functions
int main ()
Main entry point for microhil-base.
Variables
bool new_request = false
Flag for received new request from the serial port.
bool receive_in_progress = false
Flag for marking receive in progress.
Function Documentation
main()
int main ()
Main entry point for microhil-base.
Returns
0 for success exit else 1 for failed exit
Performs device initialization
Failed to perform device initialization
Waits for USB connection
Command buffer for received request
Fetching channel command request
Clean up command buffer and flag for new request
Definition at line 35 of file main.c.
{
    bool status = microhil_init();
    if (!status)
    {
        return 1;
    }
    while (!tud_cdc_connected())
    {
        sleep_ms(100);
    }
    uint8_t request[MICROHIL_REQ_LEN] = {0};
    while (status)
    {
        microhil_fetch_request(request);
        if (!receive_in_progress && new_request)
        {
            microhil_channel_switch(request);
            memset(request, 0, MICROHIL_REQ_LEN * sizeof(uint8_t));
            new_request = false;
        }
    }
    return 0;
}
References microhil_channel_switch(), microhil_fetch_request(), microhil_init(), MICROHIL_REQ_LEN, new_request, and receive_in_progress.
Variable Documentation
new_request
bool new_request = false
Flag for received new request from the serial port.
Definition at line 26 of file main.c.
Referenced by main(), and microhil_fetch_request().
receive_in_progress
bool receive_in_progress = false
Flag for marking receive in progress.
Flog for receiving in progress.
Definition at line 30 of file main.c.
Referenced by main(), and microhil_fetch_request().