microhildesk: Electux::App::Model::ModelLog Class Reference
Electux::App::Model::ModelLog Class Reference
#include <model_log.h>
Public Types
enum class ModelLogKey { FilePath , LogLevel }
Enum for log configuration keys.
Public Member Functions
ModelLog () noexcept=default
ModelLog constructor.
Entities getAllEntries () const final
Gets all model entries.
std::string toString (const ModelLogKey &key) const
Converts ModelLogKey enum to string.
bool validateKey (const std::string &key) const
Validates if key is valid serial configuration key.
bool add (const std::string &key, const std::string &data) final
Adds entity to model {'key': 'data'}.
const std::string & getEntity (const std::string &key) const final
Gets entity by key.
const Entities & get () const final
Gets model entities.
void clear () final
Clears all model entities.
Private Attributes
Entities m_entities {}
Model entities in format map of strings {key: data}.
Detailed Description
Definition at line 25 of file model_log.h.
Member Enumeration Documentation
ModelLogKey
enum class Electux::App::Model::ModelLog::ModelLogKey strong
Enum for log configuration keys.
Enumerator
FilePath
LogLevel
Definition at line 34 of file model_log.h.
        {
            FilePath,
            LogLevel
        };
Constructor & Destructor Documentation
ModelLog()
Electux::App::Model::ModelLog::ModelLog () inline default noexcept
ModelLog constructor.
Member Function Documentation
add()
bool Model::add (const std::string & key, const std::string & data) final virtual inherited
Adds entity to model {'key': 'data'}.
Parameters
key Represents model enity key to be added
data Represents model entity data to be added
Implements Electux::App::Model::IModel.
Definition at line 23 of file model.cc.
{
    auto const [it, inserted] = m_entities.try_emplace(key, data);
    return inserted;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), Electux::App::View::Settings::AppSettings::getUiData(), and Electux::App::Config::ConfigManager::load().
clear()
void Model::clear () final virtual inherited
Clears all model entities.
Implements Electux::App::Model::IModel.
Definition at line 46 of file model.cc.
{
    m_entities.clear();
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::View::Settings::AppSettings::getUiData().
get()
const Entities & Model::get () const final virtual inherited
Gets model entities.
Returns
Model entities in format map of strings
Implements Electux::App::Model::IModel.
Definition at line 41 of file model.cc.
{
    return m_entities;
}
References Electux::App::Model::Model::m_entities.
getAllEntries()
Entities ModelLog::getAllEntries () const final virtual
Gets all model entries.
Returns
Map of all model entries {key: data}
Implements Electux::App::Model::IModel.
Definition at line 33 of file model_log.cc.
{
    static const std::vector<ModelLogKey> keys =
    {
        ModelLogKey::LogLevel, ModelLogKey::FilePath
    };
    Entities entries;
    for (const auto& key : keys)
    {
        std::string keyStr = toString(key);
        entries[keyStr] = getEntity(keyStr);
    }
    return entries;
}
References FilePath, Electux::App::Model::Model::getEntity(), LogLevel, and toString().
getEntity()
const std::string & Model::getEntity (const std::string & key) const final virtual inherited
Gets entity by key.
Parameters
key Represents model enity key
Returns
Entity selected by key
Implements Electux::App::Model::IModel.
Definition at line 29 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        return it->second;
    }
    static const std::string fallback{""};
    return fallback;
}
References Electux::App::Model::Model::m_entities.
Referenced by getAllEntries(), Electux::App::Model::ModelSerial::getAllEntries(), and Electux::App::View::Settings::AppSettings::updateUiData().
toString()
std::string ModelLog::toString (const ModelLogKey & key) const
Converts ModelLogKey enum to string.
Parameters
key Represents ModelLogKey enum value
Returns
string representation of ModelLogKey enum
Definition at line 50 of file model_log.cc.
{
    switch (key)
    {
    case ModelLogKey::LogLevel: return logLevel.data();
    case ModelLogKey::FilePath: return filePath.data();
    default: return unknown.data();
    }
}
References FilePath, and LogLevel.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), getAllEntries(), Electux::App::View::Settings::AppSettings::getUiData(), Electux::App::View::Settings::AppSettings::updateUiData(), and validateKey().
validateKey()
bool ModelLog::validateKey (const std::string & key) const
Validates if key is valid serial configuration key.
Parameters
key Represents string key to be validated
Returns
status true if key is valid else false
Definition at line 60 of file model_log.cc.
{
    return key == toString(ModelLogKey::LogLevel) || key == toString(ModelLogKey::FilePath);
}
References FilePath, LogLevel, and toString().
Referenced by Electux::App::Config::ConfigManager::load().
Member Data Documentation
m_entities
Entities Electux::App::Model::Model::m_entities {} private inherited
Model entities in format map of strings {key: data}.
Definition at line 58 of file model.h.
{};
Referenced by Electux::App::Model::Model::add(), Electux::App::Model::Model::clear(), Electux::App::Model::Model::get(), and Electux::App::Model::Model::getEntity().
The documentation for this class was generated from the following files:
model/model_log.h
model/model_log.cc