microhildesk: MicroHILViewDialog Class Reference
MicroHILViewDialog Class Reference
MicroHILViewDialog class declaration and definition.
#include <microhil_view_dialog.h>
Public Member Functions
MicroHILViewDialog (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
MicroHILViewDialog constructor.
~MicroHILViewDialog ()=default
MicroHILViewDialog destructor.
closeDialog closeDialogChanged () final
Signals for emitting from dialog Close button.
void onCloseDialogChange () final
Slots for processing Close button for dialog.
void show (const Glib::ustring message, MessageType type) final
Show dialog with message.
void hide () final
Hide dialog.
Public Member Functions inherited from AbMicroHILViewDialog
virtual ~AbMicroHILViewDialog ()=default
AbMicroHILViewDialog destructor.
virtual closeDialog closeDialogChanged ()=0
Signals for emitting from dialog Close button.
virtual void onCloseDialogChange ()=0
Slots for processing Close button for dialog.
virtual void show (Glib::ustring message, MessageType type)=0
Show dialog with message.
virtual void hide ()=0
Hide dialog.
Private Member Functions
Glib::ustring toUnicodeStringMessageType (MessageType type) const
Conversion of message type to unicode string.
void mapping ()
Map Close button signal and slot.
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui
UI builder instance.
Glib::RefPtr< Gtk::Label > m_text
Dialog message text filed.
Glib::RefPtr< Gtk::Button > m_close
Close button for dialog message.
closeDialog m_closeDialog
Signal for emitting from Close button (hide about dialog)
Additional Inherited Members
Public Types inherited from AbMicroHILViewDialog
using closeDialog = sigc::signal< void(bool)>
Signal type for dialog Close button.
Detailed Description
MicroHILViewDialog class declaration and definition.
Definition at line 29 of file microhil_view_dialog.h.
Constructor & Destructor Documentation
MicroHILViewDialog()
MicroHILViewDialog::MicroHILViewDialog (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
MicroHILViewDialog constructor.
Parameters
object base object type
ui builder parser
Bind Dialog message
Bind Close button
Map signals and slots
Definition at line 44 of file microhil_view_dialog.cc.
 : Gtk::Dialog(object), m_ui{ui}
{
    m_text = Glib::RefPtr<Gtk::Label>::cast_dynamic(
        m_ui->get_object(kDialogMessage)
    );
    m_close = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kCloseButtonId)
    );
    mapping();
}
References m_close, m_text, m_ui, and mapping().
~MicroHILViewDialog()
MicroHILViewDialog::~MicroHILViewDialog () default
MicroHILViewDialog destructor.
Member Function Documentation
closeDialogChanged()
MicroHILViewDialog::closeDialog MicroHILViewDialog::closeDialogChanged () final virtual
Signals for emitting from dialog Close button.
Returns
signal after pressing Close button
Implements AbMicroHILViewDialog.
Definition at line 21 of file microhil_view_dialog_signals.cc.
{
    return m_closeDialog;
}
References m_closeDialog.
hide()
void MicroHILViewDialog::hide () final virtual
Hide dialog.
Implements AbMicroHILViewDialog.
Definition at line 72 of file microhil_view_dialog.cc.
{
}
Referenced by onCloseDialogChange().
mapping()
void MicroHILViewDialog::mapping () private
Map Close button signal and slot.
Definition at line 21 of file microhil_view_dialog_map.cc.
{
    m_close->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewDialog::onCloseDialogChange)
    );
}
References m_close, and onCloseDialogChange().
Referenced by MicroHILViewDialog().
onCloseDialogChange()
void MicroHILViewDialog::onCloseDialogChange () final virtual
Slots for processing Close button for dialog.
Implements AbMicroHILViewDialog.
Definition at line 21 of file microhil_view_dialog_slots.cc.
{
    hide();
}
References hide().
Referenced by mapping().
show()
void MicroHILViewDialog::show (const Glib::ustring message, MessageType type) final virtual
Show dialog with message.
Parameters
message for presenting
type of dialog message
Implements AbMicroHILViewDialog.
Definition at line 65 of file microhil_view_dialog.cc.
{
    const auto messageType = toUnicodeStringMessageType(type);
    this->set_title(messageType);
    m_text->set_text(message);
}
References m_text, and toUnicodeStringMessageType().
toUnicodeStringMessageType()
Glib::ustring MicroHILViewDialog::toUnicodeStringMessageType (MessageType type) const private
Conversion of message type to unicode string.
Parameters
type of dialog message
Returns
string representation of dialog message type
Definition at line 76 of file microhil_view_dialog.cc.
{
    switch(type)
    {
        case MessageType::INFO:
            return kInfoMessage;
        case MessageType::WARNING:
            return kWarningMessage;
        case MessageType::ERROR:
            return kErrorMessage;
    }
    return kInfoMessage;
}
References ERROR, INFO, and WARNING.
Referenced by show().
Member Data Documentation
m_close
Glib::RefPtr<Gtk::Button> MicroHILViewDialog::m_close private
Close button for dialog message.
Definition at line 84 of file microhil_view_dialog.h.
Referenced by mapping(), and MicroHILViewDialog().
m_closeDialog
closeDialog MicroHILViewDialog::m_closeDialog private
Signal for emitting from Close button (hide about dialog)
Definition at line 88 of file microhil_view_dialog.h.
Referenced by closeDialogChanged().
m_text
Glib::RefPtr<Gtk::Label> MicroHILViewDialog::m_text private
Dialog message text filed.
Definition at line 80 of file microhil_view_dialog.h.
Referenced by MicroHILViewDialog(), and show().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILViewDialog::m_ui private
UI builder instance.
Definition at line 76 of file microhil_view_dialog.h.
Referenced by MicroHILViewDialog().
The documentation for this class was generated from the following files:
view/dialog/microhil_view_dialog.h
view/dialog/microhil_view_dialog.cc
view/dialog/microhil_view_dialog_map.cc
view/dialog/microhil_view_dialog_signals.cc
view/dialog/microhil_view_dialog_slots.cc