microhildesk: MicroHILSerialCom Class Reference
MicroHILSerialCom Class Reference
MicroHILSerialCom class declaration and definition.
#include <microhil_serial_com.h>
Public Member Functions
MicroHILSerialCom ()
MicroHILCom constructor.
~MicroHILSerialCom ()
MicroHILCom destructor.
void open () final
Open the serial communication channel.
void close () final
Close the serial communication channel.
unsigned int baudRateToUInt (const BaudRate baudRate)
Convert baud-rate from scopped enumerator to unsigned int.
BaudRate uintToBaudRate (const unsigned int)
Convert baud-rate from unsigned int to scopped enumerator.
unsigned int dataBitsToUInt (const CharacterSize dataBits)
Convert data-bits from scopped enumerator to unsigned int.
CharacterSize uintToDataBits (const unsigned int dataBits)
Convert data-bits from unsigned int to scopped enumerator.
unsigned int parityToUInt (const Parity parity)
Convert parity from scopped enumerator to unsigned int.
Parity uintToParity (const unsigned int parity)
Convert parity from unsigned int to scopped enumerator.
unsigned int stopBitsToUInt (const StopBits stopBits)
Convert stop-bits from scopped enumerator to unsigned int.
StopBits uintToStopBits (const unsigned int stopBits)
Convert stop-bits from unsigned int to scopped enumerator.
void setup (MHString device, MHVecUInt params)
Setup the serial port parameters.
void setup (MHString device, MHSerialParams params)
Setup the serial port parameters.
void read (MHVecByte &data, size_t len, size_t timeout) final
Read from serial communication channel.
void write (MHVecByte &data) final
Write data to the serial communication channel.
Public Member Functions inherited from AbMicroHILCom
virtual ~AbMicroHILCom ()=default
AbMicroHILCom destructor.
virtual void open ()=0
Open communication channel.
virtual void close ()=0
Close communication channel.
virtual void read (MHVecByte &data, size_t len, size_t timeout)=0
Read from communication channel.
virtual void write (MHVecByte &data)=0
Write to communication channel.
Private Attributes
MHUPtr< SerialPort > m_serialPort {nullptr}
Serial port instance.
MHString m_device {}
Serial port device file path.
Detailed Description
MicroHILSerialCom class declaration and definition.
Definition at line 42 of file microhil_serial_com.h.
Constructor & Destructor Documentation
MicroHILSerialCom()
MicroHILSerialCom::MicroHILSerialCom ()
MicroHILCom constructor.
Definition at line 21 of file microhil_serial_com.cc.
                                    :
    m_serialPort{MHmakeUPtr<SerialPort>()}
{
    close();
}
References close().
~MicroHILSerialCom()
MicroHILSerialCom::~MicroHILSerialCom ()
MicroHILCom destructor.
Definition at line 27 of file microhil_serial_com.cc.
{
    close();
}
References close().
Member Function Documentation
baudRateToUInt()
unsigned int MicroHILSerialCom::baudRateToUInt (const BaudRate baudRate)
Convert baud-rate from scopped enumerator to unsigned int.
Parameters
baudRate in scoped enumerator value
Returns
unsigned integer format of baud-rate
Definition at line 61 of file microhil_serial_com_utils.cc.
{
    switch(baudRate)
    {
        case BaudRate::BAUD_50: return kInvalidParameter;
        case BaudRate::BAUD_75: return kInvalidParameter;
        case BaudRate::BAUD_110: return kBaud110;
        case BaudRate::BAUD_134: return kInvalidParameter;
        case BaudRate::BAUD_150: return kInvalidParameter;
        case BaudRate::BAUD_200: return kInvalidParameter;
        case BaudRate::BAUD_300: return kBaud300;
        case BaudRate::BAUD_600: return kBaud600;
        case BaudRate::BAUD_1200: return kBaud1200;
        case BaudRate::BAUD_1800: return kInvalidParameter;
        case BaudRate::BAUD_2400: return kBaud2400;
        case BaudRate::BAUD_4800: return kBaud4800;
        case BaudRate::BAUD_9600: return kBaud9600;
        case BaudRate::BAUD_19200: return kBaud19200;
        case BaudRate::BAUD_38400: return kBaud38400;
        case BaudRate::BAUD_57600: return kBaud57600;
        case BaudRate::BAUD_115200: return kBaud115200;
        case BaudRate::BAUD_230400: return kBaud230400;
        case BaudRate::BAUD_460800: return kInvalidParameter;
        case BaudRate::BAUD_500000: return kInvalidParameter;
        case BaudRate::BAUD_576000: return kInvalidParameter;
        case BaudRate::BAUD_921600: return kInvalidParameter;
        case BaudRate::BAUD_1000000: return kInvalidParameter;
        case BaudRate::BAUD_1152000: return kInvalidParameter;
        case BaudRate::BAUD_1500000: return kInvalidParameter;
        case BaudRate::BAUD_2000000: return kInvalidParameter;
        case BaudRate::BAUD_2500000: return kInvalidParameter;
        case BaudRate::BAUD_3000000: return kInvalidParameter;
        case BaudRate::BAUD_3500000: return kInvalidParameter;
        case BaudRate::BAUD_4000000: return kInvalidParameter;
        case BaudRate::BAUD_INVALID: return kInvalidParameter;
    }
    return kInvalidParameter;
}
close()
void MicroHILSerialCom::close () final virtual
Close the serial communication channel.
Implements AbMicroHILCom.
Definition at line 40 of file microhil_serial_com.cc.
{
    if(m_serialPort->IsOpen())
    {
        m_serialPort->Close();
    }
}
References m_serialPort.
Referenced by MicroHILSerialCom(), and ~MicroHILSerialCom().
dataBitsToUInt()
unsigned int MicroHILSerialCom::dataBitsToUInt (const CharacterSize dataBits)
Convert data-bits from scopped enumerator to unsigned int.
Parameters
dataBits in scoped enumerator value
Returns
unsigned integer format of data-bits
Definition at line 122 of file microhil_serial_com_utils.cc.
{
    switch(dataBits)
    {
        case CharacterSize::CHAR_SIZE_5: return kDataBits5;
        case CharacterSize::CHAR_SIZE_6: return kDataBits6;
        case CharacterSize::CHAR_SIZE_7: return kDataBits7;
        case CharacterSize::CHAR_SIZE_8: return kDataBits8;
        case CharacterSize::CHAR_SIZE_INVALID: return kInvalidParameter;
    }
    return kInvalidParameter;
}
References dataBits.
open()
void MicroHILSerialCom::open () final virtual
Open the serial communication channel.
Implements AbMicroHILCom.
Definition at line 32 of file microhil_serial_com.cc.
{
    if(!m_serialPort->IsOpen())
    {
        m_serialPort->Open(std::string(m_device));
    }
}
References m_device, and m_serialPort.
parityToUInt()
unsigned int MicroHILSerialCom::parityToUInt (const Parity parity)
Convert parity from scopped enumerator to unsigned int.
Parameters
parity in scoped enumerator value
Returns
unsigned integer format of parity
Definition at line 149 of file microhil_serial_com_utils.cc.
{
    switch(parity)
    {
        case Parity::PARITY_EVEN: return kParityEven;
        case Parity::PARITY_ODD: return kParityOdd;
        case Parity::PARITY_NONE: return kParityNone;
        case Parity::PARITY_INVALID: return kInvalidParameter;
    }
    return kInvalidParameter;
}
References parity.
read()
void MicroHILSerialCom::read (MHVecByte & data, size_t len, size_t timeout) final virtual
Read from serial communication channel.
Parameters
data buffer to be placed to after reading the serial port
len length of data to read before returning
timeout timeout period in miliseconds
Implements AbMicroHILCom.
Definition at line 66 of file microhil_serial_com.cc.
{
    // TODO
}
setup() [1/2]
void MicroHILSerialCom::setup (MHString device, MHSerialParams params)
Setup the serial port parameters.
Parameters
device file path for the serial port
params for the serial port
Definition at line 57 of file microhil_serial_com.cc.
{
    m_serialPort->SetBaudRate(params.baudRate);
    m_serialPort->SetCharacterSize(params.dataBits);
    m_serialPort->SetParity(params.parity);
    m_serialPort->SetStopBits(params.stopBits);
    m_device = device;
}
References m_device, and m_serialPort.
setup() [2/2]
void MicroHILSerialCom::setup (MHString device, MHVecUInt params)
Setup the serial port parameters.
Parameters
device file path for serial port
params for serial port
Definition at line 48 of file microhil_serial_com.cc.
{
    m_serialPort->SetBaudRate(uintToBaudRate(params[0]));
    m_serialPort->SetCharacterSize(uintToDataBits(params[1]));
    m_serialPort->SetParity(uintToParity(params[2]));
    m_serialPort->SetStopBits(uintToStopBits(params[3]));
    m_device = device;
}
References m_device, m_serialPort, uintToBaudRate(), uintToDataBits(), uintToParity(), and uintToStopBits().
stopBitsToUInt()
unsigned int MicroHILSerialCom::stopBitsToUInt (const StopBits stopBits)
Convert stop-bits from scopped enumerator to unsigned int.
Parameters
stopBits in scoped enumerator value
Returns
unsigned integer format of stop-bits
Definition at line 174 of file microhil_serial_com_utils.cc.
{
    switch(stopBits)
    {
        case StopBits::STOP_BITS_1: return kStopBits1;
        case StopBits::STOP_BITS_2: return kStopBits2;
        case StopBits::STOP_BITS_INVALID: return kInvalidParameter;
    }
    return kInvalidParameter;
}
References stopBits.
uintToBaudRate()
BaudRate MicroHILSerialCom::uintToBaudRate (const unsigned int baudRate)
Convert baud-rate from unsigned int to scopped enumerator.
Parameters
baudRate in unsigned integer value
Returns
scoped enumerator format of baud-rate
Definition at line 101 of file microhil_serial_com_utils.cc.
{
    switch(baudRate)
    {
        case kBaud110: return BaudRate::BAUD_110;
        case kBaud300: return BaudRate::BAUD_300;
        case kBaud600: return BaudRate::BAUD_600;
        case kBaud1200: return BaudRate::BAUD_1200;
        case kBaud2400: return BaudRate::BAUD_2400;
        case kBaud4800: return BaudRate::BAUD_4800;
        case kBaud9600: return BaudRate::BAUD_9600;
        case kBaud19200: return BaudRate::BAUD_19200;
        case kBaud38400: return BaudRate::BAUD_38400;
        case kBaud57600: return BaudRate::BAUD_57600;
        case kBaud115200: return BaudRate::BAUD_115200;
        case kBaud230400: return BaudRate::BAUD_230400;
    }
    return BaudRate::BAUD_INVALID;
}
Referenced by setup().
uintToDataBits()
CharacterSize MicroHILSerialCom::uintToDataBits (const unsigned int dataBits)
Convert data-bits from unsigned int to scopped enumerator.
Parameters
dataBits in unsigned integer format
Returns
scoped enumerator format of data-bits
Definition at line 136 of file microhil_serial_com_utils.cc.
{
    switch(dataBits)
    {
        case kDataBits5: return CharacterSize::CHAR_SIZE_5;
        case kDataBits6: return CharacterSize::CHAR_SIZE_6;
        case kDataBits7: return CharacterSize::CHAR_SIZE_7;
        case kDataBits8: return CharacterSize::CHAR_SIZE_8;
    }
    return CharacterSize::CHAR_SIZE_INVALID;
}
References dataBits.
Referenced by setup().
uintToParity()
Parity MicroHILSerialCom::uintToParity (const unsigned int parity)
Convert parity from unsigned int to scopped enumerator.
Parameters
parity in unsigned integer format
Returns
scoped enumerator format of parity
Definition at line 162 of file microhil_serial_com_utils.cc.
{
    switch(parity)
    {
        case kParityEven: return Parity::PARITY_EVEN;
        case kParityOdd: return Parity::PARITY_ODD;
        case kParityNone: return Parity::PARITY_NONE;
    }
    return Parity::PARITY_INVALID;
}
References parity.
Referenced by setup().
uintToStopBits()
StopBits MicroHILSerialCom::uintToStopBits (const unsigned int stopBits)
Convert stop-bits from unsigned int to scopped enumerator.
Parameters
stopBits in unsigned integer format
Returns
scoped enumerator format of stop-bits
Definition at line 186 of file microhil_serial_com_utils.cc.
{
    switch(stopBits)
    {
        case kStopBits1: return StopBits::STOP_BITS_1;
        case kStopBits2: return StopBits::STOP_BITS_2;
    }
    return StopBits::STOP_BITS_INVALID;
}
References stopBits.
Referenced by setup().
write()
void MicroHILSerialCom::write (MHVecByte & data) final virtual
Write data to the serial communication channel.
Parameters
data to be written to the serial port
Implements AbMicroHILCom.
Definition at line 71 of file microhil_serial_com.cc.
{
    // TODO
}
Member Data Documentation
m_device
MHString MicroHILSerialCom::m_device {} private
Serial port device file path.
Definition at line 140 of file microhil_serial_com.h.
Referenced by open(), and setup().
m_serialPort
MHUPtr<SerialPort> MicroHILSerialCom::m_serialPort {nullptr} private
Serial port instance.
Definition at line 136 of file microhil_serial_com.h.
Referenced by close(), open(), and setup().
The documentation for this class was generated from the following files:
com/microhil_serial_com.h
com/microhil_serial_com.cc
com/microhil_serial_com_utils.cc