microhil-device0: src/channel/microhil_channel_pwm.c File Reference
microhil_channel_pwm.c File Reference
#include "microhil_channel.h"
Functions
bool microhil_init_pwm ()
void microhil_write_pwm (uint8_t value)
Function Documentation
microhil_init_pwm()
bool microhil_init_pwm ()
Returns
true for success else false
Set PWM pin
Init PWM channel A
Definition at line 24 of file microhil_channel_pwm.c.
{
    bool status = false;
    gpio_set_function(6, GPIO_FUNC_PWM);
    slice_num = pwm_gpio_to_slice_num(6);
    pwm_set_wrap(slice_num, 500);
    pwm_set_chan_level(slice_num, PWM_CHAN_A, 1);
    pwm_set_clkdiv(slice_num, 50);
    pwm_set_enabled(slice_num, true);
}
References slice_num.
Referenced by microhil_init().
microhil_write_pwm()
void microhil_write_pwm (uint8_t value)
Parameters
value
Definition at line 44 of file microhil_channel_pwm.c.
{
    if (value < 0 || value > 100)
    {
        printf("microhil_write_pwm Error \r\n");
    }
    else
    {
        pwm_set_chan_level(slice_num, PWM_CHAN_A, value);
    }
}
References slice_num.
Referenced by microhil_all_channels_on(), and microhil_channel_switch().