microhil-base: src/channel/channel_buzzer.c File Reference
channel_buzzer.c File Reference
#include "io_config.h"
#include "channel.h"
Functions
bool microhil_init_buzzer ()
Performs initialization for buzzer channel.
void microhil_write_buzzer (bool value)
Turns buzzer on/off.
Variables
const uint microhil_buzzer = 6
GPIO port pin number for buzzer.
Function Documentation
microhil_init_buzzer()
bool microhil_init_buzzer ()
Performs initialization for buzzer channel.
Returns
true for success else false
Performs initialization for buzzer channel to be out
Performs initialization for buzzer channel to PWM 0
Definition at line 29 of file channel_buzzer.c.
{
    microhil_gpio_mode(microhil_buzzer, GPIO_OUT);
    return microhil_init_pwm(microhil_buzzer, PWM_CHAN_A);
}
References microhil_buzzer, microhil_gpio_mode(), and microhil_init_pwm().
Referenced by microhil_init().
microhil_write_buzzer()
void microhil_write_buzzer (bool value)
Turns buzzer on/off.
Parameters
value represents value for buzzer (true - on | false - off)
Definition at line 43 of file channel_buzzer.c.
{
    microhil_digital_write(microhil_buzzer, value);
}
References microhil_buzzer, and microhil_digital_write().
Referenced by microhil_init().
Variable Documentation
microhil_buzzer
const uint microhil_buzzer = 6
GPIO port pin number for buzzer.
Definition at line 24 of file channel_buzzer.c.
Referenced by microhil_init_buzzer(), and microhil_write_buzzer().