microhildesk: MHViewDialog Class Reference
MHViewDialog Class Reference
MHViewDialog class declaration and definition.
#include <microhil_view_dialog.h>
Public Member Functions
MHViewDialog (BaseObjectType *object, MHRPtr< Gtk::Builder > const &ui)
MHViewDialog constructor.
~MHViewDialog ()=default
MHViewDialog destructor.
SigHideDialog hideDialogTrigered () final
Signal for Close button.
void onHideDialogTriggered () final
Slot for processing Close button (self hide Dialog)
void setMessage (const MHString message, const MessageType type) final
Set message for dialog.
Public Member Functions inherited from AbMHViewDialog
virtual ~AbMHViewDialog ()=default
AbMHViewDialog destructor.
virtual SigHideDialog hideDialogTrigered ()=0
Signal for Close button.
virtual void onHideDialogTriggered ()=0
Slot for processing Close button (self hide Dialog)
virtual void setMessage (const MHString message, const MessageType type)=0
Set message for dialog.
Private Member Functions
MHString toUnicodeStringMessageType (const MessageType type)
Conversion of message type to unicode string.
void mapping ()
Map Close button (signal and slot)
Private Attributes
MHRPtr< Gtk::Builder > m_ui {nullptr}
UI builder instance.
MHRPtr< Gtk::Label > m_text {nullptr}
Dialog message text filed.
MHRPtr< Gtk::Button > m_close {nullptr}
Close button for dialog message.
SigHideDialog m_hideDialog {}
Signal for Close button (self hide Dialog)
Additional Inherited Members
Public Types inherited from AbMHViewDialog
using SigHideDialog = sigc::signal< void(bool)>
Signal type for Close button (self hide Dialog signal)
Detailed Description
MHViewDialog class declaration and definition.
Definition at line 29 of file microhil_view_dialog.h.
Constructor & Destructor Documentation
MHViewDialog()
MHViewDialog::MHViewDialog (BaseObjectType * object, MHRPtr< Gtk::Builder > const & ui)
MHViewDialog constructor.
Parameters
object base object type
ui builder instance
Bind Dialog message
Bind Close button
Map Close button (signal and slot)
Hide Dialog by default
Definition at line 44 of file microhil_view_dialog.cc.
                                                                               : Gtk::Dialog(object), m_ui{ui}
{
    m_text = MHRPtr<Gtk::Label>::cast_dynamic(m_ui->get_object(kDialogMessage));
    m_close = MHRPtr<Gtk::Button>::cast_dynamic(m_ui->get_object(kCloseButtonId));
    mapping();
    this->hide();
}
References m_close, m_text, m_ui, and mapping().
~MHViewDialog()
MHViewDialog::~MHViewDialog () default
MHViewDialog destructor.
Member Function Documentation
hideDialogTrigered()
MHViewDialog::SigHideDialog MHViewDialog::hideDialogTrigered () final virtual
Signal for Close button.
Returns
Signal for clicked Close button
Implements AbMHViewDialog.
Definition at line 21 of file microhil_view_dialog_signals.cc.
{
    return m_hideDialog;
}
References m_hideDialog.
mapping()
void MHViewDialog::mapping () private
Map Close button (signal and slot)
Definition at line 21 of file microhil_view_dialog_map.cc.
{
    m_close->signal_clicked().connect(sigc::mem_fun(*this, &MHViewDialog::onHideDialogTriggered));
}
References m_close, and onHideDialogTriggered().
Referenced by MHViewDialog().
onHideDialogTriggered()
void MHViewDialog::onHideDialogTriggered () final virtual
Slot for processing Close button (self hide Dialog)
Implements AbMHViewDialog.
Definition at line 21 of file microhil_view_dialog_slots.cc.
{
    this->hide();
}
Referenced by mapping().
setMessage()
void MHViewDialog::setMessage (const MHString message, const MessageType type) final virtual
Set message for dialog.
Parameters
message with information for user
type of dialog message
Implements AbMHViewDialog.
Definition at line 63 of file microhil_view_dialog.cc.
{
    const auto messageType = toUnicodeStringMessageType(type);
    this->set_title(messageType);
    m_text->set_text(message);
}
References m_text, and toUnicodeStringMessageType().
toUnicodeStringMessageType()
MHString MHViewDialog::toUnicodeStringMessageType (const MessageType type) private
Conversion of message type to unicode string.
Parameters
type of dialog message
Returns
string representation of dialog message type
Definition at line 70 of file microhil_view_dialog.cc.
{
    switch (type)
    {
    case MessageType::MICROHIL_INFO:
        return kInfoMessage;
    case MessageType::MICROHIL_WARNING:
        return kWarningMessage;
    case MessageType::MICROHIL_ERROR:
        return kErrorMessage;
    }
    return kInfoMessage;
}
References MICROHIL_ERROR, MICROHIL_INFO, and MICROHIL_WARNING.
Referenced by setMessage().
Member Data Documentation
m_close
MHRPtr<Gtk::Button> MHViewDialog::m_close {nullptr} private
Close button for dialog message.
Definition at line 78 of file microhil_view_dialog.h.
Referenced by mapping(), and MHViewDialog().
m_hideDialog
SigHideDialog MHViewDialog::m_hideDialog {} private
Signal for Close button (self hide Dialog)
Definition at line 82 of file microhil_view_dialog.h.
Referenced by hideDialogTrigered().
m_text
MHRPtr<Gtk::Label> MHViewDialog::m_text {nullptr} private
Dialog message text filed.
Definition at line 74 of file microhil_view_dialog.h.
Referenced by MHViewDialog(), and setMessage().
m_ui
MHRPtr<Gtk::Builder> MHViewDialog::m_ui {nullptr} private
UI builder instance.
Definition at line 70 of file microhil_view_dialog.h.
Referenced by MHViewDialog().
The documentation for this class was generated from the following files:
view/dialog/microhil_view_dialog.h
view/dialog/microhil_view_dialog.cc
view/dialog/microhil_view_dialog_map.cc
view/dialog/microhil_view_dialog_signals.cc
view/dialog/microhil_view_dialog_slots.cc