microhil-device0: src/channel/channel_pwm.c File Reference
channel_pwm.c File Reference
#include "channel_info.h"
#include "channel_error.h"
#include "channel.h"
Functions
bool microhil_init_pwm ()
Initialization of PWM channel.
void microhil_write_pwm (uint8_t value)
Write value to PWM channel.
Function Documentation
microhil_init_pwm()
bool microhil_init_pwm ()
Initialization of PWM channel.
Returns
true for success else false
Set PWM pin for buzzer
Init PWM channel A
Definition at line 26 of file channel_pwm.c.
{
    bool status = false;
    gpio_set_function(6, GPIO_FUNC_PWM);
    slice_num = pwm_gpio_to_slice_num(6);
    pwm_set_wrap(slice_num, 500);
    pwm_set_chan_level(slice_num, PWM_CHAN_A, 1);
    pwm_set_clkdiv(slice_num, 50);
    pwm_set_enabled(slice_num, true);
    status = true;
    printf("%s %s\n", MICROHIL_INFO, MICROHIL_PWM_INIT_OK);
    return status;
}
References MICROHIL_INFO, MICROHIL_PWM_INIT_OK, and slice_num.
Referenced by microhil_init().
microhil_write_pwm()
void microhil_write_pwm (uint8_t value)
Write value to PWM channel.
Parameters
value for PWM channel
Definition at line 52 of file channel_pwm.c.
{
    if (value < 0 || value > 100)
    {
        printf("%s %s\n", MICROHIL_ERROR, MICROHIL_PWM_WRITE_FAILED);
    }
    else
    {
        pwm_set_chan_level(slice_num, PWM_CHAN_A, value);
    }
}
References MICROHIL_ERROR, MICROHIL_PWM_WRITE_FAILED, and slice_num.
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), and microhil_channel_switch().