microhil-device0: src/channel/microhil_channel_init.c File Reference
microhil_channel_init.c File Reference
#include "microhil_channel.h"
Functions
void microhil_init ()
Variables
unsigned char Relays [8] = {0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1}
const int PIN_TX = 13
Function Documentation
microhil_init()
void microhil_init ()
Definition at line 31 of file microhil_channel_init.c.
{
    stdio_init_all();
    stdio_usb_init();
    gpio_init(JDQ1);
    gpio_init(JDQ2);
    gpio_init(JDQ3);
    gpio_init(JDQ4);
    gpio_init(JDQ5);
    gpio_init(JDQ6);
    gpio_init(JDQ7);
    gpio_init(JDQ8);
    gpio_set_dir(JDQ1, GPIO_OUT);
    gpio_set_dir(JDQ2, GPIO_OUT);
    gpio_set_dir(JDQ3, GPIO_OUT);
    gpio_set_dir(JDQ4, GPIO_OUT);
    gpio_set_dir(JDQ5, GPIO_OUT);
    gpio_set_dir(JDQ6, GPIO_OUT);
    gpio_set_dir(JDQ7, GPIO_OUT);
    gpio_set_dir(JDQ8, GPIO_OUT);
    PIO pio = pio0;
    int sm = 0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, sm, offset, PIN_TX, 800000, true);
    gpio_set_function(6, GPIO_FUNC_PWM);
    slice_num = pwm_gpio_to_slice_num(6);
    pwm_set_wrap(slice_num, 500);
    pwm_set_chan_level(slice_num, PWM_CHAN_A, 1);
    pwm_set_clkdiv(slice_num, 50);
    pwm_set_enabled(slice_num, true);
    put_pixel(urgb_u32(0, 0, 0)); // RGB
    // microhil_write_pwm(80); //buzzer
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, PIN_TX, put_pixel(), slice_num, urgb_u32(), ws2812_program, and ws2812_program_init().
Referenced by main().
Variable Documentation
PIN_TX
const int PIN_TX = 13
Definition at line 27 of file microhil_channel_init.c.
Referenced by microhil_init().
Relays
unsigned char Relays[8] = {0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1, 0x1}
Definition at line 23 of file microhil_channel_init.c.
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), and microhil_channel_switch().