microhil-device0: src/ws2812/ws2812.pio.h File Reference
ws2812.pio.h File Reference
#include "hardware/pio.h"
#include "hardware/clocks.h"
Classes
struct _ws2812_init
WS2812 init structure.
struct _ws2812_parallel_init
WS2812 parallel init structure.
Macros
#define WS2812_WRAP_TARGET 0
Part of instruction memory address wrap to.
#define WS2812_WRAP 3
Part of instruction memory address wrap to.
#define WS2812_T1 2
Part of cycles for PIO SM clock.
#define WS2812_T2 5
Part of cycles for PIO SM clock.
#define WS2812_T3 3
Part of cycles for PIO SM clock.
#define WS2812_PARALLEL_WRAP_TARGET 0
Part of instruction memory address wrap to (parallel)
#define WS2812_PARALLEL_WRAP 3
Part of instruction memory address wrap to (parallel)
#define WS2812_PARALLEL_T1 2
Part of cycles for PIO SM clock (parallel)
#define WS2812_PARALLEL_T2 5
Part of cycles for PIO SM clock (parallel)
#define WS2812_PARALLEL_T3 3
Part of cycles for PIO SM clock (parallel)
Typedefs
typedef struct _ws2812_init ws2812_init
WS2812 init structure.
typedef struct _ws2812_parallel_init ws2812_parallel_init
WS2812 parallel init structure.
Functions
static pio_sm_config ws2812_program_get_default_config (uint offset)
Preparing default configuration.
static void ws2812_program_init (ws2812_init *init)
Perform WS2812 program initialization.
static pio_sm_config ws2812_parallel_program_get_default_config (uint offset)
Preparing default configuration (parallel)
static void ws2812_parallel_program_init (ws2812_parallel_init *init)
Perform WS2812 parallel program initialization.
Variables
static const uint16_t ws2812_program_instructions []
PIO program instructions for WS2812.
static const struct pio_program ws2812_program
PIO program instruction structure for WS2812.
static const uint16_t ws2812_parallel_program_instructions []
PIO program instructions for WS2812 (parallel)
static const struct pio_program ws2812_parallel_program
PIO program instruction structure for WS2812 (parallel)
Macro Definition Documentation
WS2812_PARALLEL_T1
#define WS2812_PARALLEL_T1 2
Part of cycles for PIO SM clock (parallel)
Definition at line 131 of file ws2812.pio.h.
WS2812_PARALLEL_T2
#define WS2812_PARALLEL_T2 5
Part of cycles for PIO SM clock (parallel)
Definition at line 135 of file ws2812.pio.h.
WS2812_PARALLEL_T3
#define WS2812_PARALLEL_T3 3
Part of cycles for PIO SM clock (parallel)
Definition at line 139 of file ws2812.pio.h.
WS2812_PARALLEL_WRAP
#define WS2812_PARALLEL_WRAP 3
Part of instruction memory address wrap to (parallel)
Definition at line 127 of file ws2812.pio.h.
WS2812_PARALLEL_WRAP_TARGET
#define WS2812_PARALLEL_WRAP_TARGET 0
Part of instruction memory address wrap to (parallel)
Definition at line 123 of file ws2812.pio.h.
WS2812_T1
#define WS2812_T1 2
Part of cycles for PIO SM clock.
Definition at line 36 of file ws2812.pio.h.
WS2812_T2
#define WS2812_T2 5
Part of cycles for PIO SM clock.
Definition at line 40 of file ws2812.pio.h.
WS2812_T3
#define WS2812_T3 3
Part of cycles for PIO SM clock.
Definition at line 44 of file ws2812.pio.h.
WS2812_WRAP
#define WS2812_WRAP 3
Part of instruction memory address wrap to.
Definition at line 32 of file ws2812.pio.h.
WS2812_WRAP_TARGET
#define WS2812_WRAP_TARGET 0
Part of instruction memory address wrap to.
Definition at line 28 of file ws2812.pio.h.
Typedef Documentation
ws2812_init
typedef struct _ws2812_init ws2812_init
WS2812 init structure.
ws2812_parallel_init
typedef struct _ws2812_parallel_init ws2812_parallel_init
WS2812 parallel init structure.
Function Documentation
ws2812_parallel_program_get_default_config()
static pio_sm_config ws2812_parallel_program_get_default_config (uint offset) inline static
Preparing default configuration (parallel)
Parameters
offset for programm address
Returns
PIO configuratio structure for WS2812
Definition at line 168 of file ws2812.pio.h.
{
    pio_sm_config config = pio_get_default_sm_config();
    uint wrap_target = offset + WS2812_PARALLEL_WRAP_TARGET;
    uint wrap = offset + WS2812_PARALLEL_WRAP;
    sm_config_set_wrap(&config, wrap_target, wrap);
    return config;
}
References WS2812_PARALLEL_WRAP, and WS2812_PARALLEL_WRAP_TARGET.
Referenced by ws2812_parallel_program_init().
ws2812_parallel_program_init()
static void ws2812_parallel_program_init (ws2812_parallel_init * init) inline static
Perform WS2812 parallel program initialization.
Parameters
init is pointer to WS2812 parallel init structure
Definition at line 195 of file ws2812.pio.h.
{
    uint max_pin_count = init->pin_base + init->pin_count;
    for (uint i = init->pin_base; i < max_pin_count; i++)
    {
        pio_gpio_init(init->pio, i);
    }
    pio_sm_set_consecutive_pindirs(
        init->pio, init->sm, init->pin_base, init->pin_count, true
    );
    pio_sm_config config = ws2812_parallel_program_get_default_config(
        init->offset
    );
    sm_config_set_out_shift(&config, true, true, 32);
    sm_config_set_out_pins(&config, init->pin_base, init->pin_count);
    sm_config_set_set_pins(&config, init->pin_base, init->pin_count);
    sm_config_set_fifo_join(&config, PIO_FIFO_JOIN_TX);
    int cycles_per_bit = (
        WS2812_PARALLEL_T1 + WS2812_PARALLEL_T2 + WS2812_PARALLEL_T3
    );
    float div = clock_get_hz(clk_sys) / (init->freq * cycles_per_bit);
    sm_config_set_clkdiv(&config, div);
    pio_sm_init(init->pio, init->sm, init->offset, &config);
    pio_sm_set_enabled(init->pio, init->sm, true);
}
References _ws2812_parallel_init::freq, _ws2812_parallel_init::offset, _ws2812_parallel_init::pin_base, _ws2812_parallel_init::pin_count, _ws2812_parallel_init::pio, _ws2812_parallel_init::sm, ws2812_parallel_program_get_default_config(), WS2812_PARALLEL_T1, WS2812_PARALLEL_T2, and WS2812_PARALLEL_T3.
ws2812_program_get_default_config()
static pio_sm_config ws2812_program_get_default_config (uint offset) inline static
Preparing default configuration.
Parameters
offset for programm address
Returns
PIO configuratio structure for WS2812
Definition at line 73 of file ws2812.pio.h.
{
    pio_sm_config config = pio_get_default_sm_config();
    uint wrap_target = offset + WS2812_WRAP_TARGET;
    uint wrap = offset + WS2812_WRAP;
    sm_config_set_wrap(&config, wrap_target, wrap);
    sm_config_set_sideset(&config, 1, false, false);
    return config;
}
References WS2812_WRAP, and WS2812_WRAP_TARGET.
Referenced by ws2812_program_init().
ws2812_program_init()
static void ws2812_program_init (ws2812_init * init) inline static
Perform WS2812 program initialization.
Parameters
init is pointer to WS2812 init structure
Definition at line 100 of file ws2812.pio.h.
{
    pio_gpio_init(init->pio, init->pin);
    pio_sm_set_consecutive_pindirs(init->pio, init->sm, init->pin, 1, true);
    pio_sm_config config = ws2812_program_get_default_config(init->offset);
    sm_config_set_sideset_pins(&config, init->pin);
    sm_config_set_out_shift(&config, false, true, init->rgbw ? 32 : 24);
    sm_config_set_fifo_join(&config, PIO_FIFO_JOIN_TX);
    int cycles_per_bit = (WS2812_T1 + WS2812_T2 + WS2812_T3);
    float div = clock_get_hz(clk_sys) / (init->freq * cycles_per_bit);
    sm_config_set_clkdiv(&config, div);
    pio_sm_init(init->pio, init->sm, init->offset, &config);
    pio_sm_set_enabled(init->pio, init->sm, true);
}
References _ws2812_init::freq, _ws2812_init::offset, _ws2812_init::pin, _ws2812_init::pio, _ws2812_init::rgbw, _ws2812_init::sm, ws2812_program_get_default_config(), WS2812_T1, WS2812_T2, and WS2812_T3.
Referenced by microhil_pio_init().
Variable Documentation
ws2812_parallel_program
const struct pio_program ws2812_parallel_program static
Initial value:
=
{
    .instructions = ws2812_parallel_program_instructions,
    .length = 4,
    .origin = -1,
}
PIO program instruction structure for WS2812 (parallel)
Definition at line 157 of file ws2812.pio.h.
ws2812_parallel_program_instructions
const uint16_t ws2812_parallel_program_instructions[] static
Initial value:
=
{
    0x6020,
    0xa10b,
    0xa401,
    0xa103,
}
PIO program instructions for WS2812 (parallel)
Definition at line 143 of file ws2812.pio.h.
ws2812_program
const struct pio_program ws2812_program static
Initial value:
=
{
    .instructions = ws2812_program_instructions,
    .length = 4,
    .origin = -1,
}
PIO program instruction structure for WS2812.
Definition at line 62 of file ws2812.pio.h.
Referenced by microhil_pio_init().
ws2812_program_instructions
const uint16_t ws2812_program_instructions[] static
Initial value:
=
{
    0x6221,
    0x1123,
    0x1400,
    0xa442,
}
PIO program instructions for WS2812.
Definition at line 48 of file ws2812.pio.h.