microhildesk: Electux::App::Model::ModelSerial Class Reference
Electux::App::Model::ModelSerial Class Reference
#include <model_serial.h>
Public Types
enum class ModelSerialKey {
Device , Baud , Data , Parity ,
Stop , Flow
}
Enum for serial configuration keys.
Public Member Functions
ModelSerial () noexcept=default
ModelSerial constructor.
Entities getAllEntries () const final
Gets all model entries.
std::string toString (const ModelSerialKey &key) const
Converts Key enum to.
bool validateKey (const std::string &key) const
Validates if key is valid serial configuration key.
bool add (const std::string &key, const std::string &data) final
Adds entity to model {'key': 'data'}.
const std::string & getEntity (const std::string &key) const final
Gets entity by key.
const Entities & get () const final
Gets model entities.
bool update (const std::string &key, const std::string &data) final
Updates entity value by key.
void clear () final
Clears all model entities.
Private Attributes
Entities m_entities {}
Model entities in format map of strings {key: data}.
Detailed Description
Definition at line 25 of file model_serial.h.
Member Enumeration Documentation
ModelSerialKey
enum class Electux::App::Model::ModelSerial::ModelSerialKey strong
Enum for serial configuration keys.
Enumerator
Device
Baud
Data
Parity
Stop
Flow
Definition at line 34 of file model_serial.h.
        {
            Device,
            Baud,
            Data,
            Parity,
            Stop,
            Flow
        };
Constructor & Destructor Documentation
ModelSerial()
Electux::App::Model::ModelSerial::ModelSerial () inline default noexcept
ModelSerial constructor.
Member Function Documentation
add()
bool Model::add (const std::string & key, const std::string & data) final virtual inherited
Adds entity to model {'key': 'data'}.
Parameters
key Represents model enity key to be added
data Represents model entity data to be added
Implements Electux::App::Model::IModel.
Definition at line 23 of file model.cc.
{
    auto const [it, inserted] = m_entities.try_emplace(key, data);
    return inserted;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), and Electux::App::Config::ConfigManager::load().
clear()
void Model::clear () final virtual inherited
Clears all model entities.
Implements Electux::App::Model::IModel.
Definition at line 57 of file model.cc.
{
    m_entities.clear();
}
References Electux::App::Model::Model::m_entities.
get()
const Entities & Model::get () const final virtual inherited
Gets model entities.
Returns
Model entities in format map of strings
Implements Electux::App::Model::IModel.
Definition at line 41 of file model.cc.
{
    return m_entities;
}
References Electux::App::Model::Model::m_entities.
getAllEntries()
Entities ModelSerial::getAllEntries () const final virtual
Gets all model entries.
Returns
Map of all model entries {key: data}
Implements Electux::App::Model::IModel.
Definition at line 37 of file model_serial.cc.
{
    static const std::vector<ModelSerialKey> keys =
    {
        ModelSerialKey::Device,
        ModelSerialKey::Baud,
        ModelSerialKey::Data,
        ModelSerialKey::Parity,
        ModelSerialKey::Stop,
        ModelSerialKey::Flow
    };
    Entities entries;
    for (const auto& key : keys)
    {
        std::string keyStr = toString(key);
        entries[keyStr] = getEntity(keyStr);
    }
    return entries;
}
References Baud, Data, Device, Flow, Electux::App::Model::Model::getEntity(), Parity, Stop, and toString().
getEntity()
const std::string & Model::getEntity (const std::string & key) const final virtual inherited
Gets entity by key.
Parameters
key Represents model enity key
Returns
Entity selected by key
Implements Electux::App::Model::IModel.
Definition at line 29 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        return it->second;
    }
    static const std::string fallback{""};
    return fallback;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::Model::ModelControl::getAllEntries(), Electux::App::Model::ModelLog::getAllEntries(), getAllEntries(), Electux::App::View::AppHome::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToogleChanged(), Electux::App::View::AppHome::onChannelToggleChanged(), Electux::App::View::AppHome::updateUiData(), and Electux::App::View::Settings::AppSettings::updateUiData().
toString()
std::string ModelSerial::toString (const ModelSerialKey & key) const
Converts Key enum to.
Parameters
key Represents ModelSerialKey enum value
Returns
string representation of ModelSerialKey enum
Definition at line 59 of file model_serial.cc.
{
    switch (key)
    {
    case ModelSerialKey::Device: return device.data();
    case ModelSerialKey::Baud: return baud.data();
    case ModelSerialKey::Data: return data.data();
    case ModelSerialKey::Parity: return parity.data();
    case ModelSerialKey::Stop: return stop.data();
    case ModelSerialKey::Flow: return flow.data();
    default: return unknown.data();
    }
}
References Baud, Data, Device, Flow, Parity, and Stop.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), getAllEntries(), Electux::App::View::Settings::AppSettings::getUiData(), Electux::App::View::Settings::AppSettings::updateUiData(), and validateKey().
update()
bool Model::update (const std::string & key, const std::string & data) final virtual inherited
Updates entity value by key.
Parameters
key Represents model entity key
data Represents new value for the entity
Returns
True if the entity was updated, false if the key does not exist
Implements Electux::App::Model::IModel.
Definition at line 46 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        it->second = data;
        return true;
    }
    return false;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::View::AppHome::getUiData(), Electux::App::View::Settings::AppSettings::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToogleChanged(), and Electux::App::View::AppHome::onChannelToggleChanged().
validateKey()
bool ModelSerial::validateKey (const std::string & key) const
Validates if key is valid serial configuration key.
Parameters
key Represents string key to be validated
Returns
status true if key is valid else false
Definition at line 73 of file model_serial.cc.
{
    return key == toString(ModelSerialKey::Device) ||
            key == toString(ModelSerialKey::Baud) ||
            key == toString(ModelSerialKey::Data) ||
            key == toString(ModelSerialKey::Parity) ||
            key == toString(ModelSerialKey::Stop) ||
            key == toString(ModelSerialKey::Flow);
}
References Baud, Data, Device, Flow, Parity, Stop, and toString().
Referenced by Electux::App::Config::ConfigManager::load().
Member Data Documentation
m_entities
Entities Electux::App::Model::Model::m_entities {} private inherited
Model entities in format map of strings {key: data}.
Definition at line 65 of file model.h.
{};
Referenced by Electux::App::Model::Model::add(), Electux::App::Model::Model::clear(), Electux::App::Model::Model::get(), Electux::App::Model::Model::getEntity(), and Electux::App::Model::Model::update().
The documentation for this class was generated from the following files:
model/model_serial.h
model/model_serial.cc