microhildesk: MHSerialCom Class Reference
MHSerialCom Class Reference
MHSerialCom class is implementation of serial communication.
#include <microhil_serial_com.h>
Public Member Functions
MHSerialCom ()
MicroHILCom constructor.
~MHSerialCom () noexcept=default
MHSerialCom destructor.
void open () final
Opens the serial communication channel.
void close () final
Closes the serial communication channel.
void setup (const UString &device, const VecUInt &params) final
Setup the serial port parameters.
void setup (const UString &device, const MHSerialParams &params) final
Setup the serial port parameters.
void read (VecByte &data, size_t len, size_t timeout) final
Read from serial communication channel.
void write (const VecByte &data) final
Writes data to the serial communication channel.
Private Member Functions
unsigned int baudRateToUInt (const BaudRate baudRate) final
Converts baud-rate from scopped enumerator to unsigned int.
BaudRate uintToBaudRate (const unsigned int baudRate) final
Converts baud-rate from unsigned int to scopped enumerator.
unsigned int dataBitsToUInt (const CharacterSize dataBits) final
Converts data-bits from scopped enumerator to unsigned int.
CharacterSize uintToDataBits (const unsigned int dataBits) final
Converts data-bits from unsigned int to scopped enumerator.
unsigned int parityToUInt (const Parity parity) final
Converts parity from scopped enumerator to unsigned int.
Parity uintToParity (const unsigned int parity) final
Converts parity from unsigned int to scopped enumerator.
unsigned int stopBitsToUInt (const StopBits stopBits) final
Converts stop-bits from scopped enumerator to unsigned int.
StopBits uintToStopBits (const unsigned int stopBits) final
Converts stop-bits from unsigned int to scopped enumerator.
Private Attributes
UPtr< SerialPort > m_serialPort {nullptr}
Serial port instance.
UString m_device {}
Serial port device file path.
Detailed Description
MHSerialCom class is implementation of serial communication.
Definition at line 25 of file microhil_serial_com.h.
Constructor & Destructor Documentation
MHSerialCom()
MHSerialCom::MHSerialCom () explicit
MicroHILCom constructor.
Definition at line 21 of file microhil_serial_com.cc.
    : m_serialPort{makeUPtr<SerialPort>()}
{
    close();
}
References close().
~MHSerialCom()
MHSerialCom::~MHSerialCom () inline default noexcept
MHSerialCom destructor.
Member Function Documentation
baudRateToUInt()
unsigned int MHSerialCom::baudRateToUInt (const BaudRate baudRate) final private virtual
Converts baud-rate from scopped enumerator to unsigned int.
Parameters
baudRate represents scoped enumerator value
Returns
unsigned integer format of baud-rate
Implements IMHCom.
Definition at line 61 of file microhil_serial_com_utils.cc.
{
    switch (baudRate)
    {
    case BaudRate::BAUD_50:
        return kInvalidParameter;
    case BaudRate::BAUD_75:
        return kInvalidParameter;
    case BaudRate::BAUD_110:
        return kBaud110;
    case BaudRate::BAUD_134:
        return kInvalidParameter;
    case BaudRate::BAUD_150:
        return kInvalidParameter;
    case BaudRate::BAUD_200:
        return kInvalidParameter;
    case BaudRate::BAUD_300:
        return kBaud300;
    case BaudRate::BAUD_600:
        return kBaud600;
    case BaudRate::BAUD_1200:
        return kBaud1200;
    case BaudRate::BAUD_1800:
        return kInvalidParameter;
    case BaudRate::BAUD_2400:
        return kBaud2400;
    case BaudRate::BAUD_4800:
        return kBaud4800;
    case BaudRate::BAUD_9600:
        return kBaud9600;
    case BaudRate::BAUD_19200:
        return kBaud19200;
    case BaudRate::BAUD_38400:
        return kBaud38400;
    case BaudRate::BAUD_57600:
        return kBaud57600;
    case BaudRate::BAUD_115200:
        return kBaud115200;
    case BaudRate::BAUD_230400:
        return kBaud230400;
    case BaudRate::BAUD_460800:
        return kInvalidParameter;
    case BaudRate::BAUD_500000:
        return kInvalidParameter;
    case BaudRate::BAUD_576000:
        return kInvalidParameter;
    case BaudRate::BAUD_921600:
        return kInvalidParameter;
    case BaudRate::BAUD_1000000:
        return kInvalidParameter;
    case BaudRate::BAUD_1152000:
        return kInvalidParameter;
    case BaudRate::BAUD_1500000:
        return kInvalidParameter;
    case BaudRate::BAUD_2000000:
        return kInvalidParameter;
    case BaudRate::BAUD_2500000:
        return kInvalidParameter;
    case BaudRate::BAUD_3000000:
        return kInvalidParameter;
    case BaudRate::BAUD_3500000:
        return kInvalidParameter;
    case BaudRate::BAUD_4000000:
        return kInvalidParameter;
    case BaudRate::BAUD_INVALID:
        return kInvalidParameter;
    }
    return kInvalidParameter;
}
close()
void MHSerialCom::close () final virtual
Closes the serial communication channel.
Implements IMHCom.
Definition at line 35 of file microhil_serial_com.cc.
{
    if (m_serialPort->IsOpen())
    {
        m_serialPort->Close();
    }
}
References m_serialPort.
Referenced by MHSerialCom().
dataBitsToUInt()
unsigned int MHSerialCom::dataBitsToUInt (const CharacterSize dataBits) final private virtual
Converts data-bits from scopped enumerator to unsigned int.
Parameters
dataBits represents scoped enumerator value
Returns
unsigned integer format of data-bits
Implements IMHCom.
Definition at line 165 of file microhil_serial_com_utils.cc.
{
    switch (dataBits)
    {
    case CharacterSize::CHAR_SIZE_5:
        return kDataBits5;
    case CharacterSize::CHAR_SIZE_6:
        return kDataBits6;
    case CharacterSize::CHAR_SIZE_7:
        return kDataBits7;
    case CharacterSize::CHAR_SIZE_8:
        return kDataBits8;
    case CharacterSize::CHAR_SIZE_INVALID:
        return kInvalidParameter;
    }
    return kInvalidParameter;
}
References dataBits.
open()
void MHSerialCom::open () final virtual
Opens the serial communication channel.
Implements IMHCom.
Definition at line 27 of file microhil_serial_com.cc.
{
    if (!m_serialPort->IsOpen())
    {
        m_serialPort->Open(std::string(m_device));
    }
}
References m_device, and m_serialPort.
Referenced by setup().
parityToUInt()
unsigned int MHSerialCom::parityToUInt (const Parity parity) final private virtual
Converts parity from scopped enumerator to unsigned int.
Parameters
parity represents scoped enumerator value
Returns
unsigned integer format of parity
Implements IMHCom.
Definition at line 201 of file microhil_serial_com_utils.cc.
{
    switch (parity)
    {
    case Parity::PARITY_EVEN:
        return kParityEven;
    case Parity::PARITY_ODD:
        return kParityOdd;
    case Parity::PARITY_NONE:
        return kParityNone;
    case Parity::PARITY_INVALID:
        return kInvalidParameter;
    }
    return kInvalidParameter;
}
References parity.
read()
void MHSerialCom::read (VecByte & data, size_t len, size_t timeout) final virtual
Read from serial communication channel.
Parameters
data represents data to be placed to after reading
len represents length of data to read before returning
timeout represents timeout period in miliseconds
Implements IMHCom.
Definition at line 85 of file microhil_serial_com.cc.
{
    m_serialPort->Read(data, len, timeout);
}
References m_serialPort.
setup() [1/2]
void MHSerialCom::setup (const UString & device, const MHSerialParams & params) final virtual
Setup the serial port parameters.
Parameters
device represents file path for the serial port
params represents parameters for the serial port
Sets serial port device path
Sets serial port parameters
Implements IMHCom.
Definition at line 64 of file microhil_serial_com.cc.
{
    if (m_serialPort->IsOpen())
    {
        m_serialPort->Close();
    }
    m_device = device;
    open();
    m_serialPort->SetBaudRate(params.baudRate);
    m_serialPort->SetCharacterSize(params.dataBits);
    m_serialPort->SetParity(params.parity);
    m_serialPort->SetStopBits(params.stopBits);
}
References m_device, m_serialPort, and open().
setup() [2/2]
void MHSerialCom::setup (const UString & device, const VecUInt & params) final virtual
Setup the serial port parameters.
Parameters
device represents file path for the serial port
params represents parameters for the serial port
Sets serial port device path
Sets serial port parameters
Implements IMHCom.
Definition at line 43 of file microhil_serial_com.cc.
{
    if (m_serialPort->IsOpen())
    {
        m_serialPort->Close();
    }
    m_device = device;
    open();
    m_serialPort->SetBaudRate(uintToBaudRate(params[0]));
    m_serialPort->SetCharacterSize(uintToDataBits(params[1]));
    m_serialPort->SetParity(uintToParity(params[2]));
    m_serialPort->SetStopBits(uintToStopBits(params[3]));
}
References m_device, m_serialPort, open(), uintToBaudRate(), uintToDataBits(), uintToParity(), and uintToStopBits().
stopBitsToUInt()
unsigned int MHSerialCom::stopBitsToUInt (const StopBits stopBits) final private virtual
Converts stop-bits from scopped enumerator to unsigned int.
Parameters
stopBits represents scoped enumerator value
Returns
unsigned integer format of stop-bits
Implements IMHCom.
Definition at line 233 of file microhil_serial_com_utils.cc.
{
    switch (stopBits)
    {
    case StopBits::STOP_BITS_1:
        return kStopBits1;
    case StopBits::STOP_BITS_2:
        return kStopBits2;
    case StopBits::STOP_BITS_INVALID:
        return kInvalidParameter;
    }
    return kInvalidParameter;
}
References stopBits.
uintToBaudRate()
BaudRate MHSerialCom::uintToBaudRate (const unsigned int baudRate) final private virtual
Converts baud-rate from unsigned int to scopped enumerator.
Parameters
baudRate represents unsigned integer value
Returns
scoped enumerator format of baud-rate
Implements IMHCom.
Definition at line 132 of file microhil_serial_com_utils.cc.
{
    switch (baudRate)
    {
    case kBaud110:
        return BaudRate::BAUD_110;
    case kBaud300:
        return BaudRate::BAUD_300;
    case kBaud600:
        return BaudRate::BAUD_600;
    case kBaud1200:
        return BaudRate::BAUD_1200;
    case kBaud2400:
        return BaudRate::BAUD_2400;
    case kBaud4800:
        return BaudRate::BAUD_4800;
    case kBaud9600:
        return BaudRate::BAUD_9600;
    case kBaud19200:
        return BaudRate::BAUD_19200;
    case kBaud38400:
        return BaudRate::BAUD_38400;
    case kBaud57600:
        return BaudRate::BAUD_57600;
    case kBaud115200:
        return BaudRate::BAUD_115200;
    case kBaud230400:
        return BaudRate::BAUD_230400;
    }
    return BaudRate::BAUD_INVALID;
}
Referenced by setup().
uintToDataBits()
CharacterSize MHSerialCom::uintToDataBits (const unsigned int dataBits) final private virtual
Converts data-bits from unsigned int to scopped enumerator.
Parameters
dataBits represents unsigned integer format
Returns
scoped enumerator format of data-bits
Implements IMHCom.
Definition at line 184 of file microhil_serial_com_utils.cc.
{
    switch (dataBits)
    {
    case kDataBits5:
        return CharacterSize::CHAR_SIZE_5;
    case kDataBits6:
        return CharacterSize::CHAR_SIZE_6;
    case kDataBits7:
        return CharacterSize::CHAR_SIZE_7;
    case kDataBits8:
        return CharacterSize::CHAR_SIZE_8;
    }
    return CharacterSize::CHAR_SIZE_INVALID;
}
References dataBits.
Referenced by setup().
uintToParity()
Parity MHSerialCom::uintToParity (const unsigned int parity) final private virtual
Converts parity from unsigned int to scopped enumerator.
Parameters
parity represents unsigned integer format
Returns
scoped enumerator format of parity
Implements IMHCom.
Definition at line 218 of file microhil_serial_com_utils.cc.
{
    switch (parity)
    {
    case kParityEven:
        return Parity::PARITY_EVEN;
    case kParityOdd:
        return Parity::PARITY_ODD;
    case kParityNone:
        return Parity::PARITY_NONE;
    }
    return Parity::PARITY_INVALID;
}
References parity.
Referenced by setup().
uintToStopBits()
StopBits MHSerialCom::uintToStopBits (const unsigned int stopBits) final private virtual
Converts stop-bits from unsigned int to scopped enumerator.
Parameters
stopBits represents unsigned integer format
Returns
scoped enumerator format of stop-bits
Implements IMHCom.
Definition at line 248 of file microhil_serial_com_utils.cc.
{
    switch (stopBits)
    {
    case kStopBits1:
        return StopBits::STOP_BITS_1;
    case kStopBits2:
        return StopBits::STOP_BITS_2;
    }
    return StopBits::STOP_BITS_INVALID;
}
References stopBits.
Referenced by setup().
write()
void MHSerialCom::write (const VecByte & data) final virtual
Writes data to the serial communication channel.
Parameters
data represents data to be written to the serial port
Implements IMHCom.
Definition at line 90 of file microhil_serial_com.cc.
{ m_serialPort->Write(data); }
References m_serialPort.
Member Data Documentation
m_device
UString MHSerialCom::m_device {} private
Serial port device file path.
Definition at line 123 of file microhil_serial_com.h.
Referenced by open(), and setup().
m_serialPort
UPtr<SerialPort> MHSerialCom::m_serialPort {nullptr} private
Serial port instance.
Definition at line 119 of file microhil_serial_com.h.
Referenced by close(), open(), read(), setup(), and write().
The documentation for this class was generated from the following files:
com/microhil_serial_com.h
com/microhil_serial_com.cc
com/microhil_serial_com_utils.cc