microhil-base: src/channel/channel_relay.c File Reference
channel_relay.c File Reference
#include "channel.h"
#include "io_config.h"
Functions
bool microhil_init_relay ()
Performs initialization for relay channels.
void microhil_relay (microhil_channel_gpio channel, bool value)
Turns relay to ON/OFF.
void microhil_relay_all (bool value)
Turns all relays to ON/OFF.
Function Documentation
microhil_init_relay()
bool microhil_init_relay ()
Performs initialization for relay channels.
Returns
true for success else false
Initializes all control relay channels as output
Initializes all control relay channels as closed
Relay port pins configuration done
Definition at line 25 of file channel_relay.c.
{
    bool status = false;
    microhil_gpio_mode(MICROHIL_CHANNEL_0, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_1, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_2, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_3, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_4, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_5, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_6, GPIO_OUT);
    microhil_gpio_mode(MICROHIL_CHANNEL_7, GPIO_OUT);
    microhil_digital_write(MICROHIL_CHANNEL_0, false);
    microhil_digital_write(MICROHIL_CHANNEL_1, false);
    microhil_digital_write(MICROHIL_CHANNEL_2, false);
    microhil_digital_write(MICROHIL_CHANNEL_3, false);
    microhil_digital_write(MICROHIL_CHANNEL_4, false);
    microhil_digital_write(MICROHIL_CHANNEL_5, false);
    microhil_digital_write(MICROHIL_CHANNEL_6, false);
    microhil_digital_write(MICROHIL_CHANNEL_7, false);
    status = true;
    return status;
}
References MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, microhil_digital_write(), and microhil_gpio_mode().
Referenced by microhil_init().
microhil_relay()
void microhil_relay (microhil_channel_gpio channel, bool value)
Turns relay to ON/OFF.
Parameters
channel represents channel number (0 .. 7)
value represents channel value (true - ON | false - OFF)
Definition at line 62 of file channel_relay.c.
{
    microhil_digital_write(channel, value);
}
References microhil_digital_write().
Referenced by microhil_channel().
microhil_relay_all()
void microhil_relay_all (bool value)
Turns all relays to ON/OFF.
Definition at line 69 of file channel_relay.c.
{
    microhil_digital_write(MICROHIL_CHANNEL_0, value);
    microhil_digital_write(MICROHIL_CHANNEL_1, value);
    microhil_digital_write(MICROHIL_CHANNEL_2, value);
    microhil_digital_write(MICROHIL_CHANNEL_3, value);
    microhil_digital_write(MICROHIL_CHANNEL_4, value);
    microhil_digital_write(MICROHIL_CHANNEL_5, value);
    microhil_digital_write(MICROHIL_CHANNEL_6, value);
    microhil_digital_write(MICROHIL_CHANNEL_7, value);
}
References MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, MICROHIL_CHANNEL_7, and microhil_digital_write().
Referenced by microhil_all_channels().