microhil-base: src/channel/channel.c File Reference
channel.c File Reference
#include <string.h>
#include "io_config.h"
#include "channel.h"
Macros
#define MICROHIL_PRIVATE
Marks private functions.
#define MICROHIL_NUMBER_OF_CHANNELS 8
Total number of supported channels.
#define MICROHIL_ON_CHANNEL "on#end"
microHIL channel switch ON request tail
#define MICROHIL_OFF_CHANNEL "off#end"
microHIL channel switch OFF request tail
#define MICROHIL_VERBOSE "[microHIL] INFO"
Prefix verbose message.
#define MICROHIL_ALL_ON "all channels on"
Info message for all channels switched to ON.
#define MICROHIL_ALL_OFF "all channels off"
Info message for all channels switched to OFF.
Functions
MICROHIL_PRIVATE void microhil_channel (uint8_t *args)
Performs channel operation (single channel)
MICROHIL_PRIVATE void microhil_all_channels (uint8_t *args)
Performs operations over all channels.
MICROHIL_PRIVATE void microhil_board_id ()
Gets unique HW board id.
MICROHIL_PRIVATE void microhil_version ()
Gets microHIL FW version.
MICROHIL_PRIVATE int comapre_request (const void *req1, const void *req2)
Compare request with candidates from request table.
void microhil_channel_switch (uint8_t *request)
Switches channels by command request.
MICROHIL_PRIVATE microhil_channel_gpio to_gpio (uint8_t channel_number)
Converts channel number to GPIO number.
Variables
static uint8_t channels [MICROHIL_NUMBER_OF_CHANNELS] = {0}
Buffer for storing channel states.
static microhil_req request_tbl []
Request table (mapped requests and functions)
Macro Definition Documentation
MICROHIL_ALL_OFF
#define MICROHIL_ALL_OFF "all channels off"
Info message for all channels switched to OFF.
Definition at line 49 of file channel.c.
MICROHIL_ALL_ON
#define MICROHIL_ALL_ON "all channels on"
Info message for all channels switched to ON.
Definition at line 45 of file channel.c.
MICROHIL_NUMBER_OF_CHANNELS
#define MICROHIL_NUMBER_OF_CHANNELS 8
Total number of supported channels.
Definition at line 29 of file channel.c.
MICROHIL_OFF_CHANNEL
#define MICROHIL_OFF_CHANNEL "off#end"
microHIL channel switch OFF request tail
Definition at line 37 of file channel.c.
MICROHIL_ON_CHANNEL
#define MICROHIL_ON_CHANNEL "on#end"
microHIL channel switch ON request tail
Definition at line 33 of file channel.c.
MICROHIL_PRIVATE
#define MICROHIL_PRIVATE
Marks private functions.
Definition at line 25 of file channel.c.
MICROHIL_VERBOSE
#define MICROHIL_VERBOSE "[microHIL] INFO"
Prefix verbose message.
Definition at line 41 of file channel.c.
Function Documentation
comapre_request()
MICROHIL_PRIVATE int comapre_request (const void * req1, const void * req2)
Compare request with candidates from request table.
Parameters
req1 represents microHIL request
req2 represents microHIL request
Returns
compare result
Definition at line 103 of file channel.c.
{
    const microhil_req *cmd1 = req1, *cmd2 = req2;
    return memcmp(cmd1->name, cmd2->name, 9);
}
References _microhil_req::name.
Referenced by microhil_channel_switch().
microhil_all_channels()
MICROHIL_PRIVATE void microhil_all_channels (uint8_t * args)
Performs operations over all channels.
Parameters
args represents argument (state on/off)
Sets relay channels to ON
Store channel states
Sets relay channels to OFF
Store channel states
Led notification
Buzzer notification
Definition at line 186 of file channel.c.
{
    size_t on_len = strlen(MICROHIL_ON_CHANNEL);
    size_t off_len = strlen(MICROHIL_OFF_CHANNEL);
    bool on = (memcmp(args + 10, MICROHIL_ON_CHANNEL, on_len) == 0);
    bool off = (memcmp(args + 10, MICROHIL_OFF_CHANNEL, off_len) == 0);
    if (on)
    {
        microhil_relay_all(true);
        memset(channels, 1, MICROHIL_NUMBER_OF_CHANNELS * sizeof(uint8_t));
#ifdef VERBOSE
        printf("%s %s\n", MICROHIL_VERBOSE, MICROHIL_ALL_ON);
#endif
    }
    if (off)
    {
        microhil_relay_all(false);
        memset(channels, 0, MICROHIL_NUMBER_OF_CHANNELS * sizeof(uint8_t));
#ifdef VERBOSE
        printf("%s %s\n", MICROHIL_VERBOSE, MICROHIL_ALL_OFF);
#endif
    }
    microhil_write_pixel(255, 255, 255);
    microhil_write_pwm(PWM_CHAN_A, 80);
    microhil_delay_ms(100);
    microhil_write_pwm(PWM_CHAN_A, 0);
}
References channels, MICROHIL_ALL_OFF, MICROHIL_ALL_ON, microhil_delay_ms(), MICROHIL_NUMBER_OF_CHANNELS, MICROHIL_OFF_CHANNEL, MICROHIL_ON_CHANNEL, microhil_relay_all(), MICROHIL_VERBOSE, microhil_write_pixel(), and microhil_write_pwm().
microhil_board_id()
MICROHIL_PRIVATE void microhil_board_id ()
Gets unique HW board id.
Definition at line 234 of file channel.c.
{
    printf("%s", MICROHIL_BOARD_ID);
}
References MICROHIL_BOARD_ID.
microhil_channel()
MICROHIL_PRIVATE void microhil_channel (uint8_t * args)
Performs channel operation (single channel)
Parameters
args represents arguments (channel number and state on/off)
Definition at line 158 of file channel.c.
{
    uint8_t channel_number = args[6];
    size_t on_len = strlen(MICROHIL_ON_CHANNEL);
    size_t off_len = strlen(MICROHIL_OFF_CHANNEL);
    bool on = (memcmp(args + 8, MICROHIL_ON_CHANNEL, on_len) == 0);
    bool off = (memcmp(args + 8, MICROHIL_OFF_CHANNEL, off_len) == 0);
    if(on)
    {
        microhil_relay(to_gpio(channel_number), on);
#ifdef VERBOSE
        printf("%s channel %c on\n", MICROHIL_VERBOSE, channel_number);
#endif
    }
    if (off)
    {
        microhil_relay(to_gpio(channel_number), off);
#ifdef VERBOSE
        printf("%s channel %c off\n", MICROHIL_VERBOSE, channel_number);
#endif
    }
}
References MICROHIL_OFF_CHANNEL, MICROHIL_ON_CHANNEL, microhil_relay(), MICROHIL_VERBOSE, and to_gpio().
microhil_channel_switch()
void microhil_channel_switch (uint8_t * request)
Switches channels by command request.
Parameters
request represents command request
Definition at line 113 of file channel.c.
{
    microhil_req key = {request, NULL};
    microhil_req *channel_target = bsearch(
        &key,
        request_tbl,
        sizeof(request_tbl) / sizeof(request_tbl[0]),
        sizeof(request_tbl[0]),
        comapre_request
    );
    channel_target->req_operation(request);
}
References comapre_request(), _microhil_req::req_operation, and request_tbl.
Referenced by main().
microhil_version()
MICROHIL_PRIVATE void microhil_version ()
Gets microHIL FW version.
Definition at line 241 of file channel.c.
{
    printf("%s", MICROHIL_VERSION);
}
References MICROHIL_VERSION.
to_gpio()
MICROHIL_PRIVATE microhil_channel_gpio to_gpio (uint8_t channel_number)
Converts channel number to GPIO number.
Parameters
channel_number represents channel number
Returns
GPIO pin number
Definition at line 132 of file channel.c.
{
    switch(channel_number)
    {
        case 1:
            return MICROHIL_CHANNEL_0;
        case 2:
            return MICROHIL_CHANNEL_1;
        case 3:
            return MICROHIL_CHANNEL_2;
        case 4:
            return MICROHIL_CHANNEL_3;
        case 5:
            return MICROHIL_CHANNEL_4;
        case 6:
            return MICROHIL_CHANNEL_5;
        case 7:
            return MICROHIL_CHANNEL_6;
        case 8:
            return MICROHIL_CHANNEL_7;
        }
}
References MICROHIL_CHANNEL_0, MICROHIL_CHANNEL_1, MICROHIL_CHANNEL_2, MICROHIL_CHANNEL_3, MICROHIL_CHANNEL_4, MICROHIL_CHANNEL_5, MICROHIL_CHANNEL_6, and MICROHIL_CHANNEL_7.
Referenced by microhil_channel().
Variable Documentation
channels
uint8_t channels[MICROHIL_NUMBER_OF_CHANNELS] = {0} static
Buffer for storing channel states.
Definition at line 53 of file channel.c.
Referenced by microhil_all_channels().
request_tbl
microhil_req request_tbl[] static
Initial value:
= {
    {"mh#ch#1#on#end", microhil_channel},
    {"mh#ch#1#off#end", microhil_channel},
    {"mh#ch#2#on#end", microhil_channel},
    {"mh#ch#2#off#end", microhil_channel},
    {"mh#ch#3#on#end", microhil_channel},
    {"mh#ch#3#off#end", microhil_channel},
    {"mh#ch#4#on#end", microhil_channel},
    {"mh#ch#4#off#end", microhil_channel},
    {"mh#ch#5#on#end", microhil_channel},
    {"mh#ch#5#off#end", microhil_channel},
    {"mh#ch#6#on#end", microhil_channel},
    {"mh#ch#6#off#end", microhil_channel},
    {"mh#ch#7#on#end", microhil_channel},
    {"mh#ch#7#off#end", microhil_channel},
    {"mh#ch#8#on#end", microhil_channel},
    {"mh#ch#8#off#end", microhil_channel},
    {"mh#ch#all#on#end", microhil_all_channels},
    {"mh#ch#all#off#end", microhil_all_channels},
    {"mh#ch#board#id#end", microhil_board_id},
    {"mh#ch#version#end", microhil_version}
}
Request table (mapped requests and functions)
Definition at line 75 of file channel.c.
Referenced by microhil_channel_switch().