microhildesk: Electux::App::Model::ModelControl Class Reference
Electux::App::Model::ModelControl Class Reference
#include <model_control.h>
Public Types
enum class ModelControlKey {
Enable , Mode , Toggle , Timer ,
TimerEnable
}
Enum for control configuration keys.
Public Member Functions
ModelControl () noexcept=default
ModelControl constructor.
Entities getAllEntries () const final
Gets all model entries.
std::string toString (const ModelControlKey &key) const
Converts Key enum to.
bool validateKey (const std::string &key) const
Validates if key is valid control configuration key.
bool add (const std::string &key, const std::string &data) final
Adds entity to model {'key': 'data'}.
const std::string & getEntity (const std::string &key) const final
Gets entity by key.
const Entities & get () const final
Gets model entities.
bool update (const std::string &key, const std::string &data) final
Updates entity value by key.
void clear () final
Clears all model entities.
Private Attributes
Entities m_entities {}
Model entities in format map of strings {key: data}.
Detailed Description
Definition at line 25 of file model_control.h.
Member Enumeration Documentation
ModelControlKey
enum class Electux::App::Model::ModelControl::ModelControlKey strong
Enum for control configuration keys.
Enumerator
Enable
Mode
Toggle
Timer
TimerEnable
Definition at line 34 of file model_control.h.
        {
            Enable,
            Mode,
            Toggle,
            Timer,
            TimerEnable
        };
Constructor & Destructor Documentation
ModelControl()
Electux::App::Model::ModelControl::ModelControl () inline default noexcept
ModelControl constructor.
Member Function Documentation
add()
bool Model::add (const std::string & key, const std::string & data) final virtual inherited
Adds entity to model {'key': 'data'}.
Parameters
key Represents model enity key to be added
data Represents model entity data to be added
Implements Electux::App::Model::IModel.
Definition at line 23 of file model.cc.
{
    auto const [it, inserted] = m_entities.try_emplace(key, data);
    return inserted;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), and Electux::App::Config::ConfigManager::load().
clear()
void Model::clear () final virtual inherited
Clears all model entities.
Implements Electux::App::Model::IModel.
Definition at line 57 of file model.cc.
{
    m_entities.clear();
}
References Electux::App::Model::Model::m_entities.
get()
const Entities & Model::get () const final virtual inherited
Gets model entities.
Returns
Model entities in format map of strings
Implements Electux::App::Model::IModel.
Definition at line 41 of file model.cc.
{
    return m_entities;
}
References Electux::App::Model::Model::m_entities.
getAllEntries()
Entities ModelControl::getAllEntries () const final virtual
Gets all model entries.
Returns
Map of all model entries {key: data}
Implements Electux::App::Model::IModel.
Definition at line 36 of file model_control.cc.
{
    static const std::vector<ModelControlKey> keys =
    {
        ModelControlKey::Enable,
        ModelControlKey::Mode,
        ModelControlKey::Toggle,
        ModelControlKey::Timer,
        ModelControlKey::TimerEnable
    };
    Entities entries;
    for (const auto& key : keys)
    {
        std::string keyStr = toString(key);
        entries[keyStr] = getEntity(keyStr);
    }
    return entries;
}
References Enable, Electux::App::Model::Model::getEntity(), Mode, Timer, TimerEnable, Toggle, and toString().
getEntity()
const std::string & Model::getEntity (const std::string & key) const final virtual inherited
Gets entity by key.
Parameters
key Represents model enity key
Returns
Entity selected by key
Implements Electux::App::Model::IModel.
Definition at line 29 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        return it->second;
    }
    static const std::string fallback{""};
    return fallback;
}
References Electux::App::Model::Model::m_entities.
Referenced by getAllEntries(), Electux::App::Model::ModelLog::getAllEntries(), Electux::App::Model::ModelSerial::getAllEntries(), Electux::App::View::AppHome::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToogleChanged(), Electux::App::View::AppHome::onChannelToggleChanged(), Electux::App::View::AppHome::updateUiData(), and Electux::App::View::Settings::AppSettings::updateUiData().
toString()
std::string ModelControl::toString (const ModelControlKey & key) const
Converts Key enum to.
Parameters
key Represents ModelControlKey enum value
Returns
string representation of ModelControlKey enum
Definition at line 57 of file model_control.cc.
{
    switch (key)
    {
    case ModelControlKey::Enable: return enable.data();
    case ModelControlKey::Mode: return mode.data();
    case ModelControlKey::Toggle: return toggle.data();
    case ModelControlKey::Timer: return timer.data();
    case ModelControlKey::TimerEnable: return timerEnable.data();
    default: return unknown.data();
    }
}
References Enable, Mode, Timer, TimerEnable, and Toggle.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), getAllEntries(), Electux::App::View::AppHome::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToogleChanged(), Electux::App::View::AppHome::onChannelToggleChanged(), Electux::App::View::AppHome::updateUiData(), and validateKey().
update()
bool Model::update (const std::string & key, const std::string & data) final virtual inherited
Updates entity value by key.
Parameters
key Represents model entity key
data Represents new value for the entity
Returns
True if the entity was updated, false if the key does not exist
Implements Electux::App::Model::IModel.
Definition at line 46 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        it->second = data;
        return true;
    }
    return false;
}
References Electux::App::Model::Model::m_entities.
Referenced by Electux::App::View::AppHome::getUiData(), Electux::App::View::Settings::AppSettings::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToogleChanged(), and Electux::App::View::AppHome::onChannelToggleChanged().
validateKey()
bool ModelControl::validateKey (const std::string & key) const
Validates if key is valid control configuration key.
Parameters
key Represents string key to be validated
Returns
status true if key is valid else false
Definition at line 70 of file model_control.cc.
{
    return key == toString(ModelControlKey::Enable) ||
            key == toString(ModelControlKey::Mode) ||
            key == toString(ModelControlKey::Toggle) ||
            key == toString(ModelControlKey::Timer) ||
            key == toString(ModelControlKey::TimerEnable);
}
References Enable, Mode, Timer, TimerEnable, Toggle, and toString().
Referenced by Electux::App::Config::ConfigManager::load().
Member Data Documentation
m_entities
Entities Electux::App::Model::Model::m_entities {} private inherited
Model entities in format map of strings {key: data}.
Definition at line 65 of file model.h.
{};
Referenced by Electux::App::Model::Model::add(), Electux::App::Model::Model::clear(), Electux::App::Model::Model::get(), Electux::App::Model::Model::getEntity(), and Electux::App::Model::Model::update().
The documentation for this class was generated from the following files:
model/model_control.h
model/model_control.cc