microhildesk: MicroHILViewHome Class Reference
MicroHILViewHome Class Reference
#include <microhil_view_home.h>
Public Member Functions
MicroHILViewHome (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
~MicroHILViewHome ()=default
channel0Changed channel0IsChanged () final
channel1Changed channel1IsChanged () final
channel2Changed channel2IsChanged () final
channel3Changed channel3IsChanged () final
channel4Changed channel4IsChanged () final
channel5Changed channel5IsChanged () final
channel6Changed channel6IsChanged () final
channel7Changed channel7IsChanged () final
void onChannel0 () final
void onChannel1 () final
void onChannel2 () final
void onChannel3 () final
void onChannel4 () final
void onChannel5 () final
void onChannel6 () final
void onChannel7 () final
select0Changed channel0IsSelected () final
select1Changed channel1IsSelected () final
select2Changed channel2IsSelected () final
select3Changed channel3IsSelected () final
select4Changed channel4IsSelected () final
select5Changed channel5IsSelected () final
select6Changed channel6IsSelected () final
select7Changed channel7IsSelected () final
void onChannel0TypeSelected () final
void onChannel1TypeSelected () final
void onChannel2TypeSelected () final
void onChannel3TypeSelected () final
void onChannel4TypeSelected () final
void onChannel5TypeSelected () final
void onChannel6TypeSelected () final
void onChannel7TypeSelected () final
channel0Toggled channel0IsToggled () final
channel1Toggled channel1IsToggled () final
channel2Toggled channel2IsToggled () final
channel3Toggled channel3IsToggled () final
channel4Toggled channel4IsToggled () final
channel5Toggled channel5IsToggled () final
channel6Toggled channel6IsToggled () final
channel7Toggled channel7IsToggled () final
void onChannel0Toggled () final
void onChannel1Toggled () final
void onChannel2Toggled () final
void onChannel3Toggled () final
void onChannel4Toggled () final
void onChannel5Toggled () final
void onChannel6Toggled () final
void onChannel7Toggled () final
channel0SpinTimerChanged channel0IsSpinTimerChanged () final
channel1SpinTimerChanged channel1IsSpinTimerChanged () final
channel2SpinTimerChanged channel2IsSpinTimerChanged () final
channel3SpinTimerChanged channel3IsSpinTimerChanged () final
channel4SpinTimerChanged channel4IsSpinTimerChanged () final
channel5SpinTimerChanged channel5IsSpinTimerChanged () final
channel6SpinTimerChanged channel6IsSpinTimerChanged () final
channel7SpinTimerChanged channel7IsSpinTimerChanged () final
void onChannel0SpinTimerChanged () final
void onChannel1SpinTimerChanged () final
void onChannel2SpinTimerChanged () final
void onChannel3SpinTimerChanged () final
void onChannel4SpinTimerChanged () final
void onChannel5SpinTimerChanged () final
void onChannel6SpinTimerChanged () final
void onChannel7SpinTimerChanged () final
channel0TimerToggled channel0IsTimerChanged () final
channel1TimerToggled channel1IsTimerChanged () final
channel2TimerToggled channel2IsTimerChanged () final
channel3TimerToggled channel3IsTimerChanged () final
channel4TimerToggled channel4IsTimerChanged () final
channel5TimerToggled channel5IsTimerChanged () final
channel6TimerToggled channel6IsTimerChanged () final
channel7TimerToggled channel7IsTimerChanged () final
void onChannel0TimerChanged () final
void onChannel1TimerChanged () final
void onChannel2TimerChanged () final
void onChannel3TimerChanged () final
void onChannel4TimerChanged () final
void onChannel5TimerChanged () final
void onChannel6TimerChanged () final
void onChannel7TimerChanged () final
Public Member Functions inherited from AbMicroHILViewHome
virtual ~AbMicroHILViewHome ()=default
virtual channel0Changed channel0IsChanged ()=0
virtual channel1Changed channel1IsChanged ()=0
virtual channel2Changed channel2IsChanged ()=0
virtual channel3Changed channel3IsChanged ()=0
virtual channel4Changed channel4IsChanged ()=0
virtual channel5Changed channel5IsChanged ()=0
virtual channel6Changed channel6IsChanged ()=0
virtual channel7Changed channel7IsChanged ()=0
virtual void onChannel0 ()=0
virtual void onChannel1 ()=0
virtual void onChannel2 ()=0
virtual void onChannel3 ()=0
virtual void onChannel4 ()=0
virtual void onChannel5 ()=0
virtual void onChannel6 ()=0
virtual void onChannel7 ()=0
virtual select0Changed channel0IsSelected ()=0
virtual select1Changed channel1IsSelected ()=0
virtual select2Changed channel2IsSelected ()=0
virtual select3Changed channel3IsSelected ()=0
virtual select4Changed channel4IsSelected ()=0
virtual select5Changed channel5IsSelected ()=0
virtual select6Changed channel6IsSelected ()=0
virtual select7Changed channel7IsSelected ()=0
virtual void onChannel0TypeSelected ()=0
virtual void onChannel1TypeSelected ()=0
virtual void onChannel2TypeSelected ()=0
virtual void onChannel3TypeSelected ()=0
virtual void onChannel4TypeSelected ()=0
virtual void onChannel5TypeSelected ()=0
virtual void onChannel6TypeSelected ()=0
virtual void onChannel7TypeSelected ()=0
virtual channel0Toggled channel0IsToggled ()=0
virtual channel1Toggled channel1IsToggled ()=0
virtual channel2Toggled channel2IsToggled ()=0
virtual channel3Toggled channel3IsToggled ()=0
virtual channel4Toggled channel4IsToggled ()=0
virtual channel5Toggled channel5IsToggled ()=0
virtual channel6Toggled channel6IsToggled ()=0
virtual channel7Toggled channel7IsToggled ()=0
virtual void onChannel0Toggled ()=0
virtual void onChannel1Toggled ()=0
virtual void onChannel2Toggled ()=0
virtual void onChannel3Toggled ()=0
virtual void onChannel4Toggled ()=0
virtual void onChannel5Toggled ()=0
virtual void onChannel6Toggled ()=0
virtual void onChannel7Toggled ()=0
virtual channel0SpinTimerChanged channel0IsSpinTimerChanged ()=0
virtual channel1SpinTimerChanged channel1IsSpinTimerChanged ()=0
virtual channel2SpinTimerChanged channel2IsSpinTimerChanged ()=0
virtual channel3SpinTimerChanged channel3IsSpinTimerChanged ()=0
virtual channel4SpinTimerChanged channel4IsSpinTimerChanged ()=0
virtual channel5SpinTimerChanged channel5IsSpinTimerChanged ()=0
virtual channel6SpinTimerChanged channel6IsSpinTimerChanged ()=0
virtual channel7SpinTimerChanged channel7IsSpinTimerChanged ()=0
virtual void onChannel0SpinTimerChanged ()=0
virtual void onChannel1SpinTimerChanged ()=0
virtual void onChannel2SpinTimerChanged ()=0
virtual void onChannel3SpinTimerChanged ()=0
virtual void onChannel4SpinTimerChanged ()=0
virtual void onChannel5SpinTimerChanged ()=0
virtual void onChannel6SpinTimerChanged ()=0
virtual void onChannel7SpinTimerChanged ()=0
virtual channel0TimerToggled channel0IsTimerChanged ()=0
virtual channel1TimerToggled channel1IsTimerChanged ()=0
virtual channel2TimerToggled channel2IsTimerChanged ()=0
virtual channel3TimerToggled channel3IsTimerChanged ()=0
virtual channel4TimerToggled channel4IsTimerChanged ()=0
virtual channel5TimerToggled channel5IsTimerChanged ()=0
virtual channel6TimerToggled channel6IsTimerChanged ()=0
virtual channel7TimerToggled channel7IsTimerChanged ()=0
virtual void onChannel0TimerChanged ()=0
virtual void onChannel1TimerChanged ()=0
virtual void onChannel2TimerChanged ()=0
virtual void onChannel3TimerChanged ()=0
virtual void onChannel4TimerChanged ()=0
virtual void onChannel5TimerChanged ()=0
virtual void onChannel6TimerChanged ()=0
virtual void onChannel7TimerChanged ()=0
Private Member Functions
void mapping ()
void enableChannel0 ()
void disableChannel0 ()
void enableChannel1 ()
void disableChannel1 ()
void enableChannel2 ()
void disableChannel2 ()
void enableChannel3 ()
void disableChannel3 ()
void enableChannel4 ()
void disableChannel4 ()
void enableChannel5 ()
void disableChannel5 ()
void enableChannel6 ()
void disableChannel6 ()
void enableChannel7 ()
void disableChannel7 ()
void toggleModeChannel0 ()
void timerModeChannel0 ()
void toggleModeChannel1 ()
void timerModeChannel1 ()
void toggleModeChannel2 ()
void timerModeChannel2 ()
void toggleModeChannel3 ()
void timerModeChannel3 ()
void toggleModeChannel4 ()
void timerModeChannel4 ()
void toggleModeChannel5 ()
void timerModeChannel5 ()
void toggleModeChannel6 ()
void timerModeChannel6 ()
void toggleModeChannel7 ()
void timerModeChannel7 ()
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui
std::vector< Glib::RefPtr< Gtk::CheckButton > > m_enableChannels
std::vector< Glib::RefPtr< Gtk::ComboBoxText > > m_selectControlChannels
std::vector< Glib::RefPtr< Gtk::ToggleButton > > m_toggleChannels
std::vector< Glib::RefPtr< Gtk::SpinButton > > m_spinTimerChannels
std::vector< Glib::RefPtr< Gtk::ToggleButton > > m_toggleTimerChannels
std::vector< Glib::RefPtr< Gtk::ProgressBar > > m_stautsTimerChannels
Glib::RefPtr< Gtk::Adjustment > m_adjustment_digits
channel0Changed m_channel0Enabled
channel1Changed m_channel1Enabled
channel2Changed m_channel2Enabled
channel3Changed m_channel3Enabled
channel4Changed m_channel4Enabled
channel5Changed m_channel5Enabled
channel6Changed m_channel6Enabled
channel7Changed m_channel7Enabled
select0Changed m_channel0ControlType
select1Changed m_channel1ControlType
select2Changed m_channel2ControlType
select3Changed m_channel3ControlType
select4Changed m_channel4ControlType
select5Changed m_channel5ControlType
select6Changed m_channel6ControlType
select7Changed m_channel7ControlType
channel0Toggled m_channel0Toggled
channel1Toggled m_channel1Toggled
channel2Toggled m_channel2Toggled
channel3Toggled m_channel3Toggled
channel4Toggled m_channel4Toggled
channel5Toggled m_channel5Toggled
channel6Toggled m_channel6Toggled
channel7Toggled m_channel7Toggled
channel0SpinTimerChanged m_channel0SpinTimerChanged
channel1SpinTimerChanged m_channel1SpinTimerChanged
channel2SpinTimerChanged m_channel2SpinTimerChanged
channel3SpinTimerChanged m_channel3SpinTimerChanged
channel4SpinTimerChanged m_channel4SpinTimerChanged
channel5SpinTimerChanged m_channel5SpinTimerChanged
channel6SpinTimerChanged m_channel6SpinTimerChanged
channel7SpinTimerChanged m_channel7SpinTimerChanged
channel0TimerToggled m_channel0TimerToggled
channel1TimerToggled m_channel1TimerToggled
channel2TimerToggled m_channel2TimerToggled
channel3TimerToggled m_channel3TimerToggled
channel4TimerToggled m_channel4TimerToggled
channel5TimerToggled m_channel5TimerToggled
channel6TimerToggled m_channel6TimerToggled
channel7TimerToggled m_channel7TimerToggled
Additional Inherited Members
Public Types inherited from AbMicroHILViewHome
using channel0Changed = sigc::signal< void(bool)>
using channel1Changed = sigc::signal< void(bool)>
using channel2Changed = sigc::signal< void(bool)>
using channel3Changed = sigc::signal< void(bool)>
using channel4Changed = sigc::signal< void(bool)>
using channel5Changed = sigc::signal< void(bool)>
using channel6Changed = sigc::signal< void(bool)>
using channel7Changed = sigc::signal< void(bool)>
using select0Changed = sigc::signal< void(int)>
using select1Changed = sigc::signal< void(int)>
using select2Changed = sigc::signal< void(int)>
using select3Changed = sigc::signal< void(int)>
using select4Changed = sigc::signal< void(int)>
using select5Changed = sigc::signal< void(int)>
using select6Changed = sigc::signal< void(int)>
using select7Changed = sigc::signal< void(int)>
using channel0Toggled = sigc::signal< void(bool)>
using channel1Toggled = sigc::signal< void(bool)>
using channel2Toggled = sigc::signal< void(bool)>
using channel3Toggled = sigc::signal< void(bool)>
using channel4Toggled = sigc::signal< void(bool)>
using channel5Toggled = sigc::signal< void(bool)>
using channel6Toggled = sigc::signal< void(bool)>
using channel7Toggled = sigc::signal< void(bool)>
using channel0SpinTimerChanged = sigc::signal< void(int)>
using channel1SpinTimerChanged = sigc::signal< void(int)>
using channel2SpinTimerChanged = sigc::signal< void(int)>
using channel3SpinTimerChanged = sigc::signal< void(int)>
using channel4SpinTimerChanged = sigc::signal< void(int)>
using channel5SpinTimerChanged = sigc::signal< void(int)>
using channel6SpinTimerChanged = sigc::signal< void(int)>
using channel7SpinTimerChanged = sigc::signal< void(int)>
using channel0TimerToggled = sigc::signal< void(bool)>
using channel1TimerToggled = sigc::signal< void(bool)>
using channel2TimerToggled = sigc::signal< void(bool)>
using channel3TimerToggled = sigc::signal< void(bool)>
using channel4TimerToggled = sigc::signal< void(bool)>
using channel5TimerToggled = sigc::signal< void(bool)>
using channel6TimerToggled = sigc::signal< void(bool)>
using channel7TimerToggled = sigc::signal< void(bool)>
Detailed Description
Definition at line 38 of file microhil_view_home.h.
Constructor & Destructor Documentation
MicroHILViewHome()
MicroHILViewHome::MicroHILViewHome (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
Definition at line 98 of file microhil_view_home.cc.
 : Gtk::ApplicationWindow(object), m_ui{ui}
{
    // Bind channel widgets
    for (int i = 0; i < kNumberOfChannels; i++)
    {
        m_enableChannels.push_back(
            Glib::RefPtr<Gtk::CheckButton>::cast_dynamic(
                m_ui->get_object(kCheckButtonsId[i])
            )
        );
        m_selectControlChannels.push_back(
            Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
                m_ui->get_object(kComboBoxTextsId[i])
            )
        );
        m_toggleChannels.push_back(
            Glib::RefPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kToggleButtonsId[i])
            )
        );
        m_spinTimerChannels.push_back(
            Glib::RefPtr<Gtk::SpinButton>::cast_dynamic(
                m_ui->get_object(kTimerSpinButtonsId[i])
            )
        );
        m_toggleTimerChannels.push_back(
            Glib::RefPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kTimerToggleButtonsId[i])
            )
        );
        m_stautsTimerChannels.push_back(
            Glib::RefPtr<Gtk::ProgressBar>::cast_dynamic(
                m_ui->get_object(kTimerProgressBarStatus0Id[i])
            )
        );
    }
    // Map channel signals and slots
    mapping();
    // Disabled all channels by default
    disableChannel0();
    disableChannel1();
    disableChannel2();
    disableChannel3();
    disableChannel4();
    disableChannel5();
    disableChannel6();
    disableChannel7();
}
References disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), m_enableChannels, m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, m_toggleTimerChannels, m_ui, and mapping().
~MicroHILViewHome()
MicroHILViewHome::~MicroHILViewHome () default
Member Function Documentation
channel0IsChanged()
MicroHILViewHome::channel0Changed MicroHILViewHome::channel0IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 22 of file microhil_view_home_signals.cc.
{
    return m_channel0Enabled;
}
References m_channel0Enabled.
channel0IsSelected()
MicroHILViewHome::select0Changed MicroHILViewHome::channel0IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 70 of file microhil_view_home_signals.cc.
{
    return m_channel0ControlType;
}
References m_channel0ControlType.
channel0IsSpinTimerChanged()
MicroHILViewHome::channel0SpinTimerChanged MicroHILViewHome::channel0IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 166 of file microhil_view_home_signals.cc.
{
    return m_channel0SpinTimerChanged;
}
References m_channel0SpinTimerChanged.
channel0IsTimerChanged()
MicroHILViewHome::channel0TimerToggled MicroHILViewHome::channel0IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 214 of file microhil_view_home_signals.cc.
{
    return m_channel0TimerToggled;
}
References m_channel0TimerToggled.
channel0IsToggled()
MicroHILViewHome::channel0Toggled MicroHILViewHome::channel0IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 118 of file microhil_view_home_signals.cc.
{
    return m_channel0Toggled;
}
References m_channel0Toggled.
channel1IsChanged()
MicroHILViewHome::channel1Changed MicroHILViewHome::channel1IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 28 of file microhil_view_home_signals.cc.
{
    return m_channel1Enabled;
}
References m_channel1Enabled.
channel1IsSelected()
MicroHILViewHome::select1Changed MicroHILViewHome::channel1IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 76 of file microhil_view_home_signals.cc.
{
    return m_channel1ControlType;
}
References m_channel1ControlType.
channel1IsSpinTimerChanged()
MicroHILViewHome::channel1SpinTimerChanged MicroHILViewHome::channel1IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 172 of file microhil_view_home_signals.cc.
{
    return m_channel1SpinTimerChanged;
}
References m_channel1SpinTimerChanged.
channel1IsTimerChanged()
MicroHILViewHome::channel1TimerToggled MicroHILViewHome::channel1IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 220 of file microhil_view_home_signals.cc.
{
    return m_channel1TimerToggled;
}
References m_channel1TimerToggled.
channel1IsToggled()
MicroHILViewHome::channel1Toggled MicroHILViewHome::channel1IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 124 of file microhil_view_home_signals.cc.
{
    return m_channel1Toggled;
}
References m_channel1Toggled.
channel2IsChanged()
MicroHILViewHome::channel2Changed MicroHILViewHome::channel2IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 34 of file microhil_view_home_signals.cc.
{
    return m_channel2Enabled;
}
References m_channel2Enabled.
channel2IsSelected()
MicroHILViewHome::select2Changed MicroHILViewHome::channel2IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 82 of file microhil_view_home_signals.cc.
{
    return m_channel2ControlType;
}
References m_channel2ControlType.
channel2IsSpinTimerChanged()
MicroHILViewHome::channel2SpinTimerChanged MicroHILViewHome::channel2IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 178 of file microhil_view_home_signals.cc.
{
    return m_channel2SpinTimerChanged;
}
References m_channel2SpinTimerChanged.
channel2IsTimerChanged()
MicroHILViewHome::channel2TimerToggled MicroHILViewHome::channel2IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 226 of file microhil_view_home_signals.cc.
{
    return m_channel2TimerToggled;
}
References m_channel2TimerToggled.
channel2IsToggled()
MicroHILViewHome::channel2Toggled MicroHILViewHome::channel2IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 130 of file microhil_view_home_signals.cc.
{
    return m_channel2Toggled;
}
References m_channel2Toggled.
channel3IsChanged()
MicroHILViewHome::channel3Changed MicroHILViewHome::channel3IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 40 of file microhil_view_home_signals.cc.
{
    return m_channel3Enabled;
}
References m_channel3Enabled.
channel3IsSelected()
MicroHILViewHome::select3Changed MicroHILViewHome::channel3IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 88 of file microhil_view_home_signals.cc.
{
    return m_channel3ControlType;
}
References m_channel3ControlType.
channel3IsSpinTimerChanged()
MicroHILViewHome::channel3SpinTimerChanged MicroHILViewHome::channel3IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 184 of file microhil_view_home_signals.cc.
{
    return m_channel3SpinTimerChanged;
}
References m_channel3SpinTimerChanged.
channel3IsTimerChanged()
MicroHILViewHome::channel3TimerToggled MicroHILViewHome::channel3IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 232 of file microhil_view_home_signals.cc.
{
    return m_channel3TimerToggled;
}
References m_channel3TimerToggled.
channel3IsToggled()
MicroHILViewHome::channel3Toggled MicroHILViewHome::channel3IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 136 of file microhil_view_home_signals.cc.
{
    return m_channel3Toggled;
}
References m_channel3Toggled.
channel4IsChanged()
MicroHILViewHome::channel4Changed MicroHILViewHome::channel4IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 46 of file microhil_view_home_signals.cc.
{
    return m_channel4Enabled;
}
References m_channel4Enabled.
channel4IsSelected()
MicroHILViewHome::select4Changed MicroHILViewHome::channel4IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 94 of file microhil_view_home_signals.cc.
{
    return m_channel4ControlType;
}
References m_channel4ControlType.
channel4IsSpinTimerChanged()
MicroHILViewHome::channel4SpinTimerChanged MicroHILViewHome::channel4IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 190 of file microhil_view_home_signals.cc.
{
    return m_channel4SpinTimerChanged;
}
References m_channel4SpinTimerChanged.
channel4IsTimerChanged()
MicroHILViewHome::channel4TimerToggled MicroHILViewHome::channel4IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 238 of file microhil_view_home_signals.cc.
{
    return m_channel4TimerToggled;
}
References m_channel4TimerToggled.
channel4IsToggled()
MicroHILViewHome::channel4Toggled MicroHILViewHome::channel4IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 142 of file microhil_view_home_signals.cc.
{
    return m_channel4Toggled;
}
References m_channel4Toggled.
channel5IsChanged()
MicroHILViewHome::channel5Changed MicroHILViewHome::channel5IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 52 of file microhil_view_home_signals.cc.
{
    return m_channel5Enabled;
}
References m_channel5Enabled.
channel5IsSelected()
MicroHILViewHome::select5Changed MicroHILViewHome::channel5IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 100 of file microhil_view_home_signals.cc.
{
    return m_channel5ControlType;
}
References m_channel5ControlType.
channel5IsSpinTimerChanged()
MicroHILViewHome::channel5SpinTimerChanged MicroHILViewHome::channel5IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 196 of file microhil_view_home_signals.cc.
{
    return m_channel5SpinTimerChanged;
}
References m_channel5SpinTimerChanged.
channel5IsTimerChanged()
MicroHILViewHome::channel5TimerToggled MicroHILViewHome::channel5IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 244 of file microhil_view_home_signals.cc.
{
    return m_channel5TimerToggled;
}
References m_channel5TimerToggled.
channel5IsToggled()
MicroHILViewHome::channel5Toggled MicroHILViewHome::channel5IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 148 of file microhil_view_home_signals.cc.
{
    return m_channel5Toggled;
}
References m_channel5Toggled.
channel6IsChanged()
MicroHILViewHome::channel6Changed MicroHILViewHome::channel6IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 58 of file microhil_view_home_signals.cc.
{
    return m_channel6Enabled;
}
References m_channel6Enabled.
channel6IsSelected()
MicroHILViewHome::select6Changed MicroHILViewHome::channel6IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 106 of file microhil_view_home_signals.cc.
{
    return m_channel6ControlType;
}
References m_channel6ControlType.
channel6IsSpinTimerChanged()
MicroHILViewHome::channel6SpinTimerChanged MicroHILViewHome::channel6IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 202 of file microhil_view_home_signals.cc.
{
    return m_channel6SpinTimerChanged;
}
References m_channel6SpinTimerChanged.
channel6IsTimerChanged()
MicroHILViewHome::channel6TimerToggled MicroHILViewHome::channel6IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 250 of file microhil_view_home_signals.cc.
{
    return m_channel6TimerToggled;
}
References m_channel6TimerToggled.
channel6IsToggled()
MicroHILViewHome::channel6Toggled MicroHILViewHome::channel6IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 154 of file microhil_view_home_signals.cc.
{
    return m_channel6Toggled;
}
References m_channel6Toggled.
channel7IsChanged()
MicroHILViewHome::channel7Changed MicroHILViewHome::channel7IsChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 64 of file microhil_view_home_signals.cc.
{
    return m_channel7Enabled;
}
References m_channel7Enabled.
channel7IsSelected()
MicroHILViewHome::select7Changed MicroHILViewHome::channel7IsSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 112 of file microhil_view_home_signals.cc.
{
    return m_channel7ControlType;
}
References m_channel7ControlType.
channel7IsSpinTimerChanged()
MicroHILViewHome::channel7SpinTimerChanged MicroHILViewHome::channel7IsSpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 208 of file microhil_view_home_signals.cc.
{
    return m_channel7SpinTimerChanged;
}
References m_channel7SpinTimerChanged.
channel7IsTimerChanged()
MicroHILViewHome::channel7TimerToggled MicroHILViewHome::channel7IsTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 256 of file microhil_view_home_signals.cc.
{
    return m_channel7TimerToggled;
}
References m_channel7TimerToggled.
channel7IsToggled()
MicroHILViewHome::channel7Toggled MicroHILViewHome::channel7IsToggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 160 of file microhil_view_home_signals.cc.
{
    return m_channel7Toggled;
}
References m_channel7Toggled.
disableChannel0()
void MicroHILViewHome::disableChannel0 () private
Definition at line 21 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[0]->set_sensitive(false);
    m_toggleChannels[0]->set_sensitive(false);
    m_spinTimerChannels[0]->set_sensitive(false);
    m_toggleTimerChannels[0]->set_sensitive(false);
    m_stautsTimerChannels[0]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel0().
disableChannel1()
void MicroHILViewHome::disableChannel1 () private
Definition at line 39 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[1]->set_sensitive(false);
    m_toggleChannels[1]->set_sensitive(false);
    m_spinTimerChannels[1]->set_sensitive(false);
    m_toggleTimerChannels[1]->set_sensitive(false);
    m_stautsTimerChannels[1]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel1().
disableChannel2()
void MicroHILViewHome::disableChannel2 () private
Definition at line 57 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[2]->set_sensitive(false);
    m_toggleChannels[2]->set_sensitive(false);
    m_spinTimerChannels[2]->set_sensitive(false);
    m_toggleTimerChannels[2]->set_sensitive(false);
    m_stautsTimerChannels[2]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel2().
disableChannel3()
void MicroHILViewHome::disableChannel3 () private
Definition at line 75 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[3]->set_sensitive(false);
    m_toggleChannels[3]->set_sensitive(false);
    m_spinTimerChannels[3]->set_sensitive(false);
    m_toggleTimerChannels[3]->set_sensitive(false);
    m_stautsTimerChannels[3]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel3().
disableChannel4()
void MicroHILViewHome::disableChannel4 () private
Definition at line 93 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[4]->set_sensitive(false);
    m_toggleChannels[4]->set_sensitive(false);
    m_spinTimerChannels[4]->set_sensitive(false);
    m_toggleTimerChannels[4]->set_sensitive(false);
    m_stautsTimerChannels[4]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel4().
disableChannel5()
void MicroHILViewHome::disableChannel5 () private
Definition at line 111 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[5]->set_sensitive(false);
    m_toggleChannels[5]->set_sensitive(false);
    m_spinTimerChannels[5]->set_sensitive(false);
    m_toggleTimerChannels[5]->set_sensitive(false);
    m_stautsTimerChannels[5]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel5().
disableChannel6()
void MicroHILViewHome::disableChannel6 () private
Definition at line 129 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[6]->set_sensitive(false);
    m_toggleChannels[6]->set_sensitive(false);
    m_spinTimerChannels[6]->set_sensitive(false);
    m_toggleTimerChannels[6]->set_sensitive(false);
    m_stautsTimerChannels[6]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel6().
disableChannel7()
void MicroHILViewHome::disableChannel7 () private
Definition at line 147 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[7]->set_sensitive(false);
    m_toggleChannels[7]->set_sensitive(false);
    m_spinTimerChannels[7]->set_sensitive(false);
    m_toggleTimerChannels[7]->set_sensitive(false);
    m_stautsTimerChannels[7]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILViewHome(), and onChannel7().
enableChannel0()
void MicroHILViewHome::enableChannel0 () private
Definition at line 30 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[0]->set_sensitive(true);
    m_toggleChannels[0]->set_sensitive(true);
    m_spinTimerChannels[0]->set_sensitive(true);
    m_toggleTimerChannels[0]->set_sensitive(true);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0().
enableChannel1()
void MicroHILViewHome::enableChannel1 () private
Definition at line 48 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[1]->set_sensitive(true);
    m_toggleChannels[1]->set_sensitive(true);
    m_spinTimerChannels[1]->set_sensitive(true);
    m_toggleTimerChannels[1]->set_sensitive(true);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1().
enableChannel2()
void MicroHILViewHome::enableChannel2 () private
Definition at line 66 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[2]->set_sensitive(true);
    m_toggleChannels[2]->set_sensitive(true);
    m_spinTimerChannels[2]->set_sensitive(true);
    m_toggleTimerChannels[2]->set_sensitive(true);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2().
enableChannel3()
void MicroHILViewHome::enableChannel3 () private
Definition at line 84 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[3]->set_sensitive(true);
    m_toggleChannels[3]->set_sensitive(true);
    m_spinTimerChannels[3]->set_sensitive(true);
    m_toggleTimerChannels[3]->set_sensitive(true);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3().
enableChannel4()
void MicroHILViewHome::enableChannel4 () private
Definition at line 102 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[4]->set_sensitive(true);
    m_toggleChannels[4]->set_sensitive(true);
    m_spinTimerChannels[4]->set_sensitive(true);
    m_toggleTimerChannels[4]->set_sensitive(true);
    m_stautsTimerChannels[4]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel4().
enableChannel5()
void MicroHILViewHome::enableChannel5 () private
Definition at line 120 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[5]->set_sensitive(true);
    m_toggleChannels[5]->set_sensitive(true);
    m_spinTimerChannels[5]->set_sensitive(true);
    m_toggleTimerChannels[5]->set_sensitive(true);
    m_stautsTimerChannels[5]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel5().
enableChannel6()
void MicroHILViewHome::enableChannel6 () private
Definition at line 138 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[6]->set_sensitive(true);
    m_toggleChannels[6]->set_sensitive(true);
    m_spinTimerChannels[6]->set_sensitive(true);
    m_toggleTimerChannels[6]->set_sensitive(true);
    m_stautsTimerChannels[6]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel6().
enableChannel7()
void MicroHILViewHome::enableChannel7 () private
Definition at line 156 of file microhil_view_home_mode.cc.
{
    m_selectControlChannels[7]->set_sensitive(true);
    m_toggleChannels[7]->set_sensitive(true);
    m_spinTimerChannels[7]->set_sensitive(true);
    m_toggleTimerChannels[7]->set_sensitive(true);
    m_stautsTimerChannels[7]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel7().
mapping()
void MicroHILViewHome::mapping () private
Definition at line 21 of file microhil_view_home_map.cc.
{
    // Map channel signals and slots
    m_enableChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel0)
    );
    m_enableChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel1)
    );
    m_enableChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel2)
    );
    m_enableChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel3)
    );
    m_enableChannels[4]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel4)
    );
    m_enableChannels[5]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel5)
    );
    m_enableChannels[6]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel6)
    );
    m_enableChannels[7]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel7)
    );
    m_selectControlChannels[0]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel0TypeSelected)
    );
    m_selectControlChannels[1]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel1TypeSelected)
    );
    m_selectControlChannels[2]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel2TypeSelected)
    );
    m_selectControlChannels[3]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel3TypeSelected)
    );
    m_selectControlChannels[4]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel4TypeSelected)
    );
    m_selectControlChannels[5]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel5TypeSelected)
    );
    m_selectControlChannels[6]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel6TypeSelected)
    );
    m_selectControlChannels[7]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel7TypeSelected)
    );
    m_toggleChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel0Toggled)
    );
    m_toggleChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel1Toggled)
    );
    m_toggleChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel2Toggled)
    );
    m_toggleChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel3Toggled)
    );
    m_toggleChannels[4]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel4Toggled)
    );
    m_toggleChannels[5]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel5Toggled)
    );
    m_toggleChannels[6]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel6Toggled)
    );
    m_toggleChannels[7]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel7Toggled)
    );
    m_spinTimerChannels[0]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel0SpinTimerChanged)
    );
    m_spinTimerChannels[1]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel1SpinTimerChanged)
    );
    m_spinTimerChannels[2]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel2SpinTimerChanged)
    );
    m_spinTimerChannels[3]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel3SpinTimerChanged)
    );
    m_spinTimerChannels[4]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel4SpinTimerChanged)
    );
    m_spinTimerChannels[5]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel5SpinTimerChanged)
    );
    m_spinTimerChannels[6]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel6SpinTimerChanged)
    );
    m_spinTimerChannels[7]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel7SpinTimerChanged)
    );
    m_toggleTimerChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel0TimerChanged)
    );
    m_toggleTimerChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel1TimerChanged)
    );
    m_toggleTimerChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel2TimerChanged)
    );
    m_toggleTimerChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel3TimerChanged)
    );
    m_toggleTimerChannels[4]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel4TimerChanged)
    );
    m_toggleTimerChannels[5]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel5TimerChanged)
    );
    m_toggleTimerChannels[6]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel6TimerChanged)
    );
    m_toggleTimerChannels[7]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILViewHome::onChannel7TimerChanged)
    );
}
References m_enableChannels, m_selectControlChannels, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, onChannel0(), onChannel0SpinTimerChanged(), onChannel0TimerChanged(), onChannel0Toggled(), onChannel0TypeSelected(), onChannel1(), onChannel1SpinTimerChanged(), onChannel1TimerChanged(), onChannel1Toggled(), onChannel1TypeSelected(), onChannel2(), onChannel2SpinTimerChanged(), onChannel2TimerChanged(), onChannel2Toggled(), onChannel2TypeSelected(), onChannel3(), onChannel3SpinTimerChanged(), onChannel3TimerChanged(), onChannel3Toggled(), onChannel3TypeSelected(), onChannel4(), onChannel4SpinTimerChanged(), onChannel4TimerChanged(), onChannel4Toggled(), onChannel4TypeSelected(), onChannel5(), onChannel5SpinTimerChanged(), onChannel5TimerChanged(), onChannel5Toggled(), onChannel5TypeSelected(), onChannel6(), onChannel6SpinTimerChanged(), onChannel6TimerChanged(), onChannel6Toggled(), onChannel6TypeSelected(), onChannel7(), onChannel7SpinTimerChanged(), onChannel7TimerChanged(), onChannel7Toggled(), and onChannel7TypeSelected().
Referenced by MicroHILViewHome().
onChannel0()
void MicroHILViewHome::onChannel0 () final virtual
Implements AbMicroHILViewHome.
Definition at line 21 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[0]->get_active();
    if(status)
    {
        enableChannel0();
    }
    else
    {
        disableChannel0();
    }
    m_channel0Enabled.emit(status);
}
References disableChannel0(), enableChannel0(), m_channel0Enabled, and m_enableChannels.
Referenced by mapping().
onChannel0SpinTimerChanged()
void MicroHILViewHome::onChannel0SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 381 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        int value = m_spinTimerChannels[0]->get_value_as_int();
        m_channel0SpinTimerChanged.emit(value);
    }
}
References m_channel0SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel0TimerChanged()
void MicroHILViewHome::onChannel0TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 453 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[0]->get_active();
        m_channel0TimerToggled.emit(status);
    }
}
References m_channel0TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel0Toggled()
void MicroHILViewHome::onChannel0Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 309 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        bool status = m_toggleChannels[0]->get_active();
        m_channel0Toggled.emit(status);
    }
}
References m_channel0Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel0TypeSelected()
void MicroHILViewHome::onChannel0TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 149 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        int controlType = m_selectControlChannels[0]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel0();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel0();
                break;
        }
        m_channel0ControlType.emit(controlType);
    }
}
References m_channel0ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel0(), TOGGLE_BUTTON, and toggleModeChannel0().
Referenced by mapping().
onChannel1()
void MicroHILViewHome::onChannel1 () final virtual
Implements AbMicroHILViewHome.
Definition at line 37 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[1]->get_active();
    if(status)
    {
        enableChannel1();
    }
    else
    {
        disableChannel1();
    }
    m_channel1Enabled.emit(status);
}
References disableChannel1(), enableChannel1(), m_channel1Enabled, and m_enableChannels.
Referenced by mapping().
onChannel1SpinTimerChanged()
void MicroHILViewHome::onChannel1SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 390 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        int value = m_spinTimerChannels[1]->get_value_as_int();
        m_channel1SpinTimerChanged.emit(value);
    }
}
References m_channel1SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel1TimerChanged()
void MicroHILViewHome::onChannel1TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 462 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[1]->get_active();
        m_channel1TimerToggled.emit(status);
    }
}
References m_channel1TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel1Toggled()
void MicroHILViewHome::onChannel1Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 318 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        bool status = m_toggleChannels[1]->get_active();
        m_channel1Toggled.emit(status);
    }
}
References m_channel1Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel1TypeSelected()
void MicroHILViewHome::onChannel1TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 169 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        int controlType = m_selectControlChannels[1]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel1();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel1();
                break;
        }
        m_channel1ControlType.emit(controlType);
    }
}
References m_channel1ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel1(), TOGGLE_BUTTON, and toggleModeChannel1().
Referenced by mapping().
onChannel2()
void MicroHILViewHome::onChannel2 () final virtual
Implements AbMicroHILViewHome.
Definition at line 53 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[2]->get_active();
    if(status)
    {
        enableChannel2();
    }
    else
    {
        disableChannel2();
    }
    m_channel2Enabled.emit(status);
}
References disableChannel2(), enableChannel2(), m_channel2Enabled, and m_enableChannels.
Referenced by mapping().
onChannel2SpinTimerChanged()
void MicroHILViewHome::onChannel2SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 399 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        int value = m_spinTimerChannels[2]->get_value_as_int();
        m_channel2SpinTimerChanged.emit(value);
    }
}
References m_channel2SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel2TimerChanged()
void MicroHILViewHome::onChannel2TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 471 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[2]->get_active();
        m_channel2TimerToggled.emit(status);
    }
}
References m_channel2TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel2Toggled()
void MicroHILViewHome::onChannel2Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 327 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        bool status = m_toggleChannels[2]->get_active();
        m_channel2Toggled.emit(status);
    }
}
References m_channel2Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel2TypeSelected()
void MicroHILViewHome::onChannel2TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 189 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        int controlType = m_selectControlChannels[2]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel2();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel2();
                break;
        }
        m_channel2ControlType.emit(controlType);
    }
}
References m_channel2ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel2(), TOGGLE_BUTTON, and toggleModeChannel2().
Referenced by mapping().
onChannel3()
void MicroHILViewHome::onChannel3 () final virtual
Implements AbMicroHILViewHome.
Definition at line 69 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[3]->get_active();
    if(status)
    {
        enableChannel3();
    }
    else
    {
        disableChannel3();
    }
    m_channel3Enabled.emit(status);
}
References disableChannel3(), enableChannel3(), m_channel3Enabled, and m_enableChannels.
Referenced by mapping().
onChannel3SpinTimerChanged()
void MicroHILViewHome::onChannel3SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 408 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        int value = m_spinTimerChannels[3]->get_value_as_int();
        m_channel3SpinTimerChanged.emit(value);
    }
}
References m_channel3SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel3TimerChanged()
void MicroHILViewHome::onChannel3TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 480 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[3]->get_active();
        m_channel3TimerToggled.emit(status);
    }
}
References m_channel3TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel3Toggled()
void MicroHILViewHome::onChannel3Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 336 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        bool status = m_toggleChannels[3]->get_active();
        m_channel3Toggled.emit(status);
    }
}
References m_channel3Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel3TypeSelected()
void MicroHILViewHome::onChannel3TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 209 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        int controlType = m_selectControlChannels[3]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel3();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel3();
                break;
        }
        m_channel3ControlType.emit(controlType);
    }
}
References m_channel3ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel3(), TOGGLE_BUTTON, and toggleModeChannel3().
Referenced by mapping().
onChannel4()
void MicroHILViewHome::onChannel4 () final virtual
Implements AbMicroHILViewHome.
Definition at line 85 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[4]->get_active();
    if(status)
    {
        enableChannel4();
    }
    else
    {
        disableChannel4();
    }
    m_channel4Enabled.emit(status);
}
References disableChannel4(), enableChannel4(), m_channel4Enabled, and m_enableChannels.
Referenced by mapping().
onChannel4SpinTimerChanged()
void MicroHILViewHome::onChannel4SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 417 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[4]->get_active() == true)
    {
        int value = m_spinTimerChannels[4]->get_value_as_int();
        m_channel4SpinTimerChanged.emit(value);
    }
}
References m_channel4SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel4TimerChanged()
void MicroHILViewHome::onChannel4TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 489 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[4]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[4]->get_active();
        m_channel4TimerToggled.emit(status);
    }
}
References m_channel4TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel4Toggled()
void MicroHILViewHome::onChannel4Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 345 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[4]->get_active() == true)
    {
        bool status = m_toggleChannels[4]->get_active();
        m_channel4Toggled.emit(status);
    }
}
References m_channel4Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel4TypeSelected()
void MicroHILViewHome::onChannel4TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 229 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[4]->get_active() == true)
    {
        int controlType = m_selectControlChannels[4]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel4();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel4();
                break;
        }
        m_channel4ControlType.emit(controlType);
    }
}
References m_channel4ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel4(), TOGGLE_BUTTON, and toggleModeChannel4().
Referenced by mapping().
onChannel5()
void MicroHILViewHome::onChannel5 () final virtual
Implements AbMicroHILViewHome.
Definition at line 101 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[5]->get_active();
    if(status)
    {
        enableChannel5();
    }
    else
    {
        disableChannel5();
    }
    m_channel5Enabled.emit(status);
}
References disableChannel5(), enableChannel5(), m_channel5Enabled, and m_enableChannels.
Referenced by mapping().
onChannel5SpinTimerChanged()
void MicroHILViewHome::onChannel5SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 426 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[5]->get_active() == true)
    {
        int value = m_spinTimerChannels[5]->get_value_as_int();
        m_channel5SpinTimerChanged.emit(value);
    }
}
References m_channel5SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel5TimerChanged()
void MicroHILViewHome::onChannel5TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 498 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[5]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[5]->get_active();
        m_channel5TimerToggled.emit(status);
    }
}
References m_channel5TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel5Toggled()
void MicroHILViewHome::onChannel5Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 354 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[5]->get_active() == true)
    {
        bool status = m_toggleChannels[5]->get_active();
        m_channel5Toggled.emit(status);
    }
}
References m_channel5Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel5TypeSelected()
void MicroHILViewHome::onChannel5TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 249 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[5]->get_active() == true)
    {
        int controlType = m_selectControlChannels[5]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel5();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel5();
                break;
        }
        m_channel5ControlType.emit(controlType);
    }
}
References m_channel5ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel5(), TOGGLE_BUTTON, and toggleModeChannel5().
Referenced by mapping().
onChannel6()
void MicroHILViewHome::onChannel6 () final virtual
Implements AbMicroHILViewHome.
Definition at line 117 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[6]->get_active();
    if(status)
    {
        enableChannel6();
    }
    else
    {
        disableChannel6();
    }
    m_channel6Enabled.emit(status);
}
References disableChannel6(), enableChannel6(), m_channel6Enabled, and m_enableChannels.
Referenced by mapping().
onChannel6SpinTimerChanged()
void MicroHILViewHome::onChannel6SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 435 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[6]->get_active() == true)
    {
        int value = m_spinTimerChannels[6]->get_value_as_int();
        m_channel6SpinTimerChanged.emit(value);
    }
}
References m_channel6SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel6TimerChanged()
void MicroHILViewHome::onChannel6TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 507 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[6]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[6]->get_active();
        m_channel6TimerToggled.emit(status);
    }
}
References m_channel6TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel6Toggled()
void MicroHILViewHome::onChannel6Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 363 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[6]->get_active() == true)
    {
        bool status = m_toggleChannels[6]->get_active();
        m_channel6Toggled.emit(status);
    }
}
References m_channel6Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel6TypeSelected()
void MicroHILViewHome::onChannel6TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 269 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[6]->get_active() == true)
    {
        int controlType = m_selectControlChannels[6]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel6();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel6();
                break;
        }
        m_channel6ControlType.emit(controlType);
    }
}
References m_channel6ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel6(), TOGGLE_BUTTON, and toggleModeChannel6().
Referenced by mapping().
onChannel7()
void MicroHILViewHome::onChannel7 () final virtual
Implements AbMicroHILViewHome.
Definition at line 133 of file microhil_view_home_slots.cc.
{
    bool status = m_enableChannels[7]->get_active();
    if(status)
    {
        enableChannel7();
    }
    else
    {
        disableChannel7();
    }
    m_channel7Enabled.emit(status);
}
References disableChannel7(), enableChannel7(), m_channel7Enabled, and m_enableChannels.
Referenced by mapping().
onChannel7SpinTimerChanged()
void MicroHILViewHome::onChannel7SpinTimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 444 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[7]->get_active() == true)
    {
        int value = m_spinTimerChannels[7]->get_value_as_int();
        m_channel7SpinTimerChanged.emit(value);
    }
}
References m_channel7SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel7TimerChanged()
void MicroHILViewHome::onChannel7TimerChanged () final virtual
Implements AbMicroHILViewHome.
Definition at line 516 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[7]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[7]->get_active();
        m_channel7TimerToggled.emit(status);
    }
}
References m_channel7TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel7Toggled()
void MicroHILViewHome::onChannel7Toggled () final virtual
Implements AbMicroHILViewHome.
Definition at line 372 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[7]->get_active() == true)
    {
        bool status = m_toggleChannels[7]->get_active();
        m_channel7Toggled.emit(status);
    }
}
References m_channel7Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel7TypeSelected()
void MicroHILViewHome::onChannel7TypeSelected () final virtual
Implements AbMicroHILViewHome.
Definition at line 289 of file microhil_view_home_slots.cc.
{
    if(m_enableChannels[7]->get_active() == true)
    {
        int controlType = m_selectControlChannels[7]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel7();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel7();
                break;
        }
        m_channel7ControlType.emit(controlType);
    }
}
References m_channel7ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel7(), TOGGLE_BUTTON, and toggleModeChannel7().
Referenced by mapping().
timerModeChannel0()
void MicroHILViewHome::timerModeChannel0 () private
Definition at line 173 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[0]->set_sensitive(false);
    m_spinTimerChannels[0]->set_sensitive(true);
    m_toggleTimerChannels[0]->set_sensitive(true);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0TypeSelected().
timerModeChannel1()
void MicroHILViewHome::timerModeChannel1 () private
Definition at line 189 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[1]->set_sensitive(false);
    m_spinTimerChannels[1]->set_sensitive(true);
    m_toggleTimerChannels[1]->set_sensitive(true);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1TypeSelected().
timerModeChannel2()
void MicroHILViewHome::timerModeChannel2 () private
Definition at line 205 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[2]->set_sensitive(false);
    m_spinTimerChannels[2]->set_sensitive(true);
    m_toggleTimerChannels[2]->set_sensitive(true);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2TypeSelected().
timerModeChannel3()
void MicroHILViewHome::timerModeChannel3 () private
Definition at line 221 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[3]->set_sensitive(false);
    m_spinTimerChannels[3]->set_sensitive(true);
    m_toggleTimerChannels[3]->set_sensitive(true);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3TypeSelected().
timerModeChannel4()
void MicroHILViewHome::timerModeChannel4 () private
Definition at line 237 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[4]->set_sensitive(false);
    m_spinTimerChannels[4]->set_sensitive(true);
    m_toggleTimerChannels[4]->set_sensitive(true);
    m_stautsTimerChannels[4]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel4TypeSelected().
timerModeChannel5()
void MicroHILViewHome::timerModeChannel5 () private
Definition at line 253 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[5]->set_sensitive(false);
    m_spinTimerChannels[5]->set_sensitive(true);
    m_toggleTimerChannels[5]->set_sensitive(true);
    m_stautsTimerChannels[5]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel5TypeSelected().
timerModeChannel6()
void MicroHILViewHome::timerModeChannel6 () private
Definition at line 269 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[6]->set_sensitive(false);
    m_spinTimerChannels[6]->set_sensitive(true);
    m_toggleTimerChannels[6]->set_sensitive(true);
    m_stautsTimerChannels[6]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel6TypeSelected().
timerModeChannel7()
void MicroHILViewHome::timerModeChannel7 () private
Definition at line 285 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[7]->set_sensitive(false);
    m_spinTimerChannels[7]->set_sensitive(true);
    m_toggleTimerChannels[7]->set_sensitive(true);
    m_stautsTimerChannels[7]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel7TypeSelected().
toggleModeChannel0()
void MicroHILViewHome::toggleModeChannel0 () private
Definition at line 165 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[0]->set_sensitive(true);
    m_spinTimerChannels[0]->set_sensitive(false);
    m_toggleTimerChannels[0]->set_sensitive(false);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0TypeSelected().
toggleModeChannel1()
void MicroHILViewHome::toggleModeChannel1 () private
Definition at line 181 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[1]->set_sensitive(true);
    m_spinTimerChannels[1]->set_sensitive(false);
    m_toggleTimerChannels[1]->set_sensitive(false);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1TypeSelected().
toggleModeChannel2()
void MicroHILViewHome::toggleModeChannel2 () private
Definition at line 197 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[2]->set_sensitive(true);
    m_spinTimerChannels[2]->set_sensitive(false);
    m_toggleTimerChannels[2]->set_sensitive(false);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2TypeSelected().
toggleModeChannel3()
void MicroHILViewHome::toggleModeChannel3 () private
Definition at line 213 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[3]->set_sensitive(true);
    m_spinTimerChannels[3]->set_sensitive(false);
    m_toggleTimerChannels[3]->set_sensitive(false);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3TypeSelected().
toggleModeChannel4()
void MicroHILViewHome::toggleModeChannel4 () private
Definition at line 229 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[4]->set_sensitive(true);
    m_spinTimerChannels[4]->set_sensitive(false);
    m_toggleTimerChannels[4]->set_sensitive(false);
    m_stautsTimerChannels[4]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel4TypeSelected().
toggleModeChannel5()
void MicroHILViewHome::toggleModeChannel5 () private
Definition at line 245 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[5]->set_sensitive(true);
    m_spinTimerChannels[5]->set_sensitive(false);
    m_toggleTimerChannels[5]->set_sensitive(false);
    m_stautsTimerChannels[5]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel5TypeSelected().
toggleModeChannel6()
void MicroHILViewHome::toggleModeChannel6 () private
Definition at line 261 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[6]->set_sensitive(true);
    m_spinTimerChannels[6]->set_sensitive(false);
    m_toggleTimerChannels[6]->set_sensitive(false);
    m_stautsTimerChannels[6]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel6TypeSelected().
toggleModeChannel7()
void MicroHILViewHome::toggleModeChannel7 () private
Definition at line 277 of file microhil_view_home_mode.cc.
{
    m_toggleChannels[7]->set_sensitive(true);
    m_spinTimerChannels[7]->set_sensitive(false);
    m_toggleTimerChannels[7]->set_sensitive(false);
    m_stautsTimerChannels[7]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel7TypeSelected().
Member Data Documentation
m_adjustment_digits
Glib::RefPtr<Gtk::Adjustment> MicroHILViewHome::m_adjustment_digits private
Definition at line 228 of file microhil_view_home.h.
m_channel0ControlType
select0Changed MicroHILViewHome::m_channel0ControlType private
Definition at line 243 of file microhil_view_home.h.
Referenced by channel0IsSelected(), and onChannel0TypeSelected().
m_channel0Enabled
channel0Changed MicroHILViewHome::m_channel0Enabled private
Definition at line 232 of file microhil_view_home.h.
Referenced by channel0IsChanged(), and onChannel0().
m_channel0SpinTimerChanged
channel0SpinTimerChanged MicroHILViewHome::m_channel0SpinTimerChanged private
Definition at line 265 of file microhil_view_home.h.
Referenced by channel0IsSpinTimerChanged(), and onChannel0SpinTimerChanged().
m_channel0TimerToggled
channel0TimerToggled MicroHILViewHome::m_channel0TimerToggled private
Definition at line 276 of file microhil_view_home.h.
Referenced by channel0IsTimerChanged(), and onChannel0TimerChanged().
m_channel0Toggled
channel0Toggled MicroHILViewHome::m_channel0Toggled private
Definition at line 254 of file microhil_view_home.h.
Referenced by channel0IsToggled(), and onChannel0Toggled().
m_channel1ControlType
select1Changed MicroHILViewHome::m_channel1ControlType private
Definition at line 244 of file microhil_view_home.h.
Referenced by channel1IsSelected(), and onChannel1TypeSelected().
m_channel1Enabled
channel1Changed MicroHILViewHome::m_channel1Enabled private
Definition at line 233 of file microhil_view_home.h.
Referenced by channel1IsChanged(), and onChannel1().
m_channel1SpinTimerChanged
channel1SpinTimerChanged MicroHILViewHome::m_channel1SpinTimerChanged private
Definition at line 266 of file microhil_view_home.h.
Referenced by channel1IsSpinTimerChanged(), and onChannel1SpinTimerChanged().
m_channel1TimerToggled
channel1TimerToggled MicroHILViewHome::m_channel1TimerToggled private
Definition at line 277 of file microhil_view_home.h.
Referenced by channel1IsTimerChanged(), and onChannel1TimerChanged().
m_channel1Toggled
channel1Toggled MicroHILViewHome::m_channel1Toggled private
Definition at line 255 of file microhil_view_home.h.
Referenced by channel1IsToggled(), and onChannel1Toggled().
m_channel2ControlType
select2Changed MicroHILViewHome::m_channel2ControlType private
Definition at line 245 of file microhil_view_home.h.
Referenced by channel2IsSelected(), and onChannel2TypeSelected().
m_channel2Enabled
channel2Changed MicroHILViewHome::m_channel2Enabled private
Definition at line 234 of file microhil_view_home.h.
Referenced by channel2IsChanged(), and onChannel2().
m_channel2SpinTimerChanged
channel2SpinTimerChanged MicroHILViewHome::m_channel2SpinTimerChanged private
Definition at line 267 of file microhil_view_home.h.
Referenced by channel2IsSpinTimerChanged(), and onChannel2SpinTimerChanged().
m_channel2TimerToggled
channel2TimerToggled MicroHILViewHome::m_channel2TimerToggled private
Definition at line 278 of file microhil_view_home.h.
Referenced by channel2IsTimerChanged(), and onChannel2TimerChanged().
m_channel2Toggled
channel2Toggled MicroHILViewHome::m_channel2Toggled private
Definition at line 256 of file microhil_view_home.h.
Referenced by channel2IsToggled(), and onChannel2Toggled().
m_channel3ControlType
select3Changed MicroHILViewHome::m_channel3ControlType private
Definition at line 246 of file microhil_view_home.h.
Referenced by channel3IsSelected(), and onChannel3TypeSelected().
m_channel3Enabled
channel3Changed MicroHILViewHome::m_channel3Enabled private
Definition at line 235 of file microhil_view_home.h.
Referenced by channel3IsChanged(), and onChannel3().
m_channel3SpinTimerChanged
channel3SpinTimerChanged MicroHILViewHome::m_channel3SpinTimerChanged private
Definition at line 268 of file microhil_view_home.h.
Referenced by channel3IsSpinTimerChanged(), and onChannel3SpinTimerChanged().
m_channel3TimerToggled
channel3TimerToggled MicroHILViewHome::m_channel3TimerToggled private
Definition at line 279 of file microhil_view_home.h.
Referenced by channel3IsTimerChanged(), and onChannel3TimerChanged().
m_channel3Toggled
channel3Toggled MicroHILViewHome::m_channel3Toggled private
Definition at line 257 of file microhil_view_home.h.
Referenced by channel3IsToggled(), and onChannel3Toggled().
m_channel4ControlType
select4Changed MicroHILViewHome::m_channel4ControlType private
Definition at line 247 of file microhil_view_home.h.
Referenced by channel4IsSelected(), and onChannel4TypeSelected().
m_channel4Enabled
channel4Changed MicroHILViewHome::m_channel4Enabled private
Definition at line 236 of file microhil_view_home.h.
Referenced by channel4IsChanged(), and onChannel4().
m_channel4SpinTimerChanged
channel4SpinTimerChanged MicroHILViewHome::m_channel4SpinTimerChanged private
Definition at line 269 of file microhil_view_home.h.
Referenced by channel4IsSpinTimerChanged(), and onChannel4SpinTimerChanged().
m_channel4TimerToggled
channel4TimerToggled MicroHILViewHome::m_channel4TimerToggled private
Definition at line 280 of file microhil_view_home.h.
Referenced by channel4IsTimerChanged(), and onChannel4TimerChanged().
m_channel4Toggled
channel4Toggled MicroHILViewHome::m_channel4Toggled private
Definition at line 258 of file microhil_view_home.h.
Referenced by channel4IsToggled(), and onChannel4Toggled().
m_channel5ControlType
select5Changed MicroHILViewHome::m_channel5ControlType private
Definition at line 248 of file microhil_view_home.h.
Referenced by channel5IsSelected(), and onChannel5TypeSelected().
m_channel5Enabled
channel5Changed MicroHILViewHome::m_channel5Enabled private
Definition at line 237 of file microhil_view_home.h.
Referenced by channel5IsChanged(), and onChannel5().
m_channel5SpinTimerChanged
channel5SpinTimerChanged MicroHILViewHome::m_channel5SpinTimerChanged private
Definition at line 270 of file microhil_view_home.h.
Referenced by channel5IsSpinTimerChanged(), and onChannel5SpinTimerChanged().
m_channel5TimerToggled
channel5TimerToggled MicroHILViewHome::m_channel5TimerToggled private
Definition at line 281 of file microhil_view_home.h.
Referenced by channel5IsTimerChanged(), and onChannel5TimerChanged().
m_channel5Toggled
channel5Toggled MicroHILViewHome::m_channel5Toggled private
Definition at line 259 of file microhil_view_home.h.
Referenced by channel5IsToggled(), and onChannel5Toggled().
m_channel6ControlType
select6Changed MicroHILViewHome::m_channel6ControlType private
Definition at line 249 of file microhil_view_home.h.
Referenced by channel6IsSelected(), and onChannel6TypeSelected().
m_channel6Enabled
channel6Changed MicroHILViewHome::m_channel6Enabled private
Definition at line 238 of file microhil_view_home.h.
Referenced by channel6IsChanged(), and onChannel6().
m_channel6SpinTimerChanged
channel6SpinTimerChanged MicroHILViewHome::m_channel6SpinTimerChanged private
Definition at line 271 of file microhil_view_home.h.
Referenced by channel6IsSpinTimerChanged(), and onChannel6SpinTimerChanged().
m_channel6TimerToggled
channel6TimerToggled MicroHILViewHome::m_channel6TimerToggled private
Definition at line 282 of file microhil_view_home.h.
Referenced by channel6IsTimerChanged(), and onChannel6TimerChanged().
m_channel6Toggled
channel6Toggled MicroHILViewHome::m_channel6Toggled private
Definition at line 260 of file microhil_view_home.h.
Referenced by channel6IsToggled(), and onChannel6Toggled().
m_channel7ControlType
select7Changed MicroHILViewHome::m_channel7ControlType private
Definition at line 250 of file microhil_view_home.h.
Referenced by channel7IsSelected(), and onChannel7TypeSelected().
m_channel7Enabled
channel7Changed MicroHILViewHome::m_channel7Enabled private
Definition at line 239 of file microhil_view_home.h.
Referenced by channel7IsChanged(), and onChannel7().
m_channel7SpinTimerChanged
channel7SpinTimerChanged MicroHILViewHome::m_channel7SpinTimerChanged private
Definition at line 272 of file microhil_view_home.h.
Referenced by channel7IsSpinTimerChanged(), and onChannel7SpinTimerChanged().
m_channel7TimerToggled
channel7TimerToggled MicroHILViewHome::m_channel7TimerToggled private
Definition at line 283 of file microhil_view_home.h.
Referenced by channel7IsTimerChanged(), and onChannel7TimerChanged().
m_channel7Toggled
channel7Toggled MicroHILViewHome::m_channel7Toggled private
Definition at line 261 of file microhil_view_home.h.
Referenced by channel7IsToggled(), and onChannel7Toggled().
m_enableChannels
std::vector<Glib::RefPtr<Gtk::CheckButton> > MicroHILViewHome::m_enableChannels private
Definition at line 222 of file microhil_view_home.h.
Referenced by mapping(), MicroHILViewHome(), onChannel0(), onChannel0SpinTimerChanged(), onChannel0TimerChanged(), onChannel0Toggled(), onChannel0TypeSelected(), onChannel1(), onChannel1SpinTimerChanged(), onChannel1TimerChanged(), onChannel1Toggled(), onChannel1TypeSelected(), onChannel2(), onChannel2SpinTimerChanged(), onChannel2TimerChanged(), onChannel2Toggled(), onChannel2TypeSelected(), onChannel3(), onChannel3SpinTimerChanged(), onChannel3TimerChanged(), onChannel3Toggled(), onChannel3TypeSelected(), onChannel4(), onChannel4SpinTimerChanged(), onChannel4TimerChanged(), onChannel4Toggled(), onChannel4TypeSelected(), onChannel5(), onChannel5SpinTimerChanged(), onChannel5TimerChanged(), onChannel5Toggled(), onChannel5TypeSelected(), onChannel6(), onChannel6SpinTimerChanged(), onChannel6TimerChanged(), onChannel6Toggled(), onChannel6TypeSelected(), onChannel7(), onChannel7SpinTimerChanged(), onChannel7TimerChanged(), onChannel7Toggled(), and onChannel7TypeSelected().
m_selectControlChannels
std::vector<Glib::RefPtr<Gtk::ComboBoxText> > MicroHILViewHome::m_selectControlChannels private
Definition at line 223 of file microhil_view_home.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), enableChannel4(), enableChannel5(), enableChannel6(), enableChannel7(), mapping(), MicroHILViewHome(), onChannel0TypeSelected(), onChannel1TypeSelected(), onChannel2TypeSelected(), onChannel3TypeSelected(), onChannel4TypeSelected(), onChannel5TypeSelected(), onChannel6TypeSelected(), and onChannel7TypeSelected().
m_spinTimerChannels
std::vector<Glib::RefPtr<Gtk::SpinButton> > MicroHILViewHome::m_spinTimerChannels private
Definition at line 225 of file microhil_view_home.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), enableChannel4(), enableChannel5(), enableChannel6(), enableChannel7(), mapping(), MicroHILViewHome(), onChannel0SpinTimerChanged(), onChannel1SpinTimerChanged(), onChannel2SpinTimerChanged(), onChannel3SpinTimerChanged(), onChannel4SpinTimerChanged(), onChannel5SpinTimerChanged(), onChannel6SpinTimerChanged(), onChannel7SpinTimerChanged(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), timerModeChannel4(), timerModeChannel5(), timerModeChannel6(), timerModeChannel7(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), toggleModeChannel3(), toggleModeChannel4(), toggleModeChannel5(), toggleModeChannel6(), and toggleModeChannel7().
m_stautsTimerChannels
std::vector<Glib::RefPtr<Gtk::ProgressBar> > MicroHILViewHome::m_stautsTimerChannels private
Definition at line 227 of file microhil_view_home.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), enableChannel4(), enableChannel5(), enableChannel6(), enableChannel7(), MicroHILViewHome(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), timerModeChannel4(), timerModeChannel5(), timerModeChannel6(), timerModeChannel7(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), toggleModeChannel3(), toggleModeChannel4(), toggleModeChannel5(), toggleModeChannel6(), and toggleModeChannel7().
m_toggleChannels
std::vector<Glib::RefPtr<Gtk::ToggleButton> > MicroHILViewHome::m_toggleChannels private
Definition at line 224 of file microhil_view_home.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), enableChannel4(), enableChannel5(), enableChannel6(), enableChannel7(), mapping(), MicroHILViewHome(), onChannel0Toggled(), onChannel1Toggled(), onChannel2Toggled(), onChannel3Toggled(), onChannel4Toggled(), onChannel5Toggled(), onChannel6Toggled(), onChannel7Toggled(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), timerModeChannel4(), timerModeChannel5(), timerModeChannel6(), timerModeChannel7(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), toggleModeChannel3(), toggleModeChannel4(), toggleModeChannel5(), toggleModeChannel6(), and toggleModeChannel7().
m_toggleTimerChannels
std::vector<Glib::RefPtr<Gtk::ToggleButton> > MicroHILViewHome::m_toggleTimerChannels private
Definition at line 226 of file microhil_view_home.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), disableChannel4(), disableChannel5(), disableChannel6(), disableChannel7(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), enableChannel4(), enableChannel5(), enableChannel6(), enableChannel7(), mapping(), MicroHILViewHome(), onChannel0TimerChanged(), onChannel1TimerChanged(), onChannel2TimerChanged(), onChannel3TimerChanged(), onChannel4TimerChanged(), onChannel5TimerChanged(), onChannel6TimerChanged(), onChannel7TimerChanged(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), timerModeChannel4(), timerModeChannel5(), timerModeChannel6(), timerModeChannel7(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), toggleModeChannel3(), toggleModeChannel4(), toggleModeChannel5(), toggleModeChannel6(), and toggleModeChannel7().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILViewHome::m_ui private
Definition at line 218 of file microhil_view_home.h.
Referenced by MicroHILViewHome().
The documentation for this class was generated from the following files:
view/home/microhil_view_home.h
view/home/microhil_view_home.cc
view/home/microhil_view_home_map.cc
view/home/microhil_view_home_mode.cc
view/home/microhil_view_home_signals.cc
view/home/microhil_view_home_slots.cc