microhildesk: Electux::App::Config::ConfigManager Class Reference
Electux::App::Config::ConfigManager Class Reference
Config class is implementation for configuration mechanism.
#include <config_manager.h>
Public Member Functions
ConfigManager ()
Config constructor.
void setControlConfig (const ModelControl &config)
Sets control configuration.
void setSerialConfig (const ModelSerial &config)
Sets serial configuration.
void setLogConfig (const ModelLog &config)
Sets log configuration.
const ModelControl & getControlConfig () const
Gets control configuration.
const ModelSerial & getSerialConfig () const
Gets serial configuration.
const ModelLog & getLogConfig () const
Gets log configuration.
bool load () final
Loads configuration.
bool store () final
Stores configuration.
Private Member Functions
void defaultConfigStore ()
Stores default configuration.
Private Attributes
std::string m_fileName {}
Configuration parameters and properties m_fileName - file name path for load/store configuration m_controlConfig - control configuration m_serialConfig - serial port configuration m_logConfig - log configuration.
ModelControl m_controlConfig {}
ModelSerial m_serialConfig {}
ModelLog m_logConfig {}
Detailed Description
Config class is implementation for configuration mechanism.
Definition at line 34 of file config_manager.h.
Constructor & Destructor Documentation
ConfigManager()
ConfigManager::ConfigManager () explicit
Config constructor.
Definition at line 43 of file config_manager.cc.
{
    m_fileName = Glib::build_filename(Glib::get_home_dir(), configFile.data());
    auto dirPath = Glib::path_get_dirname(m_fileName);
    try
    {
        if (!std::filesystem::exists(dirPath))
        {
            std::filesystem::create_directories(dirPath);
        }
        if (!std::filesystem::exists(m_fileName))
        {
            std::ofstream file(m_fileName);
            if (!file)
            {
                throw std::ios_base::failure("Unable to create file: " + m_fileName);
            }
            defaultConfigStore();
        }
        std::cout << "Setup configuration file path: " << m_fileName << std::endl;
        load();
    } catch (const std::exception& e)
    {
        std::cerr << "Error during ConfigManager initialization: " << e.what() << std::endl;
    }
}
References defaultConfigStore(), load(), and m_fileName.
Member Function Documentation
defaultConfigStore()
void ConfigManager::defaultConfigStore () private
Stores default configuration.
Set default control configuration
Set default serial configuration
Set default log configuration
Store default configuration to file
Definition at line 185 of file config_manager.cc.
{
    m_controlConfig.add(m_controlConfig.toString(ModelControl::ModelControlKey::Enable), "false false false false false false false false");
    m_controlConfig.add(m_controlConfig.toString(ModelControl::ModelControlKey::Mode), "0 0 0 0 0 0 0 0");
    m_controlConfig.add(m_controlConfig.toString(ModelControl::ModelControlKey::Toggle), "false false false false false false false false");
    m_controlConfig.add(m_controlConfig.toString(ModelControl::ModelControlKey::Timer), "0 0 0 0 0 0 0 0");
    m_controlConfig.add(m_controlConfig.toString(ModelControl::ModelControlKey::TimerEnable), "false false false false false false false false");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Device), "/dev/ttyUSB0");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Baud), "10");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Data), "3");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Parity), "2");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Stop), "0");
    m_serialConfig.add(m_serialConfig.toString(ModelSerial::ModelSerialKey::Flow), "0");
    m_logConfig.add(m_logConfig.toString(ModelLog::ModelLogKey::FilePath), "/tmp/microhildesk.log");
    m_logConfig.add(m_logConfig.toString(ModelLog::ModelLogKey::LogLevel), "2");
    store();
}
References Electux::App::Model::Model::add(), Electux::App::Model::ModelSerial::Baud, Electux::App::Model::ModelSerial::Data, Electux::App::Model::ModelSerial::Device, Electux::App::Model::ModelControl::Enable, Electux::App::Model::ModelLog::FilePath, Electux::App::Model::ModelSerial::Flow, Electux::App::Model::ModelLog::LogLevel, m_controlConfig, m_logConfig, m_serialConfig, Electux::App::Model::ModelControl::Mode, Electux::App::Model::ModelSerial::Parity, Electux::App::Model::ModelSerial::Stop, store(), Electux::App::Model::ModelControl::Timer, Electux::App::Model::ModelControl::TimerEnable, Electux::App::Model::ModelControl::Toggle, Electux::App::Model::ModelControl::toString(), Electux::App::Model::ModelLog::toString(), and Electux::App::Model::ModelSerial::toString().
Referenced by ConfigManager().
getControlConfig()
const ModelControl & ConfigManager::getControlConfig () const
Gets control configuration.
Returns
Control configuration
Definition at line 88 of file config_manager.cc.
{
    return m_controlConfig;
}
References m_controlConfig.
Referenced by Electux::App::EntryApplication::on_startup().
getLogConfig()
const ModelLog & ConfigManager::getLogConfig () const
Gets log configuration.
Returns
Log configuration
Definition at line 98 of file config_manager.cc.
{
    return m_logConfig;
}
References m_logConfig.
Referenced by Electux::App::EntryApplication::on_startup().
getSerialConfig()
const ModelSerial & ConfigManager::getSerialConfig () const
Gets serial configuration.
Returns
Serial configuration
Definition at line 93 of file config_manager.cc.
{
    return m_serialConfig;
}
References m_serialConfig.
Referenced by Electux::App::EntryApplication::on_startup().
load()
bool ConfigManager::load () final virtual
Loads configuration.
Returns
status true for success load configuration else false
Implements Electux::App::Config::IConfig.
Definition at line 103 of file config_manager.cc.
{
    std::ifstream file(m_fileName);
    std::cout << "Loading configuration..." << std::endl;
    if (!file.is_open())
    {
        std::cerr << "Unable to open file: " << m_fileName << std::endl;
        return false;
    }
    std::string line;
    while (std::getline(file, line))
    {
        if (line.empty() || line[0] == configCommentChar)
        {
            continue;
        }
        std::istringstream iss(line);
        std::string key, value;
        if (std::getline(iss, key, configAssignDelimiter) && std::getline(iss, value))
        {
            key.erase(0, key.find_first_not_of(" \t\n\r"));
            key.erase(key.find_last_not_of(" \t\n\r") + 1);
            value.erase(0, value.find_first_not_of(" \t\n\r"));
            value.erase(value.find_last_not_of(" \t\n\r") + 1);
            if (m_serialConfig.validateKey(key))
            {
                m_serialConfig.add(key, value);
            }
            else if (m_logConfig.validateKey(key))
            {
                m_logConfig.add(key, value);
            }
            else if (m_controlConfig.validateKey(key))
            {
                m_controlConfig.add(key, value);
            }
            else
            {
                std::cerr << "Warning: Unknown configuration key: " << key << std::endl;
                return false;
            }
        }
    }
    file.close();
    std::cout << "Load configuration done." << std::endl;
    return true;
}
References Electux::App::Model::Model::add(), m_controlConfig, m_fileName, m_logConfig, m_serialConfig, Electux::App::Model::ModelControl::validateKey(), Electux::App::Model::ModelLog::validateKey(), and Electux::App::Model::ModelSerial::validateKey().
Referenced by ConfigManager().
setControlConfig()
void ConfigManager::setControlConfig (const ModelControl & config)
Sets control configuration.
Parameters
config Represents control configuration
Definition at line 73 of file config_manager.cc.
{
    m_controlConfig = config;
}
References m_controlConfig.
Referenced by Electux::App::EntryApplication::onSetupChanged().
setLogConfig()
void ConfigManager::setLogConfig (const ModelLog & config)
Sets log configuration.
Parameters
config Represents log configuration
Definition at line 83 of file config_manager.cc.
{
    m_logConfig = config;
}
References m_logConfig.
Referenced by Electux::App::EntryApplication::onSetupChanged().
setSerialConfig()
void ConfigManager::setSerialConfig (const ModelSerial & config)
Sets serial configuration.
Parameters
config Represents serial configuration
Definition at line 78 of file config_manager.cc.
{
    m_serialConfig = config;
}
References m_serialConfig.
Referenced by Electux::App::EntryApplication::onSetupChanged().
store()
bool ConfigManager::store () final virtual
Stores configuration.
Returns
status true for success store configuration else false
Implements Electux::App::Config::IConfig.
Definition at line 157 of file config_manager.cc.
{
    std::ofstream file(m_fileName);
    std::cout << "Storing configuration..." << std::endl;
    if (!file.is_open())
    {
        std::cerr << "Unable to open file: " << m_fileName << std::endl;
        return false;
    }
    auto writeModel = [&](const auto& model)
    {
        for (const auto& [key, value] : model.getAllEntries())
        {
            file << key << configAssignDelimiter << value << "\n";
        }
    };
    writeModel(m_controlConfig);
    writeModel(m_serialConfig);
    writeModel(m_logConfig);
    file.close();
    std::cout << "Store configuration done." << std::endl;
    return true;
}
References m_controlConfig, m_fileName, m_logConfig, and m_serialConfig.
Referenced by defaultConfigStore(), and Electux::App::EntryApplication::onSetupChanged().
Member Data Documentation
m_controlConfig
ModelControl Electux::App::Config::ConfigManager::m_controlConfig {} private
Definition at line 94 of file config_manager.h.
{};
Referenced by defaultConfigStore(), getControlConfig(), load(), setControlConfig(), and store().
m_fileName
std::string Electux::App::Config::ConfigManager::m_fileName {} private
Configuration parameters and properties m_fileName - file name path for load/store configuration m_controlConfig - control configuration m_serialConfig - serial port configuration m_logConfig - log configuration.
Definition at line 93 of file config_manager.h.
{};
Referenced by ConfigManager(), load(), and store().
m_logConfig
ModelLog Electux::App::Config::ConfigManager::m_logConfig {} private
Definition at line 96 of file config_manager.h.
{};
Referenced by defaultConfigStore(), getLogConfig(), load(), setLogConfig(), and store().
m_serialConfig
ModelSerial Electux::App::Config::ConfigManager::m_serialConfig {} private
Definition at line 95 of file config_manager.h.
{};
Referenced by defaultConfigStore(), getSerialConfig(), load(), setSerialConfig(), and store().
The documentation for this class was generated from the following files:
config/config_manager.h
config/config_manager.cc