microhildesk: MHLog Class Reference
MHLog Class Reference
MHLog class is implementation of log mechanism.
#include <microhil_log.h>
Public Member Functions
MHLog ()
MHLog constructor.
virtual ~MHLog () noexcept=default
MHLog destructor.
void setFilePath (const UString &logFilePath) final
Sets file path for logger.
UString getFilePath () const final
Gets file path for logger.
void setLogLevel (const UString &level) final
Sets log level.
void setLogLevel (const int level) final
Sets log level.
void setLogLevel (const LogLevel level) final
Sets log level.
LogLevel getLogLevel () const final
Gets log level.
bool open () final
Opens storage for collecting log messages.
void write (const UString &message, const LogLevel level) final
Writes log message.
bool close () final
Closes log storage.
Private Member Functions
UString getCurrentDateTime () const final
Gets current date and time.
UString toStringLogType (const LogLevel level) const final
Converts log level type to human readable string.
LogLevel toLogType (const UString &level) const final
Converts log level string to level type.
Private Attributes
UString m_logFilePath {}
Log file path.
ofstream m_logFile {}
Log file instance.
LogLevel m_logLevel {LogLevel::MICROHIL_INFO}
Type of log level.
bool m_fileOpened {false}
Flag for checking log file state.
Detailed Description
MHLog class is implementation of log mechanism.
Definition at line 29 of file microhil_log.h.
Constructor & Destructor Documentation
MHLog()
MHLog::MHLog () explicit
MHLog constructor.
Definition at line 37 of file microhil_log.cc.
    : m_fileOpened{false}
{
}
~MHLog()
virtual MHLog::~MHLog () inline virtual default noexcept
MHLog destructor.
Member Function Documentation
close()
bool MHLog::close () final virtual
Closes log storage.
Returns
status true for success close operation else false
Implements IMHLog.
Definition at line 111 of file microhil_log.cc.
{
    if (m_logFile.is_open() && m_fileOpened)
    {
        m_logFile.close();
        m_fileOpened = false;
    }
    return !m_fileOpened;
}
References m_fileOpened, and m_logFile.
getCurrentDateTime()
UString MHLog::getCurrentDateTime () const final private virtual
Gets current date and time.
Returns
current date time in string format (18-08-2023 22:52:06)
Gets local time in Day-Month-Year Hours:Minutes:Seconds format
Implements IMHLog.
Definition at line 122 of file microhil_log.cc.
{
    time_t rawTime;
    char buffer[80];
    time(&rawTime);
    const struct tm *timeInfo = localtime(&rawTime);
    strftime(buffer, 80, "%d-%m-%Y %I:%M:%S", timeInfo);
    return UString(buffer);
}
Referenced by write().
getFilePath()
UString MHLog::getFilePath () const final virtual
Gets file path for logger.
Returns
Log file path
Gets file path for logger
Implements IMHLog.
Definition at line 49 of file microhil_log.cc.
{
    return m_logFilePath;
}
References m_logFilePath.
getLogLevel()
LogLevel MHLog::getLogLevel () const final virtual
Gets log level.
Returns
Scoped enumeration of log level
Gets log level for logger
Implements IMHLog.
Definition at line 81 of file microhil_log.cc.
{
    return m_logLevel;
}
References m_logLevel.
open()
bool MHLog::open () final virtual
Opens storage for collecting log messages.
Returns
status true for success open operation else false
Implements IMHLog.
Definition at line 88 of file microhil_log.cc.
{
    if (!m_logFile.is_open() && !m_fileOpened)
    {
        m_logFile.open(m_logFilePath, ios::out);
        m_fileOpened = true;
    }
    return m_fileOpened;
}
References m_fileOpened, m_logFile, and m_logFilePath.
setFilePath()
void MHLog::setFilePath (const UString & logFilePath) final virtual
Sets file path for logger.
Parameters
logFilePath represents file path for storing log messages
Sets file path for logger
Implements IMHLog.
Definition at line 42 of file microhil_log.cc.
{
    m_logFilePath = logFilePath;
}
References m_logFilePath.
setLogLevel() [1/3]
void MHLog::setLogLevel (const int level) final virtual
Sets log level.
Parameters
level represent level for logging
Sets log level for logger
Implements IMHLog.
Definition at line 67 of file microhil_log.cc.
{
    m_logLevel = static_cast<LogLevel>(level);
}
References m_logLevel.
setLogLevel() [2/3]
void MHLog::setLogLevel (const LogLevel level) final virtual
Sets log level.
Parameters
level represents level for logging
Sets log level for logger
Implements IMHLog.
Definition at line 74 of file microhil_log.cc.
{
    m_logLevel = level;
}
References m_logLevel.
setLogLevel() [3/3]
void MHLog::setLogLevel (const UString & level) final virtual
Sets log level.
Parameters
level represent level for logging
Converts log level from string to scoped enum
Sets log level for logger
Implements IMHLog.
Definition at line 56 of file microhil_log.cc.
{
    auto logLevelPrepared = toLogType(level);
    m_logLevel = logLevelPrepared;
}
References m_logLevel, and toLogType().
toLogType()
LogLevel MHLog::toLogType (const UString & level) const final private virtual
Converts log level string to level type.
Parameters
level represents level type in string format
Returns
log level type
Implements IMHLog.
Definition at line 151 of file microhil_log.cc.
{
    if (level == kWarningLogLevel)
    {
        return LogLevel::MICROHIL_WARNING;
    }
    if (level == kErrorLogLevel)
    {
        return LogLevel::MICROHIL_ERROR;
    }
    return LogLevel::MICROHIL_INFO;
}
References MICROHIL_ERROR, MICROHIL_INFO, and MICROHIL_WARNING.
Referenced by setLogLevel().
toStringLogType()
UString MHLog::toStringLogType (const LogLevel level) const final private virtual
Converts log level type to human readable string.
Parameters
level represents log level
Returns
string representation of log level
Implements IMHLog.
Definition at line 136 of file microhil_log.cc.
{
    switch (level)
    {
    case LogLevel::MICROHIL_INFO:
        return kInfoLogLevel;
    case LogLevel::MICROHIL_WARNING:
        return kWarningLogLevel;
    case LogLevel::MICROHIL_ERROR:
        return kErrorLogLevel;
    }
    return kInfoLogLevel;
}
References MICROHIL_ERROR, MICROHIL_INFO, and MICROHIL_WARNING.
Referenced by write().
write()
void MHLog::write (const UString & message, const LogLevel level) final virtual
Writes log message.
Parameters
message represents log message to be stored
level represents log level
Implements IMHLog.
Definition at line 99 of file microhil_log.cc.
{
    const auto currentTime = getCurrentDateTime();
    const auto prefixLogLevel = toStringLogType(level);
    UString logMessage = currentTime + prefixLogLevel + message;
    if (m_logFile.is_open() && m_fileOpened)
    {
        m_logFile << logMessage;
    }
}
References getCurrentDateTime(), m_fileOpened, m_logFile, and toStringLogType().
Member Data Documentation
m_fileOpened
bool MHLog::m_fileOpened {false} private
Flag for checking log file state.
Definition at line 118 of file microhil_log.h.
Referenced by close(), open(), and write().
m_logFile
ofstream MHLog::m_logFile {} private
Log file instance.
Definition at line 110 of file microhil_log.h.
Referenced by close(), open(), and write().
m_logFilePath
UString MHLog::m_logFilePath {} private
Log file path.
Definition at line 106 of file microhil_log.h.
Referenced by getFilePath(), open(), and setFilePath().
m_logLevel
LogLevel MHLog::m_logLevel {LogLevel::MICROHIL_INFO} private
Type of log level.
Definition at line 114 of file microhil_log.h.
Referenced by getLogLevel(), and setLogLevel().
The documentation for this class was generated from the following files:
log/microhil_log.h
log/microhil_log.cc