microhildesk: MHViewHome Class Reference
MHViewHome Class Reference
MHViewHome class is implementation of home view.
#include <microhil_view_home.h>
Public Member Functions
MHViewHome (BaseObjectType *object, MHRPtr< Gtk::Builder > const &ui)
MHViewHome constructor.
SigActionViewTriggered viewChanged () final
Signal for menu items (changed view)
SigChannelChanged channelIsChanged () final
Signal for check buttons (enable/disable channel)
void onChannelChanged (Channel id) final
Slot for processing check buttons (enable/disable channel)
SigSelectChanged channelIsSelected () final
Signal for comboboxes (control type)
void onTypeSelected (Channel id) final
Slot for processing comboboxes (control type)
SigChannelToggled channelIsToggled () final
Signal for toggling buttons (turn on/turn off channel)
void onToggled (Channel id) final
Slot for processing toggle buttons (turn on/turn off channel)
SigChannelSpinTimerChanged channelIsSpinTimerChanged () final
Signal for spin buttons (based on timer)
void onSpinTimerChanged (Channel id) final
Slot for processing spin buttons (based on timer)
SigChannelTimerToggled channelIsTimerChanged () final
Signal for toggle buttons (based on timer)
void onToggleTimerChanged (Channel id) final
Slot for processing toggle buttons (turn on/turn off timer)
void onConnectClicked ()
Slot for processing Connect meni-item.
void onDisconnectClicked ()
Slot for processing Disconnect meni-item.
void onQuitClicked ()
Slot for processing Quit meni-item.
void onSerialSettingsClicked ()
Slot for processing Serial Settings meni-item.
void onLogSettingsClicked ()
Slot for processing Log Settings meni-item.
void onAboutClicked ()
Slot for processing About meni-item.
void serialSettingsConfirm (bool state) final
Sets widgets after confirming changes for the serial port.
Private Member Functions
void mapping ()
Maps channels (signals and slots)
void enableChannel (Channel id)
Enables complete channel.
void disableChannel (Channel id)
Disables complete channel.
void toggleModeChannel (Channel id)
Sets channel in toggle mode.
void timerModeChannel (Channel id)
Sets channel timer mode.
int channelToInt (Channel id)
Converts channel id to integer value.
int controlTypeToInt (channelControlType controlType)
Converts channel control type to integer value.
Private Attributes
MHRPtr< Gtk::Builder > m_ui {nullptr}
UI builder instance.
MHRPtr< Gtk::MenuItem > m_connect {nullptr}
Application Connect menu-item.
MHRPtr< Gtk::MenuItem > m_disconnect {nullptr}
Application Disconnect menu-item.
MHRPtr< Gtk::MenuItem > m_quit {nullptr}
Application Quit menu-item.
MHRPtr< Gtk::MenuItem > m_serialSettings {nullptr}
Application Serial Port Settings menu-item.
MHRPtr< Gtk::MenuItem > m_logSettings {nullptr}
Application Log Settings menu-item.
MHRPtr< Gtk::MenuItem > m_about {nullptr}
Application About menu-item.
std::vector< MHRPtr< Gtk::CheckButton > > m_enableChannels {}
Check buttons for enable/disable channels.
std::vector< MHRPtr< Gtk::ComboBoxText > > m_selectControlChannels {}
Comboboxes for selecting channel mode.
std::vector< MHRPtr< Gtk::ToggleButton > > m_toggleChannels {}
Toggle button for direct channel control.
std::vector< MHRPtr< Gtk::SpinButton > > m_spinTimerChannels {}
Spin button for setup channel timer.
std::vector< MHRPtr< Gtk::ToggleButton > > m_toggleTimerChannels {}
Toggle button for starting channel timer.
std::vector< MHRPtr< Gtk::ProgressBar > > m_stautsTimerChannels {}
Visual status for channels.
MHRPtr< Gtk::Adjustment > m_adjustment_digits {nullptr}
Adjustment setup for channel visual status.
SigActionViewTriggered m_actionViewTriggered {}
Signal for menu items (triggered another view)
SigChannelChanged m_channelEnabled {}
Signal for check buttons (enable/disable channel)
SigSelectChanged m_channelControlType {}
Signal for comboboxes (toogle/timer type control)
SigChannelToggled m_channelToggled {}
Signal for toogle buttons (turn on/turn off channel)
SigChannelSpinTimerChanged m_channelSpinTimerChanged {}
Signal for spin buttons (based on timer setup)
SigChannelTimerToggled m_channelTimerToggled {}
Signal for toogle buttons (based on timer setup)
Detailed Description
MHViewHome class is implementation of home view.
Definition at line 35 of file microhil_view_home.h.
Constructor & Destructor Documentation
MHViewHome()
MHViewHome::MHViewHome (BaseObjectType * object, MHRPtr< Gtk::Builder > const & ui)
MHViewHome constructor.
Parameters
object represents base object instance
ui represents builder instance
Disables disconnect menu-item by default
Definition at line 131 of file microhil_view_home.cc.
    : Gtk::ApplicationWindow(object), m_ui{ui}
{
    // Binds Connect menu-item
    m_connect = MHRPtr<Gtk::MenuItem>::cast_dynamic(
        m_ui->get_object(kConnectId)
    );
    // Binds Disconnect menu-item
    m_disconnect = MHRPtr<Gtk::MenuItem>::cast_dynamic(
        m_ui->get_object(kDisconnectId)
    );
    // Binds Quit menu-item
    m_quit = MHRPtr<Gtk::MenuItem>::cast_dynamic(m_ui->get_object(kQuitId));
    // Binds Serial Settings menu-item
    m_serialSettings = MHRPtr<Gtk::MenuItem>::cast_dynamic(
        m_ui->get_object(kSerialSettingsId)
    );
    // Binds Log Settings menu-item
    m_logSettings = MHRPtr<Gtk::MenuItem>::cast_dynamic(
        m_ui->get_object(kLogSettingsId)
    );
    // Binds About menu-item
    m_about = MHRPtr<Gtk::MenuItem>::cast_dynamic(m_ui->get_object(kAboutId));
    // Binds channels widgets
    for (int i = 0; i < kNumberOfViewChannels; i++)
    {
        m_enableChannels.push_back(MHRPtr<Gtk::CheckButton>::cast_dynamic(
            m_ui->get_object(kCheckButtonsId[i]))
        );
        m_selectControlChannels.push_back(
            MHRPtr<Gtk::ComboBoxText>::cast_dynamic(
                m_ui->get_object(kComboBoxTextsId[i])
            )
        );
        m_toggleChannels.push_back(
            MHRPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kToggleButtonsId[i])
            )
        );
        m_spinTimerChannels.push_back(
            MHRPtr<Gtk::SpinButton>::cast_dynamic(
                m_ui->get_object(kTimerSpinButtonsId[i])
            )
        );
        m_toggleTimerChannels.push_back(
            MHRPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kTimerToggleButtonsId[i])
            )
        );
        m_stautsTimerChannels.push_back(
            MHRPtr<Gtk::ProgressBar>::cast_dynamic(
                m_ui->get_object(kTimerProgressBarStatus0Id[i])
            )
        );
    }
    // Maps channels (signals and slots)
    mapping();
    // Disables all channels by default
    for (int i = 0; i < kNumberOfViewChannels; i++)
    {
        disableChannel(static_cast<Channel>(i));
    }
    m_disconnect->set_sensitive(false);
}
References disableChannel(), m_about, m_connect, m_disconnect, m_enableChannels, m_logSettings, m_quit, m_selectControlChannels, m_serialSettings, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, m_toggleTimerChannels, m_ui, and mapping().
Member Function Documentation
channelIsChanged()
SigChannelChanged MHViewHome::channelIsChanged () final virtual
Signal for check buttons (enable/disable channel)
Returns
Signal for clicked button
Implements AbMHViewHome.
Definition at line 26 of file microhil_view_home_signals.cc.
{
    return m_channelEnabled;
}
References m_channelEnabled.
channelIsSelected()
SigSelectChanged MHViewHome::channelIsSelected () final virtual
Signal for comboboxes (control type)
Returns
Signal for changed channel state combobox
Implements AbMHViewHome.
Definition at line 31 of file microhil_view_home_signals.cc.
{
    return m_channelControlType;
}
References m_channelControlType.
channelIsSpinTimerChanged()
SigChannelSpinTimerChanged MHViewHome::channelIsSpinTimerChanged () final virtual
Signal for spin buttons (based on timer)
Returns
Signal for changed spin button
Implements AbMHViewHome.
Definition at line 41 of file microhil_view_home_signals.cc.
{
    return m_channelSpinTimerChanged;
}
References m_channelSpinTimerChanged.
channelIsTimerChanged()
SigChannelTimerToggled MHViewHome::channelIsTimerChanged () final virtual
Signal for toggle buttons (based on timer)
Returns
Signal for toggled button
Implements AbMHViewHome.
Definition at line 46 of file microhil_view_home_signals.cc.
{
    return m_channelTimerToggled;
}
References m_channelTimerToggled.
channelIsToggled()
SigChannelToggled MHViewHome::channelIsToggled () final virtual
Signal for toggling buttons (turn on/turn off channel)
Returns
Signal for toggled button
Implements AbMHViewHome.
Definition at line 36 of file microhil_view_home_signals.cc.
{
    return m_channelToggled;
}
References m_channelToggled.
channelToInt()
int MHViewHome::channelToInt (Channel id) private
Converts channel id to integer value.
Parameters
id represents id for channel (Channel::MICROHIL_ID0 .. 7)
Returns
integer value of channel id
Definition at line 28 of file microhil_view_home_utils.cc.
{
    switch (id)
    {
    case Channel::MICROHIL_ID0:
        return 0;
    case Channel::MICROHIL_ID1:
        return 1;
    case Channel::MICROHIL_ID2:
        return 2;
    case Channel::MICROHIL_ID3:
        return 3;
    case Channel::MICROHIL_ID4:
        return 4;
    case Channel::MICROHIL_ID5:
        return 5;
    case Channel::MICROHIL_ID6:
        return 6;
    case Channel::MICROHIL_ID7:
        return 7;
    }
    return kInvalidConversionParameter;
}
References MICROHIL_ID0, MICROHIL_ID1, MICROHIL_ID2, MICROHIL_ID3, MICROHIL_ID4, MICROHIL_ID5, MICROHIL_ID6, and MICROHIL_ID7.
Referenced by onChannelChanged(), onSpinTimerChanged(), onToggled(), onToggleTimerChanged(), and onTypeSelected().
controlTypeToInt()
int MHViewHome::controlTypeToInt (channelControlType controlType) private
Converts channel control type to integer value.
Parameters
controlType represents control type
Returns
integer value of channel control type
Definition at line 53 of file microhil_view_home_utils.cc.
{
    switch (controlType)
    {
    case channelControlType::MICROHIL_TOGGLE_BUTTON:
        return 0;
    case channelControlType::MICROHIL_TIMER_BUTTON:
        return 1;
    }
    return kInvalidConversionParameter;
}
References MICROHIL_TIMER_BUTTON, and MICROHIL_TOGGLE_BUTTON.
Referenced by onTypeSelected().
disableChannel()
void MHViewHome::disableChannel (Channel id) private
Disables complete channel.
Parameters
id represents id for channel (Channel::MICROHIL_ID0 .. 7)
Definition at line 21 of file microhil_view_home_mode.cc.
{
    auto ix = static_cast<int>(id);
    m_selectControlChannels[ix]->set_sensitive(false);
    m_toggleChannels[ix]->set_sensitive(false);
    m_spinTimerChannels[ix]->set_sensitive(false);
    m_toggleTimerChannels[ix]->set_sensitive(false);
    m_stautsTimerChannels[ix]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MHViewHome(), and onChannelChanged().
enableChannel()
void MHViewHome::enableChannel (Channel id) private
Enables complete channel.
Parameters
id represents id for channel (Channel::MICROHIL_ID0 .. 7)
Definition at line 31 of file microhil_view_home_mode.cc.
{
    auto ix = static_cast<int>(id);
    m_selectControlChannels[ix]->set_sensitive(true);
    m_toggleChannels[ix]->set_sensitive(false);
    m_spinTimerChannels[ix]->set_sensitive(false);
    m_toggleTimerChannels[ix]->set_sensitive(false);
    m_stautsTimerChannels[ix]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannelChanged().
mapping()
void MHViewHome::mapping () private
Maps channels (signals and slots)
Maps Connect menu-item signal slot
Maps Disconnect menu-item signal slot
Maps Quit menu-item signal slot
Maps Serial Settings menu-item signal slot
Maps Log Settings menu-item signal slot
Maps About menu-item signal slot
Maps channels (signals and slots)
Definition at line 28 of file microhil_view_home_map.cc.
{
    m_connect->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onConnectClicked)
    );
    m_disconnect->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onDisconnectClicked)
    );
    m_quit->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onQuitClicked)
    );
    m_serialSettings->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onSerialSettingsClicked)
    );
    m_logSettings->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onLogSettingsClicked)
    );
    m_about->signal_activate().connect(
        sigc::mem_fun(*this, &MHViewHome::onAboutClicked)
    );
    for (int i = 0; i < kNumberOfMapChannels; i++)
    {
        m_enableChannels[i]->signal_toggled().connect(
            sigc::bind<Channel>(
                sigc::mem_fun(*this, &MHViewHome::onChannelChanged),
                static_cast<Channel>(i)
            )
        );
        m_selectControlChannels[i]->signal_changed().connect(
            sigc::bind<Channel>(
                sigc::mem_fun(*this, &MHViewHome::onTypeSelected),
                static_cast<Channel>(i)
            )
        );
        m_toggleChannels[i]->signal_toggled().connect(
            sigc::bind<Channel>(
                sigc::mem_fun(*this, &MHViewHome::onToggled),
                static_cast<Channel>(i)
            )
        );
        m_spinTimerChannels[i]->signal_changed().connect(
            sigc::bind<Channel>(
                sigc::mem_fun(*this, &MHViewHome::onSpinTimerChanged),
                static_cast<Channel>(i)
            )
        );
        m_toggleTimerChannels[i]->signal_toggled().connect(
            sigc::bind<Channel>(
                sigc::mem_fun(*this, &MHViewHome::onToggleTimerChanged),
                static_cast<Channel>(i)
            )
        );
    }
}
References m_about, m_connect, m_disconnect, m_enableChannels, m_logSettings, m_quit, m_selectControlChannels, m_serialSettings, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, onAboutClicked(), onChannelChanged(), onConnectClicked(), onDisconnectClicked(), onLogSettingsClicked(), onQuitClicked(), onSerialSettingsClicked(), onSpinTimerChanged(), onToggled(), onToggleTimerChanged(), and onTypeSelected().
Referenced by MHViewHome().
onAboutClicked()
void MHViewHome::onAboutClicked ()
Slot for processing About meni-item.
Definition at line 124 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_ABOUT);
}
References m_actionViewTriggered, and MICROHIL_ABOUT.
Referenced by mapping().
onChannelChanged()
void MHViewHome::onChannelChanged (Channel id) final virtual
Slot for processing check buttons (enable/disable channel)
Parameters
id represents id for channel (Channel::ID0 .. Channel::ID7)
Implements AbMHViewHome.
Definition at line 21 of file microhil_view_home_slots.cc.
{
    auto ix = channelToInt(id);
    bool status = m_enableChannels[ix]->get_active();
    if (status)
    {
        enableChannel(id);
    }
    else
    {
        disableChannel(id);
    }
    m_channelEnabled.emit(id, status);
}
References channelToInt(), disableChannel(), enableChannel(), m_channelEnabled, and m_enableChannels.
Referenced by mapping().
onConnectClicked()
void MHViewHome::onConnectClicked ()
Slot for processing Connect meni-item.
Definition at line 93 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_CONNECT);
    m_connect->set_sensitive(false);
    m_disconnect->set_sensitive(true);
    m_serialSettings->set_sensitive(true);
}
References m_actionViewTriggered, m_connect, m_disconnect, m_serialSettings, and MICROHIL_CONNECT.
Referenced by mapping().
onDisconnectClicked()
void MHViewHome::onDisconnectClicked ()
Slot for processing Disconnect meni-item.
Definition at line 101 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_DISCONNECT);
    m_connect->set_sensitive(true);
    m_disconnect->set_sensitive(false);
    m_serialSettings->set_sensitive(true);
}
References m_actionViewTriggered, m_connect, m_disconnect, m_serialSettings, and MICROHIL_DISCONNECT.
Referenced by mapping().
onLogSettingsClicked()
void MHViewHome::onLogSettingsClicked ()
Slot for processing Log Settings meni-item.
Definition at line 119 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_LOG_SETTINGS);
}
References m_actionViewTriggered, and MICROHIL_LOG_SETTINGS.
Referenced by mapping().
onQuitClicked()
void MHViewHome::onQuitClicked ()
Slot for processing Quit meni-item.
Definition at line 109 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_QUIT);
}
References m_actionViewTriggered, and MICROHIL_QUIT.
Referenced by mapping().
onSerialSettingsClicked()
void MHViewHome::onSerialSettingsClicked ()
Slot for processing Serial Settings meni-item.
Definition at line 114 of file microhil_view_home_slots.cc.
{
    m_actionViewTriggered.emit(ViewId::MICROHIL_SERIAL_SETTINGS);
}
References m_actionViewTriggered, and MICROHIL_SERIAL_SETTINGS.
Referenced by mapping().
onSpinTimerChanged()
void MHViewHome::onSpinTimerChanged (Channel id) final virtual
Slot for processing spin buttons (based on timer)
Parameters
id represents id for channel (Channel::ID0 .. Channel::ID7)
Implements AbMHViewHome.
Definition at line 71 of file microhil_view_home_slots.cc.
{
    auto ix = channelToInt(id);
    if (m_enableChannels[ix]->get_active())
    {
        int value = m_spinTimerChannels[ix]->get_value_as_int();
        m_channelSpinTimerChanged.emit(id, value);
    }
}
References channelToInt(), m_channelSpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onToggled()
void MHViewHome::onToggled (Channel id) final virtual
Slot for processing toggle buttons (turn on/turn off channel)
Parameters
id represents id for channel (Channel::ID0 .. Channel::ID7)
Implements AbMHViewHome.
Definition at line 60 of file microhil_view_home_slots.cc.
{
    auto ix = channelToInt(id);
    if (m_enableChannels[ix]->get_active())
    {
        bool status = m_toggleChannels[ix]->get_active();
        m_channelToggled.emit(id, status);
    }
}
References channelToInt(), m_channelToggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onToggleTimerChanged()
void MHViewHome::onToggleTimerChanged (Channel id) final virtual
Slot for processing toggle buttons (turn on/turn off timer)
Parameters
id represents id for channel (Channel::ID0 .. Channel::ID7)
Implements AbMHViewHome.
Definition at line 82 of file microhil_view_home_slots.cc.
{
    auto ix = channelToInt(id);
    if (m_enableChannels[ix]->get_active())
    {
        bool status = m_toggleTimerChannels[ix]->get_active();
        m_channelTimerToggled.emit(id, status);
    }
}
References channelToInt(), m_channelTimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onTypeSelected()
void MHViewHome::onTypeSelected (Channel id) final virtual
Slot for processing comboboxes (control type)
Parameters
id represents id for channel (Channel::ID0 .. Channel::ID7)
Implements AbMHViewHome.
Definition at line 38 of file microhil_view_home_slots.cc.
{
    auto ix = channelToInt(id);
    if (m_enableChannels[ix]->get_active())
    {
        int controlType = m_selectControlChannels[ix]->get_active_row_number();
        if (controlTypeToInt(channelControlType::MICROHIL_TOGGLE_BUTTON) == 0)
        {
            toggleModeChannel(id);
        }
        if (controlTypeToInt(channelControlType::MICROHIL_TIMER_BUTTON) == 1)
        {
            timerModeChannel(id);
        }
        m_channelControlType.emit(id, controlType);
    }
}
References channelToInt(), controlTypeToInt(), m_channelControlType, m_enableChannels, m_selectControlChannels, MICROHIL_TIMER_BUTTON, MICROHIL_TOGGLE_BUTTON, timerModeChannel(), and toggleModeChannel().
Referenced by mapping().
serialSettingsConfirm()
void MHViewHome::serialSettingsConfirm (bool state) final virtual
Sets widgets after confirming changes for the serial port.
Parameters
state true for confirmed changes, else false
Implements AbMHViewHome.
Definition at line 216 of file microhil_view_home.cc.
{
    m_connect->set_sensitive(!state);
    m_disconnect->set_sensitive(state);
}
References m_connect, and m_disconnect.
timerModeChannel()
void MHViewHome::timerModeChannel (Channel id) private
Sets channel timer mode.
Parameters
id represents id for channel (Channel::MICROHIL_ID0 .. 7)
Definition at line 50 of file microhil_view_home_mode.cc.
{
    auto ix = static_cast<int>(id);
    m_toggleChannels[ix]->set_sensitive(false);
    m_spinTimerChannels[ix]->set_sensitive(true);
    m_toggleTimerChannels[ix]->set_sensitive(true);
    m_stautsTimerChannels[ix]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onTypeSelected().
toggleModeChannel()
void MHViewHome::toggleModeChannel (Channel id) private
Sets channel in toggle mode.
Parameters
id represents id for channel (Channel::MICROHIL_ID0 .. 7)
Definition at line 41 of file microhil_view_home_mode.cc.
{
    auto ix = static_cast<int>(id);
    m_toggleChannels[ix]->set_sensitive(true);
    m_spinTimerChannels[ix]->set_sensitive(false);
    m_toggleTimerChannels[ix]->set_sensitive(false);
    m_stautsTimerChannels[ix]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onTypeSelected().
viewChanged()
SigActionViewTriggered MHViewHome::viewChanged () final virtual
Signal for menu items (changed view)
Returns
Signal for clicked menu item
Implements AbMHViewHome.
Definition at line 21 of file microhil_view_home_signals.cc.
{
    return m_actionViewTriggered;
}
References m_actionViewTriggered.
Member Data Documentation
m_about
MHRPtr<Gtk::MenuItem> MHViewHome::m_about {nullptr} private
Application About menu-item.
Definition at line 191 of file microhil_view_home.h.
Referenced by mapping(), and MHViewHome().
m_actionViewTriggered
SigActionViewTriggered MHViewHome::m_actionViewTriggered {} private
Signal for menu items (triggered another view)
Definition at line 223 of file microhil_view_home.h.
Referenced by onAboutClicked(), onConnectClicked(), onDisconnectClicked(), onLogSettingsClicked(), onQuitClicked(), onSerialSettingsClicked(), and viewChanged().
m_adjustment_digits
MHRPtr<Gtk::Adjustment> MHViewHome::m_adjustment_digits {nullptr} private
Adjustment setup for channel visual status.
Definition at line 219 of file microhil_view_home.h.
m_channelControlType
SigSelectChanged MHViewHome::m_channelControlType {} private
Signal for comboboxes (toogle/timer type control)
Definition at line 231 of file microhil_view_home.h.
Referenced by channelIsSelected(), and onTypeSelected().
m_channelEnabled
SigChannelChanged MHViewHome::m_channelEnabled {} private
Signal for check buttons (enable/disable channel)
Definition at line 227 of file microhil_view_home.h.
Referenced by channelIsChanged(), and onChannelChanged().
m_channelSpinTimerChanged
SigChannelSpinTimerChanged MHViewHome::m_channelSpinTimerChanged {} private
Signal for spin buttons (based on timer setup)
Definition at line 239 of file microhil_view_home.h.
Referenced by channelIsSpinTimerChanged(), and onSpinTimerChanged().
m_channelTimerToggled
SigChannelTimerToggled MHViewHome::m_channelTimerToggled {} private
Signal for toogle buttons (based on timer setup)
Definition at line 243 of file microhil_view_home.h.
Referenced by channelIsTimerChanged(), and onToggleTimerChanged().
m_channelToggled
SigChannelToggled MHViewHome::m_channelToggled {} private
Signal for toogle buttons (turn on/turn off channel)
Definition at line 235 of file microhil_view_home.h.
Referenced by channelIsToggled(), and onToggled().
m_connect
MHRPtr<Gtk::MenuItem> MHViewHome::m_connect {nullptr} private
Application Connect menu-item.
Definition at line 171 of file microhil_view_home.h.
Referenced by mapping(), MHViewHome(), onConnectClicked(), onDisconnectClicked(), and serialSettingsConfirm().
m_disconnect
MHRPtr<Gtk::MenuItem> MHViewHome::m_disconnect {nullptr} private
Application Disconnect menu-item.
Definition at line 175 of file microhil_view_home.h.
Referenced by mapping(), MHViewHome(), onConnectClicked(), onDisconnectClicked(), and serialSettingsConfirm().
m_enableChannels
std::vector<MHRPtr<Gtk::CheckButton> > MHViewHome::m_enableChannels {} private
Check buttons for enable/disable channels.
Definition at line 195 of file microhil_view_home.h.
Referenced by mapping(), MHViewHome(), onChannelChanged(), onSpinTimerChanged(), onToggled(), onToggleTimerChanged(), and onTypeSelected().
m_logSettings
MHRPtr<Gtk::MenuItem> MHViewHome::m_logSettings {nullptr} private
Application Log Settings menu-item.
Definition at line 187 of file microhil_view_home.h.
Referenced by mapping(), and MHViewHome().
m_quit
MHRPtr<Gtk::MenuItem> MHViewHome::m_quit {nullptr} private
Application Quit menu-item.
Definition at line 179 of file microhil_view_home.h.
Referenced by mapping(), and MHViewHome().
m_selectControlChannels
std::vector<MHRPtr<Gtk::ComboBoxText> > MHViewHome::m_selectControlChannels {} private
Comboboxes for selecting channel mode.
Definition at line 199 of file microhil_view_home.h.
Referenced by disableChannel(), enableChannel(), mapping(), MHViewHome(), and onTypeSelected().
m_serialSettings
MHRPtr<Gtk::MenuItem> MHViewHome::m_serialSettings {nullptr} private
Application Serial Port Settings menu-item.
Definition at line 183 of file microhil_view_home.h.
Referenced by mapping(), MHViewHome(), onConnectClicked(), and onDisconnectClicked().
m_spinTimerChannels
std::vector<MHRPtr<Gtk::SpinButton> > MHViewHome::m_spinTimerChannels {} private
Spin button for setup channel timer.
Definition at line 207 of file microhil_view_home.h.
Referenced by disableChannel(), enableChannel(), mapping(), MHViewHome(), onSpinTimerChanged(), timerModeChannel(), and toggleModeChannel().
m_stautsTimerChannels
std::vector<MHRPtr<Gtk::ProgressBar> > MHViewHome::m_stautsTimerChannels {} private
Visual status for channels.
Definition at line 215 of file microhil_view_home.h.
Referenced by disableChannel(), enableChannel(), MHViewHome(), timerModeChannel(), and toggleModeChannel().
m_toggleChannels
std::vector<MHRPtr<Gtk::ToggleButton> > MHViewHome::m_toggleChannels {} private
Toggle button for direct channel control.
Definition at line 203 of file microhil_view_home.h.
Referenced by disableChannel(), enableChannel(), mapping(), MHViewHome(), onToggled(), timerModeChannel(), and toggleModeChannel().
m_toggleTimerChannels
std::vector<MHRPtr<Gtk::ToggleButton> > MHViewHome::m_toggleTimerChannels {} private
Toggle button for starting channel timer.
Definition at line 211 of file microhil_view_home.h.
Referenced by disableChannel(), enableChannel(), mapping(), MHViewHome(), onToggleTimerChanged(), timerModeChannel(), and toggleModeChannel().
m_ui
MHRPtr<Gtk::Builder> MHViewHome::m_ui {nullptr} private
UI builder instance.
Definition at line 167 of file microhil_view_home.h.
Referenced by MHViewHome().
The documentation for this class was generated from the following files:
view/home/microhil_view_home.h
view/home/microhil_view_home.cc
view/home/microhil_view_home_map.cc
view/home/microhil_view_home_mode.cc
view/home/microhil_view_home_signals.cc
view/home/microhil_view_home_slots.cc
view/home/microhil_view_home_utils.cc