microhildesk: MicroHILViewAbout Class Reference
MicroHILViewAbout Class Reference
MicroHILViewAbout class declaration and definition.
#include <microhil_view_about.h>
Public Member Functions
MicroHILViewAbout (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
MicroHILViewAbout constructor.
~MicroHILViewAbout ()=default
MicroHILViewAbout destructor.
visibleAbout visibleAboutChanged () final
Signals for emitting from about Ok button.
void onVisibleAboutChange () final
Slots for processing Ok button for about dialog.
Public Member Functions inherited from AbMicroHILViewAbout
virtual ~AbMicroHILViewAbout ()=default
AbMicroHILViewAbout destructor.
virtual visibleAbout visibleAboutChanged ()=0
Signals for emitting from about Ok button.
virtual void onVisibleAboutChange ()=0
Slots for processing Ok button for about dialog.
Private Member Functions
void mapping ()
Map Ok button signal and slot.
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui
UI builder instance.
Glib::RefPtr< Gtk::Button > m_ok
Ok button for about view.
visibleAbout m_visibleAbout
Signal for emitting from Ok button (hide about dialog)
Additional Inherited Members
Public Types inherited from AbMicroHILViewAbout
using visibleAbout = sigc::signal< void(bool)>
Signal type for about Ok button.
Detailed Description
MicroHILViewAbout class declaration and definition.
Definition at line 28 of file microhil_view_about.h.
Constructor & Destructor Documentation
MicroHILViewAbout()
MicroHILViewAbout::MicroHILViewAbout (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
MicroHILViewAbout constructor.
Parameters
object base object type
ui builder parser
Bind Ok button
Map Ok button signal and slot
Definition at line 28 of file microhil_view_about.cc.
 : Gtk::AboutDialog(object), m_ui{ui}
{
    m_ok = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kOkButtonId)
    );
    mapping();
}
References m_ok, m_ui, and mapping().
~MicroHILViewAbout()
MicroHILViewAbout::~MicroHILViewAbout () default
MicroHILViewAbout destructor.
Member Function Documentation
mapping()
void MicroHILViewAbout::mapping () private
Map Ok button signal and slot.
Map Ok button signal and slot
Definition at line 21 of file microhil_view_about_map.cc.
{
    m_ok->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewAbout::onVisibleAboutChange)
    );
}
References m_ok, and onVisibleAboutChange().
Referenced by MicroHILViewAbout().
onVisibleAboutChange()
void MicroHILViewAbout::onVisibleAboutChange () final virtual
Slots for processing Ok button for about dialog.
Implements AbMicroHILViewAbout.
Definition at line 21 of file microhil_view_about_slots.cc.
{
    this->hide();
}
Referenced by mapping().
visibleAboutChanged()
MicroHILViewAbout::visibleAbout MicroHILViewAbout::visibleAboutChanged () final virtual
Signals for emitting from about Ok button.
Returns
signal for pressed about Ok button
Implements AbMicroHILViewAbout.
Definition at line 21 of file microhil_view_about_signals.cc.
{
    return m_visibleAbout;
}
References m_visibleAbout.
Member Data Documentation
m_ok
Glib::RefPtr<Gtk::Button> MicroHILViewAbout::m_ok private
Ok button for about view.
Definition at line 63 of file microhil_view_about.h.
Referenced by mapping(), and MicroHILViewAbout().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILViewAbout::m_ui private
UI builder instance.
Definition at line 59 of file microhil_view_about.h.
Referenced by MicroHILViewAbout().
m_visibleAbout
visibleAbout MicroHILViewAbout::m_visibleAbout private
Signal for emitting from Ok button (hide about dialog)
Definition at line 67 of file microhil_view_about.h.
Referenced by visibleAboutChanged().
The documentation for this class was generated from the following files:
view/about/microhil_view_about.h
view/about/microhil_view_about.cc
view/about/microhil_view_about_map.cc
view/about/microhil_view_about_signals.cc
view/about/microhil_view_about_slots.cc