microhildesk: Electux::App::View::AppHome Class Reference
Electux::App::View::AppHome Class Reference
Home view window definition for the microhildesk application.
#include <home.h>
Public Member Functions
AppHome ()
AppHome constructor.
SigSettings controlChanged ()
Signal for settings setup.
void setControlSetup (const SettingsSetup &setup)
Sets the configuration setup.
void getUiData ()
Gets UI data from widgets and saves them to configuration.
void updateUiData ()
Updates UI widgets with data from loaded configuration.
Protected Member Functions
void mapping (size_t index)
Maps home (signals and slots).
void onChannelEnableChanged (size_t index)
Signal handler for enablement channel.
void onChannelModeChanged (size_t index)
Signal handler for setup channel mode.
void onChannelToggleChanged (size_t index)
Signal handler for toggle mode.
void onChannelTimerChanged (size_t index)
Signal handler for timer mode.
void onChannelTimerToggleChanged (size_t index)
Signal handler for timer mode (start process).
std::vector< std::string > split_to_vector (const std::string_view &input)
Splits input string into vector of substrings.
std::string extract_param_value_by_index (const std::string_view &input, size_t index)
Extracts nth substring from input string.
std::string update_param_value_by_index (const std::string_view &input, size_t index, const std::string_view &newValue)
Updates nth substring in input string.
void update_control_config (const std::string_view &key, size_t index, const std::string_view &value)
Updates control configuration parameter.
std::string extract_config (const std::string_view &key, size_t index)
Extracts control configuration parameter.
Private Attributes
UI State and Configuration
bool m_blockSignals {false}
Flag to block signals during UI update.
SettingsSetup m_setup {}
Control parameters storage.
SigSettings m_controlSignal {}
Internal signal for control settings.
UI Widgets and Containers
Gtk::Box m_boxRoot {}
Root container for packing.
std::vector< Gtk::Box > m_boxChannels {}
Containers for individual channels.
std::vector< Gtk::CheckButton > m_enableChannels {}
Enablement checkboxes.
std::vector< Gtk::ComboBoxText > m_selectControlChannels {}
Mode selection.
std::vector< Gtk::Label > m_labelToggleChannels {}
Toggle labels.
std::vector< Gtk::ToggleButton > m_toggleChannels {}
Main toggle buttons.
std::vector< Gtk::Label > m_labelTimerChannels {}
Timer labels.
std::vector< Gtk::SpinButton > m_spinTimerChannels {}
Timer duration spinners.
std::vector< Gtk::ToggleButton > m_toggleTimerChannels {}
Timer activation buttons.
std::vector< Gtk::ProgressBar > m_statusTimerChannels {}
Timer progress indicators.
Detailed Description
Home view window definition for the microhildesk application.
Provides the main user interface for monitoring and controlling multiple channels, including toggle, timer, and mode selection.
Definition at line 50 of file home.h.
Constructor & Destructor Documentation
AppHome()
AppHome::AppHome () explicit
AppHome constructor.
Sets up the main window properties, initializes layout containers, and dynamically creates UI widgets for each channel based on defined parameters.
Setup application home window
Definition at line 57 of file home.cc.
{
    set_title(cHomeTitle.data());
    set_default_size(cHomeWidth, cHomeHeight);
    set_resizable(false);
    set_show_menubar(true);
    m_boxRoot.set_orientation(Gtk::Orientation::HORIZONTAL);
    set_child(m_boxRoot);
    for (ssize_t i = 0; i < cNumOfChannels; i++)
    {
        m_boxChannels.emplace_back(Gtk::Orientation::VERTICAL);
        auto& currentBox = m_boxChannels.back();
        // Setup Enable CheckButton
        m_enableChannels.emplace_back(std::format("{} {}", cHomeEnChannelLabel.data(), i));
        currentBox.append(m_enableChannels.back());
        // Setup Mode ComboBox
        m_selectControlChannels.emplace_back();
        for (const auto& option : cHomeChannelModeOptions)
        {
            m_selectControlChannels.back().append(option.data());
        }
        currentBox.append(m_selectControlChannels.back());
        // Setup Toggle Label and Button
        m_labelToggleChannels.emplace_back(std::format("{} {}", cHomeToggleChannelLabel.data(), i));
        currentBox.append(m_labelToggleChannels.back());
        m_toggleChannels.emplace_back();
        m_toggleChannels.back().set_label(cHomeToggleChannelButtonActivate.data());
        currentBox.append(m_toggleChannels.back());
        // Setup Timer Label, Spinner and Button
        m_labelTimerChannels.emplace_back(std::format("{} {}", cHomeTimerChannelLabel.data(), i));
        currentBox.append(m_labelTimerChannels.back());
        m_spinTimerChannels.emplace_back();
        m_spinTimerChannels.back().set_range(0.0, 3600.0);
        m_spinTimerChannels.back().set_increments(1.0, 10.0);
        currentBox.append(m_spinTimerChannels.back());
        m_toggleTimerChannels.emplace_back();
        m_toggleTimerChannels.back().set_label(cHomeTimerChannelButtonStart.data());
        currentBox.append(m_toggleTimerChannels.back());
        // Setup Progress Bar
        m_statusTimerChannels.emplace_back();
        m_statusTimerChannels.back().set_fraction(cHomeStatusFraction);
        currentBox.append(m_statusTimerChannels.back());
        // Layout and Signal Mapping
        currentBox.set_margin(cHomeBoxChannelMargin);
        currentBox.set_spacing(cHomeBoxChannelSpacing);
        m_boxRoot.append(currentBox);
        mapping(i);
    }
}
References Electux::App::Params::Channel::cNumOfChannels, m_boxChannels, m_boxRoot, m_enableChannels, m_labelTimerChannels, m_labelToggleChannels, m_selectControlChannels, m_spinTimerChannels, m_statusTimerChannels, m_toggleChannels, m_toggleTimerChannels, and mapping().
Member Function Documentation
controlChanged()
SigSettings AppHome::controlChanged ()
Signal for settings setup.
Returns the signal emitted when control settings change.
Returns
Signal emitted when control settings are changed.
The SigSettings signal instance.
Definition at line 193 of file home_ui_utils.cc.
{
    return m_controlSignal;
}
References m_controlSignal.
Referenced by Electux::App::EntryApplication::mapping().
extract_config()
std::string AppHome::extract_config (const std::string_view & key, size_t index) protected
Extracts control configuration parameter.
Extracts control configuration parameter from the model.
Parameters
key Configuration key to extract.
index Index of the parameter to extract.
Returns
Extracted value for the configuration key.
Definition at line 183 of file home_ui_utils.cc.
{
    auto controlEntity = m_setup.m_config.getEntity(key);
    return extract_param_value_by_index(controlEntity, index);
}
References extract_param_value_by_index(), Electux::App::Model::Model::getEntity(), Electux::App::View::SettingsSetup::m_config, and m_setup.
Referenced by updateUiData().
extract_param_value_by_index()
std::string AppHome::extract_param_value_by_index (const std::string_view & input, size_t index) protected
Extracts nth substring from input string.
Parameters
input Input string.
index Index of substring to extract.
Returns
Extracted substring.
Parameters
input Input string.
index Index of substring to extract.
Returns
Extracted substring or empty string if index out of bounds.
Definition at line 121 of file home_ui_utils.cc.
{
    auto elements = split_to_vector(input);
    if (index < elements.size())
    {
        return elements[index];
    }
    return std::string(cEmptyString);
}
References Electux::App::Params::Channel::cEmptyString, and split_to_vector().
Referenced by extract_config().
getUiData()
void AppHome::getUiData ()
Gets UI data from widgets and saves them to configuration.
Gets UI data from widgets and saves them to the configuration model. Emits the controlChanged signal after updating the setup.
Definition at line 66 of file home_ui_utils.cc.
{
    const auto& config = m_setup.m_config;
    const auto controlEnableKey = config.toString(ModelControlKey::Enable);
    const auto controlModeKey = config.toString(ModelControlKey::Mode);
    const auto controlToggleKey = config.toString(ModelControlKey::Toggle);
    const auto controlTimerKey = config.toString(ModelControlKey::Timer);
    const auto controlTimerEnableKey = config.toString(ModelControlKey::TimerEnable);
    for (ssize_t i = 0; i < cNumOfChannels; i++)
    {
        auto controlEnableCheckValue = boolToString(m_enableChannels[i].get_active());
        update_control_config(controlEnableKey, i, controlEnableCheckValue);
        auto controlModeComboValue = std::to_string(m_selectControlChannels[i].get_active_row_number());
        update_control_config(controlModeKey, i, controlModeComboValue);
        auto controlToggleButtonValue = boolToString(m_toggleChannels[i].get_active());
        update_control_config(controlToggleKey, i, controlToggleButtonValue);
        auto controlTimerSpinValue = std::to_string(m_spinTimerChannels[i].get_value_as_int());
        update_control_config(controlTimerKey, i, controlTimerSpinValue);
        auto controlTimerEnableButtonValue = boolToString(m_toggleTimerChannels[i].get_active());
        update_control_config(controlTimerEnableKey, i, controlTimerEnableButtonValue);
    }
    m_controlSignal.emit(m_setup);
}
References Electux::App::Params::Channel::boolToString(), Electux::App::Params::Channel::cNumOfChannels, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_enableChannels, m_selectControlChannels, m_setup, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, Electux::App::Model::Model::toString(), and update_control_config().
mapping()
void AppHome::mapping (size_t index) protected
Maps home (signals and slots).
Connects signals and slots for a specific channel in the home window.
Parameters
index Index of the channel to map.
Uses sigc::bind to pass the channel index to the handlers, ensuring that each widget's interaction is correctly routed to the corresponding channel.
Parameters
index The index of the channel being mapped.
Definition at line 32 of file home_map.cc.
{
    // Connect signals and slots for home window widgets
    m_enableChannels[index].signal_toggled().connect(
        sigc::bind(sigc::mem_fun(*this, &AppHome::onChannelEnableChanged), index)
    );
    m_selectControlChannels[index].signal_changed().connect(
        sigc::bind(sigc::mem_fun(*this, &AppHome::onChannelModeChanged), index)
    );
    m_toggleChannels[index].signal_toggled().connect(
        sigc::bind(sigc::mem_fun(*this, &AppHome::onChannelToggleChanged), index)
    );
    m_spinTimerChannels[index].signal_value_changed().connect(
        sigc::bind(sigc::mem_fun(*this, &AppHome::onChannelTimerChanged), index)
    );
    m_toggleTimerChannels[index].signal_toggled().connect(
        sigc::bind(sigc::mem_fun(*this, &AppHome::onChannelTimerToggleChanged), index)
    );
}
References m_enableChannels, m_selectControlChannels, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, onChannelEnableChanged(), onChannelModeChanged(), onChannelTimerChanged(), onChannelTimerToggleChanged(), and onChannelToggleChanged().
Referenced by AppHome().
onChannelEnableChanged()
void AppHome::onChannelEnableChanged (size_t index) protected
Signal handler for enablement channel.
Parameters
index Index of the affected channel.
Definition at line 35 of file home_slots.cc.
{
    if (m_blockSignals) { return; }
    const auto controlEnableKey = m_setup.m_config.toString(ModelControlKey::Enable);
    auto value = boolToString(m_enableChannels[index].get_active());
    update_control_config(controlEnableKey, index, value);
    m_controlSignal.emit(m_setup);
}
References Electux::App::Params::Channel::boolToString(), m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_enableChannels, m_setup, Electux::App::Model::Model::toString(), and update_control_config().
Referenced by mapping().
onChannelModeChanged()
void AppHome::onChannelModeChanged (size_t index) protected
Signal handler for setup channel mode.
Parameters
index Index of the affected channel.
Definition at line 49 of file home_slots.cc.
{
    if (m_blockSignals) { return; }
    const auto controlModeKey = m_setup.m_config.toString(ModelControlKey::Mode);
    auto controlModeComboValue = std::to_string(m_selectControlChannels[index].get_active_row_number());
    update_control_config(controlModeKey, index, controlModeComboValue);
    m_controlSignal.emit(m_setup);
}
References m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_selectControlChannels, m_setup, Electux::App::Model::Model::toString(), and update_control_config().
Referenced by mapping().
onChannelTimerChanged()
void AppHome::onChannelTimerChanged (size_t index) protected
Signal handler for timer mode.
Signal handler for timer value changes.
Parameters
index Index of the affected channel.
Definition at line 77 of file home_slots.cc.
{
    if (m_blockSignals) { return; }
    const auto controlTimerKey = m_setup.m_config.toString(ModelControlKey::Timer);
    auto controlTimerSpinValue = std::to_string(m_spinTimerChannels[index].get_value_as_int());
    update_control_config(controlTimerKey, index, controlTimerSpinValue);
    m_controlSignal.emit(m_setup);
}
References m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_setup, m_spinTimerChannels, Electux::App::Model::Model::toString(), and update_control_config().
Referenced by mapping().
onChannelTimerToggleChanged()
void AppHome::onChannelTimerToggleChanged (size_t index) protected
Signal handler for timer mode (start process).
Signal handler for timer activation toggle.
Parameters
index Index of the affected channel.
Definition at line 91 of file home_slots.cc.
{
    if (m_blockSignals) { return; }
    const auto controlTimerEnableKey = m_setup.m_config.toString(ModelControlKey::TimerEnable);
    auto controlTimerEnableButtonValue = boolToString(m_toggleTimerChannels[index].get_active());
    update_control_config(controlTimerEnableKey, index, controlTimerEnableButtonValue);
    m_controlSignal.emit(m_setup);
}
References Electux::App::Params::Channel::boolToString(), m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_setup, m_toggleTimerChannels, Electux::App::Model::Model::toString(), and update_control_config().
Referenced by mapping().
onChannelToggleChanged()
void AppHome::onChannelToggleChanged (size_t index) protected
Signal handler for toggle mode.
Parameters
index Index of the affected channel.
Definition at line 63 of file home_slots.cc.
{
    if (m_blockSignals) { return; }
    const auto controlToggleKey = m_setup.m_config.toString(ModelControlKey::Toggle);
    auto controlToggleButtonValue = boolToString(m_toggleChannels[index].get_active());
    update_control_config(controlToggleKey, index, controlToggleButtonValue);
    m_controlSignal.emit(m_setup);
}
References Electux::App::Params::Channel::boolToString(), m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_controlSignal, m_setup, m_toggleChannels, Electux::App::Model::Model::toString(), and update_control_config().
Referenced by mapping().
setControlSetup()
void AppHome::setControlSetup (const SettingsSetup & setup)
Sets the configuration setup.
Sets the internal configuration setup.
Parameters
setup Reference to the SettingsSetup object.
setup Constant reference to the SettingsSetup object.
Definition at line 120 of file home.cc.
{
    m_setup = setup;
}
References m_setup.
Referenced by Electux::App::EntryApplication::on_startup().
split_to_vector()
std::vector< std::string > AppHome::split_to_vector (const std::string_view & input) protected
Splits input string into vector of substrings.
Parameters
input Input string to split.
Returns
Vector of substrings.
Definition at line 101 of file home_ui_utils.cc.
{
    std::vector<std::string> elements;
    std::stringstream ss{std::string(input)};
    std::string item;
    while (ss >> item)
    {
        elements.push_back(item);
    }
    return elements;
}
Referenced by extract_param_value_by_index(), and update_param_value_by_index().
update_control_config()
void AppHome::update_control_config (const std::string_view & key, size_t index, const std::string_view & value) protected
Updates control configuration parameter.
Updates control configuration parameter in the model.
Parameters
key Configuration key to update.
index Index of the parameter to update.
value New value for the configuration key.
Definition at line 170 of file home_ui_utils.cc.
{
    auto controlEntity = m_setup.m_config.getEntity(key);
    auto controlValue = update_param_value_by_index(controlEntity, index, value);
    m_setup.m_config.update(key, controlValue);
}
References Electux::App::Model::Model::getEntity(), Electux::App::View::SettingsSetup::m_config, m_setup, Electux::App::Model::Model::update(), and update_param_value_by_index().
Referenced by getUiData(), onChannelEnableChanged(), onChannelModeChanged(), onChannelTimerChanged(), onChannelTimerToggleChanged(), and onChannelToggleChanged().
update_param_value_by_index()
std::string AppHome::update_param_value_by_index (const std::string_view & input, size_t index, const std::string_view & newValue) protected
Updates nth substring in input string.
Updates nth substring in input string based on channel parameters.
Parameters
input Input string.
index Index of substring to update.
newValue New value for the substring.
Returns
Updated string.
Parameters
input Input string.
index Index of substring to update.
newValue New value for the substring.
Returns
The updated string.
Definition at line 140 of file home_ui_utils.cc.
{
    auto elements = split_to_vector(input);
    if (elements.size() < cNumOfChannels)
    {
        std::string defaultValue = elements.empty() ? std::string(newValue) : elements.back();
        elements.resize(cNumOfChannels, defaultValue);
    }
    if (index < elements.size())
    {
        elements[index] = std::string(newValue);
    }
    std::string result;
    for (size_t i = 0; i < elements.size(); ++i)
    {
        result += elements[i] + (i < elements.size() - 1 ? std::string(cSpaceString) : "");
    }
    return result;
}
References Electux::App::Params::Channel::cNumOfChannels, Electux::App::Params::Channel::cSpaceString, and split_to_vector().
Referenced by update_control_config().
updateUiData()
void AppHome::updateUiData ()
Updates UI widgets with data from loaded configuration.
Updates UI widgets with data from loaded configuration. Blocks signals during the update to prevent feedback loops.
Definition at line 31 of file home_ui_utils.cc.
{
    m_blockSignals = true;
    const auto& config = m_setup.m_config;
    const auto controlEnableKey = config.toString(ModelControlKey::Enable);
    const auto controlModeKey = config.toString(ModelControlKey::Mode);
    const auto controlToggleKey = config.toString(ModelControlKey::Toggle);
    const auto controlTimerKey = config.toString(ModelControlKey::Timer);
    const auto controlTimerEnableKey = config.toString(ModelControlKey::TimerEnable);
    for (ssize_t i = 0; i < cNumOfChannels; i++)
    {
        auto controlEnableValue = extract_config(controlEnableKey, i);
        m_enableChannels[i].set_active(controlEnableValue == cTrue);
        auto controlModeValue = std::stoi(extract_config(controlModeKey, i));
        m_selectControlChannels[i].set_active(controlModeValue);
        auto controlToggleValue = extract_config(controlToggleKey, i);
        m_toggleChannels[i].set_active(controlToggleValue == cTrue);
        auto controlTimerValue = std::stoi(extract_config(controlTimerKey, i));
        m_spinTimerChannels[i].set_value(controlTimerValue);
        auto controlTimerEnableValue = extract_config(controlTimerEnableKey, i);
        m_toggleTimerChannels[i].set_active(controlTimerEnableValue == cTrue);
    }
    m_blockSignals = false;
}
References Electux::App::Params::Channel::cNumOfChannels, Electux::App::Params::Channel::cTrue, extract_config(), m_blockSignals, Electux::App::View::SettingsSetup::m_config, m_enableChannels, m_selectControlChannels, m_setup, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, and Electux::App::Model::Model::toString().
Referenced by Electux::App::EntryApplication::on_startup().
Member Data Documentation
m_blockSignals
bool Electux::App::View::AppHome::m_blockSignals {false} private
Flag to block signals during UI update.
Definition at line 161 of file home.h.
{false};
Referenced by onChannelEnableChanged(), onChannelModeChanged(), onChannelTimerChanged(), onChannelTimerToggleChanged(), onChannelToggleChanged(), and updateUiData().
m_boxChannels
std::vector<Gtk::Box> Electux::App::View::AppHome::m_boxChannels {} private
Containers for individual channels.
Definition at line 171 of file home.h.
{};
Referenced by AppHome().
m_boxRoot
Gtk::Box Electux::App::View::AppHome::m_boxRoot {} private
Root container for packing.
Definition at line 170 of file home.h.
{};
Referenced by AppHome().
m_controlSignal
SigSettings Electux::App::View::AppHome::m_controlSignal {} private
Internal signal for control settings.
Definition at line 163 of file home.h.
{};
Referenced by controlChanged(), getUiData(), onChannelEnableChanged(), onChannelModeChanged(), onChannelTimerChanged(), onChannelTimerToggleChanged(), and onChannelToggleChanged().
m_enableChannels
std::vector<Gtk::CheckButton> Electux::App::View::AppHome::m_enableChannels {} private
Enablement checkboxes.
Definition at line 172 of file home.h.
{};
Referenced by AppHome(), getUiData(), mapping(), onChannelEnableChanged(), and updateUiData().
m_labelTimerChannels
std::vector<Gtk::Label> Electux::App::View::AppHome::m_labelTimerChannels {} private
Timer labels.
Definition at line 176 of file home.h.
{};
Referenced by AppHome().
m_labelToggleChannels
std::vector<Gtk::Label> Electux::App::View::AppHome::m_labelToggleChannels {} private
Toggle labels.
Definition at line 174 of file home.h.
{};
Referenced by AppHome().
m_selectControlChannels
std::vector<Gtk::ComboBoxText> Electux::App::View::AppHome::m_selectControlChannels {} private
Mode selection.
Definition at line 173 of file home.h.
{};
Referenced by AppHome(), getUiData(), mapping(), onChannelModeChanged(), and updateUiData().
m_setup
SettingsSetup Electux::App::View::AppHome::m_setup {} private
Control parameters storage.
Definition at line 162 of file home.h.
{};
Referenced by extract_config(), getUiData(), onChannelEnableChanged(), onChannelModeChanged(), onChannelTimerChanged(), onChannelTimerToggleChanged(), onChannelToggleChanged(), setControlSetup(), update_control_config(), and updateUiData().
m_spinTimerChannels
std::vector<Gtk::SpinButton> Electux::App::View::AppHome::m_spinTimerChannels {} private
Timer duration spinners.
Definition at line 177 of file home.h.
{};
Referenced by AppHome(), getUiData(), mapping(), onChannelTimerChanged(), and updateUiData().
m_statusTimerChannels
std::vector<Gtk::ProgressBar> Electux::App::View::AppHome::m_statusTimerChannels {} private
Timer progress indicators.
Definition at line 179 of file home.h.
{};
Referenced by AppHome().
m_toggleChannels
std::vector<Gtk::ToggleButton> Electux::App::View::AppHome::m_toggleChannels {} private
Main toggle buttons.
Definition at line 175 of file home.h.
{};
Referenced by AppHome(), getUiData(), mapping(), onChannelToggleChanged(), and updateUiData().
m_toggleTimerChannels
std::vector<Gtk::ToggleButton> Electux::App::View::AppHome::m_toggleTimerChannels {} private
Timer activation buttons.
Definition at line 178 of file home.h.
{};
Referenced by AppHome(), getUiData(), mapping(), onChannelTimerToggleChanged(), and updateUiData().
The documentation for this class was generated from the following files:
view/home.h
view/home.cc
view/home_map.cc
view/home_slots.cc
view/home_ui_utils.cc