microhil-device0: src/channel/microhil_channel.h File Reference
microhil_channel.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "pico/stdio_usb.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "hardware/pwm.h"
#include "ws2812.pio.h"
Macros
#define JDQ1 21
#define JDQ2 20
#define JDQ3 19
#define JDQ4 18
#define JDQ5 17
#define JDQ6 16
#define JDQ7 15
#define JDQ8 14
#define JDQ_ALL_OFF 0
#define JDQ_ALL_ON 1
#define JDQ_ERROR 127
Functions
void microhil_init ()
void microhil_all_channels_on ()
void microhil_all_channels_off ()
void microhil_channel_switch (int id)
unsigned int id_to_gpio (int id)
void put_pixel (uint32_t pixel_grb)
uint32_t urgb_u32 (uint8_t r, uint8_t g, uint8_t b)
void microhil_write_pwm (uint8_t value)
Variables
unsigned char Relays [8]
Macro Definition Documentation
JDQ1
#define JDQ1 21
Definition at line 32 of file microhil_channel.h.
JDQ2
#define JDQ2 20
Definition at line 36 of file microhil_channel.h.
JDQ3
#define JDQ3 19
Definition at line 40 of file microhil_channel.h.
JDQ4
#define JDQ4 18
Definition at line 44 of file microhil_channel.h.
JDQ5
#define JDQ5 17
Definition at line 48 of file microhil_channel.h.
JDQ6
#define JDQ6 16
Definition at line 52 of file microhil_channel.h.
JDQ7
#define JDQ7 15
Definition at line 56 of file microhil_channel.h.
JDQ8
#define JDQ8 14
Definition at line 60 of file microhil_channel.h.
JDQ_ALL_OFF
#define JDQ_ALL_OFF 0
Definition at line 64 of file microhil_channel.h.
JDQ_ALL_ON
#define JDQ_ALL_ON 1
Definition at line 68 of file microhil_channel.h.
JDQ_ERROR
#define JDQ_ERROR 127
Definition at line 72 of file microhil_channel.h.
Function Documentation
id_to_gpio()
unsigned int id_to_gpio (int id)
Parameters
id
Returns
Definition at line 112 of file microhil_channel_action.c.
{
    switch (id)
    {
    case 1:
        return JDQ1;
    case 2:
        return JDQ2;
    case 3:
        return JDQ3;
    case 4:
        return JDQ4;
    case 5:
        return JDQ5;
    case 6:
        return JDQ6;
    case 7:
        return JDQ7;
    case 8:
        return JDQ8;
    case 9:
        return JDQ_ALL_OFF;
    case 10:
        return JDQ_ALL_ON;
    }
    return JDQ_ERROR;
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, JDQ_ALL_OFF, JDQ_ALL_ON, and JDQ_ERROR.
Referenced by microhil_channel_switch().
microhil_all_channels_off()
void microhil_all_channels_off ()
Definition at line 48 of file microhil_channel_action.c.
{
    gpio_put(JDQ8, 0);
    gpio_put(JDQ7, 0);
    gpio_put(JDQ6, 0);
    gpio_put(JDQ5, 0);
    gpio_put(JDQ4, 0);
    gpio_put(JDQ3, 0);
    gpio_put(JDQ2, 0);
    gpio_put(JDQ1, 0);
    printf("***Relay ALL off***\r\n\n");
    for (int i = 0; i < 8; i++)
    {
        Relays[i] = 0x1;
    }
    put_pixel(urgb_u32(0, 0, 0));
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, put_pixel(), Relays, and urgb_u32().
Referenced by microhil_channel_switch().
microhil_all_channels_on()
void microhil_all_channels_on ()
Definition at line 23 of file microhil_channel_action.c.
{
    gpio_put(JDQ8, 1);
    gpio_put(JDQ7, 1);
    gpio_put(JDQ6, 1);
    gpio_put(JDQ5, 1);
    gpio_put(JDQ4, 1);
    gpio_put(JDQ3, 1);
    gpio_put(JDQ2, 1);
    gpio_put(JDQ1, 1);
    printf("***Relay ALL on****\r\n\n");
    for (int i = 0; i < 8; i++)
    {
        Relays[i] = 0x0;
    }
    put_pixel(urgb_u32(255, 255, 255));
    microhil_write_pwm(80); // buzzer
    microhil_delay_ms(100);
    microhil_write_pwm(0);
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, microhil_delay_ms(), microhil_write_pwm(), put_pixel(), Relays, and urgb_u32().
Referenced by microhil_channel_switch().
microhil_channel_switch()
void microhil_channel_switch (int id)
Parameters
id
Definition at line 71 of file microhil_channel_action.c.
{
    unsigned int gpio = id_to_gpio(id);
    switch (gpio)
    {
    case JDQ_ALL_OFF:
        microhil_all_channels_off();
        break;
    case JDQ_ALL_ON:
        microhil_all_channels_on();
        break;
    case JDQ_ERROR:
        printf("****Error*****\r\n\n");
        break;
    default:
        // TODO check gpio value
        gpio_put(gpio, Relays[id - 1]);
        if (Relays[id - 1] == 1)
        {
            put_pixel(urgb_u32(255, 0, 0));
            microhil_write_pwm(80); // buzzer
            microhil_delay_ms(100);
            microhil_write_pwm(0);
            printf("****Relay 1 on*****\r\n\n");
        }
        else if (Relays[id - 1] == 0)
        {
            printf("****Relay 1 off*****\r\n\n");
        }
        Relays[id - 1] = !Relays[id - 1];
        break;
    }
}
References id_to_gpio(), JDQ_ALL_OFF, JDQ_ALL_ON, JDQ_ERROR, microhil_all_channels_off(), microhil_all_channels_on(), microhil_delay_ms(), microhil_write_pwm(), put_pixel(), Relays, and urgb_u32().
Referenced by main().
microhil_init()
void microhil_init ()
Definition at line 31 of file microhil_channel_init.c.
{
    stdio_init_all();
    stdio_usb_init();
    gpio_init(JDQ1);
    gpio_init(JDQ2);
    gpio_init(JDQ3);
    gpio_init(JDQ4);
    gpio_init(JDQ5);
    gpio_init(JDQ6);
    gpio_init(JDQ7);
    gpio_init(JDQ8);
    gpio_set_dir(JDQ1, GPIO_OUT);
    gpio_set_dir(JDQ2, GPIO_OUT);
    gpio_set_dir(JDQ3, GPIO_OUT);
    gpio_set_dir(JDQ4, GPIO_OUT);
    gpio_set_dir(JDQ5, GPIO_OUT);
    gpio_set_dir(JDQ6, GPIO_OUT);
    gpio_set_dir(JDQ7, GPIO_OUT);
    gpio_set_dir(JDQ8, GPIO_OUT);
    PIO pio = pio0;
    int sm = 0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, sm, offset, PIN_TX, 800000, true);
    gpio_set_function(6, GPIO_FUNC_PWM);
    slice_num = pwm_gpio_to_slice_num(6);
    pwm_set_wrap(slice_num, 500);
    pwm_set_chan_level(slice_num, PWM_CHAN_A, 1);
    pwm_set_clkdiv(slice_num, 50);
    pwm_set_enabled(slice_num, true);
    put_pixel(urgb_u32(0, 0, 0)); // RGB
    // microhil_write_pwm(80); //buzzer
}
References JDQ1, JDQ2, JDQ3, JDQ4, JDQ5, JDQ6, JDQ7, JDQ8, PIN_TX, put_pixel(), slice_num, urgb_u32(), ws2812_program, and ws2812_program_init().
Referenced by main().
microhil_write_pwm()
void microhil_write_pwm (uint8_t value)
Parameters
value
Definition at line 45 of file microhil_channel_utils.c.
{
    if (value < 0 || value > 100)
    {
        printf("microhil_write_pwm Error \r\n");
    }
    else
    {
        pwm_set_chan_level(slice_num, PWM_CHAN_A, value);
    }
}
References slice_num.
Referenced by microhil_all_channels_on(), and microhil_channel_switch().
put_pixel()
void put_pixel (uint32_t pixel_grb)
Parameters
pixel_grb
pixel_grb
Definition at line 24 of file microhil_channel_utils.c.
{
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().
urgb_u32()
uint32_t urgb_u32 (uint8_t r, uint8_t g, uint8_t b)
Parameters
r
g
b
Returns
Definition at line 35 of file microhil_channel_utils.c.
{
    return ((uint32_t)(r) << 8) |
           ((uint32_t)(g) << 16) |
           (uint32_t)(b);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().
Variable Documentation
Relays
unsigned char Relays[8] extern
Definition at line 23 of file microhil_channel_init.c.
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), and microhil_channel_switch().