microhil-base: src/channel/channel_init.c File Reference
channel_init.c File Reference
#include "pico/stdio_usb.h"
#include "io_config.h"
#include "channel_info.h"
#include "channel_error.h"
#include "channel.h"
Functions
bool microhil_init ()
Global device initialization.
Function Documentation
microhil_init()
bool microhil_init ()
Global device initialization.
Returns
true for success else false
Performs initialization for stdio types
Disables convertion of LF to CR
Failed to perform initialization for stdio types
Performs initialization for stdio usb
Failed to perform initialization for stdio usb
Performs initialization for RELAY chanels
Failed to perform initialization for RELAY channels
Performs initialization for PIO state machine
Failed to perform initialization for PIO
Performs initialization for BUZZER
Failed to perform initialization for BUZZER
Buzzer notification
Led notification
Definition at line 28 of file channel_init.c.
{
    bool status = false;
    status = stdio_init_all();
    stdio_set_translate_crlf(&stdio_usb, false);
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_STDIO_DONE);
    status = stdio_usb_init();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_USB_DONE);
    status = microhil_init_relay();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_RELAY_DONE);
    status = microhil_pio_init();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_PIO_DONE);
    status = microhil_init_buzzer();
    if (!status)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_INIT_FAILED);
        return status;
    }
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_BUZZER_DONE);
    microhil_write_buzzer(true);
    microhil_write_pixel(0, 0, 0);
    printf("%s %s\n", MICROHIL_CHANNEL_INFO, MICROHIL_INIT_DONE);
    return status;
}
References MICROHIL_BUZZER_DONE, MICROHIL_CHANNEL_ERROR, MICROHIL_CHANNEL_INFO, microhil_init_buzzer(), MICROHIL_INIT_DONE, MICROHIL_INIT_FAILED, microhil_init_relay(), MICROHIL_PIO_DONE, microhil_pio_init(), MICROHIL_RELAY_DONE, MICROHIL_STDIO_DONE, MICROHIL_USB_DONE, microhil_write_buzzer(), and microhil_write_pixel().
Referenced by main().