microhildesk: MHConfig Class Reference
MHConfig Class Reference
MHConfig class is implementation for configuration mechanism.
#include <microhil_config.h>
Public Member Functions
MHConfig ()
MHConfig constructor.
~MHConfig () noexcept=default
MHConfig destructor.
SigLogConfig LogConfigLoaded () final
Signal for loaded log configuration.
SigSerialConfig SerialConfigLoaded () final
Signal for loaded serial configuration.
bool isPreValid () const final
Checks is pre-validation state (existing configuration)
bool load () final
Loads configuration.
bool store () final
Stores configuration.
bool validate () final
Validates configuration (existing all expected parameters)
void setDevice (const UString &device) final
Sets serial device file path to configuration.
UString getDevice () const final
Gets serial device file path from configuration.
void setBaudRate (const int baudRate) final
Sets baud-rate for serial port to configuration.
int getBaudRate () final
Gets baud-rate for serial port from configuration.
void setDataBits (const int dataBits) final
Sets data-bits for the serial port to configuration.
int getDataBits () final
Gets data-bits for the serial port from configuration.
void setParity (const int parity) final
Sets parity for the serial port to configuration.
UString getParity () const final
Gets parity for the serial port from configuration.
void setStopBits (const int stopBits) final
Sets stop-bits for the serial port to configuration.
int getStopBits () final
Gets stop-bits for serial port from configuration.
void setLogLevel (const int level) final
Sets log level.
UString getLogLevel () const final
Gets log level.
void setLogPath (const UString &path) final
Sets log path.
UString getLogPath () const final
Gets log path.
int parityUnicodeStringToInt (const UString &parity)
Converts parity to integer format (from config file)
Private Member Functions
void setPreValid (bool configValid) final
Sets pre-validation state (existing configuration)
bool checkConfigPath () const
Checks existence of configuration file.
UString logLevelToUnicodeString (const int logLevel)
Converts integer log level to string format.
int logLevelStringToInt (const UString &level)
Converts log level in strong format to integer.
int intToBaudRate (int baudRate)
Processes and prepares baud-rate (to config file)
int baudRateToInt (int baudRate)
Processes and prepares baud-rate (from config file)
int dataBitsToInt (int dataBits)
Processes and prepares data-bits (from config file)
int intToDataBits (int dataBits)
Converts combobox index to data-bits (to config file)
UString parityToUnicodeString (const int parity)
Converts integer parity to string format (to config file)
int stopBitsToInt (int stopBits)
Converts stop-bits to integer (from config file)
int intToStopBits (int stopBits)
Converts combobox index to data-bits (to config file)
bool validateLogSettings ()
Validates log configuration (existing expected parameters)
bool validateSerialSettings ()
Validates serial configuration (existing expected parameters)
Private Attributes
std::string m_homePath {}
Configuration home directory path.
std::string m_configFilePath {}
Configuration file path.
bool m_configPreValidate {false}
Pre-validation flag for checking configuration.
Glib::KeyFile m_config {}
Configuration instance.
SigLogConfig m_logConfig {}
Signal for loaded log configuration from file.
SigSerialConfig m_serialConfig {}
Signal for loaded serial configuration from file.
Detailed Description
MHConfig class is implementation for configuration mechanism.
Definition at line 26 of file microhil_config.h.
Constructor & Destructor Documentation
MHConfig()
MHConfig::MHConfig () explicit
MHConfig constructor.
Pre-validation of configuration path
Definition at line 47 of file microhil_config.cc.
    : m_homePath{Glib::get_home_dir() + kHomeDirName}
    , m_configFilePath{m_homePath + kConfigFileName}
{
    setPreValid(checkConfigPath());
}
References checkConfigPath(), and setPreValid().
~MHConfig()
MHConfig::~MHConfig () inline default noexcept
MHConfig destructor.
Member Function Documentation
baudRateToInt()
int MHConfig::baudRateToInt (int baudRate) private virtual
Processes and prepares baud-rate (from config file)
Parameters
baudRate represents baud-rate from config file
Returns
index for combobox
Converts baud-rate to index item for combobox
Implements IMHConfig.
Definition at line 72 of file microhil_config_serial_utils.cc.
{
    switch (baudRate)
    {
    case 110:
        return 0;
    case 300:
        return 1;
    case 600:
        return 2;
    case 1200:
        return 3;
    case 2400:
        return 4;
    case 4800:
        return 5;
    case 9600:
        return 6;
    case 14400:
        return 7;
    case 19200:
        return 8;
    case 38400:
        return 9;
    case 57600:
        return 10;
    case 115200:
        return 11;
    case 128000:
        return 12;
    case 256000:
        return 13;
    }
    return 115200;
}
Referenced by getBaudRate().
checkConfigPath()
bool MHConfig::checkConfigPath () const private virtual
Checks existence of configuration file.
Returns
status true for existing configuration else false
Checks home directory /home/<username>/.microhil/
Failed to create home configuration directory
Checks config file in case of missing generate new with default setup Configuration file location: /home/<username>/.microhil/config
Implements IMHConfig.
Definition at line 122 of file microhil_config.cc.
{
    std::filesystem::directory_entry homeDirEntry{m_homePath};
    const auto homeDirExists = homeDirEntry.exists();
    if (!homeDirExists)
    {
        if (!std::filesystem::create_directory(m_homePath))
        {
            return false;
        }
    }
    const auto configFileExists = std::filesystem::exists(m_configFilePath);
    if (!configFileExists)
    {
        std::ofstream defaultConfig(m_configFilePath);
        for (int i = 0; i < kConfigLength; i++)
        {
            defaultConfig << kConfigSerialDefault[i] << "\n";
        }
        defaultConfig.close();
    }
    return true;
}
References m_configFilePath, and m_homePath.
Referenced by MHConfig().
dataBitsToInt()
int MHConfig::dataBitsToInt (int dataBits) private virtual
Processes and prepares data-bits (from config file)
Parameters
dataBits represents data-bits from config file
Returns
index for combobox
Pre-process data-bits to index item of combobox
Implements IMHConfig.
Definition at line 150 of file microhil_config_serial_utils.cc.
{
    return (dataBits - kConfigDataBitsOffset);
}
References dataBits.
Referenced by getDataBits().
getBaudRate()
int MHConfig::getBaudRate () final virtual
Gets baud-rate for serial port from configuration.
Returns
integer value for serial port baud-rate
Gets the serial port baud-rate from configuration
Pre-process baud-rate from configuration file
Implements IMHConfig.
Definition at line 73 of file microhil_config_serial.cc.
{
    auto baudRate = m_config.get_integer(kConfigSerial, kConfigBaudRate);
    return baudRateToInt(baudRate);
}
References baudRateToInt(), and m_config.
Referenced by load().
getDataBits()
int MHConfig::getDataBits () final virtual
Gets data-bits for the serial port from configuration.
Returns
integer value for data-bits for charachter
Gets the serial port data-bits from configuration
Pre-process data-bits from configuration file
Implements IMHConfig.
Definition at line 95 of file microhil_config_serial.cc.
{
    auto dataBits = m_config.get_integer(kConfigSerial, kConfigDataBits);
    return dataBitsToInt(dataBits);
}
References dataBits, dataBitsToInt(), and m_config.
Referenced by load().
getDevice()
UString MHConfig::getDevice () const final virtual
Gets serial device file path from configuration.
Returns
file path for the serial device
Gets the serial port device from configuration
Implements IMHConfig.
Definition at line 55 of file microhil_config_serial.cc.
{
    return m_config.get_string(kConfigSerial, kConfigDevice);
}
References m_config.
Referenced by load().
getLogLevel()
UString MHConfig::getLogLevel () const final virtual
Gets log level.
Returns
log level
Gets log level from configuration
Implements IMHConfig.
Definition at line 47 of file microhil_config_log.cc.
{
    return m_config.get_string(kConfigLog, kConfigLevel);
}
References m_config.
Referenced by load().
getLogPath()
UString MHConfig::getLogPath () const final virtual
Gets log path.
Returns
log path
Gets log file path from configuration
Implements IMHConfig.
Definition at line 61 of file microhil_config_log.cc.
{
    return m_config.get_string(kConfigLog, kConfigFile);
}
References m_config.
Referenced by load().
getParity()
UString MHConfig::getParity () const final virtual
Gets parity for the serial port from configuration.
Returns
parity type for the serial port
Gets the serial port parity from configuration
Implements IMHConfig.
Definition at line 117 of file microhil_config_serial.cc.
{
    return m_config.get_string(kConfigSerial, kConfigParity);
}
References m_config.
Referenced by load().
getStopBits()
int MHConfig::getStopBits () final virtual
Gets stop-bits for serial port from configuration.
Returns
integer number of stop-bits for the serial port
Gets the serial port stop-bits from configuration
Pre-process stop-bits from configuration file
Implements IMHConfig.
Definition at line 135 of file microhil_config_serial.cc.
{
    auto stopBits = (int)m_config.get_integer(kConfigSerial, kConfigStopBits);
    return stopBitsToInt(stopBits);
}
References m_config, stopBits, and stopBitsToInt().
Referenced by load().
intToBaudRate()
int MHConfig::intToBaudRate (int baudRate) private virtual
Processes and prepares baud-rate (to config file)
Parameters
baudRate represents baud-rate for serial port (combobox index)
Returns
baud-rate for the serial port in integer format
Converts index item of combobox to baud-rate
Implements IMHConfig.
Definition at line 111 of file microhil_config_serial_utils.cc.
{
    switch (baudRate)
    {
    case 0:
        return 110;
    case 1:
        return 300;
    case 2:
        return 600;
    case 3:
        return 1200;
    case 4:
        return 2400;
    case 5:
        return 4800;
    case 6:
        return 9600;
    case 7:
        return 14400;
    case 8:
        return 19200;
    case 9:
        return 38400;
    case 10:
        return 57600;
    case 11:
        return 115200;
    case 12:
        return 128000;
    case 13:
        return 256000;
    }
    return 115200;
}
Referenced by setBaudRate().
intToDataBits()
int MHConfig::intToDataBits (int dataBits) private virtual
Converts combobox index to data-bits (to config file)
Parameters
dataBits represents data-bits for serial port (index combobox)
Returns
data-bits for the serial port in integer format
Pre-process index item of combobox to data-bits
Implements IMHConfig.
Definition at line 157 of file microhil_config_serial_utils.cc.
{
    return (dataBits + kConfigDataBitsOffset);
}
References dataBits.
Referenced by setDataBits().
intToStopBits()
int MHConfig::intToStopBits (int stopBits) private virtual
Converts combobox index to data-bits (to config file)
Parameters
dataBits represents data-bits index from combobox
Returns
data-bits in integer format
Pre-process index item from combobox to stop-bits
Implements IMHConfig.
Definition at line 221 of file microhil_config_serial_utils.cc.
{
    return (stopBits + kConfigStopBitsOffset);
}
References stopBits.
Referenced by setStopBits().
isPreValid()
bool MHConfig::isPreValid () const final virtual
Checks is pre-validation state (existing configuration)
Returns
status true for success pre-validation else false
Gets pre-validation status
Implements IMHConfig.
Definition at line 166 of file microhil_config.cc.
{
    return m_configPreValidate;
};
References m_configPreValidate.
Referenced by validate().
load()
bool MHConfig::load () final virtual
Loads configuration.
Returns
status true for success load configuration else false
Load configuration from file
Validation of loaded configuration
Configuration file corrupted
Emits signal for loaded log configuration
Emits signal for loaded serial configuration
Implements IMHConfig.
Definition at line 56 of file microhil_config.cc.
{
    auto loadedConfig = m_config.load_from_file(m_configFilePath);
    auto validatedConfig = validate();
    if (!loadedConfig || !validatedConfig)
    {
        return false;
    }
    auto logPath = getLogPath();
    auto logLevel = logLevelStringToInt(getLogLevel());
    m_logConfig.emit(logPath, logLevel);
    VecUInt serialParams{};
    serialParams.push_back(getBaudRate());
    serialParams.push_back(getDataBits());
    serialParams.push_back(parityUnicodeStringToInt(getParity()));
    serialParams.push_back(getStopBits());
    auto device = getDevice();
    m_serialConfig.emit(device, serialParams);
    return true;
}
References getBaudRate(), getDataBits(), getDevice(), getLogLevel(), getLogPath(), getParity(), getStopBits(), logLevelStringToInt(), m_config, m_configFilePath, m_logConfig, m_serialConfig, parityUnicodeStringToInt(), and validate().
LogConfigLoaded()
SigLogConfig MHConfig::LogConfigLoaded () final virtual
Signal for loaded log configuration.
Returns
Signal for loaded log configuration
Signal for tracking load configuration process (log section)
Implements IMHConfig.
Definition at line 21 of file microhil_config_signals.cc.
{
    return m_logConfig;
}
References m_logConfig.
logLevelStringToInt()
int MHConfig::logLevelStringToInt (const UString & level) private virtual
Converts log level in strong format to integer.
Parameters
level represents log level in string format
Returns
log level in integer format
Implements IMHConfig.
Definition at line 67 of file microhil_config_log_utils.cc.
{
    if (level == kConfigLevelWarning)
    {
        return kConfigLevelWarningId;
    }
    if (level == kConfigLevelError)
    {
        return kConfigLevelErrorId;
    }
    return kConfigLevelInfoId;
}
Referenced by load().
logLevelToUnicodeString()
UString MHConfig::logLevelToUnicodeString (const int logLevel) private virtual
Converts integer log level to string format.
Parameters
logLevel represents log level in integer format
Returns
string format of log level
Converts integer log level to scopped enumerator class
Implements IMHConfig.
Definition at line 48 of file microhil_config_log_utils.cc.
{
    auto logLevelType = static_cast<LogLevelConfig>(logLevel);
    switch (logLevelType)
    {
    case LogLevelConfig::MICROHIL_INFO_CONFIG:
        return kConfigLevelInfo;
    case LogLevelConfig::MICROHIL_WARNING_CONFIG:
        return kConfigLevelWarning;
    case LogLevelConfig::MICROHIL_ERROR_CONFIG:
        return kConfigLevelError;
    }
    return kConfigLevelInfo;
}
References MICROHIL_ERROR_CONFIG, MICROHIL_INFO_CONFIG, and MICROHIL_WARNING_CONFIG.
Referenced by setLogLevel().
parityToUnicodeString()
UString MHConfig::parityToUnicodeString (const int parity) private virtual
Converts integer parity to string format (to config file)
Parameters
parity represents index combobox
Returns
string format of parity in string format
Converts integer parity to scopped enumerator class
Implements IMHConfig.
Definition at line 164 of file microhil_config_serial_utils.cc.
{
    auto parityPrepared = static_cast<ParityConfig>(parity);
    switch (parityPrepared)
    {
    case ParityConfig::MICROHIL_NONE_CONFIG:
        return kConfigParityNone;
    case ParityConfig::MICROHIL_ODD_CONFIG:
        return kConfigParityOdd;
    case ParityConfig::MICROHIL_EVEN_CONFIG:
        return kConfigParityEven;
    case ParityConfig::MICROHIL_MARK_CONFIG:
        return kConfigParityMark;
    case ParityConfig::MICROHIL_SPACE_CONFIG:
        return kConfigParitySpace;
    }
    return kConfigParityNone;
}
References MICROHIL_EVEN_CONFIG, MICROHIL_MARK_CONFIG, MICROHIL_NONE_CONFIG, MICROHIL_ODD_CONFIG, MICROHIL_SPACE_CONFIG, and parity.
Referenced by setParity().
parityUnicodeStringToInt()
int MHConfig::parityUnicodeStringToInt (const UString & parity) virtual
Converts parity to integer format (from config file)
Parameters
parity represents parity in string format (from config file)
Returns
parity in integer format (to combobox index)
Converts string format of parity to index item for combobox
Implements IMHConfig.
Definition at line 187 of file microhil_config_serial_utils.cc.
{
    if (parity == kConfigParityOdd)
    {
        return kConfigParityOddId;
    }
    if (parity == kConfigParityEven)
    {
        return kConfigParityEvenId;
    }
    if (parity == kConfigParityMark)
    {
        return kConfigParityMarkId;
    }
    if (parity == kConfigParitySpace)
    {
        return kConfigParitySpaceId;
    }
    return kConfigParityNoneId;
}
References parity.
Referenced by load().
SerialConfigLoaded()
SigSerialConfig MHConfig::SerialConfigLoaded () final virtual
Signal for loaded serial configuration.
Returns
Signal for loaded serial configuration
Signal for tracking load configuration process (serial section)
Implements IMHConfig.
Definition at line 28 of file microhil_config_signals.cc.
{
    return m_serialConfig;
}
References m_serialConfig.
setBaudRate()
void MHConfig::setBaudRate (const int baudRate) final virtual
Sets baud-rate for serial port to configuration.
Parameters
baudRate represents baud-rate for the serial port
Pre-process baud-rate for configuration file
Sets the serial port baud-rate to configuration
Implements IMHConfig.
Definition at line 62 of file microhil_config_serial.cc.
{
    auto baudRatePrepared = intToBaudRate(baudRate);
    m_config.set_integer(kConfigSerial, kConfigBaudRate, baudRatePrepared);
}
References intToBaudRate(), and m_config.
setDataBits()
void MHConfig::setDataBits (const int dataBits) final virtual
Sets data-bits for the serial port to configuration.
Parameters
dataBits represents data-bits for the serial port
Pre-process data-bits for configuration file
Sets the serial port data-bits to configuration
Implements IMHConfig.
Definition at line 84 of file microhil_config_serial.cc.
{
    auto dataBitsPrepared = intToDataBits(dataBits);
    m_config.set_integer(kConfigSerial, kConfigDataBits, dataBitsPrepared);
}
References dataBits, intToDataBits(), and m_config.
setDevice()
void MHConfig::setDevice (const UString & device) final virtual
Sets serial device file path to configuration.
Parameters
device represents file path for the serial device
Sets the serial port device to configuration
Implements IMHConfig.
Definition at line 48 of file microhil_config_serial.cc.
{
    m_config.set_string(kConfigSerial, kConfigDevice, device);
}
References m_config.
setLogLevel()
void MHConfig::setLogLevel (const int level) final virtual
Sets log level.
Parameters
level represents log level for log settings
Converts integer log level to string format
Sets log level to configuration
Implements IMHConfig.
Definition at line 36 of file microhil_config_log.cc.
{
    auto logLevel = logLevelToUnicodeString(level);
    m_config.set_string(kConfigLog, kConfigLevel, logLevel);
}
References logLevelToUnicodeString(), and m_config.
setLogPath()
void MHConfig::setLogPath (const UString & path) final virtual
Sets log path.
Parameters
path represents log file path for log messages
Sets log file path to configuration
Implements IMHConfig.
Definition at line 54 of file microhil_config_log.cc.
{
    m_config.set_string(kConfigLog, kConfigFile, path);
}
References m_config.
setParity()
void MHConfig::setParity (const int parity) final virtual
Sets parity for the serial port to configuration.
Parameters
parity represents parity for the serial port
Pre-process parity for configuration file
Sets the serial port parity to configuration
Implements IMHConfig.
Definition at line 106 of file microhil_config_serial.cc.
{
    auto parityPrepared = parityToUnicodeString(parity);
    m_config.set_string(kConfigSerial, kConfigParity, parityPrepared);
}
References m_config, parity, and parityToUnicodeString().
setPreValid()
void MHConfig::setPreValid (bool configValid) final private virtual
Sets pre-validation state (existing configuration)
Parameters
configValid represents indicator for existing configuration
Sets pre-validation status
Implements IMHConfig.
Definition at line 159 of file microhil_config.cc.
{
    m_configPreValidate = configValid;
}
References m_configPreValidate.
Referenced by MHConfig().
setStopBits()
void MHConfig::setStopBits (const int stopBits) final virtual
Sets stop-bits for the serial port to configuration.
Parameters
stopBits represents stop-bits for the serial port
Pre-process stop-bits for configuration file
Sets the serial port stop-bits to configuration
Implements IMHConfig.
Definition at line 124 of file microhil_config_serial.cc.
{
    const auto stopBitsPrepared = intToStopBits(stopBits);
    m_config.set_integer(kConfigSerial, kConfigStopBits, stopBitsPrepared);
}
References intToStopBits(), m_config, and stopBits.
stopBitsToInt()
int MHConfig::stopBitsToInt (int stopBits) private virtual
Converts stop-bits to integer (from config file)
Parameters
dataBits represents data-bits from config file
Returns
stop-bits in integer format (index combobox)
Pre-process stop-bits to index item for combobox
Implements IMHConfig.
Definition at line 214 of file microhil_config_serial_utils.cc.
{
    return (stopBits - kConfigStopBitsOffset);
}
References stopBits.
Referenced by getStopBits().
store()
bool MHConfig::store () final virtual
Stores configuration.
Returns
status true for success store configuration else false
Stores configuration to file
Implements IMHConfig.
Definition at line 93 of file microhil_config.cc.
{
    return m_config.save_to_file(m_configFilePath);
}
References m_config, and m_configFilePath.
validate()
bool MHConfig::validate () final virtual
Validates configuration (existing all expected parameters)
Returns
status true for success configuration validation else false
Checking configuration parameters
Configuration file corrupted
Implements IMHConfig.
Definition at line 100 of file microhil_config.cc.
{
    if (!isPreValid())
    {
        return false;
    }
    auto configLogCheck = validateLogSettings();
    auto configSerialCheck = validateSerialSettings();
    if (!configLogCheck || !configSerialCheck)
    {
        return false;
    }
    return true;
}
References isPreValid(), validateLogSettings(), and validateSerialSettings().
Referenced by load().
validateLogSettings()
bool MHConfig::validateLogSettings () private virtual
Validates log configuration (existing expected parameters)
Returns
status true for success validation else false
Checks log configuration parameters from config file
Configuration file, log section corrupted
Implements IMHConfig.
Definition at line 68 of file microhil_config_log.cc.
{
    const auto configCheck =
        (m_config.has_key(kConfigLog, kConfigLevel) &&
         m_config.has_key(kConfigLog, kConfigFile));
    if (!configCheck)
    {
        return false;
    }
    return true;
}
References m_config.
Referenced by validate().
validateSerialSettings()
bool MHConfig::validateSerialSettings () private virtual
Validates serial configuration (existing expected parameters)
Returns
status true for success validation else false
Checking serial configuration parameters from config file
Configuration file, serial section corrupted
Implements IMHConfig.
Definition at line 146 of file microhil_config_serial.cc.
{
    const auto configCheck =
        (m_config.has_key(kConfigSerial, kConfigDevice) &&
         m_config.has_key(kConfigSerial, kConfigBaudRate) &&
         m_config.has_key(kConfigSerial, kConfigDataBits) &&
         m_config.has_key(kConfigSerial, kConfigParity) &&
         m_config.has_key(kConfigSerial, kConfigStopBits));
    if (!configCheck)
    {
        return false;
    }
    return true;
}
References m_config.
Referenced by validate().
Member Data Documentation
m_config
Glib::KeyFile MHConfig::m_config {} private
Configuration instance.
Definition at line 232 of file microhil_config.h.
Referenced by getBaudRate(), getDataBits(), getDevice(), getLogLevel(), getLogPath(), getParity(), getStopBits(), load(), setBaudRate(), setDataBits(), setDevice(), setLogLevel(), setLogPath(), setParity(), setStopBits(), store(), validateLogSettings(), and validateSerialSettings().
m_configFilePath
std::string MHConfig::m_configFilePath {} private
Configuration file path.
Definition at line 224 of file microhil_config.h.
Referenced by checkConfigPath(), load(), and store().
m_configPreValidate
bool MHConfig::m_configPreValidate {false} private
Pre-validation flag for checking configuration.
Definition at line 228 of file microhil_config.h.
Referenced by isPreValid(), and setPreValid().
m_homePath
std::string MHConfig::m_homePath {} private
Configuration home directory path.
Definition at line 220 of file microhil_config.h.
Referenced by checkConfigPath().
m_logConfig
SigLogConfig MHConfig::m_logConfig {} private
Signal for loaded log configuration from file.
Definition at line 236 of file microhil_config.h.
Referenced by load(), and LogConfigLoaded().
m_serialConfig
SigSerialConfig MHConfig::m_serialConfig {} private
Signal for loaded serial configuration from file.
Definition at line 240 of file microhil_config.h.
Referenced by load(), and SerialConfigLoaded().
The documentation for this class was generated from the following files:
config/microhil_config.h
config/microhil_config.cc
config/microhil_config_log.cc
config/microhil_config_log_utils.cc
config/microhil_config_serial.cc
config/microhil_config_serial_utils.cc
config/microhil_config_signals.cc