microhildesk: MicroHILController Class Reference
MicroHILController Class Reference
MicroHILController class declaration and definition.
#include <microhil_controller.h>
Public Member Functions
MicroHILController (MHSPtr< MicroHILModel > model, MHSPtr< MicroHILView > view)
MicroHILController constructor.
~MicroHILController ()=default
MicroHILController destructor.
void setEnabled (bool switchController) final
Enable controller (enable/disable communication)
bool isEnabled () const final
Check is controller enabled (is serial communication enabled)
Public Member Functions inherited from AbMicroHILController
virtual ~AbMicroHILController ()=default
AbMicroHILController destructor.
virtual void setEnabled (bool switchController)=0
Enable controller (enable/disable communication)
virtual bool isEnabled () const =0
Check is controller enabled (is serial communication enabled)
Private Member Functions
void mapping ()
Mapping views and backend (signals and slots)
void onLogSettingsChanged (MHString path, int level)
Slot for processing log settings changes.
void onLogSettingsLoaded (MHString path, int level)
Slot for processing log settings loaded.
void onSerialSettingsChanged (MHString dev, MHVecUInt params)
Slot for processing serial settings changes.
void onSerialSettingsLoaded (MHString dev, MHVecUInt params)
Slot for processing serial settings changes.
Private Attributes
bool m_enabled {false}
Enable/Disable state of controller.
MHSPtr< MicroHILModel > m_model {nullptr}
Model instance.
MHSPtr< MicroHILView > m_view {nullptr}
View instance.
MHUPtr< MicroHILConfig > m_config {nullptr}
Configuration instance.
MHUPtr< MicroHILLog > m_log {nullptr}
Log instance.
MHUPtr< MicroHILSerialCom > m_serial {nullptr}
Serial port instance.
Detailed Description
MicroHILController class declaration and definition.
Definition at line 30 of file microhil_controller.h.
Constructor & Destructor Documentation
MicroHILController()
MicroHILController::MicroHILController (MHSPtr< MicroHILModel > model, MHSPtr< MicroHILView > view)
MicroHILController constructor.
Parameters
model instance
view instance
Mapping views and backend (signals and slots)
Checking existance of configuration
Loading configuration from file
Setup log file destination from configuration
Setup log level from configuration
Definition at line 21 of file microhil_controller.cc.
 :
    m_model{model},
    m_view{view},
    m_config{MHmakeUPtr<MicroHILConfig>()},
    m_log{MHmakeUPtr<MicroHILLog>()},
    m_serial{MHmakeUPtr<MicroHILSerialCom>()}
{
    mapping();
    if(!m_config->isPreValid())
    {
        // TODO
        // Emit signal for error handler
    }
    if(!m_config->load())
    {
        // TODO
        // Emit signal for error handler
    }
    m_log->setFilePath(m_config->getLogPath());
    m_log->setLogLevel(m_config->getLogLevel());
    if(!m_log->open())
    {
        // TODO
        // Emit signal for error handler
    }
}
References m_config, m_log, and mapping().
~MicroHILController()
MicroHILController::~MicroHILController () default
MicroHILController destructor.
Member Function Documentation
isEnabled()
bool MicroHILController::isEnabled () const final virtual
Check is controller enabled (is serial communication enabled)
Returns
boolean status true for enabled else false
Implements AbMicroHILController.
Definition at line 70 of file microhil_controller.cc.
{
    return m_enabled;
}
References m_enabled.
mapping()
void MicroHILController::mapping () private
Mapping views and backend (signals and slots)
Map log settings signal from configuration with controller slot
Map serial settings signal from configuration with controller slot
Map log view signal with controller slot
Map serial view signal with controller slot
Definition at line 21 of file microhil_controller_map.cc.
{
    m_config->LogConfigLoaded().connect(
        sigc::mem_fun(*this, &MicroHILController::onLogSettingsLoaded)
    );
    m_config->SerialConfigLoaded().connect(
        sigc::mem_fun(*this, &MicroHILController::onSerialSettingsLoaded)
    );
    m_view->getLogSettings()->logSetupChanged().connect(
        sigc::mem_fun(*this, &MicroHILController::onLogSettingsChanged)
    );
    m_view->getSerialSettings()->serialSetupChanged().connect(
        sigc::mem_fun(*this, &MicroHILController::onSerialSettingsChanged)
    );
}
References m_config, m_view, onLogSettingsChanged(), onLogSettingsLoaded(), onSerialSettingsChanged(), and onSerialSettingsLoaded().
Referenced by MicroHILController().
onLogSettingsChanged()
void MicroHILController::onLogSettingsChanged (MHString path, int level) private
Slot for processing log settings changes.
Parameters
path is absolute path of log file
level is level for logging messages
Update the log configuration
Update log handler
Definition at line 22 of file microhil_controller_slots.cc.
{
    m_config->setLogPath(path);
    m_config->setLogLevel(level);
    if (!m_config->store())
    {
        // TODO error handler
        // TODO logging
    }
    m_log->close();
    m_log->setFilePath(path);
    m_log->setLogLevel(level);
    m_log->open();
    // TODO logging
}
References m_config, and m_log.
Referenced by mapping().
onLogSettingsLoaded()
void MicroHILController::onLogSettingsLoaded (MHString path, int level) private
Slot for processing log settings loaded.
Parameters
path is absolute path of log file
logLevel is level for logging messages
Definition at line 44 of file microhil_controller_slots.cc.
{
    m_view->getLogSettings()->logSettingsLoaded(path, level);
}
References m_view.
Referenced by mapping().
onSerialSettingsChanged()
void MicroHILController::onSerialSettingsChanged (MHString dev, MHVecUInt params) private
Slot for processing serial settings changes.
Parameters
dev file path for serial device
params set of serial parameters
Update the serial port configuration Note: Glib::KeyFile store only signed integers
Update serial handler
Definition at line 49 of file microhil_controller_slots.cc.
{
    m_config->setDevice(dev);
    m_config->setBaudRate(static_cast<int>(params[0]));
    m_config->setDataBits(static_cast<int>(params[1]));
    m_config->setParity(static_cast<int>(params[2]));
    m_config->setStopBits(static_cast<int>(params[3]));
    if (!m_config->store())
    {
        // TODO error handler
        // TODO logging
    }
    m_serial->close();
    // m_serial->setup(device, params);
    // TODO dialog message to open port?
    // m_serial->open();
    // TODO logging
}
References m_config, and m_serial.
Referenced by mapping().
onSerialSettingsLoaded()
void MicroHILController::onSerialSettingsLoaded (MHString dev, MHVecUInt params) private
Slot for processing serial settings changes.
Parameters
dev file path for serial device
params set of serial parameters
Definition at line 75 of file microhil_controller_slots.cc.
{
    m_view->getSerialSettings()->serialSettingsLoaded(dev, params);
}
References m_view.
Referenced by mapping().
setEnabled()
void MicroHILController::setEnabled (bool switchController) final virtual
Enable controller (enable/disable communication)
Parameters
switchController request value
Implements AbMicroHILController.
Definition at line 65 of file microhil_controller.cc.
{
    m_enabled = switchController;
}
References m_enabled.
Member Data Documentation
m_config
MHUPtr<MicroHILConfig> MicroHILController::m_config {nullptr} private
Configuration instance.
Definition at line 96 of file microhil_controller.h.
Referenced by mapping(), MicroHILController(), onLogSettingsChanged(), and onSerialSettingsChanged().
m_enabled
bool MicroHILController::m_enabled {false} private
Enable/Disable state of controller.
Definition at line 84 of file microhil_controller.h.
Referenced by isEnabled(), and setEnabled().
m_log
MHUPtr<MicroHILLog> MicroHILController::m_log {nullptr} private
Log instance.
Definition at line 100 of file microhil_controller.h.
Referenced by MicroHILController(), and onLogSettingsChanged().
m_model
MHSPtr<MicroHILModel> MicroHILController::m_model {nullptr} private
Model instance.
Definition at line 88 of file microhil_controller.h.
m_serial
MHUPtr<MicroHILSerialCom> MicroHILController::m_serial {nullptr} private
Serial port instance.
Definition at line 104 of file microhil_controller.h.
Referenced by onSerialSettingsChanged().
m_view
MHSPtr<MicroHILView> MicroHILController::m_view {nullptr} private
View instance.
Definition at line 92 of file microhil_controller.h.
Referenced by mapping(), onLogSettingsLoaded(), and onSerialSettingsLoaded().
The documentation for this class was generated from the following files:
controller/microhil_controller.h
controller/microhil_controller.cc
controller/microhil_controller_map.cc
controller/microhil_controller_slots.cc