microhil-device0: src/channel/channel_led.c File Reference
channel_led.c File Reference
#include "channel.h"
Functions
void put_pixel (uint32_t pixel_rgb)
Write 32-bit RGB value to PIO state machine.
uint32_t urgb_u32 (uint8_t red, uint8_t green, uint8_t blue)
Generate 32-bit RGB value.
Function Documentation
put_pixel()
void put_pixel (uint32_t pixel_rgb)
Write 32-bit RGB value to PIO state machine.
Parameters
pixel_rgb is 32-bit RGB value
Definition at line 24 of file channel_led.c.
{
    pio_sm_put_blocking(pio0, 0, pixel_rgb << 8u);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().
urgb_u32()
uint32_t urgb_u32 (uint8_t red, uint8_t green, uint8_t blue)
Generate 32-bit RGB value.
Parameters
red color value
green color value
blue color value
Returns
32-bit RGB value
Definition at line 35 of file channel_led.c.
{
    return ((uint32_t)(red) << 8) |
           ((uint32_t)(green) << 16) |
           (uint32_t)(blue);
}
Referenced by microhil_all_channels_off(), microhil_all_channels_on(), microhil_channel_switch(), and microhil_init().