microhildesk: Electux::App::EntryApplication Class Reference
Electux::App::EntryApplication Class Reference
Entry point for application and main application class.
#include <application.h>
Public Member Functions
EntryApplication ()
EntryApplication constructor.
~EntryApplication () override
EntryApplication destructor.
Static Public Member Functions
static Glib::RefPtr< EntryApplication > create ()
Creates a reference pointer to EntryApplication.
Protected Member Functions
void on_startup () override
Handler for the startup signal to initialize application.
void on_activate () override
Handler for the activate signal to show main application.
void on_shutdown () override
Handler for the shutdown signal to perform cleanup.
Private Member Functions
void mapping ()
Maps signal/slots for application views and actions.
void onActionSettings ()
On action settings create window for application settings.
void onActionDoc ()
On action doc create window for help documentation.
void onActionAbout ()
On action about create dialog for about application.
void onActionQuit ()
On action for quit application.
bool onHandleClose ()
On handle close main window.
void onSetupChanged (const SettingsSetup &setup)
Slot to handle setup signal change from settings window.
Private Attributes
Application Components
Instance of the configuration manager.
std::unique_ptr< IConfig > m_configManager
std::unique_ptr< AppHome > m_home
Main application window (home view).
std::unique_ptr< AppSettings > m_settings
Settings window view.
std::unique_ptr< AppHelp > m_help
Help and documentation window view.
std::unique_ptr< AppAbout > m_about
About dialog view.
Detailed Description
Entry point for application and main application class.
Manages the application lifecycle, signal mapping, and coordinates between the configuration manager and the various UI views.
Definition at line 60 of file application.h.
Constructor & Destructor Documentation
EntryApplication()
EntryApplication::EntryApplication () explicit
EntryApplication constructor.
EntryApplication constructor. Initializes the GTK application with the unique ID and sets the global application name for the desktop environment.
Definition at line 48 of file application.cc.
    : Gtk::Application(cApplicationId.data())
    , m_configManager(std::make_unique<ConfigManager>())
    , m_home(std::make_unique<AppHome>())
    , m_settings(std::make_unique<AppSettings>())
    , m_help(std::make_unique<AppHelp>())
    , m_about(std::make_unique<AppAbout>())
{
    Glib::set_application_name(cApplicationId.data());
}
Referenced by create().
~EntryApplication()
EntryApplication::~EntryApplication () override default
EntryApplication destructor.
Member Function Documentation
create()
Glib::RefPtr< EntryApplication > EntryApplication::create () static
Creates a reference pointer to EntryApplication.
Creates a reference pointer to EntryApplication. Uses Glib::RefPtr for memory-managed instance creation.
Returns
A Glib::RefPtr to the newly created application instance.
A Glib::RefPtr pointing to the EntryApplication instance.
Definition at line 69 of file application.cc.
{
    return Glib::make_refptr_for_instance<EntryApplication>(new EntryApplication());
}
References EntryApplication().
Referenced by main().
mapping()
void EntryApplication::mapping () private
Maps signal/slots for application views and actions.
Maps signals and actions for the application views and core logic.
This method handles the registration of keyboard accelerators, binds application actions to their respective handlers, and establishes connections between view signals (like settings changes) and application slots.
Definition at line 54 of file application_map.cc.
{
    // Sets application accelerator for quit action
    set_accel_for_action(cDetailedActionName.data(), cKeyboardAccelerator.data());
    // Maps application actions to their handlers
    add_action(cFileQuitActionName.data(), sigc::mem_fun(*this, &EntryApplication::onActionQuit));
    add_action(cOptionSettingsActionName.data(), sigc::mem_fun(*this, &EntryApplication::onActionSettings));
    add_action(cHelpDocActionName.data(), sigc::mem_fun(*this, &EntryApplication::onActionDoc));
    add_action(cHelpAboutActionName.data(), sigc::mem_fun(*this, &EntryApplication::onActionAbout));
    // Connects close request signal for AppHome window
    m_home->signal_close_request().connect(sigc::mem_fun(*this, &EntryApplication::onHandleClose), false);
    // Maps application setup signals to their handlers
    m_settings->setupChanged().connect(sigc::mem_fun(*this, &EntryApplication::onSetupChanged));
    m_home->controlChanged().connect(sigc::mem_fun(*this, &EntryApplication::onSetupChanged));
}
References m_home, m_settings, onActionAbout(), onActionDoc(), onActionQuit(), onActionSettings(), onHandleClose(), and onSetupChanged().
Referenced by on_startup().
on_activate()
void EntryApplication::on_activate () override protected
Handler for the activate signal to show main application.
Handler for the activate signal to show main application. Sets the visibility of the home window to true.
Definition at line 103 of file application_slots.cc.
{
    std::cout << "Activate application..." << std::endl;
    Gtk::Application::on_activate();
    // Sets visibility for AppHome window
    m_home->set_visible(true);
    std::cout << "Activate application done." << std::endl;
}
References m_home.
on_shutdown()
void EntryApplication::on_shutdown () override protected
Handler for the shutdown signal to perform cleanup.
Handler for the shutdown signal to perform cleanup. Stores current configuration to disk before closing.
Definition at line 118 of file application_slots.cc.
{
    std::cout << "Shutting down application..." << std::endl;
    m_configManager->store();
    Gtk::Application::on_shutdown();
}
References m_configManager.
on_startup()
void EntryApplication::on_startup () override protected
Handler for the startup signal to initialize application.
Sets up the application menubar, maps signals/slots, adds the main window, and synchronizes UI data with the loaded configuration.
Definition at line 58 of file application_slots.cc.
{
    std::cout << "Startup application..." << std::endl;
    Gtk::Application::on_startup();
    // Initialize configuration manager (load files, create defaults if needed)
    m_configManager->init();
    // Sets application menubar with File, Option and Help menu
    auto menu = Gio::Menu::create();
    auto submenu_file = Gio::Menu::create();
    submenu_file->append(cFileQuitLabel.data(), cFileQuitDetailedAction.data());
    menu->append_submenu(cFileLabel.data(), submenu_file);
    auto submenu_option = Gio::Menu::create();
    submenu_option->append(cOptionSettingsLabel.data(), cOptionSettingsDetailedAction.data());
    menu->append_submenu(cOptionLabel.data(), submenu_option);
    auto submenu_help = Gio::Menu::create();
    submenu_help->append(cHelpDocLabel.data(), cHelpDocDetailedAction.data());
    submenu_help->append(cHelpAboutLabel.data(), cHelpAboutDetailedAction.data());
    menu->append_submenu(cHelpLabel.data(), submenu_help);
    set_menubar(menu);
    // Maps signal/slots for application views and actions
    mapping();
    // Sets AppHome as toplevel window, add to the application window
    add_window(*m_home);
    // Updated settings widgets data based on loaded configuration
    SettingsSetup setup;
    *setup.m_config = m_configManager->getConfig();
    m_settings->setSettingsSetup(setup);
    m_settings->updateUiData();
    m_home->setControlSetup(setup);
    m_home->updateUiData();
    std::cout << "Startup application done." << std::endl;
}
References Electux::App::View::SettingsSetup::m_config, m_configManager, m_home, m_settings, and mapping().
onActionAbout()
void EntryApplication::onActionAbout () private
On action about create dialog for about application.
Opens the about application dialog.
Definition at line 166 of file application_slots.cc.
{
    m_about->show();
}
References m_about.
Referenced by mapping().
onActionDoc()
void EntryApplication::onActionDoc () private
On action doc create window for help documentation.
Opens the help/documentation window.
Definition at line 158 of file application_slots.cc.
{
    m_help->show();
}
References m_help.
Referenced by mapping().
onActionQuit()
void EntryApplication::onActionQuit () private
On action for quit application.
On action for quit application. Hides the main window, removes it from management, and quits the loop.
Definition at line 129 of file application_slots.cc.
{
    std::cout << "Quit application." << std::endl;
    m_home->set_visible(false);
    remove_window(*m_home);
    quit();
}
References m_home.
Referenced by mapping(), and onHandleClose().
onActionSettings()
void EntryApplication::onActionSettings () private
On action settings create window for application settings.
Opens the application settings window.
Definition at line 150 of file application_slots.cc.
{
    m_settings->show();
}
References m_settings.
Referenced by mapping().
onHandleClose()
bool EntryApplication::onHandleClose () private
On handle close main window.
Slot to handle closing the main window.
Returns
true if the signal has been handled.
Always false to allow the standard signal handling flow.
Definition at line 141 of file application_slots.cc.
{
    onActionQuit();
    return false;
}
References onActionQuit().
Referenced by mapping().
onSetupChanged()
void EntryApplication::onSetupChanged (const SettingsSetup & setup) private
Slot to handle setup signal change from settings window.
Slot to handle setup signal changes from the settings window.
Parameters
setup Settings setup parameters for application.
setup The new settings parameters to be saved.
Definition at line 175 of file application_slots.cc.
{
    m_configManager->setConfig(*setup.m_config);
    m_configManager->store();
}
References Electux::App::View::SettingsSetup::m_config, and m_configManager.
Referenced by mapping().
Member Data Documentation
m_about
std::unique_ptr<AppAbout> Electux::App::EntryApplication::m_about private
About dialog view.
Definition at line 145 of file application.h.
Referenced by onActionAbout().
m_configManager
std::unique_ptr<IConfig> Electux::App::EntryApplication::m_configManager private
Definition at line 137 of file application.h.
Referenced by on_shutdown(), on_startup(), and onSetupChanged().
m_help
std::unique_ptr<AppHelp> Electux::App::EntryApplication::m_help private
Help and documentation window view.
Definition at line 143 of file application.h.
Referenced by onActionDoc().
m_home
std::unique_ptr<AppHome> Electux::App::EntryApplication::m_home private
Main application window (home view).
Definition at line 139 of file application.h.
Referenced by mapping(), on_activate(), on_startup(), and onActionQuit().
m_settings
std::unique_ptr<AppSettings> Electux::App::EntryApplication::m_settings private
Settings window view.
Definition at line 141 of file application.h.
Referenced by mapping(), on_startup(), and onActionSettings().
The documentation for this class was generated from the following files:
application.h
application.cc
application_map.cc
application_slots.cc