microhildesk: MHViewAbout Class Reference
MHViewAbout Class Reference
MHViewAbout class declaration and definition.
#include <microhil_view_about.h>
Public Member Functions
MHViewAbout (BaseObjectType *object, MHRPtr< Gtk::Builder > const &ui)
MHViewAbout constructor.
~MHViewAbout ()=default
MHViewAbout destructor.
SigHideAbout hideAboutTriggered () final
Signal for Ok button.
void onHideAboutTriggered () final
Slot for processing Ok button (self hide AboutDialog)
Public Member Functions inherited from AbMHViewAbout
virtual ~AbMHViewAbout ()=default
AbMHViewAbout destructor.
virtual SigHideAbout hideAboutTriggered ()=0
Signal for Ok button.
virtual void onHideAboutTriggered ()=0
Slot for processing Ok button (self hide AboutDialog)
Private Member Functions
void mapping ()
Map Ok button (signal and slot)
Private Attributes
MHRPtr< Gtk::Builder > m_ui {nullptr}
UI builder instance.
MHRPtr< Gtk::Button > m_ok {nullptr}
Ok button for about view.
SigHideAbout m_hideAbout {}
Signal for Ok button (self hide AboutDialog)
Additional Inherited Members
Public Types inherited from AbMHViewAbout
using SigHideAbout = sigc::signal< void(bool)>
Signal type for Ok button (self hide AboutDialog signal)
Detailed Description
MHViewAbout class declaration and definition.
Definition at line 29 of file microhil_view_about.h.
Constructor & Destructor Documentation
MHViewAbout()
MHViewAbout::MHViewAbout (BaseObjectType * object, MHRPtr< Gtk::Builder > const & ui)
MHViewAbout constructor.
Parameters
object base object type
ui builder instance
Bind Ok button
Map Ok button (signal and slot)
Hide About dialog by default
Definition at line 28 of file microhil_view_about.cc.
                                                                             : Gtk::AboutDialog(object), m_ui{ui}
{
    m_ok = MHRPtr<Gtk::Button>::cast_dynamic(m_ui->get_object(kOkButtonId));
    mapping();
    this->hide();
}
References m_ok, m_ui, and mapping().
~MHViewAbout()
MHViewAbout::~MHViewAbout () default
MHViewAbout destructor.
Member Function Documentation
hideAboutTriggered()
MHViewAbout::SigHideAbout MHViewAbout::hideAboutTriggered () final virtual
Signal for Ok button.
Returns
Signal for clicked Ok button
Implements AbMHViewAbout.
Definition at line 21 of file microhil_view_about_signals.cc.
{
    return m_hideAbout;
}
References m_hideAbout.
mapping()
void MHViewAbout::mapping () private
Map Ok button (signal and slot)
Map Ok button (signal and slot)
Definition at line 21 of file microhil_view_about_map.cc.
{
    m_ok->signal_clicked().connect(sigc::mem_fun(*this, &MHViewAbout::onHideAboutTriggered));
}
References m_ok, and onHideAboutTriggered().
Referenced by MHViewAbout().
onHideAboutTriggered()
void MHViewAbout::onHideAboutTriggered () final virtual
Slot for processing Ok button (self hide AboutDialog)
Implements AbMHViewAbout.
Definition at line 21 of file microhil_view_about_slots.cc.
{
    this->hide();
}
Referenced by mapping().
Member Data Documentation
m_hideAbout
SigHideAbout MHViewAbout::m_hideAbout {} private
Signal for Ok button (self hide AboutDialog)
Definition at line 66 of file microhil_view_about.h.
Referenced by hideAboutTriggered().
m_ok
MHRPtr<Gtk::Button> MHViewAbout::m_ok {nullptr} private
Ok button for about view.
Definition at line 62 of file microhil_view_about.h.
Referenced by mapping(), and MHViewAbout().
m_ui
MHRPtr<Gtk::Builder> MHViewAbout::m_ui {nullptr} private
UI builder instance.
Definition at line 58 of file microhil_view_about.h.
Referenced by MHViewAbout().
The documentation for this class was generated from the following files:
view/about/microhil_view_about.h
view/about/microhil_view_about.cc
view/about/microhil_view_about_map.cc
view/about/microhil_view_about_signals.cc
view/about/microhil_view_about_slots.cc