microhildesk: Electux::App::Config::Config Class Reference
Electux::App::Config::Config Class Reference
Config class is implementation for configuration mechanism.
#include <config.h>
Public Member Functions
Config ()
Config constructor.
bool load () final
Loads configuration.
bool store () final
Stores configuration.
Private Attributes
std::string m_fileName
Configuration parameters and properties m_fileName - file name path for load/store configuration m_serialConfig - serial port configuration m_logConfig - log configuration.
Electux::App::Model::ModelSerial m_serialConfig
Electux::App::Model::ModelLog m_logConfig
Detailed Description
Config class is implementation for configuration mechanism.
Definition at line 29 of file config.h.
Constructor & Destructor Documentation
Config()
Config::Config () explicit
Config constructor.
Definition at line 37 of file config.cc.
               :
    m_fileName{Glib::build_filename(Glib::get_home_dir(), configFile)},
    m_serialConfig{ModelSerial()},
    m_logConfig{ModelLog()}
{
    std::cout << "Setup configuration file path: " << m_fileName << std::endl;
}
References m_fileName.
Member Function Documentation
load()
bool Config::load () final virtual
Loads configuration.
Returns
status true for success load configuration else false
Load serial configuration
Load log configuration
Implements Electux::App::Config::IConfig.
Definition at line 45 of file config.cc.
{
    std::ifstream file(m_fileName);
    std::cout << "Load configuration..." << std::endl;
    if (!file.is_open())
    {
        std::cerr << "Unable to open file: " << m_fileName << std::endl;
        return false;
    }
    std::string line;
    std::unordered_map<std::string, std::string> configMap;
    while (std::getline(file, line))
    {
        std::istringstream iss(line);
        std::string key, value;
        if (std::getline(iss, key, '=') && std::getline(iss, value))
        {
            if (!m_serialConfig.validateKey(key) && !m_logConfig.validateKey(key))
            {
                std::cerr << "Invalid configuration key: " << key << std::endl;
                return false;
            }
            configMap[key] = value;
        }
    }
    file.close();
    std::initializer_list<ModelSerial::ModelSerialKey> serialKeys = {
        ModelSerial::ModelSerialKey::Device,
        ModelSerial::ModelSerialKey::Baud,
        ModelSerial::ModelSerialKey::Data,
        ModelSerial::ModelSerialKey::Parity,
        ModelSerial::ModelSerialKey::Stop
    };
    for (const auto key : serialKeys)
    {
        auto serialKey = m_serialConfig.toString(key);
        m_serialConfig.add(serialKey, configMap[serialKey]);
    }
    auto logLevelKey = m_logConfig.toString(ModelLog::ModelLogKey::LogLevel);
    m_logConfig.add(logLevelKey, configMap[logLevelKey]);
    std::cout << "Load configuration done." << std::endl;
    return true;
}
References Electux::App::Model::Model::add(), m_fileName, m_logConfig, m_serialConfig, Electux::App::Model::ModelLog::toString(), Electux::App::Model::ModelSerial::toString(), Electux::App::Model::ModelLog::validateKey(), and Electux::App::Model::ModelSerial::validateKey().
store()
bool Config::store () final virtual
Stores configuration.
Returns
status true for success store configuration else false
Store serial configuration
Store log configuration
Implements Electux::App::Config::IConfig.
Definition at line 103 of file config.cc.
{
    std::ofstream file(m_fileName);
    std::cout << "Store configuration..." << std::endl;
    if (!file.is_open())
    {
        std::cerr << "Unable to open file: " << m_fileName << std::endl;
        return false;
    }
    std::initializer_list<ModelSerial::ModelSerialKey> serialKeys = {
        ModelSerial::ModelSerialKey::Device,
        ModelSerial::ModelSerialKey::Baud,
        ModelSerial::ModelSerialKey::Data,
        ModelSerial::ModelSerialKey::Parity,
        ModelSerial::ModelSerialKey::Stop
    };
    for (const auto key : serialKeys)
    {
        auto serialKey = m_serialConfig.toString(key);
        file << serialKey << "=" << m_serialConfig.getEntity(serialKey) << std::endl;
    }
    auto logLevelKey = m_logConfig.toString(ModelLog::ModelLogKey::LogLevel);
    file << logLevelKey << "=" << m_logConfig.getEntity(logLevelKey) << std::endl;
    file.close();
    std::cout << "Store configuration done." << std::endl;
    return true;
}
References Electux::App::Model::Model::getEntity(), m_fileName, m_logConfig, m_serialConfig, Electux::App::Model::ModelLog::toString(), and Electux::App::Model::ModelSerial::toString().
Member Data Documentation
m_fileName
std::string Electux::App::Config::Config::m_fileName private
Configuration parameters and properties m_fileName - file name path for load/store configuration m_serialConfig - serial port configuration m_logConfig - log configuration.
Definition at line 52 of file config.h.
Referenced by Config(), load(), and store().
m_logConfig
Electux::App::Model::ModelLog Electux::App::Config::Config::m_logConfig private
Definition at line 54 of file config.h.
Referenced by load(), and store().
m_serialConfig
Electux::App::Model::ModelSerial Electux::App::Config::Config::m_serialConfig private
Definition at line 53 of file config.h.
Referenced by load(), and store().
The documentation for this class was generated from the following files:
config/config.h
config/config.cc