microhildesk: MicroHILViewSerial Class Reference
MicroHILViewSerial Class Reference
MicroHILViewSerial class declaration and definition.
#include <microhil_view_serial.h>
Public Member Functions
MicroHILViewSerial (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
MicroHILViewSerial constructor.
~MicroHILViewSerial ()=default
MicroHILViewSerial destructor.
serialSetup serialSetupChanged () final
Signal for serial settings.
serialDevicePath serialFilePathChanged () final
Signal for device file path input.
void onSerialFilePathChanged () final
Slot for processing device file path input.
serialBaudRate serialBaudRateChanged () final
Signal for baud rate combobox.
void onSerialBaudRateChanged () final
Slot for processing baud rate combobox.
serialDataBits serialDataBitsChanged () final
Signal for data bits combobox.
void onSerialDataBitsChanged () final
Slot for processing data bits combobox.
serialParity serialParityChanged () final
Signal for parity combobox.
void onSerialParityChanged () final
Slot for processing parity combobox.
serialStopBits serialStopBitsChanged () final
Signal for stop bits combobox.
void onSerialStopBitsChanged () final
Slot for processing stop bits combobox.
cancelSerial cancelSerialTriggered () final
Signal for Cancel button.
okSerial okSerialTriggered () final
Signal for Ok button.
void onCancelSerialTriggered () final
Slot for processing Cancel button (dismiss)
void onOkSerialTriggered () final
Slot for processing Ok button (confirm)
Public Member Functions inherited from AbMicroHILViewSerial
virtual ~AbMicroHILViewSerial ()=default
AbMicroHILViewLog destructor.
virtual serialSetup serialSetupChanged ()=0
Signal for serial settings.
virtual serialDevicePath serialFilePathChanged ()=0
Signal for device file path input.
virtual void onSerialFilePathChanged ()=0
Slot for processing device file path input.
virtual serialBaudRate serialBaudRateChanged ()=0
Signal for baud rate combobox.
virtual void onSerialBaudRateChanged ()=0
Slot for processing baud rate combobox.
virtual serialDataBits serialDataBitsChanged ()=0
Signal for data bits combobox.
virtual void onSerialDataBitsChanged ()=0
Slot for processing data bits combobox.
virtual serialParity serialParityChanged ()=0
Signal for parity combobox.
virtual void onSerialParityChanged ()=0
Slot for processing parity combobox.
virtual serialStopBits serialStopBitsChanged ()=0
Signal for stop bits combobox.
virtual void onSerialStopBitsChanged ()=0
Slot for processing stop bits combobox.
virtual cancelSerial cancelSerialTriggered ()=0
Signal for Cancel button.
virtual okSerial okSerialTriggered ()=0
Signal for Ok button.
virtual void onCancelSerialTriggered ()=0
Slot for processing Cancel button (dismiss)
virtual void onOkSerialTriggered ()=0
Slot for processing Ok button (confirm)
Private Member Functions
void mapping ()
Map all widgets (signals and slots)
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui {nullptr}
UI builder instance.
Glib::RefPtr< Gtk::Entry > m_device {nullptr}
Set device file path.
Glib::RefPtr< Gtk::ComboBoxText > m_baudRate {nullptr}
Select baud rate.
Glib::RefPtr< Gtk::ComboBoxText > m_dataBits {nullptr}
Select data bits.
Glib::RefPtr< Gtk::ComboBoxText > m_parity {nullptr}
Select parity.
Glib::RefPtr< Gtk::ComboBoxText > m_stopBits {nullptr}
Select stop bits.
Glib::RefPtr< Gtk::Button > m_cancel {nullptr}
Dismiss button.
Glib::RefPtr< Gtk::Button > m_ok {nullptr}
Confirm button.
serialSetup m_serialSetup {}
ignal for serial settings
serialDevicePath m_serialDevicePath {}
Signal for device path input.
serialBaudRate m_serialBaudeRate {}
Signal for baud rate combobox.
serialDataBits m_serialDataBits {}
Signal for data bits combobox.
serialParity m_serialParity {}
Signal for parity combobox.
serialStopBits m_serialStopBits {}
Signal for stop bits combobox.
cancelSerial m_cancelSerial {}
Signal for Cancel button (dismiss)
okSerial m_okSerial {}
Signal for Ok button (confirm)
Additional Inherited Members
Public Types inherited from AbMicroHILViewSerial
using serialSetup = sigc::signal< void(Glib::ustring, unsigned int, unsigned int, unsigned int, unsigned int)>
Signal type for serial settings.
using serialDevicePath = sigc::signal< void(Glib::ustring)>
Signal type for serial device file path input.
using serialBaudRate = sigc::signal< void(int)>
Signal type for serial baud rate combobox.
using serialDataBits = sigc::signal< void(int)>
Signal type for serial data bits combobox.
using serialParity = sigc::signal< void(int)>
Signal type for serial parity combobox.
using serialStopBits = sigc::signal< void(int)>
Signal type for serial stop bits combobox.
using cancelSerial = sigc::signal< void(bool)>
Signal type for Cancel button.
using okSerial = sigc::signal< void(bool)>
Signal type for Ok button.
Detailed Description
MicroHILViewSerial class declaration and definition.
Definition at line 30 of file microhil_view_serial.h.
Constructor & Destructor Documentation
MicroHILViewSerial()
MicroHILViewSerial::MicroHILViewSerial (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
MicroHILViewSerial constructor.
Parameters
object base object instance
ui buider instance
Bind Log file path entry
Bind baud rate combobox
Bind data bits combobox
Bind parity combobox
Bind stop bits combobox
Bind Cancel button
Bind Ok button
Map all widgets (signals and slots)
Hide Serial Settings by default
Definition at line 52 of file microhil_view_serial.cc.
 : Gtk::Dialog(object), m_ui{ui}
{
    m_device = Glib::RefPtr<Gtk::Entry>::cast_dynamic(
        m_ui->get_object(kDevicePathId)
    );
    m_baudRate = Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
        m_ui->get_object(kBaudRateSelectorId)
    );
    m_dataBits = Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
        m_ui->get_object(kDataBitsSelectorId)
    );
    m_parity = Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
        m_ui->get_object(kParitySelectorId)
    );
    m_stopBits = Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
        m_ui->get_object(kStopBitsId)
    );
    m_cancel = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kCancelButtonId)
    );
    m_ok = Glib::RefPtr<Gtk::Button>::cast_dynamic(
        m_ui->get_object(kOkButtonId)
    );
    mapping();
    this->hide();
}
References m_baudRate, m_cancel, m_dataBits, m_device, m_ok, m_parity, m_stopBits, m_ui, and mapping().
~MicroHILViewSerial()
MicroHILViewSerial::~MicroHILViewSerial () default
MicroHILViewSerial destructor.
Member Function Documentation
cancelSerialTriggered()
MicroHILViewSerial::cancelSerial MicroHILViewSerial::cancelSerialTriggered () final virtual
Signal for Cancel button.
Returns
Signal for clicked Cancel button
Implements AbMicroHILViewSerial.
Definition at line 58 of file microhil_view_serial_signals.cc.
{
    return m_cancelSerial;
}
References m_cancelSerial.
mapping()
void MicroHILViewSerial::mapping () private
Map all widgets (signals and slots)
Map all widgets (signals and slots)
Definition at line 21 of file microhil_view_serial_map.cc.
{
    m_device->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onSerialFilePathChanged)
    );
    m_baudRate->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onSerialBaudRateChanged)
    );
    m_dataBits->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onSerialDataBitsChanged)
    );
    m_parity->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onSerialParityChanged)
    );
    m_stopBits->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onSerialStopBitsChanged)
    );
    m_cancel->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onCancelSerialTriggered)
    );
    m_ok->signal_clicked().connect(
        sigc::mem_fun(*this, &MicroHILViewSerial::onOkSerialTriggered)
    );
}
References m_baudRate, m_cancel, m_dataBits, m_device, m_ok, m_parity, m_stopBits, onCancelSerialTriggered(), onOkSerialTriggered(), onSerialBaudRateChanged(), onSerialDataBitsChanged(), onSerialFilePathChanged(), onSerialParityChanged(), and onSerialStopBitsChanged().
Referenced by MicroHILViewSerial().
okSerialTriggered()
MicroHILViewSerial::okSerial MicroHILViewSerial::okSerialTriggered () final virtual
Signal for Ok button.
Returns
Signal for clicked Ok button
Implements AbMicroHILViewSerial.
Definition at line 64 of file microhil_view_serial_signals.cc.
{
    return m_okSerial;
}
References m_okSerial.
onCancelSerialTriggered()
void MicroHILViewSerial::onCancelSerialTriggered () final virtual
Slot for processing Cancel button (dismiss)
Implements AbMicroHILViewSerial.
Definition at line 46 of file microhil_view_serial_slots.cc.
{
    this->hide();
}
Referenced by mapping().
onOkSerialTriggered()
void MicroHILViewSerial::onOkSerialTriggered () final virtual
Slot for processing Ok button (confirm)
Emit new serial settings
Implements AbMicroHILViewSerial.
Definition at line 51 of file microhil_view_serial_slots.cc.
{
    auto devicePath = m_device->get_text();
    auto baudRate = m_baudRate->get_active_row_number();
    auto dataBits = m_dataBits->get_active_row_number();
    auto parity = m_parity->get_active_row_number();
    auto stopBits = m_stopBits->get_active_row_number();
    m_serialSetup.emit(
        devicePath, baudRate, dataBits, parity, stopBits
    );
    this->hide();
}
References m_baudRate, m_dataBits, m_device, m_parity, m_serialSetup, and m_stopBits.
Referenced by mapping().
onSerialBaudRateChanged()
void MicroHILViewSerial::onSerialBaudRateChanged () final virtual
Slot for processing baud rate combobox.
Implements AbMicroHILViewSerial.
Definition at line 26 of file microhil_view_serial_slots.cc.
{
    // TODO
}
Referenced by mapping().
onSerialDataBitsChanged()
void MicroHILViewSerial::onSerialDataBitsChanged () final virtual
Slot for processing data bits combobox.
Implements AbMicroHILViewSerial.
Definition at line 31 of file microhil_view_serial_slots.cc.
{
    // TODO
}
Referenced by mapping().
onSerialFilePathChanged()
void MicroHILViewSerial::onSerialFilePathChanged () final virtual
Slot for processing device file path input.
Implements AbMicroHILViewSerial.
Definition at line 21 of file microhil_view_serial_slots.cc.
{
    // TODO
}
Referenced by mapping().
onSerialParityChanged()
void MicroHILViewSerial::onSerialParityChanged () final virtual
Slot for processing parity combobox.
Implements AbMicroHILViewSerial.
Definition at line 36 of file microhil_view_serial_slots.cc.
{
    // TODO
}
Referenced by mapping().
onSerialStopBitsChanged()
void MicroHILViewSerial::onSerialStopBitsChanged () final virtual
Slot for processing stop bits combobox.
Implements AbMicroHILViewSerial.
Definition at line 41 of file microhil_view_serial_slots.cc.
{
    // TODO
}
Referenced by mapping().
serialBaudRateChanged()
MicroHILViewSerial::serialBaudRate MicroHILViewSerial::serialBaudRateChanged () final virtual
Signal for baud rate combobox.
Returns
Signal for selected baud rate combobox
Implements AbMicroHILViewSerial.
Definition at line 34 of file microhil_view_serial_signals.cc.
{
    return m_serialBaudeRate;
}
References m_serialBaudeRate.
serialDataBitsChanged()
MicroHILViewSerial::serialDataBits MicroHILViewSerial::serialDataBitsChanged () final virtual
Signal for data bits combobox.
Returns
Signal for selected data bits combobox
Implements AbMicroHILViewSerial.
Definition at line 40 of file microhil_view_serial_signals.cc.
{
    return m_serialDataBits;
}
References m_serialDataBits.
serialFilePathChanged()
MicroHILViewSerial::serialDevicePath MicroHILViewSerial::serialFilePathChanged () final virtual
Signal for device file path input.
Returns
Signal for changed device file path entry
Implements AbMicroHILViewSerial.
Definition at line 28 of file microhil_view_serial_signals.cc.
{
    return m_serialDevicePath;
}
References m_serialDevicePath.
serialParityChanged()
MicroHILViewSerial::serialParity MicroHILViewSerial::serialParityChanged () final virtual
Signal for parity combobox.
Returns
Signal for selected parity combobox
Implements AbMicroHILViewSerial.
Definition at line 46 of file microhil_view_serial_signals.cc.
{
    return m_serialParity;
}
References m_serialParity.
serialSetupChanged()
MicroHILViewSerial::serialSetup MicroHILViewSerial::serialSetupChanged () final virtual
Signal for serial settings.
Returns
Signal for changed serial settings
Implements AbMicroHILViewSerial.
Definition at line 22 of file microhil_view_serial_signals.cc.
{
    return m_serialSetup;
}
References m_serialSetup.
serialStopBitsChanged()
MicroHILViewSerial::serialStopBits MicroHILViewSerial::serialStopBitsChanged () final virtual
Signal for stop bits combobox.
Returns
Signal for selected stop bits combobox
Implements AbMicroHILViewSerial.
Definition at line 52 of file microhil_view_serial_signals.cc.
{
    return m_serialStopBits;
}
References m_serialStopBits.
Member Data Documentation
m_baudRate
Glib::RefPtr<Gtk::ComboBoxText> MicroHILViewSerial::m_baudRate {nullptr} private
Select baud rate.
Definition at line 128 of file microhil_view_serial.h.
Referenced by mapping(), MicroHILViewSerial(), and onOkSerialTriggered().
m_cancel
Glib::RefPtr<Gtk::Button> MicroHILViewSerial::m_cancel {nullptr} private
Dismiss button.
Definition at line 144 of file microhil_view_serial.h.
Referenced by mapping(), and MicroHILViewSerial().
m_cancelSerial
cancelSerial MicroHILViewSerial::m_cancelSerial {} private
Signal for Cancel button (dismiss)
Definition at line 176 of file microhil_view_serial.h.
Referenced by cancelSerialTriggered().
m_dataBits
Glib::RefPtr<Gtk::ComboBoxText> MicroHILViewSerial::m_dataBits {nullptr} private
Select data bits.
Definition at line 132 of file microhil_view_serial.h.
Referenced by mapping(), MicroHILViewSerial(), and onOkSerialTriggered().
m_device
Glib::RefPtr<Gtk::Entry> MicroHILViewSerial::m_device {nullptr} private
Set device file path.
Definition at line 124 of file microhil_view_serial.h.
Referenced by mapping(), MicroHILViewSerial(), and onOkSerialTriggered().
m_ok
Glib::RefPtr<Gtk::Button> MicroHILViewSerial::m_ok {nullptr} private
Confirm button.
Definition at line 148 of file microhil_view_serial.h.
Referenced by mapping(), and MicroHILViewSerial().
m_okSerial
okSerial MicroHILViewSerial::m_okSerial {} private
Signal for Ok button (confirm)
Definition at line 180 of file microhil_view_serial.h.
Referenced by okSerialTriggered().
m_parity
Glib::RefPtr<Gtk::ComboBoxText> MicroHILViewSerial::m_parity {nullptr} private
Select parity.
Definition at line 136 of file microhil_view_serial.h.
Referenced by mapping(), MicroHILViewSerial(), and onOkSerialTriggered().
m_serialBaudeRate
serialBaudRate MicroHILViewSerial::m_serialBaudeRate {} private
Signal for baud rate combobox.
Definition at line 160 of file microhil_view_serial.h.
Referenced by serialBaudRateChanged().
m_serialDataBits
serialDataBits MicroHILViewSerial::m_serialDataBits {} private
Signal for data bits combobox.
Definition at line 164 of file microhil_view_serial.h.
Referenced by serialDataBitsChanged().
m_serialDevicePath
serialDevicePath MicroHILViewSerial::m_serialDevicePath {} private
Signal for device path input.
Definition at line 156 of file microhil_view_serial.h.
Referenced by serialFilePathChanged().
m_serialParity
serialParity MicroHILViewSerial::m_serialParity {} private
Signal for parity combobox.
Definition at line 168 of file microhil_view_serial.h.
Referenced by serialParityChanged().
m_serialSetup
serialSetup MicroHILViewSerial::m_serialSetup {} private
ignal for serial settings
Definition at line 152 of file microhil_view_serial.h.
Referenced by onOkSerialTriggered(), and serialSetupChanged().
m_serialStopBits
serialStopBits MicroHILViewSerial::m_serialStopBits {} private
Signal for stop bits combobox.
Definition at line 172 of file microhil_view_serial.h.
Referenced by serialStopBitsChanged().
m_stopBits
Glib::RefPtr<Gtk::ComboBoxText> MicroHILViewSerial::m_stopBits {nullptr} private
Select stop bits.
Definition at line 140 of file microhil_view_serial.h.
Referenced by mapping(), MicroHILViewSerial(), and onOkSerialTriggered().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILViewSerial::m_ui {nullptr} private
UI builder instance.
Definition at line 120 of file microhil_view_serial.h.
Referenced by MicroHILViewSerial().
The documentation for this class was generated from the following files:
view/settings/serial/microhil_view_serial.h
view/settings/serial/microhil_view_serial.cc
view/settings/serial/microhil_view_serial_map.cc
view/settings/serial/microhil_view_serial_signals.cc
view/settings/serial/microhil_view_serial_slots.cc