microhildesk: MHCommander Class Reference
MHCommander Class Reference
MHCommander class is implementation of command mechanism.
#include <microhil_commander.h>
Public Member Functions
MHCommander (SPtr< IMHCom > serial)
MHCommander constructor.
~MHCommander () noexcept=default
MHCommander destructor.
void executeCommand (const int id, const std::string &onoff) final
Executes microHIL command.
Private Member Functions
void getId ()
Gets identification of microHIL HW.
void getVersion ()
Gets version of microHIL FW.
void setChannel (const int id, const std::string &onoff)
Sets channel state.
void setAllChannel (const std::string &onoff)
Sets all channels.
Private Attributes
SPtr< IMHCom > m_serial {nullptr}
Serial port instance.
Detailed Description
MHCommander class is implementation of command mechanism.
Definition at line 26 of file microhil_commander.h.
Constructor & Destructor Documentation
MHCommander()
MHCommander::MHCommander (SPtr< IMHCom > serial) explicit
MHCommander constructor.
Definition at line 48 of file microhil_commander.cc.
    : m_serial{serial}
{
}
~MHCommander()
MHCommander::~MHCommander () inline default noexcept
MHCommander destructor.
Member Function Documentation
executeCommand()
void MHCommander::executeCommand (const int id, const std::string & onoff) final virtual
Executes microHIL command.
Parameters
id represents command identification
onoff represents command operation
Implements IMHCommander.
Definition at line 53 of file microhil_commander.cc.
{
    switch (id)
    {
    case 0:
        getId();
        break;
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
        setChannel(id, onoff);
        break;
    case 9:
        setAllChannel(onoff);
        break;
    case 10:
        getVersion();
        break;
    default:;
    }
}
References getId(), getVersion(), setAllChannel(), and setChannel().
getId()
void MHCommander::getId () private
Gets identification of microHIL HW.
Definition at line 80 of file microhil_commander.cc.
{
    std::string command = kId;
    const VecByte data(command.begin(), command.end());
    m_serial->write(data);
}
References m_serial.
Referenced by executeCommand().
getVersion()
void MHCommander::getVersion () private
Gets version of microHIL FW.
Definition at line 87 of file microhil_commander.cc.
{
    std::string command = kVersion;
    const VecByte data(command.begin(), command.end());
    m_serial->write(data);
}
References m_serial.
Referenced by executeCommand().
setAllChannel()
void MHCommander::setAllChannel (const std::string & onoff) private
Sets all channels.
Parameters
onoff represents command operation
Definition at line 106 of file microhil_commander.cc.
{
    std::string command;
    command.append(kChannelsBegin);
    command.append(onoff);
    command.append(kEnd);
    const VecByte data(command.begin(), command.end());
    m_serial->write(data);
}
References m_serial.
Referenced by executeCommand().
setChannel()
void MHCommander::setChannel (const int id, const std::string & onoff) private
Sets channel state.
Parameters
id represents command identification
onoff represents command operation
Definition at line 94 of file microhil_commander.cc.
{
    std::string command;
    command.append(kChannelBegin);
    command.append(std::to_string(id));
    command.append(kHash);
    command.append(onoff);
    command.append(kEnd);
    const VecByte data(command.begin(), command.end());
    m_serial->write(data);
}
References m_serial.
Referenced by executeCommand().
Member Data Documentation
m_serial
SPtr<IMHCom> MHCommander::m_serial {nullptr} private
Serial port instance.
Definition at line 65 of file microhil_commander.h.
Referenced by getId(), getVersion(), setAllChannel(), and setChannel().
The documentation for this class was generated from the following files:
commander/microhil_commander.h
commander/microhil_commander.cc