microhildesk: MicroHILView Class Reference
MicroHILView Class Reference
#include <microhil_view.h>
Public Member Functions
MicroHILView (BaseObjectType *object, Glib::RefPtr< Gtk::Builder > const &ui)
~MicroHILView ()=default
channel0Changed channel0IsChanged () final
channel1Changed channel1IsChanged () final
channel2Changed channel2IsChanged () final
channel3Changed channel3IsChanged () final
void onChannel0 () final
void onChannel1 () final
void onChannel2 () final
void onChannel3 () final
select0Changed channel0IsSelected () final
select1Changed channel1IsSelected () final
select2Changed channel2IsSelected () final
select3Changed channel3IsSelected () final
void onChannel0TypeSelected () final
void onChannel1TypeSelected () final
void onChannel2TypeSelected () final
void onChannel3TypeSelected () final
channel0Toggled channel0IsToggled () final
channel1Toggled channel1IsToggled () final
channel2Toggled channel2IsToggled () final
channel3Toggled channel3IsToggled () final
void onChannel0Toggled () final
void onChannel1Toggled () final
void onChannel2Toggled () final
void onChannel3Toggled () final
channel0SpinTimerChanged channel0IsSpinTimerChanged () final
channel1SpinTimerChanged channel1IsSpinTimerChanged () final
channel2SpinTimerChanged channel2IsSpinTimerChanged () final
channel3SpinTimerChanged channel3IsSpinTimerChanged () final
void onChannel0SpinTimerChanged () final
void onChannel1SpinTimerChanged () final
void onChannel2SpinTimerChanged () final
void onChannel3SpinTimerChanged () final
channel0TimerToggled channel0IsTimerChanged () final
channel1TimerToggled channel1IsTimerChanged () final
channel2TimerToggled channel2IsTimerChanged () final
channel3TimerToggled channel3IsTimerChanged () final
void onChannel0TimerChanged () final
void onChannel1TimerChanged () final
void onChannel2TimerChanged () final
void onChannel3TimerChanged () final
Public Member Functions inherited from AbMicroHILView
virtual ~AbMicroHILView ()=default
virtual channel0Changed channel0IsChanged ()=0
virtual channel1Changed channel1IsChanged ()=0
virtual channel2Changed channel2IsChanged ()=0
virtual channel3Changed channel3IsChanged ()=0
virtual void onChannel0 ()=0
virtual void onChannel1 ()=0
virtual void onChannel2 ()=0
virtual void onChannel3 ()=0
virtual select0Changed channel0IsSelected ()=0
virtual select1Changed channel1IsSelected ()=0
virtual select2Changed channel2IsSelected ()=0
virtual select3Changed channel3IsSelected ()=0
virtual void onChannel0TypeSelected ()=0
virtual void onChannel1TypeSelected ()=0
virtual void onChannel2TypeSelected ()=0
virtual void onChannel3TypeSelected ()=0
virtual channel0Toggled channel0IsToggled ()=0
virtual channel1Toggled channel1IsToggled ()=0
virtual channel2Toggled channel2IsToggled ()=0
virtual channel3Toggled channel3IsToggled ()=0
virtual void onChannel0Toggled ()=0
virtual void onChannel1Toggled ()=0
virtual void onChannel2Toggled ()=0
virtual void onChannel3Toggled ()=0
virtual channel0SpinTimerChanged channel0IsSpinTimerChanged ()=0
virtual channel1SpinTimerChanged channel1IsSpinTimerChanged ()=0
virtual channel2SpinTimerChanged channel2IsSpinTimerChanged ()=0
virtual channel3SpinTimerChanged channel3IsSpinTimerChanged ()=0
virtual void onChannel0SpinTimerChanged ()=0
virtual void onChannel1SpinTimerChanged ()=0
virtual void onChannel2SpinTimerChanged ()=0
virtual void onChannel3SpinTimerChanged ()=0
virtual channel0TimerToggled channel0IsTimerChanged ()=0
virtual channel1TimerToggled channel1IsTimerChanged ()=0
virtual channel2TimerToggled channel2IsTimerChanged ()=0
virtual channel3TimerToggled channel3IsTimerChanged ()=0
virtual void onChannel0TimerChanged ()=0
virtual void onChannel1TimerChanged ()=0
virtual void onChannel2TimerChanged ()=0
virtual void onChannel3TimerChanged ()=0
Private Member Functions
void mapping ()
void enableChannel0 ()
void disableChannel0 ()
void enableChannel1 ()
void disableChannel1 ()
void enableChannel2 ()
void disableChannel2 ()
void enableChannel3 ()
void disableChannel3 ()
void toggleModeChannel0 ()
void timerModeChannel0 ()
void toggleModeChannel1 ()
void timerModeChannel1 ()
void toggleModeChannel2 ()
void timerModeChannel2 ()
void toggleModeChannel3 ()
void timerModeChannel3 ()
Private Attributes
Glib::RefPtr< Gtk::Builder > m_ui
std::vector< Glib::RefPtr< Gtk::CheckButton > > m_enableChannels
std::vector< Glib::RefPtr< Gtk::ComboBoxText > > m_selectControlChannels
std::vector< Glib::RefPtr< Gtk::ToggleButton > > m_toggleChannels
std::vector< Glib::RefPtr< Gtk::SpinButton > > m_spinTimerChannels
std::vector< Glib::RefPtr< Gtk::ToggleButton > > m_toggleTimerChannels
std::vector< Glib::RefPtr< Gtk::ProgressBar > > m_stautsTimerChannels
Glib::RefPtr< Gtk::Adjustment > m_adjustment_digits
channel0Changed m_channel0Enabled
channel1Changed m_channel1Enabled
channel2Changed m_channel2Enabled
channel3Changed m_channel3Enabled
select0Changed m_channel0ControlType
select1Changed m_channel1ControlType
select2Changed m_channel2ControlType
select3Changed m_channel3ControlType
channel0Toggled m_channel0Toggled
channel1Toggled m_channel1Toggled
channel2Toggled m_channel2Toggled
channel3Toggled m_channel3Toggled
channel0SpinTimerChanged m_channel0SpinTimerChanged
channel1SpinTimerChanged m_channel1SpinTimerChanged
channel2SpinTimerChanged m_channel2SpinTimerChanged
channel3SpinTimerChanged m_channel3SpinTimerChanged
channel0TimerToggled m_channel0TimerToggled
channel1TimerToggled m_channel1TimerToggled
channel2TimerToggled m_channel2TimerToggled
channel3TimerToggled m_channel3TimerToggled
Additional Inherited Members
Public Types inherited from AbMicroHILView
using channel0Changed = sigc::signal< void(bool)>
using channel1Changed = sigc::signal< void(bool)>
using channel2Changed = sigc::signal< void(bool)>
using channel3Changed = sigc::signal< void(bool)>
using select0Changed = sigc::signal< void(int)>
using select1Changed = sigc::signal< void(int)>
using select2Changed = sigc::signal< void(int)>
using select3Changed = sigc::signal< void(int)>
using channel0Toggled = sigc::signal< void(bool)>
using channel1Toggled = sigc::signal< void(bool)>
using channel2Toggled = sigc::signal< void(bool)>
using channel3Toggled = sigc::signal< void(bool)>
using channel0SpinTimerChanged = sigc::signal< void(int)>
using channel1SpinTimerChanged = sigc::signal< void(int)>
using channel2SpinTimerChanged = sigc::signal< void(int)>
using channel3SpinTimerChanged = sigc::signal< void(int)>
using channel0TimerToggled = sigc::signal< void(bool)>
using channel1TimerToggled = sigc::signal< void(bool)>
using channel2TimerToggled = sigc::signal< void(bool)>
using channel3TimerToggled = sigc::signal< void(bool)>
Detailed Description
Definition at line 38 of file microhil_view.h.
Constructor & Destructor Documentation
MicroHILView()
MicroHILView::MicroHILView (BaseObjectType * object, Glib::RefPtr< Gtk::Builder > const & ui)
Definition at line 74 of file microhil_view.cc.
 : Gtk::ApplicationWindow(object), m_ui{ui}
{
    // Bind channel widgets
    for (int i = 0; i < kNumberOfChannels; i++)
    {
        m_enableChannels.push_back(
            Glib::RefPtr<Gtk::CheckButton>::cast_dynamic(
                m_ui->get_object(kCheckButtonsId[i])
            )
        );
        m_selectControlChannels.push_back(
            Glib::RefPtr<Gtk::ComboBoxText>::cast_dynamic(
                m_ui->get_object(kComboBoxTextsId[i])
            )
        );
        m_toggleChannels.push_back(
            Glib::RefPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kToggleButtonsId[i])
            )
        );
        m_spinTimerChannels.push_back(
            Glib::RefPtr<Gtk::SpinButton>::cast_dynamic(
                m_ui->get_object(kTimerSpinButtonsId[i])
            )
        );
        m_toggleTimerChannels.push_back(
            Glib::RefPtr<Gtk::ToggleButton>::cast_dynamic(
                m_ui->get_object(kTimerToggleButtonsId[i])
            )
        );
        m_stautsTimerChannels.push_back(
            Glib::RefPtr<Gtk::ProgressBar>::cast_dynamic(
                m_ui->get_object(kTimerProgressBarStatus0Id[i])
            )
        );
    }
    // Map channel signals and slots
    mapping();
    // Disabled all channels by default
    disableChannel0();
    disableChannel1();
    disableChannel2();
    disableChannel3();
}
References disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), m_enableChannels, m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, m_toggleTimerChannels, m_ui, and mapping().
~MicroHILView()
MicroHILView::~MicroHILView () default
Member Function Documentation
channel0IsChanged()
MicroHILView::channel0Changed MicroHILView::channel0IsChanged () final virtual
Implements AbMicroHILView.
Definition at line 21 of file microhil_view_signals.cc.
{
    return m_channel0Enabled;
}
References m_channel0Enabled.
channel0IsSelected()
MicroHILView::select0Changed MicroHILView::channel0IsSelected () final virtual
Implements AbMicroHILView.
Definition at line 41 of file microhil_view_signals.cc.
{
    return m_channel0ControlType;
}
References m_channel0ControlType.
channel0IsSpinTimerChanged()
MicroHILView::channel0SpinTimerChanged MicroHILView::channel0IsSpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 82 of file microhil_view_signals.cc.
{
    return m_channel0SpinTimerChanged;
}
References m_channel0SpinTimerChanged.
channel0IsTimerChanged()
MicroHILView::channel0TimerToggled MicroHILView::channel0IsTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 105 of file microhil_view_signals.cc.
{
    return m_channel0TimerToggled;
}
References m_channel0TimerToggled.
channel0IsToggled()
MicroHILView::channel0Toggled MicroHILView::channel0IsToggled () final virtual
Implements AbMicroHILView.
Definition at line 61 of file microhil_view_signals.cc.
{
    return m_channel0Toggled;
}
References m_channel0Toggled.
channel1IsChanged()
MicroHILView::channel1Changed MicroHILView::channel1IsChanged () final virtual
Implements AbMicroHILView.
Definition at line 26 of file microhil_view_signals.cc.
{
    return m_channel1Enabled;
}
References m_channel1Enabled.
channel1IsSelected()
MicroHILView::select1Changed MicroHILView::channel1IsSelected () final virtual
Implements AbMicroHILView.
Definition at line 46 of file microhil_view_signals.cc.
{
    return m_channel1ControlType;
}
References m_channel1ControlType.
channel1IsSpinTimerChanged()
MicroHILView::channel1SpinTimerChanged MicroHILView::channel1IsSpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 88 of file microhil_view_signals.cc.
{
    return m_channel1SpinTimerChanged;
}
References m_channel1SpinTimerChanged.
channel1IsTimerChanged()
MicroHILView::channel1TimerToggled MicroHILView::channel1IsTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 110 of file microhil_view_signals.cc.
{
    return m_channel1TimerToggled;
}
References m_channel1TimerToggled.
channel1IsToggled()
MicroHILView::channel1Toggled MicroHILView::channel1IsToggled () final virtual
Implements AbMicroHILView.
Definition at line 66 of file microhil_view_signals.cc.
{
    return m_channel1Toggled;
}
References m_channel1Toggled.
channel2IsChanged()
MicroHILView::channel2Changed MicroHILView::channel2IsChanged () final virtual
Implements AbMicroHILView.
Definition at line 31 of file microhil_view_signals.cc.
{
    return m_channel2Enabled;
}
References m_channel2Enabled.
channel2IsSelected()
MicroHILView::select2Changed MicroHILView::channel2IsSelected () final virtual
Implements AbMicroHILView.
Definition at line 51 of file microhil_view_signals.cc.
{
    return m_channel2ControlType;
}
References m_channel2ControlType.
channel2IsSpinTimerChanged()
MicroHILView::channel2SpinTimerChanged MicroHILView::channel2IsSpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 94 of file microhil_view_signals.cc.
{
    return m_channel2SpinTimerChanged;
}
References m_channel2SpinTimerChanged.
channel2IsTimerChanged()
MicroHILView::channel2TimerToggled MicroHILView::channel2IsTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 115 of file microhil_view_signals.cc.
{
    return m_channel2TimerToggled;
}
References m_channel2TimerToggled.
channel2IsToggled()
MicroHILView::channel2Toggled MicroHILView::channel2IsToggled () final virtual
Implements AbMicroHILView.
Definition at line 71 of file microhil_view_signals.cc.
{
    return m_channel2Toggled;
}
References m_channel2Toggled.
channel3IsChanged()
MicroHILView::channel3Changed MicroHILView::channel3IsChanged () final virtual
Implements AbMicroHILView.
Definition at line 36 of file microhil_view_signals.cc.
{
    return m_channel3Enabled;
}
References m_channel3Enabled.
channel3IsSelected()
MicroHILView::select3Changed MicroHILView::channel3IsSelected () final virtual
Implements AbMicroHILView.
Definition at line 56 of file microhil_view_signals.cc.
{
    return m_channel3ControlType;
}
References m_channel3ControlType.
channel3IsSpinTimerChanged()
MicroHILView::channel3SpinTimerChanged MicroHILView::channel3IsSpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 100 of file microhil_view_signals.cc.
{
    return m_channel3SpinTimerChanged;
}
References m_channel3SpinTimerChanged.
channel3IsTimerChanged()
MicroHILView::channel3TimerToggled MicroHILView::channel3IsTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 120 of file microhil_view_signals.cc.
{
    return m_channel3TimerToggled;
}
References m_channel3TimerToggled.
channel3IsToggled()
MicroHILView::channel3Toggled MicroHILView::channel3IsToggled () final virtual
Implements AbMicroHILView.
Definition at line 76 of file microhil_view_signals.cc.
{
    return m_channel3Toggled;
}
References m_channel3Toggled.
disableChannel0()
void MicroHILView::disableChannel0 () private
Definition at line 126 of file microhil_view.cc.
{
    m_selectControlChannels[0]->set_sensitive(false);
    m_toggleChannels[0]->set_sensitive(false);
    m_spinTimerChannels[0]->set_sensitive(false);
    m_toggleTimerChannels[0]->set_sensitive(false);
    m_stautsTimerChannels[0]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILView(), and onChannel0().
disableChannel1()
void MicroHILView::disableChannel1 () private
Definition at line 144 of file microhil_view.cc.
{
    m_selectControlChannels[1]->set_sensitive(false);
    m_toggleChannels[1]->set_sensitive(false);
    m_spinTimerChannels[1]->set_sensitive(false);
    m_toggleTimerChannels[1]->set_sensitive(false);
    m_stautsTimerChannels[1]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILView(), and onChannel1().
disableChannel2()
void MicroHILView::disableChannel2 () private
Definition at line 162 of file microhil_view.cc.
{
    m_selectControlChannels[2]->set_sensitive(false);
    m_toggleChannels[2]->set_sensitive(false);
    m_spinTimerChannels[2]->set_sensitive(false);
    m_toggleTimerChannels[2]->set_sensitive(false);
    m_stautsTimerChannels[2]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILView(), and onChannel2().
disableChannel3()
void MicroHILView::disableChannel3 () private
Definition at line 180 of file microhil_view.cc.
{
    m_selectControlChannels[3]->set_sensitive(false);
    m_toggleChannels[3]->set_sensitive(false);
    m_spinTimerChannels[3]->set_sensitive(false);
    m_toggleTimerChannels[3]->set_sensitive(false);
    m_stautsTimerChannels[3]->set_sensitive(false);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by MicroHILView(), and onChannel3().
enableChannel0()
void MicroHILView::enableChannel0 () private
Definition at line 135 of file microhil_view.cc.
{
    m_selectControlChannels[0]->set_sensitive(true);
    m_toggleChannels[0]->set_sensitive(true);
    m_spinTimerChannels[0]->set_sensitive(true);
    m_toggleTimerChannels[0]->set_sensitive(true);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0().
enableChannel1()
void MicroHILView::enableChannel1 () private
Definition at line 153 of file microhil_view.cc.
{
    m_selectControlChannels[1]->set_sensitive(true);
    m_toggleChannels[1]->set_sensitive(true);
    m_spinTimerChannels[1]->set_sensitive(true);
    m_toggleTimerChannels[1]->set_sensitive(true);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1().
enableChannel2()
void MicroHILView::enableChannel2 () private
Definition at line 171 of file microhil_view.cc.
{
    m_selectControlChannels[2]->set_sensitive(true);
    m_toggleChannels[2]->set_sensitive(true);
    m_spinTimerChannels[2]->set_sensitive(true);
    m_toggleTimerChannels[2]->set_sensitive(true);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2().
enableChannel3()
void MicroHILView::enableChannel3 () private
Definition at line 189 of file microhil_view.cc.
{
    m_selectControlChannels[3]->set_sensitive(true);
    m_toggleChannels[3]->set_sensitive(true);
    m_spinTimerChannels[3]->set_sensitive(true);
    m_toggleTimerChannels[3]->set_sensitive(true);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_selectControlChannels, m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3().
mapping()
void MicroHILView::mapping () private
Definition at line 21 of file microhil_view_map.cc.
{
    // Map channel signals and slots
    m_enableChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel0)
    );
    m_enableChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel1)
    );
    m_enableChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel2)
    );
    m_enableChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel3)
    );
    m_selectControlChannels[0]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel0TypeSelected)
    );
    m_selectControlChannels[1]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel1TypeSelected)
    );
    m_selectControlChannels[2]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel2TypeSelected)
    );
    m_selectControlChannels[3]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel3TypeSelected)
    );
    m_toggleChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel0Toggled)
    );
    m_toggleChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel1Toggled)
    );
    m_toggleChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel2Toggled)
    );
    m_toggleChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel3Toggled)
    );
    m_spinTimerChannels[0]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel0SpinTimerChanged)
    );
    m_spinTimerChannels[1]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel1SpinTimerChanged)
    );
    m_spinTimerChannels[2]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel2SpinTimerChanged)
    );
    m_spinTimerChannels[3]->signal_changed().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel3SpinTimerChanged)
    );
    m_toggleTimerChannels[0]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel0TimerChanged)
    );
    m_toggleTimerChannels[1]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel1TimerChanged)
    );
    m_toggleTimerChannels[2]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel2TimerChanged)
    );
    m_toggleTimerChannels[3]->signal_toggled().connect(
        sigc::mem_fun(*this, &MicroHILView::onChannel3TimerChanged)
    );
}
References m_enableChannels, m_selectControlChannels, m_spinTimerChannels, m_toggleChannels, m_toggleTimerChannels, onChannel0(), onChannel0SpinTimerChanged(), onChannel0TimerChanged(), onChannel0Toggled(), onChannel0TypeSelected(), onChannel1(), onChannel1SpinTimerChanged(), onChannel1TimerChanged(), onChannel1Toggled(), onChannel1TypeSelected(), onChannel2(), onChannel2SpinTimerChanged(), onChannel2TimerChanged(), onChannel2Toggled(), onChannel2TypeSelected(), onChannel3(), onChannel3SpinTimerChanged(), onChannel3TimerChanged(), onChannel3Toggled(), and onChannel3TypeSelected().
Referenced by MicroHILView().
onChannel0()
void MicroHILView::onChannel0 () final virtual
Implements AbMicroHILView.
Definition at line 21 of file microhil_view_slots.cc.
{
    bool status = m_enableChannels[0]->get_active();
    if(status)
    {
        enableChannel0();
    }
    else
    {
        disableChannel0();
    }
    m_channel0Enabled.emit(status);
}
References disableChannel0(), enableChannel0(), m_channel0Enabled, and m_enableChannels.
Referenced by mapping().
onChannel0SpinTimerChanged()
void MicroHILView::onChannel0SpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 201 of file microhil_view_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        int value = m_spinTimerChannels[0]->get_value_as_int();
        m_channel0SpinTimerChanged.emit(value);
    }
}
References m_channel0SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel0TimerChanged()
void MicroHILView::onChannel0TimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 237 of file microhil_view_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[0]->get_active();
        m_channel0TimerToggled.emit(status);
    }
}
References m_channel0TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel0Toggled()
void MicroHILView::onChannel0Toggled () final virtual
Implements AbMicroHILView.
Definition at line 165 of file microhil_view_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        bool status = m_toggleChannels[0]->get_active();
        m_channel0Toggled.emit(status);
    }
}
References m_channel0Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel0TypeSelected()
void MicroHILView::onChannel0TypeSelected () final virtual
Implements AbMicroHILView.
Definition at line 85 of file microhil_view_slots.cc.
{
    if(m_enableChannels[0]->get_active() == true)
    {
        int controlType = m_selectControlChannels[0]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel0();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel0();
                break;
        }
        m_channel0ControlType.emit(controlType);
    }
}
References m_channel0ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel0(), TOGGLE_BUTTON, and toggleModeChannel0().
Referenced by mapping().
onChannel1()
void MicroHILView::onChannel1 () final virtual
Implements AbMicroHILView.
Definition at line 37 of file microhil_view_slots.cc.
{
    bool status = m_enableChannels[1]->get_active();
    if(status)
    {
        enableChannel1();
    }
    else
    {
        disableChannel1();
    }
    m_channel1Enabled.emit(status);
}
References disableChannel1(), enableChannel1(), m_channel1Enabled, and m_enableChannels.
Referenced by mapping().
onChannel1SpinTimerChanged()
void MicroHILView::onChannel1SpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 210 of file microhil_view_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        int value = m_spinTimerChannels[1]->get_value_as_int();
        m_channel1SpinTimerChanged.emit(value);
    }
}
References m_channel1SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel1TimerChanged()
void MicroHILView::onChannel1TimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 246 of file microhil_view_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[1]->get_active();
        m_channel1TimerToggled.emit(status);
    }
}
References m_channel1TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel1Toggled()
void MicroHILView::onChannel1Toggled () final virtual
Implements AbMicroHILView.
Definition at line 174 of file microhil_view_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        bool status = m_toggleChannels[1]->get_active();
        m_channel1Toggled.emit(status);
    }
}
References m_channel1Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel1TypeSelected()
void MicroHILView::onChannel1TypeSelected () final virtual
Implements AbMicroHILView.
Definition at line 105 of file microhil_view_slots.cc.
{
    if(m_enableChannels[1]->get_active() == true)
    {
        int controlType = m_selectControlChannels[1]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel1();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel1();
                break;
        }
        m_channel1ControlType.emit(controlType);
    }
}
References m_channel1ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel1(), TOGGLE_BUTTON, and toggleModeChannel1().
Referenced by mapping().
onChannel2()
void MicroHILView::onChannel2 () final virtual
Implements AbMicroHILView.
Definition at line 53 of file microhil_view_slots.cc.
{
    bool status = m_enableChannels[2]->get_active();
    if(status)
    {
        enableChannel2();
    }
    else
    {
        disableChannel2();
    }
    m_channel2Enabled.emit(status);
}
References disableChannel2(), enableChannel2(), m_channel2Enabled, and m_enableChannels.
Referenced by mapping().
onChannel2SpinTimerChanged()
void MicroHILView::onChannel2SpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 219 of file microhil_view_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        int value = m_spinTimerChannels[2]->get_value_as_int();
        m_channel2SpinTimerChanged.emit(value);
    }
}
References m_channel2SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel2TimerChanged()
void MicroHILView::onChannel2TimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 255 of file microhil_view_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[2]->get_active();
        m_channel2TimerToggled.emit(status);
    }
}
References m_channel2TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel2Toggled()
void MicroHILView::onChannel2Toggled () final virtual
Implements AbMicroHILView.
Definition at line 183 of file microhil_view_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        bool status = m_toggleChannels[2]->get_active();
        m_channel2Toggled.emit(status);
    }
}
References m_channel2Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel2TypeSelected()
void MicroHILView::onChannel2TypeSelected () final virtual
Implements AbMicroHILView.
Definition at line 125 of file microhil_view_slots.cc.
{
    if(m_enableChannels[2]->get_active() == true)
    {
        int controlType = m_selectControlChannels[2]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel2();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel2();
                break;
        }
        m_channel2ControlType.emit(controlType);
    }
}
References m_channel2ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel2(), TOGGLE_BUTTON, and toggleModeChannel2().
Referenced by mapping().
onChannel3()
void MicroHILView::onChannel3 () final virtual
Implements AbMicroHILView.
Definition at line 69 of file microhil_view_slots.cc.
{
    bool status = m_enableChannels[3]->get_active();
    if(status)
    {
        enableChannel3();
    }
    else
    {
        disableChannel3();
    }
    m_channel3Enabled.emit(status);
}
References disableChannel3(), enableChannel3(), m_channel3Enabled, and m_enableChannels.
Referenced by mapping().
onChannel3SpinTimerChanged()
void MicroHILView::onChannel3SpinTimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 228 of file microhil_view_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        int value = m_spinTimerChannels[3]->get_value_as_int();
        m_channel3SpinTimerChanged.emit(value);
    }
}
References m_channel3SpinTimerChanged, m_enableChannels, and m_spinTimerChannels.
Referenced by mapping().
onChannel3TimerChanged()
void MicroHILView::onChannel3TimerChanged () final virtual
Implements AbMicroHILView.
Definition at line 264 of file microhil_view_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        bool status = m_toggleTimerChannels[3]->get_active();
        m_channel3TimerToggled.emit(status);
    }
}
References m_channel3TimerToggled, m_enableChannels, and m_toggleTimerChannels.
Referenced by mapping().
onChannel3Toggled()
void MicroHILView::onChannel3Toggled () final virtual
Implements AbMicroHILView.
Definition at line 192 of file microhil_view_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        bool status = m_toggleChannels[3]->get_active();
        m_channel3Toggled.emit(status);
    }
}
References m_channel3Toggled, m_enableChannels, and m_toggleChannels.
Referenced by mapping().
onChannel3TypeSelected()
void MicroHILView::onChannel3TypeSelected () final virtual
Implements AbMicroHILView.
Definition at line 145 of file microhil_view_slots.cc.
{
    if(m_enableChannels[3]->get_active() == true)
    {
        int controlType = m_selectControlChannels[3]->get_active_row_number();
        switch(controlType)
        {
            case static_cast<int>(channelControlType::TOGGLE_BUTTON):
                toggleModeChannel3();
                break;
            case static_cast<int>(channelControlType::TIMER_BUTTON):
                timerModeChannel3();
                break;
        }
        m_channel3ControlType.emit(controlType);
    }
}
References m_channel3ControlType, m_enableChannels, m_selectControlChannels, TIMER_BUTTON, timerModeChannel3(), TOGGLE_BUTTON, and toggleModeChannel3().
Referenced by mapping().
timerModeChannel0()
void MicroHILView::timerModeChannel0 () private
Definition at line 206 of file microhil_view.cc.
{
    m_toggleChannels[0]->set_sensitive(false);
    m_spinTimerChannels[0]->set_sensitive(true);
    m_toggleTimerChannels[0]->set_sensitive(true);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0TypeSelected().
timerModeChannel1()
void MicroHILView::timerModeChannel1 () private
Definition at line 222 of file microhil_view.cc.
{
    m_toggleChannels[1]->set_sensitive(false);
    m_spinTimerChannels[1]->set_sensitive(true);
    m_toggleTimerChannels[1]->set_sensitive(true);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1TypeSelected().
timerModeChannel2()
void MicroHILView::timerModeChannel2 () private
Definition at line 238 of file microhil_view.cc.
{
    m_toggleChannels[2]->set_sensitive(false);
    m_spinTimerChannels[2]->set_sensitive(true);
    m_toggleTimerChannels[2]->set_sensitive(true);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2TypeSelected().
timerModeChannel3()
void MicroHILView::timerModeChannel3 () private
Definition at line 254 of file microhil_view.cc.
{
    m_toggleChannels[3]->set_sensitive(false);
    m_spinTimerChannels[3]->set_sensitive(true);
    m_toggleTimerChannels[3]->set_sensitive(true);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3TypeSelected().
toggleModeChannel0()
void MicroHILView::toggleModeChannel0 () private
Definition at line 198 of file microhil_view.cc.
{
    m_toggleChannels[0]->set_sensitive(true);
    m_spinTimerChannels[0]->set_sensitive(false);
    m_toggleTimerChannels[0]->set_sensitive(false);
    m_stautsTimerChannels[0]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel0TypeSelected().
toggleModeChannel1()
void MicroHILView::toggleModeChannel1 () private
Definition at line 214 of file microhil_view.cc.
{
    m_toggleChannels[1]->set_sensitive(true);
    m_spinTimerChannels[1]->set_sensitive(false);
    m_toggleTimerChannels[1]->set_sensitive(false);
    m_stautsTimerChannels[1]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel1TypeSelected().
toggleModeChannel2()
void MicroHILView::toggleModeChannel2 () private
Definition at line 230 of file microhil_view.cc.
{
    m_toggleChannels[2]->set_sensitive(true);
    m_spinTimerChannels[2]->set_sensitive(false);
    m_toggleTimerChannels[2]->set_sensitive(false);
    m_stautsTimerChannels[2]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel2TypeSelected().
toggleModeChannel3()
void MicroHILView::toggleModeChannel3 () private
Definition at line 246 of file microhil_view.cc.
{
    m_toggleChannels[3]->set_sensitive(true);
    m_spinTimerChannels[3]->set_sensitive(false);
    m_toggleTimerChannels[3]->set_sensitive(false);
    m_stautsTimerChannels[3]->set_sensitive(true);
}
References m_spinTimerChannels, m_stautsTimerChannels, m_toggleChannels, and m_toggleTimerChannels.
Referenced by onChannel3TypeSelected().
Member Data Documentation
m_adjustment_digits
Glib::RefPtr<Gtk::Adjustment> MicroHILView::m_adjustment_digits private
Definition at line 167 of file microhil_view.h.
m_channel0ControlType
select0Changed MicroHILView::m_channel0ControlType private
Definition at line 178 of file microhil_view.h.
Referenced by channel0IsSelected(), and onChannel0TypeSelected().
m_channel0Enabled
channel0Changed MicroHILView::m_channel0Enabled private
Definition at line 171 of file microhil_view.h.
Referenced by channel0IsChanged(), and onChannel0().
m_channel0SpinTimerChanged
channel0SpinTimerChanged MicroHILView::m_channel0SpinTimerChanged private
Definition at line 192 of file microhil_view.h.
Referenced by channel0IsSpinTimerChanged(), and onChannel0SpinTimerChanged().
m_channel0TimerToggled
channel0TimerToggled MicroHILView::m_channel0TimerToggled private
Definition at line 199 of file microhil_view.h.
Referenced by channel0IsTimerChanged(), and onChannel0TimerChanged().
m_channel0Toggled
channel0Toggled MicroHILView::m_channel0Toggled private
Definition at line 185 of file microhil_view.h.
Referenced by channel0IsToggled(), and onChannel0Toggled().
m_channel1ControlType
select1Changed MicroHILView::m_channel1ControlType private
Definition at line 179 of file microhil_view.h.
Referenced by channel1IsSelected(), and onChannel1TypeSelected().
m_channel1Enabled
channel1Changed MicroHILView::m_channel1Enabled private
Definition at line 172 of file microhil_view.h.
Referenced by channel1IsChanged(), and onChannel1().
m_channel1SpinTimerChanged
channel1SpinTimerChanged MicroHILView::m_channel1SpinTimerChanged private
Definition at line 193 of file microhil_view.h.
Referenced by channel1IsSpinTimerChanged(), and onChannel1SpinTimerChanged().
m_channel1TimerToggled
channel1TimerToggled MicroHILView::m_channel1TimerToggled private
Definition at line 200 of file microhil_view.h.
Referenced by channel1IsTimerChanged(), and onChannel1TimerChanged().
m_channel1Toggled
channel1Toggled MicroHILView::m_channel1Toggled private
Definition at line 186 of file microhil_view.h.
Referenced by channel1IsToggled(), and onChannel1Toggled().
m_channel2ControlType
select2Changed MicroHILView::m_channel2ControlType private
Definition at line 180 of file microhil_view.h.
Referenced by channel2IsSelected(), and onChannel2TypeSelected().
m_channel2Enabled
channel2Changed MicroHILView::m_channel2Enabled private
Definition at line 173 of file microhil_view.h.
Referenced by channel2IsChanged(), and onChannel2().
m_channel2SpinTimerChanged
channel2SpinTimerChanged MicroHILView::m_channel2SpinTimerChanged private
Definition at line 194 of file microhil_view.h.
Referenced by channel2IsSpinTimerChanged(), and onChannel2SpinTimerChanged().
m_channel2TimerToggled
channel2TimerToggled MicroHILView::m_channel2TimerToggled private
Definition at line 201 of file microhil_view.h.
Referenced by channel2IsTimerChanged(), and onChannel2TimerChanged().
m_channel2Toggled
channel2Toggled MicroHILView::m_channel2Toggled private
Definition at line 187 of file microhil_view.h.
Referenced by channel2IsToggled(), and onChannel2Toggled().
m_channel3ControlType
select3Changed MicroHILView::m_channel3ControlType private
Definition at line 181 of file microhil_view.h.
Referenced by channel3IsSelected(), and onChannel3TypeSelected().
m_channel3Enabled
channel3Changed MicroHILView::m_channel3Enabled private
Definition at line 174 of file microhil_view.h.
Referenced by channel3IsChanged(), and onChannel3().
m_channel3SpinTimerChanged
channel3SpinTimerChanged MicroHILView::m_channel3SpinTimerChanged private
Definition at line 195 of file microhil_view.h.
Referenced by channel3IsSpinTimerChanged(), and onChannel3SpinTimerChanged().
m_channel3TimerToggled
channel3TimerToggled MicroHILView::m_channel3TimerToggled private
Definition at line 202 of file microhil_view.h.
Referenced by channel3IsTimerChanged(), and onChannel3TimerChanged().
m_channel3Toggled
channel3Toggled MicroHILView::m_channel3Toggled private
Definition at line 188 of file microhil_view.h.
Referenced by channel3IsToggled(), and onChannel3Toggled().
m_enableChannels
std::vector<Glib::RefPtr<Gtk::CheckButton> > MicroHILView::m_enableChannels private
Definition at line 161 of file microhil_view.h.
Referenced by mapping(), MicroHILView(), onChannel0(), onChannel0SpinTimerChanged(), onChannel0TimerChanged(), onChannel0Toggled(), onChannel0TypeSelected(), onChannel1(), onChannel1SpinTimerChanged(), onChannel1TimerChanged(), onChannel1Toggled(), onChannel1TypeSelected(), onChannel2(), onChannel2SpinTimerChanged(), onChannel2TimerChanged(), onChannel2Toggled(), onChannel2TypeSelected(), onChannel3(), onChannel3SpinTimerChanged(), onChannel3TimerChanged(), onChannel3Toggled(), and onChannel3TypeSelected().
m_selectControlChannels
std::vector<Glib::RefPtr<Gtk::ComboBoxText> > MicroHILView::m_selectControlChannels private
Definition at line 162 of file microhil_view.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), mapping(), MicroHILView(), onChannel0TypeSelected(), onChannel1TypeSelected(), onChannel2TypeSelected(), and onChannel3TypeSelected().
m_spinTimerChannels
std::vector<Glib::RefPtr<Gtk::SpinButton> > MicroHILView::m_spinTimerChannels private
Definition at line 164 of file microhil_view.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), mapping(), MicroHILView(), onChannel0SpinTimerChanged(), onChannel1SpinTimerChanged(), onChannel2SpinTimerChanged(), onChannel3SpinTimerChanged(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), and toggleModeChannel3().
m_stautsTimerChannels
std::vector<Glib::RefPtr<Gtk::ProgressBar> > MicroHILView::m_stautsTimerChannels private
Definition at line 166 of file microhil_view.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), MicroHILView(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), and toggleModeChannel3().
m_toggleChannels
std::vector<Glib::RefPtr<Gtk::ToggleButton> > MicroHILView::m_toggleChannels private
Definition at line 163 of file microhil_view.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), mapping(), MicroHILView(), onChannel0Toggled(), onChannel1Toggled(), onChannel2Toggled(), onChannel3Toggled(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), and toggleModeChannel3().
m_toggleTimerChannels
std::vector<Glib::RefPtr<Gtk::ToggleButton> > MicroHILView::m_toggleTimerChannels private
Definition at line 165 of file microhil_view.h.
Referenced by disableChannel0(), disableChannel1(), disableChannel2(), disableChannel3(), enableChannel0(), enableChannel1(), enableChannel2(), enableChannel3(), mapping(), MicroHILView(), onChannel0TimerChanged(), onChannel1TimerChanged(), onChannel2TimerChanged(), onChannel3TimerChanged(), timerModeChannel0(), timerModeChannel1(), timerModeChannel2(), timerModeChannel3(), toggleModeChannel0(), toggleModeChannel1(), toggleModeChannel2(), and toggleModeChannel3().
m_ui
Glib::RefPtr<Gtk::Builder> MicroHILView::m_ui private
Definition at line 160 of file microhil_view.h.
Referenced by MicroHILView().
The documentation for this class was generated from the following files:
view/microhil_view.h
view/microhil_view.cc
view/microhil_view_map.cc
view/microhil_view_signals.cc
view/microhil_view_slots.cc