microhil-device0: src/channel/channel_uart.c File Reference
channel_uart.c File Reference
#include <stdlib.h>
#include <string.h>
#include "channel_error.h"
#include "channel.h"
Functions
uint16_t microhil_fetch_command (uint8_t *buffer)
Fetch microHIL command messages from the serial port.
unsigned char * microhil_extract_command_property (unsigned char *cmd)
Extract command property (private)
int microhil_process_all_on (unsigned char *cmd_property)
Process command property for all channels ON (private)
int microhil_process_all_off (unsigned char *cmd_property)
Process command property for all channels OFF (private)
int microhil_process_channel_on (unsigned char *cmd_property, int index)
Process command property for channel (private)
int microhil_process_channel_off (unsigned char *cmd_property, int index)
Process command property for channel (private)
channel_gpio_num microhil_process_command (unsigned char *cmd)
Process microHIL command messages from uart.
Function Documentation
microhil_extract_command_property()
unsigned char * microhil_extract_command_property (unsigned char * cmd)
Extract command property (private)
Extract command property.
Parameters
cmd is whole command messsage for processing
Returns
command property
Sanity check for expected command message prefix
Not matched expected command message prefix
Extract command property
Command message property (microHIL format)
Definition at line 54 of file channel_uart.c.
{
    int cmd_len = strlen(cmd);
    int prefix_len = strlen(MICROHIL_CMD_PREFIX);
    int len = cmd_len - prefix_len;
    int status = strncmp(cmd, MICROHIL_CMD_PREFIX, prefix_len);
    if(status != 0)
    {
        return NULL;
    }
    unsigned char *cmd_property = (unsigned char *)malloc(len);
    sprintf(cmd_property, "%s", cmd + prefix_len);
    return cmd_property;
}
References MICROHIL_CMD_PREFIX.
Referenced by microhil_process_command().
microhil_fetch_command()
uint16_t microhil_fetch_command (uint8_t * buffer)
Fetch microHIL command messages from the serial port.
Parameters
buffer storage for received message from the serial port
Returns
number of received bytes from the serial port
Definition at line 28 of file channel_uart.c.
{
    uint16_t buffer_index = 0;
    while(true)
    {
        int byte = getchar_timeout_us(100);
        if(byte != PICO_ERROR_TIMEOUT && buffer_index < MICROHIL_CMD_LEN)
        {
            buffer[buffer_index++] = (byte & 0xFF);
        }
        else
        {
            buffer[buffer_index] = 0;
            break;
        }
    }
    return buffer_index;
}
References MICROHIL_CMD_LEN.
Referenced by main().
microhil_process_all_off()
int microhil_process_all_off (unsigned char * cmd_property)
Process command property for all channels OFF (private)
Parameters
cmd_property instruction
Returns
command id for all channels OFF
Definition at line 95 of file channel_uart.c.
{
    int len = strlen(MICROHIL_CMD_PROP_ALL_OFF);
    return strncmp(cmd_property, MICROHIL_CMD_PROP_ALL_OFF, len);
}
References MICROHIL_CMD_PROP_ALL_OFF.
Referenced by microhil_process_command().
microhil_process_all_on()
int microhil_process_all_on (unsigned char * cmd_property)
Process command property for all channels ON (private)
Parameters
cmd_property instruction
Returns
command id for all channels ON
Definition at line 85 of file channel_uart.c.
{
    int len = strlen(MICROHIL_CMD_PROP_ALL_ON);
    return strncmp(cmd_property, MICROHIL_CMD_PROP_ALL_ON, len);
}
References MICROHIL_CMD_PROP_ALL_ON.
Referenced by microhil_process_command().
microhil_process_channel_off()
int microhil_process_channel_off (unsigned char * cmd_property, int index)
Process command property for channel (private)
Parameters
cmd_property instruction
id for channel
Returns
command id for channel
Definition at line 126 of file channel_uart.c.
{
    if(0 > index || index > 8)
    {
        return (int)MICROHIL_CHANNELS_ERROR;
    }
    char *operation_off = (char *)malloc(5);
    sprintf(operation_off, "%d#off", index);
    int status = strncmp(cmd_property, operation_off, strlen(operation_off));
    free(operation_off);
    return status;
}
References MICROHIL_CHANNELS_ERROR.
Referenced by microhil_process_command().
microhil_process_channel_on()
int microhil_process_channel_on (unsigned char * cmd_property, int index)
Process command property for channel (private)
Parameters
cmd_property instruction
id for channel
Returns
command id for channel
Definition at line 106 of file channel_uart.c.
{
    if(0 > index || index > 8)
    {
        return (int) MICROHIL_CHANNELS_ERROR;
    }
    char *operation_on = (char *)malloc(4);
    sprintf(operation_on, "%d#on", index);
    int status = strncmp(cmd_property, operation_on, strlen(operation_on));
    free(operation_on);
    return status;
}
References MICROHIL_CHANNELS_ERROR.
Referenced by microhil_process_command().
microhil_process_command()
channel_gpio_num microhil_process_command (unsigned char * cmd)
Process microHIL command messages from uart.
Parameters
cmd is whole command for processing
Returns
GPIO port number
Failed to extract command property
Request command all channels ON
Request command all channels OFF
Request command switch channel 1..8
Request command switch channel 1..8
Requested command not supported
Definition at line 145 of file channel_uart.c.
{
    unsigned char *cmd_property = microhil_extract_command_property(cmd);
    if(cmd_property == NULL)
    {
        printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_EXT_PROP_FAILED);
        return MICROHIL_CHANNELS_ERROR;
    }
    if(microhil_process_all_on(cmd_property) == 0)
    {
        free(cmd_property);
        return MICROHIL_ALL_CHANNELS_ON;
    }
    if(microhil_process_all_off(cmd_property) == 0)
    {
        free(cmd_property);
        return MICROHIL_ALL_CHANNELS_OFF;
    }
    for(int i = 0; i < MICROHIL_NUMBER_OF_CHANNELS; i++)
    {
        if(microhil_process_channel_on(cmd_property, i) == 0)
        {
            free(cmd_property);
            return index_to_gpio(i);
        }
        if(microhil_process_channel_off(cmd_property, i) == 0)
        {
            free(cmd_property);
            return index_to_gpio(i);
        }
    }
    free(cmd_property);
    printf("%s %s\n", MICROHIL_CHANNEL_ERROR, MICROHIL_NO_SUPPORT);
    return MICROHIL_CHANNELS_ERROR;
}
References index_to_gpio(), MICROHIL_ALL_CHANNELS_OFF, MICROHIL_ALL_CHANNELS_ON, MICROHIL_CHANNEL_ERROR, MICROHIL_CHANNELS_ERROR, MICROHIL_EXT_PROP_FAILED, microhil_extract_command_property(), MICROHIL_NO_SUPPORT, MICROHIL_NUMBER_OF_CHANNELS, microhil_process_all_off(), microhil_process_all_on(), microhil_process_channel_off(), and microhil_process_channel_on().
Referenced by main().