microhildesk: MicroHILConfig Class Reference
MicroHILConfig Class Reference
MicroHILConfig class declaration and definition.
#include <microhil_config.h>
Public Member Functions
MicroHILConfig ()
MicroHILConfig constructor.
~MicroHILConfig ()=default
MicroHILConfig destructor.
SigLogConfig LogConfigLoaded () final
Signal for loaded log configuration.
SigSerialConfig SerialConfigLoaded () final
Signal for loaded serial configuration.
bool load () final
Load configuration from file.
bool store () final
Store configuration.
bool validate () final
Validate configuration (existing all expected parameters)
void setDevice (const Glib::ustring device) final
Setting serial device file path to configuration.
Glib::ustring getDevice () final
Getting serial device file path from configuration.
void setBaudRate (const int baudRate) final
Setting baud rate for serial port to configuration.
int getBaudRate () final
Getting baud rate for serial port from configuration.
void setDataBits (const int dataBits) final
Setting data bits for serial port to configuration.
int getDataBits () final
Getting data bits for serial port from configuration.
void setParity (const int parity) final
Setting parity for serial port to configuration.
Glib::ustring getParity () final
Getting parity for serial port from configuration.
void setStopBits (const int stopBits) final
Setting stop bits for serial port to configuration.
int getStopBits () final
Getting stop bits for serial port from configuration.
void setLogLevel (const int level) final
Setting log level.
Glib::ustring getLogLevel () final
Getting log level.
void setLogPath (const Glib::ustring path) final
Setting log path.
Glib::ustring getLogPath () final
Getting log path.
Public Member Functions inherited from AbMicroHILConfig
virtual ~AbMicroHILConfig ()=default
AbMicroHILConfig destructor.
virtual SigLogConfig LogConfigLoaded ()=0
Signal for loaded log configuration.
virtual SigSerialConfig SerialConfigLoaded ()=0
Signal for loaded serial configuration.
virtual bool load ()=0
Load configuration.
virtual bool store ()=0
Store configuration.
virtual bool validate ()=0
Validate configuration (existing all expected parameters)
void setPreValid (bool configValid)
Set pre-validation state (existing configuration)
bool isPreValid () const
Check is pre-validation state (existing configuration)
virtual void setDevice (const Glib::ustring device)=0
Setting serial device file path to configuration.
virtual Glib::ustring getDevice ()=0
Getting serial device file path from configuration.
virtual void setBaudRate (const int baudRate)=0
Setting baud rate for serial port to configuration.
virtual int getBaudRate ()=0
Getting baud rate for serial port from configuration.
virtual void setDataBits (const int dataBits)=0
Setting data bits for serial port to configuration.
virtual int getDataBits ()=0
Getting data bits for serial port from configuration.
virtual void setParity (const int parity)=0
Setting parity for serial port to configuration.
virtual Glib::ustring getParity ()=0
Getting parity for serial port from configuration.
virtual void setStopBits (const int stopBits)=0
Setting stop bits for serial port to configuration.
virtual int getStopBits ()=0
Getting stop bits for serial port from configuration.
virtual void setLogLevel (const int level)=0
Setting log level.
virtual Glib::ustring getLogLevel ()=0
Getting log level.
virtual void setLogPath (const Glib::ustring path)=0
Setting log path.
virtual Glib::ustring getLogPath ()=0
Getting log path.
Private Member Functions
bool checkConfigPath ()
Checking existence of configuration file.
Glib::ustring logLevelToUnicodeString (const int logLevel)
Convert integer log level to string format.
int logLevelStringToInt (const Glib::ustring level)
Convert log level in strong format to integer.
int intToBaudRate (const int baudRate)
Process and prepare baud rate (to config file)
int baudRateToInt (const int baudRate)
Process and prepare baud rate (from config file)
int dataBitsToInt (const int dataBits)
Process and prepare data bits (from config file)
int intToDataBits (const int dataBits)
Convert combobox index to data bits (to config file)
Glib::ustring parityToUnicodeString (const int parity)
Convert integer parity to string format (to config file)
int parityUnicodeStringToInt (const Glib::ustring parity)
Convert parity to integer format (from config file)
int stopBitsToInt (const int stopBits)
Convert stop-bits to integer (from config file)
int intToStopBits (const int stopBits)
Convert combobox index to data-bits (to config file)
bool validateLogSettings ()
Validate log configuration (existing expected parameters)
bool validateSerialSettings ()
Validate serial configuration (existing expected parameters)
Private Attributes
std::string m_homePath {}
Home directory path.
std::string m_configFilePath {}
Configuration file path.
Glib::KeyFile m_config {}
Configuration instance.
SigLogConfig m_logConfig {}
Signal for loaded log configuration from file.
SigSerialConfig m_serialConfig {}
Signal for loaded serial configuration from file.
Additional Inherited Members
Public Types inherited from AbMicroHILConfig
using SigLogConfig = sigc::signal< void(Glib::ustring, int)>
Signal type for loaded log configuration from file.
using SigSerialConfig = sigc::signal< void(Glib::ustring, int, int, int, int)>
Signal type for loaded serial configuration from file.
Detailed Description
MicroHILConfig class declaration and definition.
Definition at line 26 of file microhil_config.h.
Constructor & Destructor Documentation
MicroHILConfig()
MicroHILConfig::MicroHILConfig ()
MicroHILConfig constructor.
Setup expected paths for home directory and configuration file
Pre-validation of configuration path
Definition at line 55 of file microhil_config.cc.
{
    m_homePath = Glib::get_home_dir() + kHomeDirName;
    m_configFilePath = m_homePath + kConfigFileName;
    setPreValid(checkConfigPath());
}
References checkConfigPath(), m_configFilePath, m_homePath, and AbMicroHILConfig::setPreValid().
~MicroHILConfig()
MicroHILConfig::~MicroHILConfig () default
MicroHILConfig destructor.
Member Function Documentation
baudRateToInt()
int MicroHILConfig::baudRateToInt (const int baudRate) private
Process and prepare baud rate (from config file)
Parameters
baudRate value from config file
Returns
index for combobox
Convert baud-rate to index item for combobox
Definition at line 72 of file microhil_config_serial_utils.cc.
{
    switch(baudRate)
    {
        case 110: return 0;
        case 300: return 1;
        case 600: return 2;
        case 1200: return 3;
        case 2400: return 4;
        case 4800: return 5;
        case 9600: return 6;
        case 14400: return 7;
        case 19200: return 8;
        case 38400: return 9;
        case 57600: return 10;
        case 115200: return 11;
        case 128000: return 12;
        case 256000: return 13;
    }
    return 115200;
}
Referenced by getBaudRate().
checkConfigPath()
bool MicroHILConfig::checkConfigPath () private
Checking existence of configuration file.
Returns
boolean status true for existing else false
Failed to create home configuration directory
Definition at line 131 of file microhil_config.cc.
{
    // Check home directory /home/<username>/.microhil/
    std::filesystem::directory_entry homeDirEntry{m_homePath};
    auto homeDirExists = homeDirEntry.exists();
    if(!homeDirExists)
    {
        if(!std::filesystem::create_directory(m_homePath))
        {
            return false;
        }
    }
    // Check config file in case of missing generate new with default setup
    // Configuration file location: /home/<username>/.microhil/config
    auto configFileExists = std::filesystem::exists(m_configFilePath);
    if(!configFileExists)
    {
        std::ofstream defaultConfig(m_configFilePath);
        for (int i = 0; i < kConfigLength; i++)
        {
            defaultConfig << kConfigSerialDefault[i] << "\n";
        }
        defaultConfig.close();
    }
    return true;
}
References m_configFilePath, and m_homePath.
Referenced by MicroHILConfig().
dataBitsToInt()
int MicroHILConfig::dataBitsToInt (const int dataBits) private
Process and prepare data bits (from config file)
Parameters
dataBits value from config file
Returns
index for combobox
Pre-process data-bits to index item of combobox
Definition at line 122 of file microhil_config_serial_utils.cc.
{
    return (dataBits - kConfigDataBitsOffset);
}
Referenced by getDataBits().
getBaudRate()
int MicroHILConfig::getBaudRate () final virtual
Getting baud rate for serial port from configuration.
Returns
integer value for serial port baud rate
Pre-process baud-rate from configuration file
Implements AbMicroHILConfig.
Definition at line 73 of file microhil_config_serial.cc.
{
    auto baudRate = m_config.get_integer(
        kConfigSerialSection, kConfigSerialBaudRate
    );
    return baudRateToInt(baudRate);
}
References baudRateToInt(), and m_config.
Referenced by load().
getDataBits()
int MicroHILConfig::getDataBits () final virtual
Getting data bits for serial port from configuration.
Returns
integer value for data bits for charachter
Pre-process data-bits from configuration file
Implements AbMicroHILConfig.
Definition at line 95 of file microhil_config_serial.cc.
{
    auto dataBits = m_config.get_integer(
        kConfigSerialSection, kConfigSerialDataBits
    );
    return dataBitsToInt(dataBits);
}
References dataBitsToInt(), and m_config.
Referenced by load().
getDevice()
Glib::ustring MicroHILConfig::getDevice () final virtual
Getting serial device file path from configuration.
Returns
file path for serial device
Implements AbMicroHILConfig.
Definition at line 55 of file microhil_config_serial.cc.
{
    return m_config.get_string(
        kConfigSerialSection, kConfigSerialDevice
    );
}
References m_config.
Referenced by load().
getLogLevel()
Glib::ustring MicroHILConfig::getLogLevel () final virtual
Getting log level.
Returns
log level
Implements AbMicroHILConfig.
Definition at line 47 of file microhil_config_log.cc.
{
    return m_config.get_string(kConfigLogSection, kConfigLogLevel);
}
References m_config.
Referenced by load().
getLogPath()
Glib::ustring MicroHILConfig::getLogPath () final virtual
Getting log path.
Returns
log path
Implements AbMicroHILConfig.
Definition at line 59 of file microhil_config_log.cc.
{
    return m_config.get_string(kConfigLogSection, kConfigLogFile);
}
References m_config.
Referenced by load().
getParity()
Glib::ustring MicroHILConfig::getParity () final virtual
Getting parity for serial port from configuration.
Returns
parity type for the serial port
Implements AbMicroHILConfig.
Definition at line 117 of file microhil_config_serial.cc.
{
    return m_config.get_string(
        kConfigSerialSection, kConfigSerialParity
    );
}
References m_config.
Referenced by load().
getStopBits()
int MicroHILConfig::getStopBits () final virtual
Getting stop bits for serial port from configuration.
Returns
integer number of stop bits for the serial port
Pre-process stop-bits from configuration file
Implements AbMicroHILConfig.
Definition at line 135 of file microhil_config_serial.cc.
{
    auto stopBits = (int) m_config.get_integer(
        kConfigSerialSection, kConfigSerialStopBits
    );
    return stopBitsToInt(stopBits);
}
References m_config, and stopBitsToInt().
Referenced by load().
intToBaudRate()
int MicroHILConfig::intToBaudRate (const int baudRate) private
Process and prepare baud rate (to config file)
Parameters
baudRate for serial port (combobox index)
Returns
baud rate for serial port in integer format
Convert index item of combobox to baud-rate
Definition at line 97 of file microhil_config_serial_utils.cc.
{
    switch(baudRate)
    {
        case 0: return 110;
        case 1: return 300;
        case 2: return 600;
        case 3: return 1200;
        case 4: return 2400;
        case 5: return 4800;
        case 6: return 9600;
        case 7: return 14400;
        case 8: return 19200;
        case 9: return 38400;
        case 10: return 57600;
        case 11: return 115200;
        case 12: return 128000;
        case 13: return 256000;
    }
    return 115200;
}
Referenced by setBaudRate().
intToDataBits()
int MicroHILConfig::intToDataBits (const int dataBits) private
Convert combobox index to data bits (to config file)
Parameters
dataBits for serial port (index combobox)
Returns
data bits for serial port in integer format
Pre-process index item of combobox to data-bits
Definition at line 129 of file microhil_config_serial_utils.cc.
{
    return (dataBits + kConfigDataBitsOffset);
}
Referenced by setDataBits().
intToStopBits()
int MicroHILConfig::intToStopBits (const int stopBits) private
Convert combobox index to data-bits (to config file)
Parameters
dataBits index from combobox
Returns
data-bits in integer format
Pre-process index item from combobox to stop-bits
Definition at line 193 of file microhil_config_serial_utils.cc.
{
    return (stopBits + kConfigStopBitsOffset);
}
Referenced by setStopBits().
load()
bool MicroHILConfig::load () final virtual
Load configuration from file.
Returns
boolean status true for success else false
Load configuration from file
Validation of loaded configuration
Configuration file corrupted
Emit signal for loaded log configuration
Emit signal for loaded serial configuration
Implements AbMicroHILConfig.
Definition at line 67 of file microhil_config.cc.
{
    auto loadedConfig = m_config.load_from_file(m_configFilePath);
    auto validatedConfig = validate();
    if(!loadedConfig || !validatedConfig)
    {
        return false;
    }
    m_logConfig.emit(
        getLogPath(),
        logLevelStringToInt(getLogLevel())
    );
    m_serialConfig.emit(
        getDevice(),
        getBaudRate(),
        getDataBits(),
        parityUnicodeStringToInt(getParity()),
        getStopBits()
    );
    return true;
}
References getBaudRate(), getDataBits(), getDevice(), getLogLevel(), getLogPath(), getParity(), getStopBits(), logLevelStringToInt(), m_config, m_configFilePath, m_logConfig, m_serialConfig, parityUnicodeStringToInt(), and validate().
LogConfigLoaded()
MicroHILConfig::SigLogConfig MicroHILConfig::LogConfigLoaded () final virtual
Signal for loaded log configuration.
Returns
Signal for loaded log configuration
Implements AbMicroHILConfig.
Definition at line 22 of file microhil_config_signals.cc.
{
    return m_logConfig;
}
References m_logConfig.
logLevelStringToInt()
int MicroHILConfig::logLevelStringToInt (const Glib::ustring level) private
Convert log level in strong format to integer.
Parameters
level in string format
Returns
log level in integer format
Definition at line 68 of file microhil_config_log_utils.cc.
{
    if(level == kConfigLogLevelWarning)
    {
        return kConfigLogLevelWarningId;
    }
    if(level == kConfigLogLevelError)
    {
        return kConfigLogLevelErrorId;
    }
    return kConfigLogLevelInfoId;
}
Referenced by load().
logLevelToUnicodeString()
Glib::ustring MicroHILConfig::logLevelToUnicodeString (const int logLevel) private
Convert integer log level to string format.
Parameters
logLevel in integer format
Returns
string format of log level
Convert integer log level to scopped enumerator class
Definition at line 48 of file microhil_config_log_utils.cc.
{
    auto logLevelType = static_cast<LogLevelConfig>(logLevel);
    switch(logLevelType)
    {
        case LogLevelConfig::MICROHIL_INFO_CONFIG:
            return kConfigLogLevelInfo;
        case LogLevelConfig::MICROHIL_WARNING_CONFIG:
            return kConfigLogLevelWarning;
        case LogLevelConfig::MICROHIL_ERROR_CONFIG:
            return kConfigLogLevelError;
    }
    return kConfigLogLevelInfo;
}
References MICROHIL_ERROR_CONFIG, MICROHIL_INFO_CONFIG, and MICROHIL_WARNING_CONFIG.
Referenced by setLogLevel().
parityToUnicodeString()
Glib::ustring MicroHILConfig::parityToUnicodeString (const int parity) private
Convert integer parity to string format (to config file)
Parameters
parity index combobox
Returns
string format of parity in string format
Convert integer parity to scopped enumerator class
Definition at line 136 of file microhil_config_serial_utils.cc.
{
    auto parityPrepared = static_cast<ParityConfig>(parity);
    switch(parityPrepared)
    {
        case ParityConfig::MICROHIL_NONE_CONFIG:
            return kConfigParityNone;
        case ParityConfig::MICROHIL_ODD_CONFIG:
            return kConfigParityOdd;
        case ParityConfig::MICROHIL_EVEN_CONFIG:
            return kConfigParityEven;
        case ParityConfig::MICROHIL_MARK_CONFIG:
            return kConfigParityMark;
        case ParityConfig::MICROHIL_SPACE_CONFIG:
            return kConfigParitySpace;
    }
    return kConfigParityNone;
}
References MICROHIL_EVEN_CONFIG, MICROHIL_MARK_CONFIG, MICROHIL_NONE_CONFIG, MICROHIL_ODD_CONFIG, and MICROHIL_SPACE_CONFIG.
Referenced by setParity().
parityUnicodeStringToInt()
int MicroHILConfig::parityUnicodeStringToInt (const Glib::ustring parity) private
Convert parity to integer format (from config file)
Parameters
parity in string format (from config file)
Returns
parity in integer format (to combobox index)
Convert string format of parity to index item for combobox
Definition at line 159 of file microhil_config_serial_utils.cc.
{
    if(parity == kConfigParityOdd)
    {
        return kConfigParityOddId;
    }
    if(parity == kConfigParityEven)
    {
        return kConfigParityEvenId;
    }
    if(parity == kConfigParityMark)
    {
        return kConfigParityMarkId;
    }
    if(parity == kConfigParitySpace)
    {
        return kConfigParitySpaceId;
    }
    return kConfigParityNoneId;
}
Referenced by load().
SerialConfigLoaded()
MicroHILConfig::SigSerialConfig MicroHILConfig::SerialConfigLoaded () final virtual
Signal for loaded serial configuration.
Returns
Signal for loaded serial configuration
Implements AbMicroHILConfig.
Definition at line 28 of file microhil_config_signals.cc.
{
    return m_serialConfig;
}
References m_serialConfig.
setBaudRate()
void MicroHILConfig::setBaudRate (const int baudRate) final virtual
Setting baud rate for serial port to configuration.
Parameters
baudRate for serial port
Pre-process baud-rate for configuration file
Implements AbMicroHILConfig.
Definition at line 62 of file microhil_config_serial.cc.
{
    auto baudRatePrepared = intToBaudRate(baudRate);
    m_config.set_integer(
        kConfigSerialSection, kConfigSerialBaudRate, baudRatePrepared
    );
}
References intToBaudRate(), and m_config.
setDataBits()
void MicroHILConfig::setDataBits (const int dataBits) final virtual
Setting data bits for serial port to configuration.
Parameters
dataBits for serial port
Pre-process data-bits for configuration file
Implements AbMicroHILConfig.
Definition at line 84 of file microhil_config_serial.cc.
{
    auto dataBitsPrepared = intToDataBits(dataBits);
    m_config.set_integer(
        kConfigSerialSection, kConfigSerialDataBits, dataBitsPrepared
    );
}
References intToDataBits(), and m_config.
setDevice()
void MicroHILConfig::setDevice (const Glib::ustring device) final virtual
Setting serial device file path to configuration.
Parameters
device file path
Implements AbMicroHILConfig.
Definition at line 48 of file microhil_config_serial.cc.
{
    m_config.set_string(
        kConfigSerialSection, kConfigSerialDevice, device
    );
}
References m_config.
setLogLevel()
void MicroHILConfig::setLogLevel (const int level) final virtual
Setting log level.
Parameters
level for log settings
Convert integer log level to string format
Implements AbMicroHILConfig.
Definition at line 36 of file microhil_config_log.cc.
{
    auto logLevel = logLevelToUnicodeString(level);
    m_config.set_string(
        kConfigLogSection, kConfigLogLevel, logLevel
    );
}
References logLevelToUnicodeString(), and m_config.
setLogPath()
void MicroHILConfig::setLogPath (const Glib::ustring path) final virtual
Setting log path.
Parameters
path for log messages
Implements AbMicroHILConfig.
Definition at line 52 of file microhil_config_log.cc.
{
    m_config.set_string(
        kConfigLogSection, kConfigLogFile, path
    );
}
References m_config.
setParity()
void MicroHILConfig::setParity (const int parity) final virtual
Setting parity for serial port to configuration.
Parameters
parity for serial port
Pre-process parity for configuration file
Implements AbMicroHILConfig.
Definition at line 106 of file microhil_config_serial.cc.
{
    auto parityPrepared = parityToUnicodeString(parity);
    m_config.set_string(
        kConfigSerialSection, kConfigSerialParity, parityPrepared
    );
}
References m_config, and parityToUnicodeString().
setStopBits()
void MicroHILConfig::setStopBits (const int stopBits) final virtual
Setting stop bits for serial port to configuration.
Parameters
stopBits for serial port
Pre-process stop-bits for configuration file
Implements AbMicroHILConfig.
Definition at line 124 of file microhil_config_serial.cc.
{
    auto stopBitsPrepared = intToStopBits(stopBits);
    m_config.set_integer(
        kConfigSerialSection, kConfigSerialStopBits, stopBitsPrepared
    );
}
References intToStopBits(), and m_config.
stopBitsToInt()
int MicroHILConfig::stopBitsToInt (const int stopBits) private
Convert stop-bits to integer (from config file)
Parameters
dataBits from config file
Returns
stop-bits in integer format (index combobox)
Pre-process stop-bits to index item for combobox
Definition at line 186 of file microhil_config_serial_utils.cc.
{
    return (stopBits - kConfigStopBitsOffset);
}
Referenced by getStopBits().
store()
bool MicroHILConfig::store () final virtual
Store configuration.
Returns
boolean status true for success else false
Implements AbMicroHILConfig.
Definition at line 104 of file microhil_config.cc.
{
    return m_config.save_to_file(m_configFilePath);
}
References m_config, and m_configFilePath.
validate()
bool MicroHILConfig::validate () final virtual
Validate configuration (existing all expected parameters)
Returns
boolean status true for success else false
Checking configuration parameters
Configuration file corrupted
Implements AbMicroHILConfig.
Definition at line 109 of file microhil_config.cc.
{
    if(!isPreValid())
    {
        return false;
    }
    auto configLogCheck = validateLogSettings();
    auto configSerialCheck = validateSerialSettings();
    if(!configLogCheck || !configSerialCheck)
    {
        return false;
    }
    return true;
}
References AbMicroHILConfig::isPreValid(), validateLogSettings(), and validateSerialSettings().
Referenced by load().
validateLogSettings()
bool MicroHILConfig::validateLogSettings () private
Validate log configuration (existing expected parameters)
Returns
boolean status true for success else false
Checking log configuration parameters from config file
Configuration file, log section corrupted
Definition at line 64 of file microhil_config_log.cc.
{
    auto configCheck = (
        m_config.has_key(kConfigLogSection, kConfigLogLevel) &&
        m_config.has_key(kConfigLogSection, kConfigLogFile)
    );
    if(!configCheck)
    {
        return false;
    }
    return true;
}
References m_config.
Referenced by validate().
validateSerialSettings()
bool MicroHILConfig::validateSerialSettings () private
Validate serial configuration (existing expected parameters)
Returns
boolean status true for success else false
Checking serial configuration parameters from config file
Configuration file, serial section corrupted
Definition at line 146 of file microhil_config_serial.cc.
{
    auto configCheck = (
        m_config.has_key(kConfigSerialSection, kConfigSerialDevice) &&
        m_config.has_key(kConfigSerialSection, kConfigSerialBaudRate) &&
        m_config.has_key(kConfigSerialSection, kConfigSerialDataBits) &&
        m_config.has_key(kConfigSerialSection, kConfigSerialParity) &&
        m_config.has_key(kConfigSerialSection, kConfigSerialStopBits)
    );
    if(!configCheck)
    {
        return false;
    }
    return true;
}
References m_config.
Referenced by validate().
Member Data Documentation
m_config
Glib::KeyFile MicroHILConfig::m_config {} private
Configuration instance.
Definition at line 218 of file microhil_config.h.
Referenced by getBaudRate(), getDataBits(), getDevice(), getLogLevel(), getLogPath(), getParity(), getStopBits(), load(), setBaudRate(), setDataBits(), setDevice(), setLogLevel(), setLogPath(), setParity(), setStopBits(), store(), validateLogSettings(), and validateSerialSettings().
m_configFilePath
std::string MicroHILConfig::m_configFilePath {} private
Configuration file path.
Definition at line 214 of file microhil_config.h.
Referenced by checkConfigPath(), load(), MicroHILConfig(), and store().
m_homePath
std::string MicroHILConfig::m_homePath {} private
Home directory path.
Definition at line 210 of file microhil_config.h.
Referenced by checkConfigPath(), and MicroHILConfig().
m_logConfig
SigLogConfig MicroHILConfig::m_logConfig {} private
Signal for loaded log configuration from file.
Definition at line 222 of file microhil_config.h.
Referenced by load(), and LogConfigLoaded().
m_serialConfig
SigSerialConfig MicroHILConfig::m_serialConfig {} private
Signal for loaded serial configuration from file.
Definition at line 226 of file microhil_config.h.
Referenced by load(), and SerialConfigLoaded().
The documentation for this class was generated from the following files:
config/microhil_config.h
config/microhil_config.cc
config/microhil_config_log.cc
config/microhil_config_log_utils.cc
config/microhil_config_serial.cc
config/microhil_config_serial_utils.cc
config/microhil_config_signals.cc