microhildesk: Electux::App::Model::Model Class Reference
Electux::App::Model::Model Class Reference
Concrete implementation of the IModel interface.
#include <model.h>
Public Member Functions
Model () noexcept=default
Model constructor.
bool add (const std::string_view &key, const std::string_view &data) final
Adds an entity to the model.
bool validateKey (const std::string_view &key) const final
Validates if a string key is a valid serial configuration key.
const std::string & getEntity (const std::string_view &key) const final
Gets an entity value by its key.
const Entities & get () const final
Gets all model entities.
Entities getAllEntries () const final
Gets a copy of all serial model entries.
bool update (const std::string_view &key, const std::string_view &data) final
Updates an entity value by its key.
void clear () final
Clears all model entities.
std::string_view toString (const ModelSerialKey &key) const final
Converts a ModelSerialKey enum value to its string representation.
std::string_view toString (const ModelLogKey &key) const final
Converts a ModelLogKey enum value to its string representation.
std::string_view toString (const ModelControlKey &key) const final
Converts a ModelControlKey enum value to its string representation.
Private Attributes
Entities m_entities {}
Internal storage for model entities in map format {key: data}.
Detailed Description
Concrete implementation of the IModel interface.
Provides a standard container for managing application entities using an internal map-based storage mechanism.
Definition at line 35 of file model.h.
Constructor & Destructor Documentation
Model()
Electux::App::Model::Model::Model () inline default noexcept
Model constructor.
Member Function Documentation
add()
bool Model::add (const std::string_view & key, const std::string_view & data) final virtual
Adds an entity to the model.
Parameters
key Represents the model entity key to be added.
data Represents the model entity data to be added.
Returns
true if the entity was successfully added, false otherwise.
Parameters
key Represents the model entity key to be added.
data Represents the model entity data to be added.
Returns
true if the entity was successfully added, false if it already exists.
Implements Electux::App::Model::IModel.
Definition at line 82 of file model.cc.
{
    if (m_entities.find(key) != m_entities.end())
    {
        return false;
    }
    auto [it, inserted] = m_entities.emplace(std::string(key), std::string(data));
    return inserted;
}
References m_entities.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), and Electux::App::Config::ConfigManager::load().
clear()
void Model::clear () final virtual
Clears all model entities.
Clears all entities from the internal storage.
Implements Electux::App::Model::IModel.
Definition at line 209 of file model.cc.
{
    m_entities.clear();
}
References m_entities.
get()
const Entities & Model::get () const final virtual
Gets all model entities.
Returns
Constant reference to the map of strings {key: data}.
Constant reference to the internal map of entities.
Implements Electux::App::Model::IModel.
Definition at line 132 of file model.cc.
{
    return m_entities;
}
References m_entities.
getAllEntries()
Entities Model::getAllEntries () const final virtual
Gets a copy of all serial model entries.
Gets a copy of all control model entries.
Returns
A map containing all serial configuration entries {key: data}.
Iterates through all defined ModelControlKey values and retrieves their current string data from the underlying map.
Returns
A map containing all control configuration entries {key: data}.
Implements Electux::App::Model::IModel.
Definition at line 144 of file model.cc.
{
    Entities entries;
    auto fill = [&](auto&& keys)
    {
        for (const auto& key : keys)
        {
            std::string keyStr{toString(key)};
            entries.emplace(std::move(keyStr), getEntity(keyStr));
        }
    };
    static const std::vector<ModelControlKey> controlKeys =
    {
        ModelControlKey::Enable,
        ModelControlKey::Mode,
        ModelControlKey::Toggle,
        ModelControlKey::Timer,
        ModelControlKey::TimerEnable
    };
    static const std::vector<ModelLogKey> logKeys =
    {
        ModelLogKey::LogLevel,
        ModelLogKey::FilePath
    };
    static const std::vector<ModelSerialKey> serialKeys =
    {
        ModelSerialKey::Device,
        ModelSerialKey::Baud,
        ModelSerialKey::Data,
        ModelSerialKey::Parity,
        ModelSerialKey::Stop,
        ModelSerialKey::Flow
    };
    fill(controlKeys);
    fill(logKeys);
    fill(serialKeys);
    return entries;
}
References Electux::App::Model::Baud, Electux::App::Model::Data, Electux::App::Model::Device, Electux::App::Model::Enable, Electux::App::Model::FilePath, Electux::App::Model::Flow, getEntity(), Electux::App::Model::LogLevel, Electux::App::Model::Mode, Electux::App::Model::Parity, Electux::App::Model::Stop, Electux::App::Model::Timer, Electux::App::Model::TimerEnable, Electux::App::Model::Toggle, and toString().
getEntity()
const std::string & Model::getEntity (const std::string_view & key) const final virtual
Gets an entity value by its key.
Parameters
key Represents the model entity key.
Returns
Reference to the string entity selected by key.
Parameters
key Represents the model entity key.
Returns
Reference to the string entity selected by key, or fallback if not found.
Implements Electux::App::Model::IModel.
Definition at line 116 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        return it->second;
    }
    static const std::string fallback{cFallback.data(), cFallback.size()};
    return fallback;
}
References Electux::App::Model::cFallback, and m_entities.
Referenced by Electux::App::View::AppHome::extract_config(), getAllEntries(), Electux::App::View::AppHome::update_control_config(), and Electux::App::View::Settings::AppSettings::updateUiData().
toString() [1/3]
std::string_view Model::toString (const ModelControlKey & key) const final virtual
Converts a ModelControlKey enum value to its string representation.
Parameters
key Represents the ModelControlKey enum value.
Returns
A string_view containing the key name.
Parameters
key Represents the ModelControlKey enum value.
Returns
A string_view containing the constant key name.
Implements Electux::App::Model::IModel.
Definition at line 219 of file model.cc.
{
    switch (key)
    {
        case ModelControlKey::Enable:      return cEnable;
        case ModelControlKey::Mode:        return cMode;
        case ModelControlKey::Toggle:      return cToggle;
        case ModelControlKey::Timer:       return cTimer;
        case ModelControlKey::TimerEnable: return cTimerEnable;
        default:                           return cUnknown;
    }
}
References Electux::App::Model::cEnable, Electux::App::Model::cMode, Electux::App::Model::cTimer, Electux::App::Model::cTimerEnable, Electux::App::Model::cToggle, Electux::App::Model::cUnknown, Electux::App::Model::Enable, Electux::App::Model::Mode, Electux::App::Model::Timer, Electux::App::Model::TimerEnable, and Electux::App::Model::Toggle.
toString() [2/3]
std::string_view Model::toString (const ModelLogKey & key) const final virtual
Converts a ModelLogKey enum value to its string representation.
Parameters
key Represents the ModelLogKey enum value.
Returns
A string_view containing the key name.
Parameters
key Represents the ModelLogKey enum value.
Returns
A string_view containing the constant key name.
Implements Electux::App::Model::IModel.
Definition at line 237 of file model.cc.
{
    switch (key)
    {
        case ModelLogKey::LogLevel: return cLogLevel;
        case ModelLogKey::FilePath: return cFilePath;
        default:                    return cUnknown;
    }
}
References Electux::App::Model::cFilePath, Electux::App::Model::cLogLevel, Electux::App::Model::cUnknown, Electux::App::Model::FilePath, and Electux::App::Model::LogLevel.
toString() [3/3]
std::string_view Model::toString (const ModelSerialKey & key) const final virtual
Converts a ModelSerialKey enum value to its string representation.
Parameters
key Represents the ModelSerialKey enum value.
Returns
A string_view containing the key name.
Parameters
key Represents the ModelSerialKey enum value.
Returns
A string_view containing the constant key name.
Implements Electux::App::Model::IModel.
Definition at line 252 of file model.cc.
{
    switch (key)
    {
        case ModelSerialKey::Device: return cDevice;
        case ModelSerialKey::Baud:   return cBaud;
        case ModelSerialKey::Data:   return cData;
        case ModelSerialKey::Parity: return cParity;
        case ModelSerialKey::Stop:   return cStop;
        case ModelSerialKey::Flow:   return cFlow;
        default:                     return cUnknown;
    }
}
References Electux::App::Model::Baud, Electux::App::Model::cBaud, Electux::App::Model::cData, Electux::App::Model::cDevice, Electux::App::Model::cFlow, Electux::App::Model::cParity, Electux::App::Model::cStop, Electux::App::Model::cUnknown, Electux::App::Model::Data, Electux::App::Model::Device, Electux::App::Model::Flow, Electux::App::Model::Parity, and Electux::App::Model::Stop.
Referenced by Electux::App::Config::ConfigManager::defaultConfigStore(), getAllEntries(), Electux::App::View::AppHome::getUiData(), Electux::App::View::Settings::AppSettings::getUiData(), Electux::App::View::AppHome::onChannelEnableChanged(), Electux::App::View::AppHome::onChannelModeChanged(), Electux::App::View::AppHome::onChannelTimerChanged(), Electux::App::View::AppHome::onChannelTimerToggleChanged(), Electux::App::View::AppHome::onChannelToggleChanged(), Electux::App::View::AppHome::updateUiData(), and Electux::App::View::Settings::AppSettings::updateUiData().
update()
bool Model::update (const std::string_view & key, const std::string_view & data) final virtual
Updates an entity value by its key.
Parameters
key Represents the model entity key.
data Represents the new value for the entity.
Returns
true if the entity was updated, false if the key does not exist.
Implements Electux::App::Model::IModel.
Definition at line 195 of file model.cc.
{
    auto it = m_entities.find(key);
    if (it != m_entities.end())
    {
        it->second = data;
        return true;
    }
    return false;
}
References m_entities.
Referenced by Electux::App::View::Settings::AppSettings::getUiData(), and Electux::App::View::AppHome::update_control_config().
validateKey()
bool Model::validateKey (const std::string_view & key) const final virtual
Validates if a string key is a valid serial configuration key.
Validates if a string key is a valid control configuration key.
Parameters
key Represents the string key to be validated.
Returns
true if the key is valid, false otherwise.
Parameters
key Represents the string key to be validated.
Returns
true if the key matches one of the internal constants, else false.
Implements Electux::App::Model::IModel.
Definition at line 99 of file model.cc.
{
    static const std::initializer_list<std::string_view> validKeys =
    {
        cEnable, cMode, cToggle, cTimer, cTimerEnable,
        cLogLevel, cFilePath,
        cDevice, cBaud, cData, cParity, cStop, cFlow
    };
    return std::any_of(validKeys.begin(), validKeys.end(), [&](auto k) { return k == key; });
}
References Electux::App::Model::cBaud, Electux::App::Model::cData, Electux::App::Model::cDevice, Electux::App::Model::cEnable, Electux::App::Model::cFilePath, Electux::App::Model::cFlow, Electux::App::Model::cLogLevel, Electux::App::Model::cMode, Electux::App::Model::cParity, Electux::App::Model::cStop, Electux::App::Model::cTimer, Electux::App::Model::cTimerEnable, and Electux::App::Model::cToggle.
Referenced by Electux::App::Config::ConfigManager::load().
Member Data Documentation
m_entities
Entities Electux::App::Model::Model::m_entities {} private
Internal storage for model entities in map format {key: data}.
Definition at line 115 of file model.h.
{};
Referenced by add(), clear(), get(), getEntity(), and update().
The documentation for this class was generated from the following files:
model/model.h
model/model.cc