name: microhildesk C checker
on:
  push:
    branches: [ master ]
    paths:
      - 'sw/microhildesk0/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'sw/microhildesk1/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check length of line in modules
        id: long_line_checker
        run: |
          echo Checking length of line in modules
          modules_ok=0
          modules=($(find sw/ -type f -name '*.c' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_length=$(wc -L < "${mod}"); [[ $line_length -gt 80 ]] && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo "action_state=success" >> "$GITHUB_ENV" || echo "action_state=failure" >> "$GITHUB_ENV"
      - name: Check on failures
        if: "$action_state" == "failure"
        run: exit 1
