name: microhildesk build checker
on:
  push:
    branches: [ master ]
    paths:
      - 'sw/microhildesk/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'sw/microhildesk/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install gtkmm
      id: install_gtkmm
      run: |
        sudo apt update
        sudo apt install pkg-config
        sudo apt install libserial-dev
        sudo apt install libgtkmm-3.0-dev
        sudo apt install libgtk-4-dev
        sudo apt install libgtkmm-4.0-dev
    - name: make all
      id: gnu_make_all
      run: |
        cd sw/microhildesk/build
        make all
    - name: make clean
      id: gnu_make_clean
      run: |
        cd sw/microhildesk/build
        make clean
