name: microhildesk build checker
on:
  push:
    branches: [ master ]
    paths:
      - 'sw/microhildesk/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'sw/microhildesk/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install gtkmm
      id: install_gtkmm
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y pkg-config
        sudo apt-get install -y libserial-dev
        sudo apt-get install -y libgtkmm-3.0-dev
        sudo apt-get install -y libgtk-4-dev
		sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make
        sudo apt-get update
        sudo apt-get install -y libgtkmm-4.0-dev
    - name: make all
      id: gnu_make_all
      run: |
        cd sw/microhildesk/build
        make all
    - name: make clean
      id: gnu_make_clean
      run: |
        cd sw/microhildesk/build
        make clean
