name: Lint Code Base MicroHIL
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Lint Code Base MicroHIL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code MicroHIL
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base MicroHIL
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
