microhildesk: Electux::App::Com::SerialCom Class Reference
Electux::App::Com::SerialCom Class Reference
Implementation of serial communication using LibSerial.
#include <serial_com.h>
Public Member Functions
SerialCom (std::unique_ptr< ILibSerialPort > port=std::make_unique< LibSerialPortWrapper >())
Constructor for SerialCom.
~SerialCom () noexcept
Destructor for SerialCom. Ensures the serial port is closed and resources are released.
bool open () final
Opens the serial communication channel.
bool close () final
Closes the serial communication channel.
bool isOpen () const final
Checks if the communication channel is currently open.
void read (std::vector< uint8_t > &data, size_t len) final
Reads data from the serial communication channel.
void write (const std::vector< uint8_t > &data) final
Writes data to the serial communication channel.
bool setup (const SerialParams &params) final
Configures the serial port with specific parameters.
void setBaudRate (BaudRate baudRate) final
Sets the baud rate for the serial port.
void setCharacterSize (CharacterSize characterSize) final
Sets the character size for the serial port.
void setParity (Parity parity) final
Sets the parity mode for the serial port.
void setStopBits (StopBits stopBits) final
Sets the number of stop bits for the serial port.
void setFlowControl (FlowControl flowControl) final
Sets the flow control mode for the serial port.
Protected Member Functions
Utility Conversion Methods
Overridden helpers for LibSerial enum and numeric type conversion.
uint32_t baudToUint (const BaudRate baud) final
Converts BaudRate enum to numeric uint32_t.
BaudRate uintToBaud (const uint32_t baud) final
Converts numeric uint32_t to BaudRate enum.
uint32_t dataBitsToUint (const CharacterSize data) final
Converts CharacterSize enum to numeric uint32_t.
CharacterSize uintToDataBits (const uint32_t data) final
Converts numeric uint32_t to CharacterSize enum.
uint32_t parityToUint (const Parity parity) final
Converts Parity enum to numeric uint32_t.
Parity uintToParity (const uint32_t parity) final
Converts numeric uint32_t to Parity enum.
uint32_t stopBitsToUint (const StopBits stop) final
Converts StopBits enum to numeric uint32_t.
StopBits uintToStopBits (const uint32_t stop) final
Converts numeric uint32_t to StopBits enum.
uint32_t flowControlToUint (const FlowControl flow) final
Converts FlowControl enum to numeric uint32_t.
FlowControl uintToFlowControl (const uint32_t flow) final
Converts numeric uint32_t to FlowControl enum.
Private Attributes
std::unique_ptr< ILibSerialPort > m_serialPort {nullptr}
Unique pointer to the ILibSerialPort implementation for serial port operations.
std::string m_device {}
Path to the serial port device (e.g., "/dev/ttyS0").
Detailed Description
Implementation of serial communication using LibSerial.
This class implements the ICom interface to provide concrete serial port operations, including hardware configuration and data I/O.
Definition at line 40 of file serial_com.h.
Constructor & Destructor Documentation
SerialCom()
SerialCom::SerialCom (std::unique_ptr< ILibSerialPort > port = std::make_unique<LibSerialPortWrapper>()) explicit
Constructor for SerialCom.
Constructs a SerialCom object with the given serial port adapter.
Parameters
port Unique pointer to an ILibSerialPort implementation.
port A unique pointer to an ILibSerialPort implementation.
Definition at line 29 of file serial_com.cc.
    : m_serialPort(std::move(port))
{
    std::cout << "SerialCom constructor called." << std::endl;
}
~SerialCom()
SerialCom::~SerialCom () noexcept
Destructor for SerialCom. Ensures the serial port is closed and resources are released.
Destructor for the SerialCom class. Ensures the serial port is closed.
Definition at line 38 of file serial_com.cc.
{
    if (!close())
    {
        std::cerr << "Close error: Serial port was not closed properly." << std::endl;
    }
    std::cout << "SerialCom destructor called." << std::endl;
}
References close().
Member Function Documentation
baudToUint()
uint32_t SerialCom::baudToUint (const BaudRate baud) final protected virtual
Converts BaudRate enum to numeric uint32_t.
Parameters
baud Scoped enumerator value.
Returns
Numeric representation of the baud rate.
Parameters
baud Scoped enumerator value representing baud rate.
Returns
Numeric representation or cComInvalidParameter if unsupported.
Implements Electux::App::Com::ISerial.
Definition at line 31 of file serial_com_baud_rate.cc.
{
    switch (baud)
    {
    case BaudRate::BAUD_50:
        return cComInvalidParameter;
    case BaudRate::BAUD_75:
        return cComInvalidParameter;
    case BaudRate::BAUD_110:
        return cComBaud110;
    case BaudRate::BAUD_134:
        return cComInvalidParameter;
    case BaudRate::BAUD_150:
        return cComInvalidParameter;
    case BaudRate::BAUD_200:
        return cComInvalidParameter;
    case BaudRate::BAUD_300:
        return cComBaud300;
    case BaudRate::BAUD_600:
        return cComBaud600;
    case BaudRate::BAUD_1200:
        return cComBaud1200;
    case BaudRate::BAUD_1800:
        return cComInvalidParameter;
    case BaudRate::BAUD_2400:
        return cComBaud2400;
    case BaudRate::BAUD_4800:
        return cComBaud4800;
    case BaudRate::BAUD_9600:
        return cComBaud9600;
    case BaudRate::BAUD_19200:
        return cComBaud19200;
    case BaudRate::BAUD_38400:
        return cComBaud38400;
    case BaudRate::BAUD_57600:
        return cComBaud57600;
    case BaudRate::BAUD_115200:
        return cComBaud115200;
    case BaudRate::BAUD_230400:
        return cComBaud230400;
    case BaudRate::BAUD_460800:
        return cComInvalidParameter;
    case BaudRate::BAUD_500000:
        return cComInvalidParameter;
    case BaudRate::BAUD_576000:
        return cComInvalidParameter;
    case BaudRate::BAUD_921600:
        return cComInvalidParameter;
    case BaudRate::BAUD_1000000:
        return cComInvalidParameter;
    case BaudRate::BAUD_1152000:
        return cComInvalidParameter;
    case BaudRate::BAUD_1500000:
        return cComInvalidParameter;
    case BaudRate::BAUD_2000000:
        return cComInvalidParameter;
    case BaudRate::BAUD_2500000:
        return cComInvalidParameter;
    case BaudRate::BAUD_3000000:
        return cComInvalidParameter;
    case BaudRate::BAUD_3500000:
        return cComInvalidParameter;
    case BaudRate::BAUD_4000000:
        return cComInvalidParameter;
    default:
        return cComInvalidParameter;
    }
}
References Electux::App::Params::SerialComConstants::cComBaud110, Electux::App::Params::SerialComConstants::cComBaud115200, Electux::App::Params::SerialComConstants::cComBaud1200, Electux::App::Params::SerialComConstants::cComBaud19200, Electux::App::Params::SerialComConstants::cComBaud230400, Electux::App::Params::SerialComConstants::cComBaud2400, Electux::App::Params::SerialComConstants::cComBaud300, Electux::App::Params::SerialComConstants::cComBaud38400, Electux::App::Params::SerialComConstants::cComBaud4800, Electux::App::Params::SerialComConstants::cComBaud57600, Electux::App::Params::SerialComConstants::cComBaud600, Electux::App::Params::SerialComConstants::cComBaud9600, and Electux::App::Params::SerialComConstants::cComInvalidParameter.
close()
bool SerialCom::close () final virtual
Closes the serial communication channel.
Closes the serial port.
Returns
True if the channel was successfully closed, false otherwise.
True if the port was successfully closed, false otherwise.
Implements Electux::App::Com::ICom.
Definition at line 81 of file serial_com.cc.
{
    if (isOpen())
    {
        m_serialPort->Close();
        std::cout << "Serial port closed successfully." << std::endl;
        return true;
    }
    return false;
}
References isOpen(), and m_serialPort.
Referenced by ~SerialCom().
dataBitsToUint()
uint32_t SerialCom::dataBitsToUint (const CharacterSize data) final protected virtual
Converts CharacterSize enum to numeric uint32_t.
Parameters
data Scoped enumerator value.
Returns
Numeric representation of data bits.
Parameters
data CharacterSize enumerator.
Returns
Numeric representation of data bits.
Implements Electux::App::Com::ISerial.
Definition at line 31 of file serial_com_data_bits.cc.
{
    switch (data)
    {
    case CharacterSize::CHAR_SIZE_5:
        return cComDataBits5;
    case CharacterSize::CHAR_SIZE_6:
        return cComDataBits6;
    case CharacterSize::CHAR_SIZE_7:
        return cComDataBits7;
    case CharacterSize::CHAR_SIZE_8:
        return cComDataBits8;
    default:
        return cComInvalidParameter;
    }
}
References Electux::App::Params::SerialComConstants::cComDataBits5, Electux::App::Params::SerialComConstants::cComDataBits6, Electux::App::Params::SerialComConstants::cComDataBits7, Electux::App::Params::SerialComConstants::cComDataBits8, and Electux::App::Params::SerialComConstants::cComInvalidParameter.
flowControlToUint()
uint32_t SerialCom::flowControlToUint (const FlowControl flow) final protected virtual
Converts FlowControl enum to numeric uint32_t.
Parameters
flow Scoped enumerator value.
Returns
Numeric representation of flow control.
Parameters
flow FlowControl enumerator.
Returns
Numeric representation of flow control mode.
Implements Electux::App::Com::ISerial.
Definition at line 31 of file serial_com_flow_control.cc.
{
    switch (flow)
    {
    case FlowControl::FLOW_CONTROL_NONE:
        return cComFlowControlNone;
    case FlowControl::FLOW_CONTROL_HARDWARE:
        return cComFlowControlHw;
    case FlowControl::FLOW_CONTROL_SOFTWARE:
        return cComFlowControlSw;
    case FlowControl::FLOW_CONTROL_INVALID:
    default:
        return cComInvalidParameter;
    }
}
References Electux::App::Params::SerialComConstants::cComFlowControlHw, Electux::App::Params::SerialComConstants::cComFlowControlNone, Electux::App::Params::SerialComConstants::cComFlowControlSw, and Electux::App::Params::SerialComConstants::cComInvalidParameter.
isOpen()
bool SerialCom::isOpen () const final virtual
Checks if the communication channel is currently open.
Checks if the serial port is open.
Returns
True if the channel is open, false otherwise.
True if the port is open, false otherwise.
Implements Electux::App::Com::ICom.
Definition at line 97 of file serial_com.cc.
{
    bool open = m_serialPort->IsOpen();
    std::cout << "Serial port is " << (open ? "open." : "closed.") << std::endl;
    return open;
}
References m_serialPort, and open().
Referenced by close(), open(), read(), and write().
open()
bool SerialCom::open () final virtual
Opens the serial communication channel.
Opens the serial port.
Returns
True if the channel was successfully opened, false otherwise.
True if the port was successfully opened, false otherwise.
Implements Electux::App::Com::ICom.
Definition at line 52 of file serial_com.cc.
{
    if (m_device.empty())
    {
        std::cerr << "Open error: Device path is empty!" << std::endl;
        return false;
    }
    if (!isOpen())
    {
        try
        {
            m_serialPort->Open(m_device);
            std::cout << "Serial port opened successfully." << std::endl;
            return true;
        }
        catch (const std::exception &e)
        {
            std::cerr << "Open error: " << e.what() << std::endl;
        }
    }
    return false;
}
References isOpen(), m_device, and m_serialPort.
Referenced by isOpen().
parityToUint()
uint32_t SerialCom::parityToUint (const Parity parity) final protected virtual
Converts Parity enum to numeric uint32_t.
Parameters
parity Scoped enumerator value.
Returns
Numeric representation of parity.
Parameters
parity Parity enumerator.
Returns
Numeric representation of parity mode.
Implements Electux::App::Com::ISerial.
Definition at line 31 of file serial_com_parity.cc.
{
    switch (parity)
    {
    case Parity::PARITY_EVEN:
        return cComParityEven;
    case Parity::PARITY_ODD:
        return cComParityOdd;
    case Parity::PARITY_NONE:
        return cComParityNone;
    case Parity::PARITY_INVALID:
        return cComInvalidParameter;
    }
    return cComInvalidParameter;
}
References Electux::App::Params::SerialComConstants::cComInvalidParameter, Electux::App::Params::SerialComConstants::cComParityEven, Electux::App::Params::SerialComConstants::cComParityNone, and Electux::App::Params::SerialComConstants::cComParityOdd.
read()
void SerialCom::read (std::vector< uint8_t > & data, size_t len) final virtual
Reads data from the serial communication channel.
Reads data from the serial port.
Parameters
data Vector buffer to store the received bytes.
len The number of bytes to read before returning.
data A vector to store the read data.
len The number of bytes to read.
Implements Electux::App::Com::ICom.
Definition at line 109 of file serial_com.cc.
{
    if (!isOpen())
    {
        std::cerr << "Read error: Serial port closed." << std::endl;
        return;
    }
    m_serialPort->Read(data, len);
    std::cout << "Read " << data.size() << " bytes from serial port." << std::endl;
}
References isOpen(), and m_serialPort.
setBaudRate()
void SerialCom::setBaudRate (BaudRate baudRate) final virtual
Sets the baud rate for the serial port.
Parameters
baudRate The desired baud rate.
Implements Electux::App::Com::ISerial.
Definition at line 141 of file serial_com.cc.
{
    m_serialPort->SetBaudRate(baudRate);
}
References m_serialPort.
Referenced by setup().
setCharacterSize()
void SerialCom::setCharacterSize (CharacterSize characterSize) final virtual
Sets the character size for the serial port.
Parameters
characterSize The desired character size.
Implements Electux::App::Com::ISerial.
Definition at line 150 of file serial_com.cc.
{
    m_serialPort->SetCharacterSize(characterSize);
}
References m_serialPort.
Referenced by setup().
setFlowControl()
void SerialCom::setFlowControl (FlowControl flowControl) final virtual
Sets the flow control mode for the serial port.
Parameters
flowControl The desired flow control mode.
Implements Electux::App::Com::ISerial.
Definition at line 177 of file serial_com.cc.
{
    m_serialPort->SetFlowControl(flowControl);
}
References m_serialPort.
Referenced by setup().
setParity()
void SerialCom::setParity (Parity parity) final virtual
Sets the parity mode for the serial port.
Parameters
parity The desired parity mode.
Implements Electux::App::Com::ISerial.
Definition at line 159 of file serial_com.cc.
{
    m_serialPort->SetParity(parity);
}
References m_serialPort.
Referenced by setup().
setStopBits()
void SerialCom::setStopBits (StopBits stopBits) final virtual
Sets the number of stop bits for the serial port.
Parameters
stopBits The desired number of stop bits.
Implements Electux::App::Com::ISerial.
Definition at line 168 of file serial_com.cc.
{
    m_serialPort->SetStopBits(stopBits);
}
References m_serialPort.
Referenced by setup().
setup()
bool SerialCom::setup (const SerialParams & params) final virtual
Configures the serial port with specific parameters.
Parameters
params Reference to SerialParams structure (configuration).
Returns
True if setup was successful, false otherwise.
Implements Electux::App::Com::ISerial.
Definition at line 30 of file serial_com_setup.cc.
{
    try
    {
        setBaudRate(params.baud);
        setCharacterSize(params.data);
        setParity(params.parity);
        setStopBits(params.stop);
        setFlowControl(params.flow);
        m_device = params.device;
        return true;
    }
    catch (const std::exception &e)
    {
        std::cerr << "Setup error: " << e.what() << std::endl;
        return false;
    }
}
References Electux::App::Com::SerialParams::baud, Electux::App::Com::SerialParams::data, Electux::App::Com::SerialParams::device, Electux::App::Com::SerialParams::flow, m_device, Electux::App::Com::SerialParams::parity, setBaudRate(), setCharacterSize(), setFlowControl(), setParity(), setStopBits(), and Electux::App::Com::SerialParams::stop.
stopBitsToUint()
uint32_t SerialCom::stopBitsToUint (const StopBits stop) final protected virtual
Converts StopBits enum to numeric uint32_t.
Parameters
stop Scoped enumerator value.
Returns
Numeric representation of stop bits.
Parameters
stop StopBits enumerator.
Returns
Numeric representation of stop bits.
Implements Electux::App::Com::ISerial.
Definition at line 31 of file serial_com_stop_bits.cc.
{
    switch (stop)
    {
    case StopBits::STOP_BITS_1:
        return cComStopBits1;
    case StopBits::STOP_BITS_2:
        return cComStopBits2;
    case StopBits::STOP_BITS_INVALID:
        return cComInvalidParameter;
    }
    return cComInvalidParameter;
}
References Electux::App::Params::SerialComConstants::cComInvalidParameter, Electux::App::Params::SerialComConstants::cComStopBits1, and Electux::App::Params::SerialComConstants::cComStopBits2.
uintToBaud()
BaudRate SerialCom::uintToBaud (const uint32_t baud) final protected virtual
Converts numeric uint32_t to BaudRate enum.
Parameters
baud Numeric value.
Returns
Scoped enumerator for the baud rate.
Parameters
baud Numeric value representing baud rate.
Returns
BaudRate enumerator or BAUD_INVALID if mapping fails.
Implements Electux::App::Com::ISerial.
Definition at line 105 of file serial_com_baud_rate.cc.
{
    switch (baud)
    {
    case cComBaud110:
        return BaudRate::BAUD_110;
    case cComBaud300:
        return BaudRate::BAUD_300;
    case cComBaud600:
        return BaudRate::BAUD_600;
    case cComBaud1200:
        return BaudRate::BAUD_1200;
    case cComBaud2400:
        return BaudRate::BAUD_2400;
    case cComBaud4800:
        return BaudRate::BAUD_4800;
    case cComBaud9600:
        return BaudRate::BAUD_9600;
    case cComBaud19200:
        return BaudRate::BAUD_19200;
    case cComBaud38400:
        return BaudRate::BAUD_38400;
    case cComBaud57600:
        return BaudRate::BAUD_57600;
    case cComBaud115200:
        return BaudRate::BAUD_115200;
    case cComBaud230400:
        return BaudRate::BAUD_230400;
    }
    return BaudRate::BAUD_INVALID;
}
References Electux::App::Params::SerialComConstants::cComBaud110, Electux::App::Params::SerialComConstants::cComBaud115200, Electux::App::Params::SerialComConstants::cComBaud1200, Electux::App::Params::SerialComConstants::cComBaud19200, Electux::App::Params::SerialComConstants::cComBaud230400, Electux::App::Params::SerialComConstants::cComBaud2400, Electux::App::Params::SerialComConstants::cComBaud300, Electux::App::Params::SerialComConstants::cComBaud38400, Electux::App::Params::SerialComConstants::cComBaud4800, Electux::App::Params::SerialComConstants::cComBaud57600, Electux::App::Params::SerialComConstants::cComBaud600, and Electux::App::Params::SerialComConstants::cComBaud9600.
uintToDataBits()
CharacterSize SerialCom::uintToDataBits (const uint32_t data) final protected virtual
Converts numeric uint32_t to CharacterSize enum.
Parameters
data Numeric value.
Returns
Scoped enumerator for data bits.
Parameters
data Numeric representation of data bits.
Returns
CharacterSize enumerator or CHAR_SIZE_INVALID if unsupported.
Implements Electux::App::Com::ISerial.
Definition at line 53 of file serial_com_data_bits.cc.
{
    switch (data)
    {
    case cComDataBits5:
        return CharacterSize::CHAR_SIZE_5;
    case cComDataBits6:
        return CharacterSize::CHAR_SIZE_6;
    case cComDataBits7:
        return CharacterSize::CHAR_SIZE_7;
    case cComDataBits8:
        return CharacterSize::CHAR_SIZE_8;
    }
    return CharacterSize::CHAR_SIZE_INVALID;
}
References Electux::App::Params::SerialComConstants::cComDataBits5, Electux::App::Params::SerialComConstants::cComDataBits6, Electux::App::Params::SerialComConstants::cComDataBits7, and Electux::App::Params::SerialComConstants::cComDataBits8.
uintToFlowControl()
FlowControl SerialCom::uintToFlowControl (const uint32_t flow) final protected virtual
Converts numeric uint32_t to FlowControl enum.
Parameters
flow Numeric value.
Returns
Scoped enumerator for flow control.
Parameters
flow Numeric representation of flow control mode.
Returns
Corresponding FlowControl enumerator or FLOW_CONTROL_INVALID if unsupported.
Implements Electux::App::Com::ISerial.
Definition at line 52 of file serial_com_flow_control.cc.
{
    switch (flow)
    {
    case cComFlowControlNone:
        return FlowControl::FLOW_CONTROL_NONE;
    case cComFlowControlHw:
        return FlowControl::FLOW_CONTROL_HARDWARE;
    case cComFlowControlSw:
        return FlowControl::FLOW_CONTROL_SOFTWARE;
    default:
        return FlowControl::FLOW_CONTROL_INVALID;
    }
}
References Electux::App::Params::SerialComConstants::cComFlowControlHw, Electux::App::Params::SerialComConstants::cComFlowControlNone, and Electux::App::Params::SerialComConstants::cComFlowControlSw.
uintToParity()
Parity SerialCom::uintToParity (const uint32_t parity) final protected virtual
Converts numeric uint32_t to Parity enum.
Parameters
parity Numeric value.
Returns
Scoped enumerator for parity.
Parameters
parity Numeric format of parity.
Returns
Parity enumerator or PARITY_INVALID.
Implements Electux::App::Com::ISerial.
Definition at line 53 of file serial_com_parity.cc.
{
    switch (parity)
    {
    case cComParityEven:
        return Parity::PARITY_EVEN;
    case cComParityOdd:
        return Parity::PARITY_ODD;
    case cComParityNone:
        return Parity::PARITY_NONE;
    }
    return Parity::PARITY_INVALID;
}
References Electux::App::Params::SerialComConstants::cComParityEven, Electux::App::Params::SerialComConstants::cComParityNone, and Electux::App::Params::SerialComConstants::cComParityOdd.
uintToStopBits()
StopBits SerialCom::uintToStopBits (const uint32_t stop) final protected virtual
Converts numeric uint32_t to StopBits enum.
Parameters
stop Numeric value.
Returns
Scoped enumerator for stop bits.
Parameters
stop Numeric format of stop bits.
Returns
StopBits enumerator or STOP_BITS_INVALID.
Implements Electux::App::Com::ISerial.
Definition at line 51 of file serial_com_stop_bits.cc.
{
    switch (stop)
    {
    case cComStopBits1:
        return StopBits::STOP_BITS_1;
    case cComStopBits2:
        return StopBits::STOP_BITS_2;
    }
    return StopBits::STOP_BITS_INVALID;
}
References Electux::App::Params::SerialComConstants::cComStopBits1, and Electux::App::Params::SerialComConstants::cComStopBits2.
write()
void SerialCom::write (const std::vector< uint8_t > & data) final virtual
Writes data to the serial communication channel.
Writes data to the serial port.
Parameters
data Vector containing the sequence of bytes to transmit.
data A vector containing the data to write.
Implements Electux::App::Com::ICom.
Definition at line 125 of file serial_com.cc.
{
    if (!isOpen())
    {
        std::cerr << "Write error: Serial port closed." << std::endl;
        return;
    }
    m_serialPort->Write(data);
    std::cout << "Wrote " << data.size() << " bytes to serial port." << std::endl;
}
References isOpen(), and m_serialPort.
Member Data Documentation
m_device
std::string Electux::App::Com::SerialCom::m_device {} private
Path to the serial port device (e.g., "/dev/ttyS0").
Definition at line 210 of file serial_com.h.
{};
Referenced by open(), and setup().
m_serialPort
std::unique_ptr<ILibSerialPort> Electux::App::Com::SerialCom::m_serialPort {nullptr} private
Unique pointer to the ILibSerialPort implementation for serial port operations.
Adapter for serial port abstraction
Definition at line 208 of file serial_com.h.
{nullptr};
Referenced by close(), isOpen(), open(), read(), setBaudRate(), setCharacterSize(), setFlowControl(), setParity(), setStopBits(), and write().
The documentation for this class was generated from the following files:
com/serial_com.h
com/serial_com.cc
com/serial_com_baud_rate.cc
com/serial_com_data_bits.cc
com/serial_com_flow_control.cc
com/serial_com_parity.cc
com/serial_com_setup.cc
com/serial_com_stop_bits.cc